### ISSUE TITLE
Very long files mess up due to sample count overflow

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#1010]
Original [issue 1108](https://code.google.com/p/ddb/issues/detail?id=1108) created by Alexey-Yakovenko on 2014-05-06T15:20:25.000Z:

<b>What steps will reproduce the problem?</b>
<b>Какие шаги приводят к воспроизведению</b>
<b>проблемы?</b>
1. Create a file longer than about 12.5 hours (at 44.1kHz)
2. Attempt to play
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
<b>Какой ожидаемый вывод? Что вы видите</b>
<b>вместо него?</b>
Depending on the codec, it may not play at all, or seeking may be really messed up.

<b>What version of the product are you using? On what operating system and CPU</b>
<b>architecture?</b>
<b>Какую версию продукта вы используете? На</b>
<b>какой операционной системе и</b>
<b>архитектуре CPU?</b>
trunk
Crunchbang Linux
Pentium 4

<b>How did you install the product?</b>
<b>Как вы установили продукт?</b>
Build from source

<b>Please provide any additional information below.</b>
<b>Пожалуйста, предоставьте любую</b>
<b>дополнительную информацию ниже.</b>
This appears to be due to startsample and endsample in ddb_playitem_t having simple int data types, so on 32 bit and some 64 bit platforms it is limited to about 2 billion samples.  There may be other variables that have similar limits (cuesheets?). This is less than 3 hours at 192kHz, more at lower rates.  Most people will never see this, but chain together a few albums and you'll hit the limit.

**Comment by Alexey-Yakovenko** [comment]
I just added 64bit start/end sample values, while preserving backwards compat with the old 32 bit ones. There's a slight source-level API change, but binary compatibility is preserved. Needs to be tested more thoroughly.

**Comment by Lithopsian** [comment]
Better now.  Breaks API backwards-compatibility (startsample and endsample are now startssample32 and endsample32).  Is the API major number going to change?

Seeking still has problems, with some codecs at least.  decoder->seek_sample still only supports int input, and although decoder->seek has float input, it often is just a wrapper to seek_sample.

**Comment by Alexey-Yakovenko** [comment]
> Better now. Breaks API backwards-compatibility (startsample and endsample are now startssample32 and endsample32). Is the API major number going to change?

No. The plan is to change the variable names back to their old names, it was easier to convert all the code to new functions this way.

> Seeking still has problems, with some codecs at least. decoder->seek_sample still only supports int input, and although decoder->seek has float input, it often is just a wrapper to seek_sample.

That's a good point.. and needs fixing too. But I had to start somewhere. Can't guarantee this is getting fixed in 1.8 though.
