### ISSUE TITLE
gtk3.14 regression: track properties multiline text cell is broken

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#1111]
Original [issue 1209](https://code.google.com/p/ddb/issues/detail?id=1209) created by Alexey-Yakovenko on 2014-10-05T14:17:46.000Z:

<b>What steps will reproduce the problem?</b>
1. enter inline edit mode on any field
2. try selecting text with mouse

<b>What is the expected output? What do you see instead?</b>

selection doesn't work, the field will drop out of edit mode, and flash some sort of context menus

**Comment by Alexey-Yakovenko** [comment]
@cboxdoerfer can I ask you to verify whether this bug is still valid and recent GTK3 versions?

**Comment by cboxdoerfer** [comment]
Yes sure. Bug still happens with GTK 3.18.2.

**Comment by cboxdoerfer** [comment]
However inline text editing in pltbrowser works, so maybe there's a bug in deadbeefs code.

**Comment by Alexey-Yakovenko** [comment]
yeah, that's because pltbrowser doesn't use the custom cell which I made for multiline editing in the track properties. It worked until the gtk3.14 tho.

**Comment by cboxdoerfer** [comment]
Ok, didn't know this was a custom text cell. But I guess then this shouldn't be too hard to fix.

**Comment by Alexey-Yakovenko** [comment]
Yeah, I'll just ifdef it for GTK2 only, and make a separate popup dialog for GTK3 with a multiline text field.

**Comment by Alexey-Yakovenko** [comment]
GTK bug report for tracking purpose: https://bugzilla.gnome.org/show_bug.cgi?id=760007

**Comment by Alexey-Yakovenko** [comment]
While this bug cannot be fixed on deadbeef side, there's now a workaround, via right clicking, and selecting Edit, which would open a separate dialog where text selection works fine.

For further help, please contact GTK3 devs, and say hello.
