### ISSUE TITLE
wrong charset detected on streaming mp3

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#1137]
Original [issue 1235](https://code.google.com/p/ddb/issues/detail?id=1235) created by Alexey-Yakovenko on 2014-11-19T11:14:00.000Z:

<b>What steps will reproduce the problem?</b>
<b>Какие шаги приводят к воспроизведению</b>
<b>проблемы?</b>
1. I play a radio stream (http://icecast.omroep.nl/radio4-baroque-bb-mp3)
2. The radio repeats some scores and for one I could notice an odd behaviour (wrong font or font error for the letter ä).
3. That not happens in other audio players when playing the same link.

<b>What is the expected output? What do you see instead?</b>
<b>Какой ожидаемый вывод? Что вы видите</b>
<b>вместо него?</b>
The expected behaviour is the correct font as seen in the attached image for different players.
The odd behaviour is seen in the attached image for ddb.

<b>What version of the product are you using? On what operating system and CPU</b>
<b>architecture?</b>
<b>Какую версию продукта вы используете? На</b>
<b>какой операционной системе и</b>
<b>архитектуре CPU?</b>

Deadbeef version 0.6.2
Xubuntu 14.04 - Linux 3.13.0-39-generic 
Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz

<b>How did you install the product?</b>
<b>Как вы установили продукт?</b>

from deb

<b>Please provide any additional information below.</b>
<b>Пожалуйста, предоставьте любую</b>
<b>дополнительную информацию ниже.</b>

Trying to recreate the issue with an audio file renamed to contain the letter ä, that was displayed correctly. (Cannot say what the difference is between the letter ä as written by me when renaming that file and the one as it appears in the name of the radio stream.)

**Comment by Alexey-Yakovenko** [comment]
closing because the bug is too old and can't be reproduced easy enough.

**Comment by cipricus** [comment]
I have this bug all the time, especially when listening to radio streams: ä and oe are replaced with Chinese characters. 
This also happens when metadata contain French characters like ç, é and others. 

Sometimes whole characters are replaced  with Chines ones, even if only one of them is French/German.

This bug is not old, as it is exactly the same **in 0.7** as I first met it.

Also, although relatively rare, it involves files that are correctly read by **all** other players that I tested - not just the aforementioned VLC.

[![enter image description here][1]][1]


  [1]: http://img.ctrlv.in/img/16/02/03/56b20e4422935.png

Saving this playlist as m3u, it contains these lines:

    #EXTM3U
    #EXTINF:163,Serge Gainsbourg - Le poin輟nneur des Lilas
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1958 - Du chant à la une !/02 - Le poinçonneur des Lilas.mp3
    #EXTINF:143,Serge Gainsbourg - Charleston des d駑駭ageurs de
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1958 - Du chant à la une !/10 - Charleston des déménageurs de piano.mp3
    #EXTINF:129,Serge Gainsbourg - Adieu cr饌ture
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1959 - Serge Gainsbourg N°2/14 - Adieu créature.mp3
    #EXTINF:134,Serge Gainsbourg - Indiff駻ente
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1959 - Serge Gainsbourg N°2/17 - Indifférente.mp3
    #EXTINF:180,Serge Gainsbourg - La chanson de Pr騅ert
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1961 - L'Étonnant Serge Gainsbourg/01 - La chanson de Prévert.mp3
    #EXTINF:158,Serge Gainsbourg - Les Go駑ons
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1962 - Serge Gainsbourg N° 4/11 - Les Goémons.mp3
    #EXTINF:142,Serge Gainsbourg - Ce grand m馗hant vous
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1962 - Serge Gainsbourg N° 4/18 - Ce grand méchant vous.mp3
    #EXTINF:143,Serge Gainsbourg - Chez les y騫駸
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1963 - Gainsbourg Confidentiel/01 - Chez les yéyés.mp3
    #EXTINF:123,Serge Gainsbourg - Joanna
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1964 - Gainsbourg Percussions/13 - Joanna.mp3
    #EXTINF:163,Serge Gainsbourg - Chanson du for軋t
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/what/01 - Chanson du forçat.mp3
    #EXTINF:69,Serge Gainsbourg - Chanson du for軋t II
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/what/02 - Chanson du forçat II.mp3
    #EXTINF:115,Serge Gainsbourg - Vilaines filles, mauvais gar輟
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/what/20 - Vilaines filles, mauvais garçons.mp3

**Comment by Alexey-Yakovenko** [comment]
@cipricus hello. please file a new bug report about this. thank you.

**Comment by Alexey-Yakovenko** [comment]
most likely you need to go to edit -> preferences and disable the character set autodetection.
