### ISSUE TITLE
Use libappindicator for tray icon

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#1170]
Original [issue 1268](https://code.google.com/p/ddb/issues/detail?id=1268) created by Alexey-Yakovenko on 2015-02-13T13:38:29.000Z:

I am using plasma next on archlinux. It is known that plasma next has dropped support for xembed tray icons. GTK applications should use libappindicator to display a tray icon in plasma next. Is there any plan to implement tray icon with libappindicator?

**Comment by vovochka404** [comment]
Как известно, зима близиться... А точнее plasma5 уже начинает становиться дефолтом в дистрибутивах и тебе прекрасно известно что обычные gtk иконки там не поддерживаются более.

Изучение тематики показало что libappindicator обладает одним существенным недостатком, а именно отсутствие события "клик мыши". Оно просто вывалит меню, что соответственно меняет поведеине по умолчанию, а этого хотелось бы избежать. Вообще говоря с обработкой событий там как-то плоховато.

Есть и другой вариант. https://github.com/jjk-jacky/statusnotifier
Но он не имеет встроенного fallback'а, т.е. заморочится придется сильнее чем с appindicator, к тому же как я понял только для gtk3 версии.
А еще видать эту либу надо тащить к себе в проект.


Наверняка вы уже что-то думали по всему этому поводу, может поделитесь мыслями, соображениями по этому поводу? Стоит ли ждать вашей реализации, или таки попробовать наваять что-то самому? :)

**Comment by Alexey-Yakovenko** [comment]
@vovochka404 
Сожалею, но я ничего не думал по этому поводу, и никаких изменений в отношении индикаторов у меня нет.

**Comment by vovochka404** [comment]
А возражения?
Если я таки попробую прицепить appindicator?

**Comment by Alexey-Yakovenko** [comment]
возражения против чего конкретно, и почему они у меня должны возникнуть?

**Comment by Alexey-Yakovenko** [comment]
Switching to english..

I will explain my position on the Tray icon vs AppIndicators:

The tray icon in deadbeef is useful, because:
* you can control the volume (scrollwheel);
* pause/unpause (middle click);
* view the current track in tooltip (hover);
* hide/unhide the player (left click)
* access the mostly useless menu (right click).

Of this list, the indicators can only do the last item.

The problem is, the preferred way to do this in Ubuntu/Unity is using MPRIS to integrate with Ubuntu Sound menu.

This means, appindicator for deadbeef is not needed.

Now, am I missing something?

**Comment by Alexey-Yakovenko** [comment]
Another thing to note, @vovochka404 

The playback menu, which I guess is reason why you want the appindicator, is already accessible via the dock icon. Here's the screenshot from Ubuntu:

![](http://i.imgur.com/yXQR15l.png)

and I just added the same thing to OSX version:

![](http://i.imgur.com/t0DTNVm.png)

Is this thing not available in KDE?

**Comment by vovochka404** [comment]
#### About plasma5/KDE5
The main and only problem of tray icon in plasma5 is that it's absolutely absent.
[Old systray sticked to X11 is not supported any more](http://notmart.org/blog/2014/06/systemtray-plasma-next-and-gtk/)

![scr17](https://cloud.githubusercontent.com/assets/1563204/8197523/f88d9dd0-14d3-11e5-918c-88183d6dcfb6.png)


#### About appindicator limitations
[Appindicator](http://developer.ubuntu.com/api/devel/ubuntu-13.10/c/AppIndicator3-0.1.html) has scroll-event signal and secondary_activate_target (meny entry).
Yep, in fact it's really inconvenient, but better then nothing.

On the other hand i've proposed [another realization](https://github.com/jjk-jacky/statusnotifier) of [StatusNotifier](http://www.notmart.org/misc/statusnotifieritem/index.html) protocol.
It's more flexible, allows to control all events, but has no builtin fallback to a common tray icon.

**Comment by Alexey-Yakovenko** [comment]
So what about the dock icon menu and sound menu, similar to Unity? Is it supported on KDE? If not, then obviously KDE is going different route than everything else, and you might want to implement the appindicator to fill the gap. But that would mostly be KDE-specific feature.

**Comment by vovochka404** [comment]
Plasma have no dock by default (and never had).
Task bar has no any app specific menus.
Tray works just like always (except it doesn't support xembed-based icons and only works with SNI)
KMix must support Sound Menu (but it's about MPRIS, nothing related to icons).

**Comment by Alexey-Yakovenko** [comment]
But if there's kmix with sound menu -- why do you need another appindicator for deadbeef?

**Comment by vovochka404** [comment]
In fact i didn't now that kmix in kde5 has support for Sound Menu :)
Will check later when i'll be at home.

But it's inconvenient to work with player through kmix.
I want deadbeef to have it's common tray icon :)

**Comment by vovochka404** [comment]
And!
On the other hand currently:
1) deadbeef supports mpris through 3d party plugins.
2) deadbeef dies in opensuse 13.2 when this plugin is used.

**Comment by Alexey-Yakovenko** [comment]
> I want deadbeef to have it's common tray icon :)

App indicators do not replace or simulate system tray icons. Well, maybe they do in KDE, but definitely not in GNOME, Unity, or OSX (where they originated). Dock should be used instead. When there's no doc -- there's a problem. And I will repeat my question again :) What feature(s) of the system tray icon do you want to put in the appindicator? The menu is possible, and turned out that scroll wheel is possible. But nothing else.

If you want system tray -- you will have to use something that has system tray. Like XFCE, LXDE, MATE, etc.

> deadbeef dies in opensuse 13.2 when this plugin is used.

This is because the plugin is poorly implemented. Which doesn't mean nobody will make a better one which doesn't crash.

**Comment by vovochka404** [comment]
> App indicators do not replace or simulate system tray icons.

AppIndicator - is just a realization of StatusNotifier specification (but contains fallback to a common systray icon for environments without StatusNotifierWatchers).
The representation on StatusNotifierItems - is task of StatusNotifierHosts.
In unity the role of SNH played by dock.
In kde - by tray.
Their behavior is just the same.

> What feature(s) of the system tray icon do you want to put in the appindicator? The menu is possible, and turned out that scroll wheel is possible. But nothing else.

From the status notifier spec about signals:
ContextMenu - commonly rmb.
Activate - commonly lmb
SecondaryActivate - commonly mmb
Scroll - scroll
But activators depends on StatusNotifierHost

So, if custom realization will be used (not libappindicator) but the other one i've proposed then all current behavior will be saved. But the main problem of this custom realization is that it's looks like for gtk3.

**Comment by Alexey-Yakovenko** [comment]
I will try the statusnotifier demo app, and will get back to you.

**Comment by Alexey-Yakovenko** [comment]
I have tried to build the statusnotifier lib, and turned out it doesn't work on ubuntu 12.04. Do you know which linux distro it is compatible with, so that I can try it easily?

**Comment by vovochka404** [comment]
В чем выражается это "не работает"?
В осутствии иконки? Или оно умирает?
Иконки вероятно нет из-за того что эта реализация расчитана сугубо на StatusNotifier
И как я говорил, не имеет фолбека на стандартные иконки.
Т.е. если в 12.10 не запущено ни одно StatusNotifierHost - то конечно иконки не будет, ничего работать не будет.

Для того что бы это проверить - достаточно запустить qdbusviewer и фильтранунть сессию по status и убедится есть ли StatusNotifierWatcher и какой-нибудь StatusNotifierHost

Я знаю что это дело поддерживается лишь в kde4/5 и Unity (не знаю с какой версии).
Но может и не только...

**Comment by Alexey-Yakovenko** [comment]
> В чем выражается это "не работает"?

https://github.com/jjk-jacky/statusnotifier/issues/6

**Comment by vovochka404** [comment]
it's must be fixed in "next" branch

**Comment by Alexey-Yakovenko** [comment]
Yes, the "next" branch worked better. I built the lib, and the example. Running the example doesn't do anything though -- no icons appear in notification area. I'm running unity.

**Comment by vovochka404** [comment]
Have u seen help? Have specified icon via --icon?

**Comment by vovochka404** [comment]
And add --status active

**Comment by Alexey-Yakovenko** [comment]
I didn't know there's help :)

Running like this: ```./a.out -i /usr/share/icons/hicolor/48x48/apps/gdu-error.png -s active```

Still nothing happens.

I have tried many different ways to specify the icon name, full path, just the name, name.png -- nothing works.

**Comment by vovochka404** [comment]
-I -this must be a path to a file,
-i - must be an icon name.

Do u have StatusNotifierHost in your system?

**Comment by Alexey-Yakovenko** [comment]
> Do u have StatusNotifierHost in your system?

How do I find out? There's no such process.
I thought that this thing is a standard indicator, just implemented with another library.

**Comment by vovochka404** [comment]
It's dbusinterface.
check it via qdbusviewer.

I've described it in [this](#issuecomment-112761697) comment

**Comment by Alexey-Yakovenko** [comment]
ok that's more tricky. it requires to install qt4 devtools, and apt-get says it will take 4 hours. waiting for it.

**Comment by vovochka404** [comment]
Sorry for that... I don't know any other way to inspect current dbus session. :(

**Comment by Serranya** [comment]
> deadbeef dies in opensuse 13.2 when this plugin is used.

Are you talking about [my rewrite](https://github.com/Serranya/deadbeef-mpris2-plugin) of the MPRIS plugin ? If so please open a bug report.

**Comment by vovochka404** [comment]
> Are you talking about my rewrite of the MPRIS plugin ? If so please open a bug report.

Nope. Packman currently provides only [first](https://github.com/kernelhcy/DeaDBeeF-MPRIS-plugin) and unmaintained plugin

**Comment by Alexey-Yakovenko** [comment]
Checked in qdbusviewer, and I don't have any StatusNotifierHost. What does that mean? Do KDE and Unity use different protocols for indicators?

**Comment by Alexey-Yakovenko** [comment]
> Nope. Packman currently provides only first and unmaintained plugin

The deadbeef wiki links to the one @Serranya linked. Unfortunately, the app devs don't have any control what distribution maintainers put in their repositories.

**Comment by vovochka404** [comment]
> Unity use different protocols for indicators?

Nope. Looks like your current unity version does not support StatusNotifier. :(
May be u can try with cairo-dock? It also must [support](http://glx-dock.org/bg_topic.php?t=5664) StatusNotifier.

**Comment by Alexey-Yakovenko** [comment]
I tried running KDE, and the example worked, the icon appeared in there.

**Comment by Alexey-Yakovenko** [comment]
Yes, I can try cairo-dock, but that's useless, because the whole point of running the example was to see whether it will work in both KDE and Unity. It doesn't.

**Comment by vovochka404** [comment]
It doesn't work in your unity version.
And i've spoken about fallback to an old GtkStatusIcon several times.

libappindicator have a builting fallback support. This lib - doesn't.
So, when receiving "registration-failed" signal deadbeef should return to old behavior.

I've mentioned this as one of the problems of this lib, that fallback must be implemented by hands.
The second one - i don't think that  it'll be easy to port it to gtk2 (or may be it's easy, i don't know)

**Comment by Alexey-Yakovenko** [comment]
To me, looks like appindicator lib is a far better option then. Except it doesn't support mouse clicking etc.

The conclusion is: all libs are bad.

I'm not convinced thad deadbeef needs to have any of them integrated.

You're free to implement a deadbeef plugin for any of the libs though.

Hope I answered all of your questions.

**Comment by vovochka404** [comment]
Nope, you aren't :)
With plugin i won't be able to control common icon.

May be i can try to deal with gtk2 porting and creat a fallback functionality?

Will u accept such patch? Or plugin is the only way?

**Comment by Alexey-Yakovenko** [comment]
> With plugin i won't be able to control common icon.

Do you mean the tray icon? You're not supposed to control it.
The indicator is a separate thing from tray icon. They can even exist simultaneously.
The user will have to decide whether he wants the built-in tray icon, or the indicator.
Both need to be OFF by default.

> Will u accept such patch?

I can't tell whether I'd accept a patch before I see the patch.

> Or plugin is the only way?

Plugin is the only way either way -- patch or not.

**Comment by vovochka404** [comment]
A little bit oftop, will delete it later.
What ide do u use?

**Comment by Alexey-Yakovenko** [comment]
Depends on the OS... VisualStudio on windows, XCode on OSX, and I couldn't find any good IDE for linux, so just stick with VIM and GDB in xterm.

**Comment by vovochka404** [comment]
And here i'm back.

I'd like to discuss following [patch](https://github.com/Alexey-Yakovenko/deadbeef/compare/master...vovochka404:sni?expand=1)
It's a preview version :)

This patch adds modified version of statusnotifier lib.
It removes tray-related stuff from gtkui.c to tray_cmn.c|tray_sni.c.
It adds --enable-sni configure option.

The idea is to use tray_cmn when this flag is disabled and to use tray_sni if it's enabled.

tray_cmn have only GtkStatusIcon based realization.
tray_sni tries to initiate StatusNotifierItem and if fails - returns to GtkStatusIcon
But currently tray_sni is only possible way (in this preview).

Please, do not judge too strictly, i'm absolutely new to all this c/gtk stuff.
If this idea can survive (and accepted as a patch), please help me to make it :)
Any advises will be welcomed :)

If this idea is bad, please explain why :)

**Comment by Alexey-Yakovenko** [comment]
> If this idea is bad, please explain why :)

I'm not taking patches containing code under GPL 3. Usually I'm not taking GPL2 patches either.
That reason alone is enough, but I'll try to cover other reasons after I build and look at the result.

**Comment by vovochka404** [comment]
Hm... License... I'v forget about it :( (Russian mentality)

So okay, plugin... How it can be done? :(

**Comment by Alexey-Yakovenko** [comment]
Another reason:

> configure: error: dbusmenu-glib and dbusmenu-gtk is required for SNI support for gtk2ui plugin

GTKUI must remain compatible with computers running GTK2.12.x / GTK3.0.x and up.

When you add features adding hard dependencies which are not compatible with older systems -- it becomes impossible to make a single build, which is compatible with both new and old systems.

Making such feature a plugin makes it a _soft_ dependency. Which is possible to ship without breaking compatibility with older systems.

**Comment by vovochka404** [comment]
But this is not a hard dependency, it's a choice.
This "feature" is disabled by default (thus it doesn't require anything)  and a maintainer or user should decide whether he wants it or not.

**Comment by Alexey-Yakovenko** [comment]
It's a compile-time option versus runtime option. Users don't like compiling. When providing binary builds to them, they expect stuff to "just work".

**Comment by vovochka404** [comment]
And here a maintainer of a package in a distribution have to decide whether this feature is possible in this distribution or not. If distribution is compatible with this feature - why not to use it?

**Comment by Alexey-Yakovenko** [comment]
I need to generate the binary builds compatible with all distros, and the builds must have all deadbeef features included in them, configurable at runtime. As I already mentioned, we are talking about 2 completely independent separate use cases. Your approach would work for the users who build the app themselves, but not for the case when I build the app.

**Comment by vovochka404** [comment]
Don't know how this is done in a deb world, but in an rpm based something like this:
```spec
./configure ... \
%if %suse_version >= 1310
  --enable-sni \
%else
  --disable-sni \
%endif
```


But okay, хозяин - барин :)

How this trayicon replacement can be done via a plugin?

**Comment by Alexey-Yakovenko** [comment]
> Don't know how this is done in a deb world, but in an rpm based something like this:

It's probably done the same way, but I will repeat 3rd time -- you misunderstanding my point. You're talking about compile time configuration, while I'm talking about run-time.

> How this trayicon replacement can be done via a plugin?

The code would be exactly the same I guess. Just put into a separate plugin.
See how other plugins work.

**Comment by Alexey-Yakovenko** [comment]
You should not make your plugin _replace_ the system tray icon provided by GTKUI.

In fact, your plugin doesn't have to assume that GTKUI is even used.

Are there any functions in the statusnotifier code that has to interact with other app windows?

**Comment by vovochka404** [comment]
> The code would be exactly the same I guess. Just put into a separate plugin.
See how other plugins work.

But i'll have to remove current hardcoded GtkStatusIcon. Right?

> you misunderstanding my point.
Yes... That's true... from my point of your position looks like: all code must work in old distors, but if it's not working in a modern DE - it doesn't metter.

> Are there any functions in the statusnotifier code that has to interact with other app windows?
How about basic one: show/hide main window? :)
And as i understand, current popup menu is also a part of a gtkui. So it must be reimplemented in a separate plugin?

The other case:
gtkui knows nothing about sni plugin.
i'm disabling tray icon (because it's duplicates sni) and what is the default behavior for gtkui mainwindow on close? Yep... Exit. Not to hide to tray.

How can i control this behavior via plugin?

**Comment by vovochka404** [comment]
Also about current [GtkStatusIcon](https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html) - it's deprecated.
How long you will be able to use it?

**Comment by Alexey-Yakovenko** [comment]
> But i'll have to remove current hardcoded GtkStatusIcon. Right?

No. Why would you? Just leave it alone.

> Yes... That's true... from my point of your position looks like: all code must work in old distors, but if it's not working in a modern DE - it doesn't metter.

This is not correct. First of all, I disagree that it "doesn't work". As I explained at the top of this thread, it works correctly in Unity and OSX, the way it's designed to be, without using the tray icon.

KDE way is different from everything else, because it doesn't have the dock, but removes the system tray __at the same time__ (which no one else was doing AFAIK). Since this feature is _only_ useful in KDE -- it needs to be in a specialised kde-specific plugin.

Another thing you're wrong about is that "when it's not working it doesn't matter". No. My point is that when it's working it needs to be made into working, but not at the cost of breaking other things.

> How can i control this behavior via plugin?

By using the same config variables as GTKUI is using.

> How long you will be able to use it?

It's not going to disappear from GTK2 and GTK3.
It will most likely be removed in GTK4.
Hope that answers your question.

**Comment by vovochka404** [comment]
Ok, I'll go the plugin way...

> By using the same config variables as GTKUI is using.

But how about menu re-implementation and MainWindow show/hide?
I really don't know how to make this show/hide functionality via plugin.

Do you have any proposals how to control that there is no 2 icons at the same time?
Do not show sni when there is a common tray icon enabled? But in case of plasma5 it's just not seen.
Show sni just only in case of plasma5? :)

**Comment by Alexey-Yakovenko** [comment]
> But how about menu re-implementation and MainWindow show/hide?

If you only care about GTKUI, then you can use the GTKUI API for that. It exposes GtkWidget pointer of the main window, so you can query its state, and work off that.

```#include <deadbeef/gtkui_api.h>```

See more info about this [on the wiki here](https://github.com/Alexey-Yakovenko/deadbeef/wiki/Porting-GUI-plugins-to-deadbeef-from-0.5.x-to-0.6.0), the "Example2: deadbeef 0.6 only" is what you want, I believe.

> Do you have any proposals how to control that there is no 2 icons at the same time?

Do you have a repro how to get into this situation? are there DEs which have both tray and the indicators at the same time?

> Show sni just only in case of plasma5? :)

I suppose it would show as soon as your plugin is installed. Otherwise not shown.
And user could go in the plugin settings, and switch it off.

**Comment by vovochka404** [comment]
> Do you have a repro how to get into this situation? are there DEs which have both tray and the indicators at the same time?

KDE4 as minimum.
Supports old tray and SNI.

**Comment by Alexey-Yakovenko** [comment]
Well, in this case, it's unlikely that the users will want to install the SNI in the first place...

But if they just want to have SNI instead of tray - the best for them would be to open Preferences, and disable the tray icon.

**Comment by vovochka404** [comment]
> If you only care about GTKUI, then you can use the GTKUI API for that. It exposes GtkWidget pointer of the main window, so you can query its state, and work off that.
#include <deadbeef/gtkui_api.h>
See more info about this on the wiki here, the "Example2: deadbeef 0.6 only" is what you want, I believe.

Thanks for this.. Will investigate further and ask if something will be unclear to me :)

**Comment by vovochka404** [comment]
Hi, again :)
I've almost finished with my plugin and i have 2 questions.

1) would you mind to place two strings somewhere in your project for localization purpose?
I don't think it's wise to have separate *.po files.

2) I have many glib/gtk warnings, mainly related to:
1. (deadbeef:654): Gtk-WARNING **: Screen for GtkWindow not set; you must always set
2. css related stuff:
(process:654): Gtk-CRITICAL **: _gtk_css_rgba_value_get_rgba: assertion 'rgba->class == &GTK_CSS_VALUE_RGBA' failed

(process:654): Gtk-CRITICAL **: _gtk_css_rgba_value_get_rgba: assertion 'rgba->class == &GTK_CSS_VALUE_RGBA' failed


I do not see that you are specifying anything screen related for menu in gtkui.
And i don't understand where from this css related warnings are coming..

Can you help me with this?

**Comment by Alexey-Yakovenko** [comment]
1. In general, no. Plugin devs are supposed to localize their stuff on their own.
2. Looks like some GTK3 theme issue to me.

**Comment by vovochka404** [comment]
But what about "screen" stuff? Can you help with this?

You can check plugin [here](https://github.com/vovochka404/deadbeef-statusnotifier-plugin)

**Comment by Alexey-Yakovenko** [comment]
I know managing localization of your project is a huge task.
I'd say just keep it english-only for now.

> But what about "screen" stuff? Can you help with this?

I never seen this problem before. I think it's caused by your GTK3 theme.

**Comment by vovochka404** [comment]
And also, can you check (sni_update_tooltip)[https://github.com/vovochka404/deadbeef-statusnotifier-plugin/blob/master/src/sni.c]?
I'm afraid that there may be something wrong with memory managment... may be you can advise something?

**Comment by Alexey-Yakovenko** [comment]
There's a tool called [valgrind](http://valgrind.org/), which can find memory problems.

**Comment by vovochka404** [comment]
i'm a little bit afraid of that tooltip can be lager than 1000 bytes..

**Comment by Alexey-Yakovenko** [comment]
then use snprintf instead of sprintf, to make sure buffer doesn't overflow.
or calculate the precise buffer size from data, and allocate exactly how much is needed.

**Comment by snevolin** [comment]
В Fedora 22 plasma 5 по дефолту, и иконка в deadbeef просто не видна всем пользователям KDE. Без иконки пользоваться deadbeef неудобно. Как-то это всё-таки можно исправить?

**Comment by Alexey-Yakovenko** [comment]
@snevolin готового решения пока нет, но если собрать deadbeef из ветки statusnotifier -- там есть поддержка kde-трея.

**Comment by vovochka404** [comment]
@snevolin Попробуй использовать мой плагин: https://github.com/vovochka404/deadbeef-statusnotifier-plugin
Но он может и не завестись с последней версией gtk
По крайней мере у меня не заводится в opensuse tumbleweed, никак руки не дойдут переписать.
Но если ты согласен быть моим тестером/пользователем, я постараюсь исправить эту проблему побыстрее :)

**Comment by snevolin** [comment]
@vovochka404 Отписал ошибку в твой репозиторий

**Comment by vovochka404** [comment]
@Alexey-Yakovenko Можешь добавить ссылку на мой плагин к себе в wiki? :)
Может так же в G+ рассказать? :)

**Comment by Alexey-Yakovenko** [comment]
@vovochka404 сделал

**Comment by Alexey-Yakovenko** [comment]
@vovochka404  вообще в deadbeef уже есть штатный плагин для этого дела, но он немножко недоделан до релизного состояния. но в master, например, уже можно бы и смержить.

**Comment by vovochka404** [comment]
@Alexey-Yakovenko спасибо :) Я видел что шла какая-то активность в этом направлении и надеялся что в 7 версии он уже будет :) Но его не оказалось, а актуальность с каждым днём растёт :)

**Comment by Alexey-Yakovenko** [comment]
@vovochka404  в связи с тем, что оно не доделано -- его еще и в 0.7.1 не будет.

**Comment by vovochka404** [comment]
Жаль, жаль...
А можно в вики небольшое описание к плагину? А то ведь кто поймет что Status Notifier - это иконка в трее, а не какая-то уведомляшка о каких-то состояниях?
Что-нибудь типа: provices alternative tray icon (mainly for plasma5 DE)

**Comment by Alexey-Yakovenko** [comment]
Status Notifier / Alternative status icon / Appindicator -- так будет норм?

**Comment by vovochka404** [comment]
Большинству пользователей эти слова не о чем не говорят конечно. Но хоть в одном из вариантов есть слово icon :)

**Comment by Alexey-Yakovenko** [comment]
никто и никогда в линуксе не использует слово System Tray (в оригинале) - это перебежчики с винды притащили. но ок, добавлю.

**Comment by vovochka404** [comment]
Спасибо большое  :)

**Comment by Alexey-Yakovenko** [comment]
App indicator type status icons are now supported on master branch.

**Comment by xgdgsc** [comment]
This is supported? I 'm on archlinux with plasma desktop and doesn' t see tray icon.

**Comment by Alexey-Yakovenko** [comment]
@xgdgsc It used to work, but then something changed in how newer linux distributions handle the notification area, and the library which deadbeef used for this stopped working, so I had to disable it.

I'm waiting until linux distributions / DEs come to some common conclusion about how they want to do system tray / notification area, and provide some API to support it - I can't keep up with these changes.

**Comment by vovochka404** [comment]
@xgdgsc , can u try my [plugin](https://github.com/vovochka404/deadbeef-statusnotifier-plugin)?

**Comment by xgdgsc** [comment]
Thanks. Your plugin works well, I added an archlinux package.

**Comment by koroki** [comment]
> @xgdgsc , can u try my [plugin](https://github.com/vovochka404/deadbeef-statusnotifier-plugin)?

Thanks!
