### ISSUE TITLE
Tab container UI component

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#1182]
Original [issue 1281](https://code.google.com/p/ddb/issues/detail?id=1281) created by Alexey-Yakovenko on 2015-02-23T14:19:51.000Z:

Would it be possible to implement a tab container component like in foobar2000? It should work the same as the &quot;playlist with tabs&quot; component, except allowing the user to put other UI components on each tab.

Also, I'm quite impressed with the progress on deadbeef since I last tried configuring it, I'm almost able to replicate my foobar2000 layout now. Great job!

**Comment by Alexey-Yakovenko** [comment]
@cboxdoerfer is this done now?

**Comment by cboxdoerfer** [comment]
Yes. At least I don't know of any remaining issues.
