### ISSUE TITLE
5.1 channel .tak file crashes ddb with "corrupted double-linked list"

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#1193]
What steps will reproduce the problem?

1. play this specific 5.1ch 48kHz .tak file

What is the expected output? What do you see instead?

deadbeef crashes with "error in deadbeef: corrupted double-linked list" message either immediately, or after a few seconds of playing the file. Other 5.1ch files seem to be fine.

What version of the product are you using? On what operating system and CPU
architecture?

today's ddb git snapshot, arch x64

How did you install the product?

AUR

Please provide any additional information below.

ALSA or PulseAudio output doesn't seem to make any difference. Not a ffmpeg issue either, ffplay plays the file fine. This is the first time I'm playing this file on ddb, so I don't know if it's some kind of regression. foobar2000 was playing it fine, as well (and the file passes its integrity check). It doesn't matter if the file is a part of a large playlist or loaded alone.

Attaching the two crash reports. First one was when it crashed immediately, the second one was when it crashed after actually starting to play.

**Comment by Alexey-Yakovenko** [comment]
the original attached log is not very useful, seems to be showing glib memory corruption output without gdb.

**Comment by Soukyuu** [comment]
Hmm, well it's still happening even after reboot, and for some reason only this track is affected. I haven't had any unexpected crashes with other programs so far.

[Here](https://dl.dropboxusercontent.com/u/19330332/crashfile.tak) is the file in question (please tell me when you get it so I can remove the link).

**Comment by Alexey-Yakovenko** [comment]
got the file, thanks

**Comment by Alexey-Yakovenko** [comment]
The crash is triggered by av_free_packet call. Backtrace from release build below.
Need to make a debug build for better understanding..

```
#0  0xb7e47a3e in ?? () from /lib/i386-linux-gnu/libc.so.6
#1  0xb60b2fab in av_free ()
   from /home/waker/Downloads/deadbeef-0.6.2/plugins/ffmpeg.so
#2  0xb60aba4b in av_buffer_default_free ()
   from /home/waker/Downloads/deadbeef-0.6.2/plugins/ffmpeg.so
#3  0xb60abd9b in av_buffer_unref ()
   from /home/waker/Downloads/deadbeef-0.6.2/plugins/ffmpeg.so
#4  0xb6020c09 in av_free_packet ()
   from /home/waker/Downloads/deadbeef-0.6.2/plugins/ffmpeg.so
#5  0xb5ff2a89 in ?? ()
   from /home/waker/Downloads/deadbeef-0.6.2/plugins/ffmpeg.so
#6  0x0805fd52 in ?? ()
#7  0xb7f82d4c in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#8  0xb7ec0dde in clone () from /lib/i386-linux-gnu/libc.so.6
```
