### ISSUE TITLE
OSD: some characters not parsed correctly (',&, maybe more)

### ISSUE THREAD

**Issue by Soukyuu** [Alexey-Yakovenko/deadbeef#1195]
Running on KDE4SC, archlinux x64, deadbeef-git. If any tags contain ' or & it is shown on the OSD as HTML escape sequence instead of the actual character: `I&apos;ve` instead of `I've` for example.

**Comment by Alexey-Yakovenko** [comment]
Can't reproduce. ' and & show up in kde notifications as expected.
The only difference is that I'm was running ubuntu 12.04 when testing this.
Works correctly in Unity too.
Please report the bug to archlinux or KDE bug tracker.

**Comment by Soukyuu** [comment]
Looks like a regression in the latest KDE4 version. Considering KDE4 is EOL, that won't be fixed. Plasma seems to have fixed it partially: apostrophe is omitted, but ampersand shows up properly. I've created a [bug report](https://bugs.kde.org/show_bug.cgi?id=346710) for the issue.

**Comment by Soukyuu** [comment]
So [according to the KDE devs](https://bugs.kde.org/show_bug.cgi?id=346710#c1), the error with ' not appearing is on ddb side. I've tried sending the notifications manually, and the apostrophe appears for the same notification text where ddb strips it. Please have a look at it.

**Comment by mck182** [comment]
As the mentioned KDE dev, I'd like to update on this - this was an unexpected thing we've just discovered with QtQuick's Text when used with StyledText - it supports html3.2 entities only while &apos; is html4 entity. So we've now made sure that both ' and &apos; will always work.

**Comment by mck182** [comment]
Btw. that fix is for Plasma 5.3.1 only, it will not get backported to KDE4/Plasma4 as there are no more releases planned. That would have to be up on distributions to backport this patch, unfortunately.

**Comment by Alexey-Yakovenko** [comment]
> So according to the KDE devs, the error with ' not appearing is on ddb side.

Why is it working here then?

![works for me](https://cloud.githubusercontent.com/assets/1895698/7348626/61198b1a-ecf3-11e4-9e3c-bc5701f7964b.png)

**Comment by Alexey-Yakovenko** [comment]
I'll remove the code which escapes the ' as &apos; and see how it looks with other notification daemons.

**Comment by mck182** [comment]
If that's kde4, it uses a different system throughout. I don't know much about it tbh, I maintain only the Plasma5 one. Also, in Plasma5 it works fine in the title, the body is a problem (it's a different component).

**Comment by Alexey-Yakovenko** [comment]
@mck182 the 1st comment in this bug says "Running on KDE4SC".  My ubuntu has KDE 4.8.5, and the ```&apos;``` works fine, which means it was broken or removed in the later version. If unescaped ```'``` works with other notification daemons -- I'll unescape it.

**Comment by mck182** [comment]
There were many changes to the notification popup in the 4 series, in fact I myself changed it once to support some html stuff properly and I remember it got broken at some point after that. Then 4.9/4.10 (don't remember) featured a QML rewrite, so that may have changed it again.

Nevertheless, ' should work just fine, but keeping `&apos;` shouldn't be a problem either (and it's definitely safer, imo).

**Comment by Alexey-Yakovenko** [comment]
I tested in Unity and XFCE, both work with ```'``` and ```&apos;``` correctly. Tried removing all escaping ```<>"'``` etc, they still work... Looks like they are not trying to treat the content as XML/HTML anymore. But I'm keeping the escaping for everything except the ```'``` to maximize compatibility.

**Comment by Alexey-Yakovenko** [comment]
Another possible reason why it works now, while it didn't work before, is because of the new libdbus... I send the content using dbus_message_append_args argument of type DBUS_TYPE_STRING. Might be that libdbus devs added automatic escaping there some time ago.

**Comment by Alexey-Yakovenko** [comment]
This build has the fix
https://drone.io/github.com/Alexey-Yakovenko/deadbeef/538

**Comment by Soukyuu** [comment]
Well, with that build the only thing not working on KDE4 is the `&amp;`

On plasma-workspace-git everything works fine now, so it's fixed for the maintained version I guess.

**Comment by Alexey-Yakovenko** [comment]
The original NotifyOSD specification says that implementations must support all of them, including the ```&apos;```.

Look here: https://wiki.ubuntu.com/NotifyOSD#Sanitizing_body_text

There's the recommendation to escape at least the ```<>&``` characters.

So definitely looks like a bug in the KDE implementation.

**Comment by Soukyuu** [comment]
Since it's a bug in the old KDE4 implementation, there is nothing you can do. It's a legacy release by now, once everyone moves on to plasma, it will solve itself. Thanks for fixing the apostrophe.

**Comment by Alexey-Yakovenko** [comment]
Np. I disagree though that fixing the apostrophe was the right thing to do (that means supporting broken implementation, and possibly causing _correct_ implementations to break).
If we see regressions -- I will most likely revert the "fix", or make it configurable.

**Comment by Soukyuu** [comment]
Well actually, the apostrophe is working in plasma even without the fix on your side - there was a bug on KDE's side that made the apostrophe not show up for ddb and amarok. Now that it is fixed on that side, the problem will fix itself as soon as 5.3.1 is released. 

Personally, I'm not that bothered about it, so you could revert the fix at any time.

**Comment by Alexey-Yakovenko** [comment]
Then I will just do it.

**Comment by mck182** [comment]
Fwiw, the "original" freedesktop notification specification is at http://www.galago-project.org/specs/notification/0.9/index.html and that's the one KDE4 (and everyone else) implements. And this one does not say anything about 's. 

That NotifyOSD is Ubuntu-only specification, nobody else adopted it afaik.

**Comment by Alexey-Yakovenko** [comment]
Thanks for the info. It looks, however, that everyone except KDE (and including KDE4 in the past) implemented the Ubuntu's text sanitisation recommendation. Some implementations in the past failed to display the text correctly, if the XML reserved characters were not escaped. But that was several years ago.

**Comment by Alexey-Yakovenko** [comment]
It looks though that the apostrophe is not one of the problematic characters. So it might be safe to keep it.
