### ISSUE TITLE
DDB jumps between playlists if same song is contained in both and the 2nd one is focused

### ISSUE THREAD

**Issue by Soukyuu** [Alexey-Yakovenko/deadbeef#1198]
I'm not sure if it's the intended behavior. 

Currently, if you have a song playing in one playlist, and editing another one which also contains this song, ddb will jump from playing the first playlist to the one you are editing once the song is over finishes.

- deadbeef-git on arch x64

**Comment by cboxdoerfer** [comment]
Can't reproduce this behavior. What playback options do you have set (order, looping ...)?

**Comment by Soukyuu** [comment]
Hmm. I think I know what happened. I actually drag&dropped the files that were in playlist A to playlist B and it moved the tracks, which I didn't notice. The files are now part of the playlist B, so the behavior makes sense.

Bonus question, is there a way to _copy_ not move the songs between playlists? fb2k way of ctrl+c ctrl+v doesn't seem to work.

**Comment by Alexey-Yakovenko** [comment]
you can copy by holding ctrl key while drag-dropping.

copy&paste is on the way, @cboxdoerfer is working on it.

**Comment by Soukyuu** [comment]
great, thanks for the heads-up
