### ISSUE TITLE
[suggestion] "Load playlist" should create a new playlist, not overwrite by default

### ISSUE THREAD

**Issue by Soukyuu** [Alexey-Yakovenko/deadbeef#1199]
Currently, when you load a playlist, it will replace the contents of the currently selected playlist. IMHO, when one loads a playlist, the usual intention is to add it to the list of playlists, not overwrite an already loaded one. 

Could you please make deadbeef automatically create a new playlist and load the playlist into it? The name could be set to the name of the playlist file.

**Comment by Alexey-Yakovenko** [comment]
I don't think so. The purpose of the "load playlist" is to load the playlist file contents into the current tab.
Perhaps it would make sense for some people to have another menu item "load playlist in new tab", but adding features like this will just bloat menus to much.

**Comment by Soukyuu** [comment]
I guess that's just different opinions. Please consider setting the playlist name to the playlist file name instead of leaving it as "new playlist" at least.
