### ISSUE TITLE
Quietly skip unsupported files when adding them from cli

### ISSUE THREAD

**Issue by anlar** [Alexey-Yakovenko/deadbeef#1204]
If you launch deadbeef and add to it's parameters several files, it will fail to add them all if at least one of them is unsupported media file. But if you add them as a folder it will just skip all non-media files and load everything else.

E.g, there is the following dir structure:

```
test-dir/
├── 01.mp3
├── 02.mp3
└── info.png
```

Now `deadbeef test-dir` will load all mp3 files, but `cd test-dir && deadbeef *` will fail with:

```
playlist load fail (/tmp/test-dir/info.png)!
failed to add file or folder /tmp/test-dir/info.png
```

**Comment by andreas--e** [comment]
Does `cd test-dir && deadbeef *.mp3` work for you at least?
