### ISSUE TITLE
Cover Artwork Not Showing in 0.6.2 (LMDE 2 Betsy MATE 32bit)

### ISSUE THREAD

**Issue by atarax42** [Alexey-Yakovenko/deadbeef#1210]
I added the artwork column to the deadbeef track list. I open a playlist and play a track but the artwork is not showing. There is also no default placeholder image for the album cover. The cover image (cover.jpg) is embedded in the mp3 file and can also be found in the album folder. In the plugin settings both 'read from embedded tags' and 'read from local directory' are enabled. When launching deadbeef from the terminal I can see that the plugin /usr/lib/i386-linux-gnu/deadbeef/artwork.so is found and loaded.
![bildschirmfoto](https://cloud.githubusercontent.com/assets/2667824/7435377/87ec1ec6-f043-11e4-8b91-2a3411703e87.png)

**Comment by Alexey-Yakovenko** [comment]
Please read the help. Accessible from the Help menu. It explains how to make cover art display in the playlist.

**Comment by atarax42** [comment]
Thanx! Sorry for stealing your time...
