### ISSUE TITLE
Request: To Change cache /path

### ISSUE THREAD

**Issue by meuwe** [Alexey-Yakovenko/deadbeef#1211]
Hi,

It's always been my understanding in Linux that in the $HOME users directory ```/home/user/.cache``` this is just a temporary directory of cache being temporarily stored, while an application is in use.

Take the application ```Bleachbit``` as an example for system cleaning, it cleans the cache by default in Linux.

Can you please remove the  ```/home/user/.cache/deadbeef``` path that contains the ```bio``` ```covers``` and ```lyric``` and place them instead into ```/home/user/.config/deadbeef```?

thank you

**Comment by Alexey-Yakovenko** [comment]
1. Your understanding doesn't seem to be correct.
2. You can change the deadbeef's cache folder location using the XDG_CACHE_HOME environment variable, as specified by [freedesktop's basedir spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

This is what the spec says:

> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

Nothing about that the app must clean it on exit.

**Comment by meuwe** [comment]
I know a cache could be used as something more permanent, but I've also seen in my computer years that caches are something also for just the temporary storage of files/folders, otherwise how do we explain applications like CCleaner & Bleachit, which happen to clean out the cache /paths?

So if I use XDG_CACHE_HOME, can I do this just for changing deadbeef only?

Would it be difficult to just have ```bio``` ```covers``` and ```lyric``` placed /home/user/.config/deadbeef?
This isn't so difficult to do is it? Because these three directories, does deadbeef use the cache for any other things, or many other things? Again, I don't understand why you can't have everything live under the ~/.config/deadbeef path?

thank you

**Comment by Alexey-Yakovenko** [comment]
> how do we explain applications like CCleaner & Bleachit, which happen to clean out the cache /paths?

Why do we need to explain this? Cleaning up the cache is not forbidden, and their cache is not required to persist between sessions - that is why.

> So if I use XDG_CACHE_HOME, can I do this just for changing deadbeef only?

Yes, you just run deadbeef like this: ```XDG_CACHE_HOME=$HOME/mycachefolder deadbeef```

> Would it be difficult to just have bio covers and lyric placed /home/user/.config/deadbeef?

It is simple. See above.

> Again, I don't understand why you can't have everything live under the ~/.config/deadbeef path?

I can: ```XDG_CACHE_HOME=$HOME/.config/deadbeef/cache deadbeef```

But doing this by default would not be correct. Cache is not a part of configuration.

**Comment by Alexey-Yakovenko** [comment]
FYI
> a temporary directory of cache being temporarily stored, while an application is in use.

This is what /tmp is for. Deadbeef is using this where appropriate. Cache is different.

**Comment by meuwe** [comment]
Thank you for your help and time Alexey :)

**Comment by Alexey-Yakovenko** [comment]
What exactly do you mean by "can't get it to work"? What happens if you do it?

I don't know how to show this... It's supposed to "just work".

**Comment by meuwe** [comment]
I tried this two ways;

```XDG_CACHE_HOME=$HOME/.config/deadbeef/cache deadbeef```
and
```XDG_CACHE_HOME=/home/user/.config/deadbeef/cache```

Then I started deadbeef two times with these changes and it created a ```deadbeef``` directory in the $HOME/.cache

**Comment by Alexey-Yakovenko** [comment]
You just need to literally type this in the terminal:
```
XDG_CACHE_HOME=$HOME/.config/deadbeef/cache deadbeef
```

**Comment by meuwe** [comment]
Ok,

I'm trying to get this to work in ```$HOME/.config/user-dirs.dirs``` The ```user-dirs.dires``` is my understanding where to place XDG related info...

Placing ```XDG_CACHE_HOME=$HOME/.config/deadbeef/cache deadbeef``` in the user-dirs.dirs does nothing, this is what I'd like to figure out...

Should this work in the ```user-dirs.dirs?

thanks

**Comment by cboxdoerfer** [comment]
No, like Alexey said, you only need to type this `XDG_CACHE_HOME=$HOME/.config/deadbeef/cache deadbeef` in the terminal, that's all you need to do. Just make sure you closed deadbeef before you do that.

**Comment by meuwe** [comment]
Terminal I understood...

Why will this not work in ```user-dirs.dirs```? That is a standard for XDG...

The ```user-dirs.dirs``` is where I keep all my XDG entries to keep track of, and I'd like to be able to do it this way.

So there is no way to do this in the ```user-dirs.dirs```?

**Comment by cboxdoerfer** [comment]
Because you don't want to override `XDG_CACHE_HOME` for every application. Or do you want firefox or chromium to write their cache in `$HOME/.config/deadbeef/cache`?

You want to modify only deadbeefs environment and Alexey told you one proper way how to do that. And like I said, if you want that to work with your application starter you probably need to edit deadbeefs desktop file. Just place a copy of that in `~/.local/share/applications/` and add the environment variable there.

**Comment by meuwe** [comment]
I see what you're saying, I was wondering this too, by placing in ```user-dirs.dirs```, if this can be done just for one application, but I guess not.

So when you said add alias to the deadbeef.desktop do I do it like this?

```alias XDG_CACHE_HOME=$HOME/.config/deadbeef/cache deadbeef```

thanks

**Comment by Alexey-Yakovenko** [comment]
@meuwe 

Asking about every simple thing like this on the bug tracker won't get you far.
I can't believe that you couldn't figure this out for 10 days now.
Try reading the relevant sections of the bash manual. And regarding the .desktop -- you're supposed to be running some sort of desktop environment, like XFCE or GNOME or KDE, all of them have UI tools for creating launchers, desktop shortcuts, etc. That's what .desktop files are.
Come on, creating a shortcut which sets the variable and runs a program can't be THAT hard, right?

**Comment by meuwe** [comment]
Sorry for being lazy you're right Alexey.

THANKS! :)
