### ISSUE TITLE
Various Artists Albums are messed up

### ISSUE THREAD

**Issue by Okanda** [Alexey-Yakovenko/deadbeef#1221]
Hello. 

I didn't find anything about that in the Issues. 

When by "Artist/Year/Album" is selected in grouping options, the various artists albums are shown not grouped. 
They are grouped track by track. 

See screenshots for more detail, it's been a long time I wrote in english! Don't know if I'm clear! 

Deadbeef is really great. Thank you for your good work. 

![capture_1deadbeef](https://cloud.githubusercontent.com/assets/12570903/7787404/b5c99d0e-020a-11e5-8d1a-31886cc075a8.png)
![capture_2deadbeef](https://cloud.githubusercontent.com/assets/12570903/7787412/1158c58c-020b-11e5-8d8f-4600b5194a69.png)

**Comment by Alexey-Yakovenko** [comment]
You should use album artist instead of the artist.
Try group by -> custom -> ```%B-%y-%b```

**Comment by Okanda** [comment]
Works like a sharm. 

Thank you.
