### ISSUE TITLE
Global hotkeys not working properly with new gnome media-keys handling

### ISSUE THREAD

**Issue by tglarner** [Alexey-Yakovenko/deadbeef#1223]
After an update from debian wheezy to jessie including gnome, the hotkey feature seems to be broken. By default, deadbeef does not react to any use of the media keys anymore.

However, if I disable the media-keys handling in org.gnome.settings-daemon.plugins.media-keys using the dconf-editor, everything is fine again - at least for deadbeef. It even works if I disable not the handling in its entirety but specific keys there.
Of course, this setting breaks the media keys support for other applications.

I experienced this issue in gnome3 and gnome-flashback with the current deadbeef version v0.6.2.

**Comment by Alexey-Yakovenko** [comment]
It's always been like this, and it's not fixable. Sorry.
