### ISSUE TITLE
Pulseaudio mutes DeaDBeeF at the start of new songs, at random

### ISSUE THREAD

**Issue by Cronanius** [Alexey-Yakovenko/deadbeef#1225]
I'm not sure if this is a pulseaudio problem or bug with deadbeef, so I'll start here because I have no idea how to go about troubleshooting this myself. The problem is as follows: whenever I deliberately "play" a new song, go forward or back in a playlist, Pulseaudio (which I'd like to point out that I hate, but everything uses it now) mutes the output of deadbeef. It also does this randomly at the start of a new song being played (sometimes it mutes, sometimes it doesn't). I'm running a 64-bit (multilib) install on a fresh install of Funtoo (which is basically Gentoo) linux.

**Comment by Alexey-Yakovenko** [comment]
Gentoo forums should be more helpful on the topic, or google for something like "pulseaudio auto mute". Even if automute is not the problem, it should give you some directions where to look for other pulseaudio settings/plugins/etc.
