### ISSUE TITLE
0.6.2 gtk-button=larger buttons, smaller icon tray

### ISSUE THREAD

**Issue by Geyup** [Alexey-Yakovenko/deadbeef#1228]
Hi,

I compiled 0.6.2 from source.

My Specs:
Slackware 14.1 x86_64
Openbox 3.6
tint2

I use .gtkrc-2.0.mine to change sizes for button and toolbars, etc., below is the contents of it;
```
gtk-icon-sizes = "panel-menu=16,16:panel=16,16:gtk-menu=16,16 \
:gtk-large-toolbar=28,28:gtk-small-toolbar=28,28:gtk-button=28,28"
```
If I change the ```gtk-button=28,28``` size to 28, the system tray icon appears smaller,  but the toolbar buttons, stop, play, pause, etc., the appear bigger.

If I change the ```gtk-button=24,24``` size to 24, the system tray icon appears normal size, but the toolbar buttons appear smaller.

I don't understand why changing the ```gtk-button=28,28``` size larger makes the system tray toolbar smaller, and not stay normal size?

**Comment by Alexey-Yakovenko** [comment]
The GTK theming questions do not belong here. Unlikely that anybody will be able to answer them here.

**Comment by Geyup** [comment]
Sorry I did not explain better, I thought you would understand that deadbeef does not have any Preferences options to make any toolbar or button changes.

SInce it doesn't, the end-user needs to either do this by hand on small window managers, and I thought maybe someone could lend help to this problem, since deadbeef lacks the options.

thank you
