### ISSUE TITLE
cdda, slackware: libcdda_paranoia compile error

### ISSUE THREAD

**Issue by Geyup** [Alexey-Yakovenko/deadbeef#1232]
I just grabbed from git today;

```git clone https://github.com/Alexey-Yakovenko/deadbeef.git```

I have these versions of libs;
```libcddb-1.3.2-x86_64-2  libcdio-0.83-x86_64-1```

deadbeef fails to compile with cdda errors;

make[2]: Entering directory `/tmp/foo/deadbeef-0.6.2/plugins/wavpack'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/tmp/foo/deadbeef-0.6.2/plugins/wavpack'
Making all in plugins/sndfile
make[2]: Entering directory `/tmp/foo/deadbeef-0.6.2/plugins/sndfile'
  CC     sndfile.lo
  CCLD   sndfile.la
make[2]: Leaving directory `/tmp/foo/deadbeef-0.6.2/plugins/sndfile'
Making all in plugins/vfs_curl
make[2]: Entering directory `/tmp/foo/deadbeef-0.6.2/plugins/vfs_curl'
  CC     vfs_curl.lo
  CCLD   vfs_curl.la
make[2]: Leaving directory `/tmp/foo/deadbeef-0.6.2/plugins/vfs_curl'
Making all in plugins/cdda
make[2]: Entering directory `/tmp/foo/deadbeef-0.6.2/plugins/cdda'
  CC     cdda.lo
cdda.c:27:32: fatal error: cdda_interface.h: No such file or directory
     #include <cdda_interface.h>
                                ^
compilation terminated.
make[2]: *** [cdda.lo] Error 1
make[2]: Leaving directory `/tmp/foo/deadbeef-0.6.2/plugins/cdda'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/foo/deadbeef-0.6.2'
make: *** [all] Error 2

**Comment by Alexey-Yakovenko** [comment]
You need to either install libcdda_paranoia, or use ```--disable-cdda-paranoia``` configure flag.
For some reason, this is not autodetected, I'll fix when I have some time.

**Comment by Alexey-Yakovenko** [comment]
I just verified that cdparanoia detection is there, and it works correctly. You probably have the cdparanoia libs installed, but not the dev packages.

**Comment by Geyup** [comment]
Hi Alexey,

You shouldn't jump so quick to close reports assuming end-user error.

I'm a Slackware user, been running it and compile software and packaging it 15 years, when I make a bug report, I do so, because I know there is a problem.

Slackware does not dividie packages up into dev packages, when you get a package in slackware everything is in it for compiling.

```
cdparanoia-III_10.2-x86_64-1

usr/
usr/doc/
usr/doc/cdparanoia-III-10.2/
usr/doc/cdparanoia-III-10.2/COPYING-LGPL
usr/doc/cdparanoia-III-10.2/COPYING-GPL
usr/doc/cdparanoia-III-10.2/README
usr/include/
usr/include/cdda/
usr/include/cdda/cdda_interface.h
usr/include/cdda/cdda_paranoia.h
usr/include/cdda/utils.h
usr/bin/
usr/bin/cdparanoia
usr/man/
usr/man/man1/
usr/man/man1/cdparanoia.1.gz
usr/man/jp/
usr/man/jp/man1/
usr/man/jp/man1/cdparanoia.1.gz
usr/lib64/
usr/lib64/libcdda_paranoia.a
usr/lib64/libcdda_interface.so.0.10.2
usr/lib64/libcdda_interface.a
usr/lib64/libcdda_paranoia.so.0.10.2
install/
install/doinst.sh
install/slack-desc
```

deadbeef 0.6.2 compiles and installs fine.

Here's also the output from the latest git branch, showing it'd detecting cdparanoia;

```
checking for main in -lcdio... yes
checking for main in -lcddb... yes
checking for main in -lcdda_interface... yes
checking for main in -lcdda_paranoia... yes

Plugin Summary:
cdda: yes - cd audio player
```

**Comment by Geyup** [comment]
Sorry I edited out all the things I was saying in my last reply, I didn't want you to think I was acting rude, or big head, there is some issue going on with the latest git...

thank you

**Comment by Geyup** [comment]
Hi Alexey,

Here's a patch for users that might have the headers in /usr/include/cdda/

https://gist.github.com/Geyup/ba1fc709586918bf8e5b

**Comment by Alexey-Yakovenko** [comment]
> I hope you didn't close this because you thought end-user error?

I always close immediately as soon as I think that the question or bug is resolved. Users often don't come back after the initial post.

> deadbeef 0.6.2 compiles and installs fine, but the latest git branch fails.

cdparanoia libs support was added after 0.6.2

anyway, thanks for investigation, I'll have a look at the patch.

**Comment by Geyup** [comment]
Oh yes, I always come back, until it's truly dead, I'm a Slacker :)

Cheers

**Comment by Alexey-Yakovenko** [comment]
Should work now, please try.

**Comment by Geyup** [comment]
After submitting the patch I started to realize to make it the way you did, hehe... :)

All good now...

Cheers
