### ISSUE TITLE
Настраиваемый список обязательных тегов

### ISSUE THREAD

**Issue by vegasd** [Alexey-Yakovenko/deadbeef#1234]
В «Свойства дорожки» и в показе тегов сейчас отображается определённый набор тегов: Исполнитель, Название дорожки, Альбом, Композитор и другие. Дальше идут все остальные теги так, как они прописаны в файле (например в ogg и flac можно писать их в разном регистре, обычно пишут капсом). «Обязательные» теги отображаются всегда, даже если они пустые, и они переведены на разные языки. Теги ниже, соответственно, никак не переводятся. Хотелось бы возможноть либо настроить этот список обязательных тегов и их «перевод» (например ORGANIZATION=Лейбл наряду с ARTIST=Исполнитель), либо же просто отключать «обязательные», дабы отображались всегда все те (и только те) теги, которые прописаны в медиафайле так, как они там прописаны (то есть, без перевода).

**Comment by mallniya** [comment]
Плюс это помогает при вводе новых данных в нестандартные тэги -- вместо того, чтобы вводить каждый раз имя нестандартного тэга и только потом его значение -- этот тэг можно будет захардкодить. Сэкономит кучу времени и нервов. Крайне желательная фича.

**Comment by mallniya** [comment]
Кстати, не дубль ли это  #1164?

**Comment by Alexey-Yakovenko** [comment]
угу, спасибо
