### ISSUE TITLE
Tear down and replace SourceForge page

### ISSUE THREAD

**Issue by niedzielski** [Alexey-Yakovenko/deadbeef#1237]
I just found this GitHub repo when poking around the SourceForge site. I had assumed the project was dead (no pun intended) because the official site is hosted on SourceForge and they have a terrible reputation. My ad blocker actually requires explicit permission to visit any SF page. Please consider GitHub Pages or another alternative for hosting the site so people can see it's alive and well.

**Comment by Alexey-Yakovenko** [comment]
It had been considered, and refused, because github doesn't provide full replacement of the necessary features. If you're interested in continuing this discussion, please do so in a more appropriate place -- e.g. one of our IRC channels.
