### ISSUE TITLE
Missing Prereq

### ISSUE THREAD

**Issue by apapdev007** [Alexey-Yakovenko/deadbeef#1238]
You might want to add libjansson4 and libjansson-dev to the prerequisites listed in your MD file. My system didn't have them already installed.

checking for JANSSON... no
configure: error: Package requirements (jansson) were not met:

No package 'jansson' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables JANSSON_CFLAGS
and JANSSON_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by Alexey-Yakovenko** [comment]
all the dependencies are listed in the [README](https://github.com/Alexey-Yakovenko/deadbeef/blob/master/README) file

The README.md file is just a short project page for github.
