### ISSUE TITLE
Player crashes when a .m4a file is added

### ISSUE THREAD

**Issue by silverweed** [Alexey-Yakovenko/deadbeef#1239]
Deadbeef is crashing with a "Floating point exception" when either a .m4a file or a folder containing a .m4a file is added to the playlist.

Apparently, this only happens with files which the UNIX `file` command detects as: `(Audio Only).m4a: ISO Media` (with nothing else after "ISO Media"). For example, it doesn't happen with "Apple iTunes ALAC/AAC-LC (.M4A) Audio" files.

**OS**: Debian stretch (testing)

**Deadbeef version**: deadbeef 0.5.6, from Debian testing repository

**Steps to reproduce**:  
- open deadbeef
- add a .m4a file
- (Floating point exception)

`gdb` points out `/usr/lib/x86_64-linux-gnu/deadbeef/aac.so` as the crashing point (obviously I can't tell much more than this since I'm running the repository binary without the debugging symbols enabled).

**Comment by Alexey-Yakovenko** [comment]
Do you have an example file? or at least a call stack?
