### ISSUE TITLE
deadbeef on latest GTK crashed when I try open "Add file(s)" or "Add folder(s)" dialog 

### ISSUE THREAD

**Issue by NTMan** [Alexey-Yakovenko/deadbeef#1241]
deadbeef on latest GTK crashed when I try open "Add file(s)" or "Add folder(s)" dialog 

$ rpm -q gtk3
gtk3-3.17.6-1.fc23.x86_64

Demonstration: https://drive.google.com/file/d/0B0nwzlfiB4aQRk5WREgtN1FkUUU/view?usp=sharing (please use Google Chrome for HD quality)

$ Downloads/deadbeef-0.6.2/deadbeef
starting deadbeef 0.6.2 [static] [portable]
server_start
searching for GUI plugins in /home/mikhail/.local/lib64/deadbeef
searching for GUI plugins in /home/mikhail/.local/lib/deadbeef
searching for GUI plugins in /home/mikhail/Downloads/deadbeef-0.6.2/plugins
plug_load_all: scandir found 51 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/ddb_gui_GTK3.so
loading plugins from /home/mikhail/.local/lib64/deadbeef
loading plugins from /home/mikhail/.local/lib/deadbeef
loading plugins from /home/mikhail/Downloads/deadbeef-0.6.2/plugins
plug_load_all: scandir found 51 files
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/aac.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/adplug.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/alac.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/alsa.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/artwork.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/cdda.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/converter.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/converter_gtk2.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/converter_gtk3.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/dca.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/ddb_ao.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/ddb_dumb.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/ddb_mono2stereo.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/ddb_shn.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/dsp_libsrc.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/ffap.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/ffmpeg.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/flac.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/gme.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/hotkeys.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/lastfm.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/m3u.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/mms.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/mpgmad.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/musepack.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/notify.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/nullout.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/oss.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/pltbrowser_gtk2.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/pltbrowser_gtk3.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/pulse.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/shellexec.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/shellexecui_gtk2.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/shellexecui_gtk3.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/sid.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/sndfile.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/supereq.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/tta.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/vfs_curl.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/vfs_zip.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/vorbis.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/vtx.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/wavpack.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/wildmidi.so
loading plugin /home/mikhail/Downloads/deadbeef-0.6.2/plugins/wma.so
libWildMidi(WM_BufferFile:640): ERROR Unable to stat /etc/timidity/freepats/freepats.cfg (No such file or directory)
selected output plugin: ALSA output plugin
INFO: loading playlist Music
INFO: from file /home/mikhail/.config/deadbeef/playlists/0.dbpl
INFO: loading playlist VA - Queen Dance Traxx I - 1996
INFO: from file /home/mikhail/.config/deadbeef/playlists/1.dbpl
INFO: loading playlist DORO & Warlock
INFO: from file /home/mikhail/.config/deadbeef/playlists/2.dbpl
INFO: loading playlist Celldweller (FLAC)
INFO: from file /home/mikhail/.config/deadbeef/playlists/3.dbpl
INFO: loading playlist New Playlist (2)
INFO: from file /home/mikhail/.config/deadbeef/playlists/4.dbpl
INFO: loading playlist 22
INFO: from file /home/mikhail/.config/deadbeef/playlists/5.dbpl
INFO: loading playlist New Playlist (4)
INFO: from file /home/mikhail/.config/deadbeef/playlists/6.dbpl
INFO: loading playlist New Playlist (5)
INFO: from file /home/mikhail/.config/deadbeef/playlists/7.dbpl
INFO: loading playlist Electric Lady Lab - Flash - (2011)
INFO: from file /home/mikhail/.config/deadbeef/playlists/8.dbpl
INFO: loading playlist Scorpions Discography ALAC
INFO: from file /home/mikhail/.config/deadbeef/playlists/9.dbpl
INFO: loading playlist New Playlist (6)
INFO: from file /home/mikhail/.config/deadbeef/playlists/10.dbpl
INFO: loading playlist DBT
INFO: from file /home/mikhail/.config/deadbeef/playlists/11.dbpl
INFO: loading playlist 11
INFO: from file /home/mikhail/.config/deadbeef/playlists/12.dbpl
INFO: loading playlist Celldweller
INFO: from file /home/mikhail/.config/deadbeef/playlists/13.dbpl
INFO: loading playlist Crypt of the NecroDancer by Danny Baranowsky (2014) [MP3, 192]
INFO: from file /home/mikhail/.config/deadbeef/playlists/14.dbpl
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 3.0.0

(deadbeef:11917): GLib-GObject-WARNING **: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
connecting button tray signals

(deadbeef:11917): GLib-GObject-WARNING **: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.

(deadbeef:11917): GLib-GObject-WARNING **: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
gtkui: found cover-art loader plugin

(deadbeef:11917): Gtk-CRITICAL **: Error building template class 'GtkFileChooserWidget' for an instance of type 'GtkFileChooserWidget': .:274:1 Invalid object type 'GtkPlacesView'

(deadbeef:11917): Gtk-CRITICAL **: gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_gesture_long_press_new: assertion 'GTK_IS_WIDGET (widget)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_gesture_single_set_touch_only: assertion 'GTK_IS_GESTURE_SINGLE (gesture)' failed

(deadbeef:11917): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(deadbeef:11917): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(deadbeef:11917): GLib-GObject-CRITICAL **: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed

(deadbeef:11917): GLib-GObject-CRITICAL **: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_view_get_selection: assertion 'GTK_IS_TREE_VIEW (tree_view)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_selection_set_select_function: assertion 'GTK_IS_TREE_SELECTION (selection)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_view_enable_model_drag_source: assertion 'GTK_IS_TREE_VIEW (tree_view)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_drag_source_get_target_list: assertion 'GTK_IS_WIDGET (widget)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_drag_source_set_target_list: assertion 'GTK_IS_WIDGET (widget)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_drag_dest_set: assertion 'GTK_IS_WIDGET (widget)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_drag_dest_get_target_list: assertion 'GTK_IS_WIDGET (widget)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_drag_dest_set_target_list: assertion 'GTK_IS_WIDGET (widget)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_view_set_search_column: assertion 'GTK_IS_TREE_VIEW (tree_view)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_view_column_set_sort_column_id: assertion 'GTK_IS_TREE_VIEW_COLUMN (tree_column)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_view_column_set_sort_column_id: assertion 'GTK_IS_TREE_VIEW_COLUMN (tree_column)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_view_column_set_sort_column_id: assertion 'GTK_IS_TREE_VIEW_COLUMN (tree_column)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_view_column_set_sort_column_id: assertion 'GTK_IS_TREE_VIEW_COLUMN (tree_column)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_view_column_set_attributes: assertion 'GTK_IS_TREE_VIEW_COLUMN (tree_column)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_view_column_set_attributes: assertion 'GTK_IS_TREE_VIEW_COLUMN (tree_column)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_view_column_set_attributes: assertion 'GTK_IS_TREE_VIEW_COLUMN (tree_column)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_view_column_set_attributes: assertion 'GTK_IS_TREE_VIEW_COLUMN (tree_column)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_view_column_set_attributes: assertion 'GTK_IS_TREE_VIEW_COLUMN (tree_column)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_tree_view_column_set_attributes: assertion 'GTK_IS_TREE_VIEW_COLUMN (tree_column)' failed

(deadbeef:11917): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed

(deadbeef:11917): Gtk-CRITICAL **: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed
**
Gtk:ERROR:gtkfilechooserwidget.c:8485:post_process_ui: assertion failed: (cells)
Aborted (core dumped)

**Comment by Alexey-Yakovenko** [comment]
aren't stable versions of GTK have even version numbers?
looks like GTK3.17 is not backwards compatible.. It is worth reporting this issue to GTK devs upstream.
but I hope they will fix this in 3.18. otherwise I'll get in touch with them and ask to fix it.

**Comment by jtojnar** [comment]
Fixed in gtk master https://bugzilla.gnome.org/show_bug.cgi?id=754133

**Comment by Alexey-Yakovenko** [comment]
Thanks
