### ISSUE TITLE
Playing a wma files is too quiet

### ISSUE THREAD

**Issue by Karol-Ryfer** [Alexey-Yakovenko/deadbeef#1251]
Playing a wma files is too quiet - the maximum volume is too small.

**Comment by Alexey-Yakovenko** [comment]
Just confirmed this bug. Not sure how to fix it yet..

**Comment by Alexey-Yakovenko** [comment]
The first fix was wrong, the new fix seems to be correct.

I first thought that precision was not enough for decoding in fixed-point, but turned out it was an off-by-one error in conversion from fixed to int16.
