### ISSUE TITLE
build system: creating ar inside ar

### ISSUE THREAD

**Issue by novel** [Alexey-Yakovenko/deadbeef#1255]
Looks like deadbeef build system is creating ar inside ar for static libs, for example:

https://github.com/Alexey-Yakovenko/deadbeef/blob/master/plugins/gtkui/Makefile.am#L158

Appears that it causes problems on FreeBSD:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=199319

**Comment by Alexey-Yakovenko** [comment]
What kind of problems?

**Comment by Alexey-Yakovenko** [comment]
I can't find any indication that any of my build scripts create ar inside ar, and last time I tried -- deadbeef worked on freebsd just fine.

**Comment by Alexey-Yakovenko** [comment]
Ah I got what the talk is about.
The mentioned *.a files are not used by deadbeef, and can be deleted. They are created by libtool by default, I don't know how to disable them. If anyone knows -- please let me know :)

**Comment by novel** [comment]
The problem it creates is that when it tries to install and strip libraries it fails because strip cannot handle ar inside ar, as could be seen from this log:

```
libtool: install: /usr/bin/install -c -o root -g wheel .libs/vorbis.a /wrkdirs/usr/ports/audio/deadbeef/work/stage/usr/local/lib/deadbeef/vorbis.a
libtool: install: strip --strip-debug /wrkdirs/usr/ports/audio/deadbeef/work/stage/usr/local/lib/deadbeef/vorbis.a
strip: file format not recognized
Makefile:508: recipe for target 'install-pkglibLTLIBRARIES' failed
gmake[4]: *** [install-pkglibLTLIBRARIES] Error 1
```
ar inside ar appears to be created here:

```
libtool: link: ar cru .libs/vorbis.a ../liboggedit/liboggedit.a  vorbis.o
```

I guess it comes from here:

https://github.com/Alexey-Yakovenko/deadbeef/blob/master/plugins/vorbis/Makefile.am#L7

**Comment by novel** [comment]
As you mention .a files are not used by default, I'm wondering if it's safe to use '--disable-static' for ./configure? I gave it a quick test and it appears to work fine.

**Comment by Alexey-Yakovenko** [comment]
It should be safe.

**Comment by novel** [comment]
Great, thanks.

Then probably AC_DISABLE_STATIC or LT_INIT([disable-static ]) could be used.

It still sounds like a workaround though. On the other hand, I wasn't able to find if it's OK to use ar inside ar.
