### ISSUE TITLE
Looping single should signal synthesizing or looping inputs to play forever

### ISSUE THREAD

**Issue by kode54** [Alexey-Yakovenko/deadbeef#1256]
... except when converting. The former will only require a simple check during playback reading for the setting of the player's looping flag, but the latter will require the addition of a flags parameter to the decoder initialization function, so that the decoder may be signaled of certain things that the caller wants. foobar2000 uses such flag signaling on decode_initialize, one of the flags being that the decoder is being opened for playback rather than any other purpose, and another flag also signals whether or not looping is allowed. The first flag can be used by inputs to decide whether to allow hooking for things like, say, real time channel muting control, real time tempo/pitch control, or even real time info displays. The latter is more in line with preventing looping in cases of conversion.

I have already addressed the first part of this issue in the DUMB and GME inputs in my fork on my Gitlab server, as well as in the xSF plugin I have on the same server. I have not, however, addressed the issue of converters.

Changing the function declaration to include a new int32 parameter for flags should not break importing the functions from existing binary plugins, since stack cleanup is the caller's responsibility, and existing binaries will ignore any extra parameters on the stack. Changing all plugin source code to include the extra parameter shouldn't be hard either. Unless you can think of a better way to do it than breaking API.

Maybe add an extra callback interface that accepts the decoder's info pointer and returns whether the file should play forever or not, and use a dictionary or something to look that up on a per-decoder basis?

**Comment by Alexey-Yakovenko** [comment]
```DB_fileinfo_t *(*open) (uint32_t hints);```

is this one not good enough?

**Comment by kode54** [comment]
Arse biscuits, I didn't even notice that hints flag already existed. Okay then, one or possibly two more hint flags. I leave it to you to decide which to use, since the foobar2000 way may not be ideal for DeaDBeeF.

Optional: Playback hint flag to tell decoders when it's safe to interface to external (sync locked) global variables that can be adjusted in real time to control the playback instance, but should otherwise be cached on open for converter instances. Maybe this isn't really needed right now.

Suggested: No looping flag, hinted by external tasks such as the converter, and a benchmarker if you ever add one, to tell the input it should end normally.

I'm currently using the following in deadbeef.h after the function API structure declaration, but there's likely a better way to do it that doesn't involve API breakage.

```
// Cue by kode54, signals synthesizing or looping inputs to play forver on their own
static inline int _DB_play_forever(DB_functions_t * deadbeef)
{
	return deadbeef->conf_get_int ("playback.loop", PLAYBACK_MODE_LOOP_ALL) == PLAYBACK_MODE_LOOP_SINGLE;
}
#define DB_play_forever() _DB_play_forever(deadbeef)
```

It could probably use a better name.

**Comment by Alexey-Yakovenko** [comment]
"can_loop" flag is better IMO, compared with "no_loop", mainly because we don't want this behavior by default when used outside of the streamer.

**Comment by kode54** [comment]
Yes, you're quite right. Just needs a new flag definition, and the addition of that flag hint to the normal playback code.

Adding support for it to the inputs is a different matter, I mainly did it with real time checking of the loop flag because it would allow changing the setting while a track is playing, but perhaps that isn't necessary.

**Comment by Alexey-Yakovenko** [comment]
Yes, I got that part.. I recommend to cache the setting though, and react to the "DB_EV_CONFIGCHANGED", because queries like conf_get_int are slow -- it's a mutex-guarded lookup into a dictionary, which isn't even a hash map -- but just an array of strings.

**Comment by Alexey-Yakovenko** [comment]
I cherry-picked stuff from your clone, cleaned up the history a bit, reformatted the gme codebase back to its original formatting, and reapplied my gme fixes on top. We need to decide on the formatting in those files.. I'm trying to keep the files as close to upstream as possible, but your GME update seemed to replace all linebreaks.. Did GME upstream do that?

Anyway, this issue is resolved now, I guess...

**Comment by kode54** [comment]
My upstream may have Windows line endings, which is why I tried to maintain Unix line endings in my DeaDBeeF fork. I will try to find a way to reformat the line endings without breaking the whole repository.
