### ISSUE TITLE
96/24 ALAC files play as 16 bits

### ISSUE THREAD

**Issue by kode54** [Alexey-Yakovenko/deadbeef#1258]
The header in these files specifies a depth of 16 bits, but somehow other players manage to glean that they are in fact 24 bit files.

**Comment by Alexey-Yakovenko** [comment]
Saved

**Comment by kode54** [comment]
I fixed this in my repository, it involves:

1) Reading the bit depth from the setup data.
2) Adjusting the codec parameters for sample size and bytes per sample based on that setup data.
3) Returning the sample size from the setup data so the caller knows what bit depth to expect.

**Comment by Alexey-Yakovenko** [comment]
Is there a way to subscribe to receive changes in your repo?
I tried, but I get this after signing in: ```Your account is blocked. Retry when an admin has unblocked it.```

**Comment by kode54** [comment]
I have no idea why it started blocking accounts like that, it blocked someone else's account as well. I've unblocked all the accounts.
