### ISSUE TITLE
[tf 2.0] Support for $num() fb2k string function

### ISSUE THREAD

**Issue by andreas--e** [Alexey-Yakovenko/deadbeef#1279]
waker, during a short chat with one of your main developers, he too said this function is not just another gimmick, but a valuable addition to TF 2.0.

Let me requote the most important bit from fb2k docs:

`num(n,len)`

Formats the integer number n in decimal notation with len characters.(...) If n is not numeric, it is treated as zero. Examples:

    $num(123,5) → 00123
    $num(-123,5) → -0123
    $num(4.8,5) → 00004
    $num(A1,5) → 00000

Basic idea: there is neither a rounding function in ddb nor in fb2k. So back in my Win2k days, I've simply "misused" this function to turn a '123.47' value (think of BPM!) into a better readable '123'.

I can't deny, that there is lots of __room for improvement towards fb2k__. So deadbeef might, in theory, go ahead and offer a `$num(n, len, digits)` variant that would even allow a `digits` amount of digits (fixed).
That would turn a pretty silly, overexact BPM value of 123.874 into '123.8'.
Equivalent functions in other languages will be `trunc()` or, IIRC from my 80s BASIC days, `FIX()`. :)

Thanks for considering in advance.

**Comment by Serranya** [comment]
Im working on this right now. Can you tell me what the desired fb2k behaviour is when len is shorter than n ?

Right now im truncating n

    $num(123, 2) -> 12

**Comment by Alexey-Yakovenko** [comment]
@Serranya fb2k doesn't truncate (it would output 123)

**Comment by Serranya** [comment]
Ah damn. I think I need to update my code again.
