### ISSUE TITLE
How to display %genre% field in Playlist

### ISSUE THREAD

**Issue by lliseil** [Alexey-Yakovenko/deadbeef#1281]
I feel dumb that I cannot display the %genre% ID3 field in playslist (as a column) in excellent Deadbeef. Have read *Title formatting* 1&2, and *FAQ*. 

Choose "Personnalised" then added `%genre%`, then `%@genre@`, and columns stays empty. Yeas for all the tracks that have this field completed.

PS: Great player; luv its speed and versability (nice list of greffons). Now it'd be handy if i knew how to make it display tracks genres.

Deadbeaf-git r6066.4218746-1 that I recompiled today - Arch Linux

**Comment by Alexey-Yakovenko** [comment]
It's broken in trunk at the moment. for now the workaround is to use $meta(genre), this will be fixed soon-ish.

**Comment by lliseil** [comment]
Gotcha thank you Alexey.

**Comment by fred0r** [comment]
workaround still works :)
