### ISSUE TITLE
[Linux] Не получается кастомизировать интерфейс

### ISSUE THREAD

**Issue by kalterfive** [Alexey-Yakovenko/deadbeef#1282]
Имеем `deadbeef --version`:
```
starting deadbeef 0.6.2
DeaDBeeF 0.6.2 Copyright © 2009-2013 Alexey Yakovenko
```

Проблема:
* Настраиваем интерфейс посредством "Design Mode"
* Выходим из Design Mode
* Перезапускаем плеер
* Получаем [внезапный результат](http://i.imgur.com/gsFZ1ID.png)
  * То есть сбитый и не дефолтный интерфейс вкупе со сбитым плейлистом

Что я пытался сделать?
* Задействовать плагины:
 * wavefrom
 * infobar
 * quik search
* Расположить остальные элементы:
 * Playback control
 * Volume control
 * Playlist
 * Buttons со следующими действиями:
  * Playback -> Order -> Linear
  * Playback -> Order -> Snuffle tracks
  * Playback -> Looping -> Loop all
  * Playback -> Looping -> Loop single track
  * Jump to currently track

С плагинами всё понятно... во-первых, они для 0.6.2 всегда работали. Во-вторых, пробовал строить интерфейс без сторонних элементов. Ну и в-третьих, пробовал запускать плеер вообще без загрузки user-plugins.
 
Лог загрузки / завершения 0.6.2: http://pastebin.com/MT2sEtmQ  
Тоже самое, только для devel: http://pastebin.com/Hy10fQE0  
Казалось бы, что-то не так с библиотекой wildmidi.so... точнее, с директорией, которую она не может найти. Чёрт с ним -- установил нужный пакет и избавился от подозрительного сообщения в логе, но общую проблему это так и не решило.

Больше информации  
`ls -l ~/.config/deadbeef/`
```
total 12
-rw-r--r-- 1 kalterfive users 3307 Oct  7 00:03 config
-rw-r--r-- 1 kalterfive users  234 Oct  7 00:03 dspconfig
drwxr-xr-x 2 kalterfive users 4096 Oct  6 23:14 playlists
srwxr-xr-x 1 kalterfive users    0 Oct  7 00:02 socket
```
`ls -l ~/.config/deadbeef/playlists`
```
total 0
```
`cat ~/.config/deadbeef/config`  
http://pastebin.com/9SmnTZjX

**Comment by Alexey-Yakovenko** [comment]
wildmidi точно не виновато.
в логах ничего подозрительного не вижу.
хотелось бы кроме скриншота "что получилось" увидеть "что ожидалось увидеть".
в конфиге сохранен ровно тот интерфейс, который я вижу на скриншоте:

`gtkui.layout.0.6.2 tabbed_playlist hideheaders=0 {}`

**Comment by Alexey-Yakovenko** [comment]
нужно смотреть в логи перед действием "Перезапускаем плеер", т.е. сразу после выхода из плеера.

(если что, с подобной проблемой я не сталкивался, и никто о подобном не сообщал)

**Comment by kalterfive** [comment]
[Вот так](http://i.imgur.com/vkPnsSW.png). Все сплитеры залочены. На хоткей `C-e` повешено toggle menubar, на `C-q` выход из плеера. Соответственно, после выхода имеем такой результат, который уже отправил выше.

Можно ли в DeaDBeeF включить что-то вроде debug-mode для получения более подробной информации? Потому что как оказалось... если делать всё постепенно, то результат получается каким он и ожидался, а если всё сразу - нет.

**Comment by Alexey-Yakovenko** [comment]
проблема происходит на любой версии, включая сборку из git master? у меня появилась мысль, что где-то используется буфер фиксированного размера, и этого размера не хватает чтобы сохранить такой конфиг. но симптомы не до конца соответствуют...

**Comment by Alexey-Yakovenko** [comment]
> Можно ли в DeaDBeeF включить что-то вроде debug-mode для получения более подробной информации?

да, можно запустить deadbeef в отладчике типа gdb, и посмотреть что происходит.

**Comment by kalterfive** [comment]
> проблема происходит на любой версии, включая сборку из git master?
Да.

**Comment by Alexey-Yakovenko** [comment]
попробовал воспроизвести без плагинов. проблем не возникло, буфера не переполняются. щас буду пробовать с плагинами

**Comment by Alexey-Yakovenko** [comment]
сделал интерфейс как на скриншоте, со всеми плагинами, никаких проблем, плейлисты в порядке, интерфейс сохраняется.

чтобы что-то понять, нужен лог в момент возникновения проблемы, т.е.:

> нужно смотреть в логи перед действием "Перезапускаем плеер", т.е. сразу после выхода из плеера.

**Comment by Alexey-Yakovenko** [comment]
стоит ли ожидать дополнительной информации по этому багу, или можно закрывать?

**Comment by kalterfive** [comment]
Если ранее хоть как-то с определённой периодичностью получалось словить такое поведение, то сейчас уже нет. Вероятно, те непонятные фазы луны и расположения звёзд больше не сходится.

Собственно, по этой же причине мучить отладчик не стал. Думаю, стоит перевести в `closed`, сейчас я ничего не могу конкретно сказать о проблеме.
