### ISSUE TITLE
Feature request: use SPACE key toggle play/pause

### ISSUE THREAD

**Issue by bjornfor** [Alexey-Yakovenko/deadbeef#1286]
Using the SPACE key to toggle play/pause is quite common in media players I think (just checked VLC and Qmmp). At least I was surprised when deadbeef didn't do anything when I hit SPACE.

I'm on deadbeef 0.6.2.

**Comment by Kilte** [comment]
Edit > Preferences > Hotkeys > Add

**Comment by bjornfor** [comment]
Thanks for that info. But I still think this should be enabled by default. I didn't have to do anything with VLC or Qmmp for SPACE to work.

**Comment by Alexey-Yakovenko** [comment]
It won't be enabled by default, sorry.
