### ISSUE TITLE
Clicking playlist album art below the lowest item row does not focus the group

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1288]
Normally, clicking the album art image in a playlist will cause all the items in the group to be selected and the first item in the group to receive the focus.

If the album art is taller than the item rows in the group, it will increase the group height (min_height logic) to fit.  Clicking on the white space forced below the last group item does nothing.

Clicking on the image at the level of the whitespace below the last item row causes all the items to be selected, but the focus does not change.  In the code, this is because the click is not detected as being over a row, although it is detected as being within a group.

**Comment by cboxdoerfer** [comment]
Thx, confirmed. I guess that's my code responsible for this bug. I'll fix that.
