### ISSUE TITLE
Playlist column drags happen too easily, often accidentally

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1294]
Dragging a playlist column header to the left over a narrower column happens when the drag moves one pixel.  This happens a lot accidentally when trying resize the column.  Then returning it to its original position takes a monumental drag in the opposite direction.

The drag algorithm is based on the left edge of the dragged column moving between the left edge of the drop column and a position calculated as the width of the dragged column to the right of the left edge of the drop column (although this is overridden if the position of the left edge of the dragged column is within the initial location of that column)).  If the drag column is wider than the drop column this means that a dragged column swaps for a single pixel movement, while drags to the right must be moved the entire width of the column.

A better algorithm is to swap columns when the left edge of a column is moved past the midpoint of the previous column, or the right edge is moved past the midpoint of the next column.  This means that a swap cannot happen until the drag has moved at least half a column width, mistaken drags can be reversed by a small movement in the opposite direction, and drags left or right are equally easy (or difficult).

I've tested the algorithm and I think it works nicely.  I can include it with the playlist album art changes if you think it is OK.  There is a diff for the change at this url, but it is relative to my already-modified local copy of ddblistview.c
http://nartowicz.webspace.virginmedia.com/diff

**Comment by Alexey-Yakovenko** [comment]
Please remove the commented-out lines, and provide the patch in unified diff format (git default)

**Comment by Alexey-Yakovenko** [comment]
p.s. I'm already doing the same on OSX, and like it more than the original algorythm, so it should be fine.
