### ISSUE TITLE
Network stream did not work after disconnect

### ISSUE THREAD

**Issue by Chudnovskiy** [Alexey-Yakovenko/deadbeef#1297]
Долго терпел да не вытерпел :) Если плеер играет сетевой поток и тот по каким-либо причинам обрывается (пропал интернет, спящий режим и т.п.), то плеер после нескольких секунд ожидания продолжения потока "выплёвывает" остатки буфера и затыкается. Локальные файлы плеер продолжает играть, а вот сетевые потоки больше не воспроизводит до перезапуска. DeaDBeeF 0.6.2, Ubuntu 12.04-15.04

**Comment by Alexey-Yakovenko** [comment]
билд из транка тоже так себя ведет?

```
commit 6412e20241bdcc6054a150b5435480b4f739b0d3
Author: Alexey Yakovenko <wakeroid@gmail.com>
Date:   Fri Dec 12 22:15:33 2014 +0100

    streamer: fix resuming network streams after losing network connection
```

**Comment by Chudnovskiy** [comment]
Скачал сырцы, компильнул, запустил, проверил - работает! Спасибо что ткнули носом :)
