### ISSUE TITLE
Pinned titlebar does not redraw on vertical expose in GTK2

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1301]
Can someone confirm this for me, to make sure I'm not hallucinating?  I'm testing the redraw clip changes I've made and saw something odd, but it seems to have been a longstanding problem.  The fix is simple.  I just wanted to be sure other people see the same problem in case I'm missing something.

Set up a playlist so that a group is pinned, that is the group is partially scrolled but the titlebar is pushed down and remains visible (right click and make sure that the pin groups checkbox is selected).  Now wipe another window vertically over that titlebar so that it is revealed by the top or bottom of the other window.

In GTK2 the titlebar is no longer visible, and the underlying row is drawn.  Expose by moving the window horizontally over the titlebar and it is successfully redrawn.  Scrolls and switching windows will redraw the whole playlist and everything will be fine again.  In GTK3 it works fine, because the GTK3 code on trunk does not pass a clip region to the render function (actually it does, but always the whole draw area), but I have added this and that's when I spotted the problem.

**Comment by cboxdoerfer** [comment]
Can't reproduce it. By "window" do you mean an actual window of another application or a widget in the deadbeef layout?

**Comment by Alexey-Yakovenko** [comment]
I can't reproduce either. But this problem can be WM-dependent, because cmpositing WMs can cache the window contents.

**Comment by Alexey-Yakovenko** [comment]
Yes, the bug is valid in openbox, reproduced by following the steps described above, just drag any window over deadbeef window to force group title be redrawn.

**Comment by Lithopsian** [comment]
I'm using Openbox with no compositing.  You can also reproduce it, probably on any WM, by carefully aligning widgets so that a menu popup exposes the pinned titlebar in the right way.  The problem occurs when the top or bottom edge of the expose region lies within the pinned titlebar.  Anyway, the fix is simple so I'll add it.

**Comment by Lithopsian** [comment]
This is fixed in pull request #1303.
