### ISSUE TITLE
Смена поп-апа для конвертирования/добавления в плейлист

### ISSUE THREAD

**Issue by Bfgeshka** [Alexey-Yakovenko/deadbeef#1302]
Такие процессы для большого списка файлов много проходить долго и при этом мешают работе с плеером (особенно добавление в плейлист, т.к. при этом взаимодействовать вообще нельзя).

Предлагаю сменить на что-нибудь другое - например, на строку в/над/под строкой состояния, либо сверху или снизу плейлиста, на котором совершается действие. Конечно, опционально через настройки GTK2/3 UI.

Извиняюсь, если дубль - поиск ничего не дал.

**Comment by Alexey-Yakovenko** [comment]
duplicate of #690
