### ISSUE TITLE
Resizing a column sometimes starts a drag instead

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1304]
This has been driving me nuts for a while.  I used to think I was clicking in the wrong place or moving the mouse, but now I think there is a real problem.  I can reproduce easily in GTK3, but never in GTK2.

Place the mouse over a column header divider.  Put it as far to the right as possible on a divider and still have the double arrow cursor.  Now click and move the mouse to try and resize.  A drag starts instead.  Just me?

**Comment by Lithopsian** [comment]
I got confirmation from a couple of people that this can be reproduced.  I also tested on several other machines and OS's.

So a bit of digging finds that it is a rounding error.  Event coordinates are doubles, but in GTK2 they appear to be pre-rounded and never have a fractional part.  In GTK3 they have fractions.  The test for the sizing cursor assigns the x coordinate to an int and then compares to the column boundary, but the test for dragging compares the double directly to the column boundary.

I'll prepare a fix for later.

**Comment by Alexey-Yakovenko** [comment]
great!

**Comment by Lithopsian** [comment]
Starting a resize can also "jump".  The active region for resizing is the last four pixels of each column, and the divider line is drawn approximately 2 pixels to the left of the "official" column edge.  When a resize begins, the edge of the column is immediately moved to the cursor position, which means it jumps up to four pixels making the column smaller.  The visible divider line becomes aligned about 2 pixels to the left of the apparent cursor position.

I plan to fix the column size relative to the cursor position when it is first clicked, the same way that a drag location is exactly relative to the initial click.  There will be no jump in the position of the divider or the size of the column.  The divider will remain at the position relative to the cursor that it was when the resize started.

**Comment by andreas--e** [comment]
Lithopsian, I'm so happy you found a fix for this. I've known this problem on GTK3 since early 0.6 versions, so for very very long. Thanks!

**Comment by Lithopsian** [comment]
The threshold for starting a header drag is also broken.  There is code for not starting a drag operation until the mouse has moved a configurable (default 8) number of pixels, but gtk_drag_check_threshold() is called incorrectly and always returns TRUE.  So header drags start as soon as the mouse moves.  This contributes to the problem by starting drags accidentally, although with the new DND algorithm it is now easy to terminate the drag without anything happening.

I plan on fixing this so that header drags only start after the threshold is exceeded.  This is consistent with playlist dragging, but let me know if you don't want it and I'll just take out the broken code.

**Comment by Alexey-Yakovenko** [comment]
I would definitely like to have this fixed :)

**Comment by Lithopsian** [comment]
If the scrollpoint changes when resizing then the drag point doesn't stay over the divider.  This happens if the horizontal scrollbar is moved all the way to the right, then a column is resized smaller.  The problem is that the scrollpoint is recalculated after the new column width has been calculated.  It all lines up again after a while if the column size is increased again.  Hmmm ..... tricky.

**Comment by Lithopsian** [comment]
I don't know what to do in this situation.  The pointer moves, but the divider can't move because it is already scrolled all the way across.  If the column is allowed to shrink, then the scrollpos also moves, the column shrinks at twice the expected rate, and the pointer is no longer over the divider.  Then if the pointer is moved back to the right the column continues to shrink until the divider is under the pointer again.

It can almost be fixed by increasing the size of the next column to keep the divider under the pointer, but this can't be done with the last column.  Except by dragging in blank space beyond the last column which is very undesirable.

An alternative is not to allow the column to shrink in this situation.  Like hitting the minimum column width, the pointer will move and the column will stay the same, but the reasons will be less obvious.  Nothing further would happen until the pointer is back over the divider.  Maybe the existing not-great situation is the best.  It is intuitive even if it is a little clunky at rare times.  Any alternative might be more annoying.

**Comment by Lithopsian** [comment]
Another issue is when to perform a column sort.  Previously it could only happen if the button release happened in the exact same spot as the button press, similar to a classic button click but even more strict.  Any movement at all would start a drag and there wouldn't be a sort.

Now the pointer can move before a drag begins.  Then a sort might be done even though the pointer had moved between the press and release.  If a drag only starts after a certain horizontal movement, then the pointer could move a long way vertically and still a sort would be done.  My first reaction was to block sorting only if the pointer had moved outside the header completely or it had moved onto the resize zone.  Maybe it would be better to restrict it to "classic" clicks, with the press and release in essentially the same place?  Accidental sorting is very annoying because it can be difficult to return to the original order.

**Comment by Lithopsian** [comment]
I've created another pull request, since it is easier to see what I describe in action.  I'll add to it if either of these last two issues needs changing, or anything else odd shows up.

**Comment by Lithopsian** [comment]
This shouldn't happen any more.  The drag threshold, drag positioning, and resize zone detection have all been modified to avoid glitches.
