### ISSUE TITLE
gtkui/tf: segfault when gtkui titlebar format for stopped state contains certain fields

### ISSUE THREAD

**Issue by cboxdoerfer** [Alexey-Yakovenko/deadbeef#1305]
Steps to reproduce: Place a field in ```Preferences -> GUI/Misc -> Titlebar text while stopped``` that accesses track metadata (e.g. ```%artist%```, ```%album%```, ...), and stop playback

What happens: DeaDBeeF crashes because of segfault

In ```gtkui_set_titlebar ()```  ```streamer_get_playling_track ()``` returns ```NULL``` if the playback is stopped, and we pass that to the tf handling. However, for most fields that access ```it``` in  ```tf_eval_int ()``` there's no NULL-check -> segfault.

**Comment by cboxdoerfer** [comment]
Well the possible fixes are obvious, but I'm not sure what solution you prefer. Of course we could avoid passing ```it = NULL``` to the tf handling, but personally I'd prefer to add a single NULL-check for all the tf fields that require access to track metadata, to prevent this kind of bugs in the future.

**Comment by Alexey-Yakovenko** [comment]
I'll have a look.
