### ISSUE TITLE
Playlist horizontal scrolling is desperately slow with the thumb buttons ...

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1307]
... and rather fast with a mouse wheel.

The scroll step is set to 1 pixel, compared to 20 pixels for the vertical scroll bar.  Should they both be 20?  Or something a little less for horizontal scrolling?

Mousewheel scrolling with the mouse over the drawarea also scrolls 20 pixels per step.  With the mouse over the scrollbar itself, a different increment is used.  I believe it is the page size to the power 2/3.  The vertical scrollbar page size is set to half of the drawarea height and it produces nice results with the mousehweel.

The horizontal scrollbar page size is set to the full width of the drawarea and tends to just skip from one end of the range to the other when scrolling, since there isn't typically a huge scroll range.  There is the same effect when clicking on the scrollbar, a very large "page" jump.  Should the page size be smaller?  Half the width like the vertical scrollbar?

**Comment by Lithopsian** [comment]
A slight correction: mousewheel scrolling over the list is 40 pixels at a time (the vertical thumb buttons are 20 pixels, the horizontal ones 1 pixel at a time), about the same as mousewheel scrolling over the vertical scrollbar in a list that is 500 pixels tall, or the horizontal scrollbar in a list 250 pixels wide.  Larger playlist widgets scroll more quickly when wheeling over the scrollbars, but the same when wheeling over the drawing area.  With smooth scrolling in GTK3, the 40 pixel step is modified by delta values which depend on the device.

**Comment by Alexey-Yakovenko** [comment]
How do you make the thumb buttons to emit scroll events? Is that something preconfigured in certain DE/WM? I'm running ubuntu 12.04 + virtualbox, the thumb buttons simply do nothing..

**Comment by Lithopsian** [comment]
I don't know.  Is it a virtualbox thing?  Many GTK3 themes don't have scrollbar buttons, but the ones that do always seem to work.  They don't actually emit scroll events, just change the value of the scrollbar range which we detect as a "value_changed" signal.

**Comment by Alexey-Yakovenko** [comment]
Oh, I misunderstood what you meant by thumb buttons I guess..
I thought you mean those physical buttons on the left side of the mouse, which you press with your thumb.

**Comment by Lithopsian** [comment]
Sorry, I meant the buttons at the top and bottom of the scrollbar.  Or in this case the left and right of the horizontal scrollbar.

The extra mouse buttons might emit scroll events.  Mouse buttons 6 and 7 are usually mapped to the horizontal scroll events.  We detect those if they exist.  The back and forward buttons on the sides of a mouse are generally mapped to buttons 8 and 9 of the mouse button event.  We mostly ignore those, but maybe they could be used for something?  They do act as an ordinary click on the seekbar.

**Comment by Lithopsian** [comment]
Playlist scrolling is generally quite slow and jerky.  Each scroll event causes a complete redraw.  Using gdk_window_scroll() is much faster.  For horizontal scrolling and vertical scrolling without pinned groups, this is very simple.  Previous changes mean that only the clip region, by row (and group) and column,  is redrawn in both GTK2 and GTK3.

With pinned groups, the title line of the pinned group (before or after the scroll, depending on the direction) has to be explicitly invalidated.  Also any album art in the pinned group has to be invalidated.  To support this, all the clip rectangles have to be drawn separately.  Each rectangle has to be clipped explicitly since only the bounding rectangle is clipped implicitly on an expose event.

Performance varies with scroll increment, theme, number if playitens, and pinned group size, but typically 5-20 times faster in my tests.  Smooth scrolling is actually quite smooth!  I think this would be worth a try unless there is some deal-breaker that I haven't thought of.

**Comment by Alexey-Yakovenko** [comment]
> Using gdk_window_scroll() is much faster.

but this is not compatible with pinned groups.

**Comment by Lithopsian** [comment]
All listview scrolling is now done using gdk_window_scroll(), and seems to be basically working.  Mouse wheel scrolling speed is consistent whether over the list or the scrollbars, and the thumb button scroll rates are consistent.
