### ISSUE TITLE
Busy loop

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1309]
I noticed 100% CPU usage from Deadbeef and managed to narrow down a way to reproduce this.
1. Load two playlists with tracks.
2. Start a track in one list and pause it.
3. Go to the other playlist and select a track.
4. Shutdown Deadbeef and restart.
Everything starts and appears to run normally, but check CPU usage.  I have no clue what is looping.  Starting playback returns CPU usage to normal.

**Comment by Alexey-Yakovenko** [comment]
Reproduced.. seems like the streamer is trying to find the current track in the current playlist all the time.
