### ISSUE TITLE
Paging up in a playlist briefly scrolls to the end of the list when reaching the first item

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1310]
1. Create a playlist long enough to have several pages and a scrollbar.
2. Page down, then back up to the top.  Make sure that the last page up keypress will go beyond the first item.

When the cursor would page beyond the first item, the playlist will briefly scroll to the end of the range, then quickly redraw with the first item selected.  This is easier to see with album art since the wrong image will flash up for a moment.If groups are not pinned then the first item in the playlist will be selected, but the list will not be scrolled right to the top.  This is the position reached naturally by selecting the first item when positioned at the end of the list.

I think this is as simple as setting the scroll position to the upper adjustment value instead of the lower when paging up beyond cursor position zero.

**Comment by Lithopsian** [comment]
This shouldn't happen any more.  Paging past the top of the list sets the scroll position to the lower bound instead of the upper.

**Comment by Alexey-Yakovenko** [comment]
Why can't you close your own bug reports after fixing them yourself?
I thought you can do so either by clicking "close" on github, or writing `fixes #XYZ` in the commit message.

**Comment by Lithopsian** [comment]
Sorry, I guess I can close my own issues.  I didn't realise I had such power.
