### ISSUE TITLE
Very short tracks are inaudible

### ISSUE THREAD

**Issue by danpla** [Alexey-Yakovenko/deadbeef#1311]
ALSA plugin doesn't play very short tracks. The progressbar quickly flashes, but there is no sound.
I noticed that the problem depends on the size of the buffer: the shorter length of the track, the smaller buffer size is required to play it.

For example, you will not hear this 139ms track with default buffer size (8192):
http://cgit.freedesktop.org/sound-theme-freedesktop/plain/stereo/bell.oga
This track can be heard only if the buffer size is 3077 or less.

The `aplay` ALSA utility with the same parameters plays this file (decoded to WAV) without problems:
`aplay --buffer-size=8192 --period-size=1024 bell.wav`
As well as all other programs I've tried (mplayer, ogg123, vlc, avplay).

At the same time, everything is fine with PulseAudio output, regardless of the buffer size.

GNU/Linux, x86-64, Ubuntu 14.04
DeaDBeeF 0.6.2

**Comment by Alexey-Yakovenko** [comment]
I have this problem both in alsa and pulse, but not coreaudio.

**Comment by Alexey-Yakovenko** [comment]
This one is fixed on trunk.
