### ISSUE TITLE
Play item text shows behind pinned title in themes with transparent row background

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1318]
The treeview row background colour on some themes is transparent.  These themes include HighContrast and the default (ie. broken) theme in GTK3.  On these themes, a pinned group title background does not hide any underlying text.  Selected row backgrounds and the focus box can also show across the album art column for the same reason.

![2015-11-04--1446665680_1280x1024_scrot](https://cloud.githubusercontent.com/assets/7702742/10949526/4109891e-832b-11e5-9720-5bcd60978402.png)

**Comment by Alexey-Yakovenko** [comment]
I'm also getting black text on black background with the same use case, plus the problem you described above (GTK 3.4.0, ubuntu 12.04)

**Comment by Lithopsian** [comment]
Where is the black text on black background showing?  Is that HighContrast or HighContrastInverse?

**Comment by cboxdoerfer** [comment]
Works fine here with both GTK2 and GTK3 ui. Tried it with Adwaita, HighContrast, HighContrastInverse and all other themes I have installed (numix, elementary, arc, ...). The only exception, and that has been known already, is the default Mint theme with the GTK2 ui which triggers that bug.

@Lithopsian which version of GTK3 are you using? I'm running 3.18.

**Comment by Alexey-Yakovenko** [comment]
> Where is the black text on black background showing? Is that HighContrast or HighContrastInverse?

entire playlist is black except the column headers and the selected track(s).
It's on high contrast.

**Comment by Lithopsian** [comment]
Solid black indicates a theme failure, something not defined and coming out black.  Happens a lot in GTK3 as features are changed or added.  Strange though, because I have GTK 3.4.2 here and HighContrast looks basically fine.

I don't have GTK 3.18!  Maybe they updated the standard themes to have a defined background colour for treeview rows?  Do you see the transparent backgrounds with Mint-X theme in GTK2?  In Mint or something else?  I couldn't find a GTK2 theme that did this.

I could work round this fairly easily.  Whenever the playlist draws a treeview background that it expects to hide something already drawn, just paint it with the window background colour first.  It should only happen with the pinned title and the album art column, that I can think of.  Do you think it is worth it?

**Comment by cboxdoerfer** [comment]
Yes, with Mint-X themes and GTK2 UI I can see the transparent backgrounds, but all other themes I tried seem to be fine. I'm running Debian Testing and Arch Linux, both with GTK 3.18 and GTK 2.24.28.

**Comment by Alexey-Yakovenko** [comment]
> I could work round this fairly easily. Whenever the playlist draws a treeview background that it expects to hide something already drawn, just paint it with the window background colour first. It should only happen with the pinned title and the album art column, that I can think of. Do you think it is worth it?

This problem is not critical in any way. Worth or not -- you decide. We always had, and will always have, GTK themes which break rendering (both gtk2 and gtk3). Some can be worked around, some can't. That's why we have the theming override.

**Comment by Lithopsian** [comment]
Transparent backgrounds are entirely legitimate, although it seems to be accidental in these cases.  I'll make the code more robust about drawing a valid background.

The black areas in bad themes occur when even the window doesn't have a valid colour and so is considered transparent.  I think exactly what happens depends on the window manager.

**Comment by Lithopsian** [comment]
The PR sets the playlist background by drawing the normal window background, the normal widget background, then the even treeview row background.  This should take care of transparency on the widget background or the treeview colour, so the group title and album art column should properly overwrite any underlying rows that were drawn.

I've also applied this to the whole playlist.  GTK should draw the background itself whenever there is an expose event, but you wanted to do it explicitly also.  To take advantage of doing that, I don't redraw all the rows and fill areas that are even row coloured anyway, only the odd and selected ones.
