### ISSUE TITLE
SIGFPE: DIV by zero

### ISSUE THREAD

**Issue by derselbst** [Alexey-Yakovenko/deadbeef#1329]
For very small files a division by zero will occur at [streamer.c:1820](https://github.com/Alexey-Yakovenko/deadbeef/blob/master/streamer.c#L1820) in case (bytes_in_one_second < blocksize)

**Comment by Alexey-Yakovenko** [comment]
This code doesn't depend on the file size.. I guess zero can happen when samplerate and bits-per-sample are very small, and e.g. blocksize is less than 120..
For this, your file should be e.g. 8 bits ber sample, 1 channel, 119Hz, that would give (119*1*1)/120 = 0.
Is that the kind of file you've got?
