### ISSUE TITLE
Playlist context menu with range selection doesn't always activate "Remove from Playback Queue"

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1335]
If more than one playlist item is selected and one of them is in the playback queue, then the context menu should allow "Remove from Playback Queue" to be performed.  It is only allowed if the actual item under the pointer when clicked is in the playqueue.

**Comment by Alexey-Yakovenko** [comment]
How to reproduce this bug?

**Comment by Lithopsian** [comment]
To reproduce, add some but not all items to the playqueue.  Select at least one item in the playqueue and at least one item not in the playqueue.  Right click on a selected item not in the playqueue.  The "Remove from Playback Queue" option is disabled.
