### ISSUE TITLE
Cursor follow playback doesn't work correctly in background playlist

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1336]
The cursor follows the playing track, but the previously playing track is not de-selected.

**Comment by cboxdoerfer** [comment]
This might be a regression of my recent changes to the selection handling. I'll have a look.

**Comment by Lithopsian** [comment]
I think it is longstanding.  See songchanged_cb in widgets.c.  In the block for background playlists, it explicitly sets selected for the new track, but doesn't seem to do anything about the old track.

**Comment by cboxdoerfer** [comment]
My fault: https://github.com/Alexey-Yakovenko/deadbeef/pull/1313/files#diff-1e3bc00686d13e426675222108a525a9L2121

**Comment by cboxdoerfer** [comment]
I'll prepare a patch
