### ISSUE TITLE
Add "Total Discs" field in the properties dialog

### ISSUE THREAD

**Issue by danpla** [Alexey-Yakovenko/deadbeef#1340]
A "Total Discs" property like in Foobar2000:
![screenshot](https://www.foobar2000.org/images/img/properties-multi-metadata.png)

Many tag formats allow writing "discs" field in "current/total" format (TPOS in id3, WM/PartOfSet in ASF etc.), but, for example, VorbisComments use separate "DISCNUMBER" and "DISCTOTAL" fields for this.

**Comment by saivert** [comment]
Actually according to the ID3v2.3 spec this is stored in the TPOS frame as x/x. foobar2000 just splits this up into two fields in the metadata editor. When you enter a number in the Total Discs field in foobar2000 it gets written to the TPOS frame together with the track number.
I wouldn't mind if deadbeef adopted the foobar2000 style here as it makes it more clear with two fields, but others may disagree and prefer the combined field.

**Comment by Lithopsian** [comment]
The properties dialog, and the widget, show tags in two types of field.  A fixed list of known tags are displayed with formal names, for example "Disc Number".  These fields always appear, even if the tag is not present and there is no value for the field.  The second type of field is simply the tag name, with the tag value.  This type of field appears in angle brackets to further distinguish it from the fixed field names.  They only appear if a tag is actually present.  Both types of tag can be edited.

So any type of disc total tag that is present should appear in the dialog, although only with the tag name, not a nice name.  If the disc total tags were mapped to a fixed tag name, it would always appear in the dialog, but usually be empty, similar to your screenshot.

What does Deadbeef do with TPOS right now?  I know how it handles VorbisComments and that appears as two fields.  The DISCNUMBER is already mapped to the fixed "Disc Number" field, which doesn't include the total discs, so we are already halfway to having two fields.

**Comment by danpla** [comment]
> Actually according to the ID3v2.3 spec this is stored in the TPOS frame as x/x

Yes, this is what I had in mind. Just a little mistake; I fixed the description.

I think there is no other "right" way to add support for a separate "total discs" field in the tags (like "DISCTOTAL" in vorbis comments). Implementing this will require a new metadata internally (probably `numdiscs` in manner of `numtracks`), which will also help to remove a "[special case](https://github.com/Alexey-Yakovenko/deadbeef/blob/facec841e9d4a3de1a770bd164efed28504e6793/tf.c#L1386)" from the `tf.c`. After this, the only way to keep "combined" field is to join `dics` and `numdiscs` into the one string before opening the "Track Properties" dialog, and split them back after "Apply".

But the main reason is not the implementation details, but the fact that it's a bad solution in terms of UI: "Track Number" and "Total Tracks" are already separated, so the number of discs is also requires a personal field; like the "Track Number" holds only a track number, the "Disc Number" must contain only a disc number, but nothing else.

> What does Deadbeef do with TPOS right now?

Currently, it does nothing.

**Comment by danpla** [comment]
["WM/PartOfSet"](https://msdn.microsoft.com/en-us/library/windows/desktop/dd757974%28v=vs.85%29.aspx) also may be separated.

However, Foobar2000 doesn't split it and always uses proprietary "foobar2000/TOTALDISCS" to store "total discs", so probably this should be handled in a some way.

But this is not so easy, since values of "total" part of "WM/PartOfSet" and "foobar2000/TOTALDISCS" can be different. Maybe it makes sense to give the Foobar extension higher priority, i.e. so that "WM/PartOfSet" will set "numdiscs" only if it's not already added, and "foobar2000/TOTALDISCS" will override it in all cases.

**Comment by Alexey-Yakovenko** [comment]
@danpla is there a list of all "foobar2000/" ASF fields?

**Comment by Alexey-Yakovenko** [comment]
I can imagine that fb2k might be writing all "unknown" fields like this, as a fallback, when there's no exact mapping defined.

**Comment by Alexey-Yakovenko** [comment]
Another question is how ffmpeg itself is treating these fields. This needs to be tested, or looked up in the ffmpeg sources. But in our own wma plugin, we can do this.

**Comment by Alexey-Yakovenko** [comment]
Looked in the ffmpeg sources. ASF codec puts the entire contents of "WM/PartOfSet" in the "disc", so this might need additional parsing, which I will add.

**Comment by danpla** [comment]
Yes, it turned out that Foobar2000 always does like that for any metadata that doesn't have a suitable field in a certain tag format (seems like Foobar developers just don't know that "WM/PartOfSet" can contain two values). For ASF, it prepends "foobar2000/" to a name of a metadata; for ID3, it uses TXXX frames.

This is also true for the "Performer" property: it's written as "foobar2000/PERFORMER" and TXXX:PEFROMER respectively, so Deadbeef will have to handle this someday for the "performer" meta.

These two tables may be useful in future:
http://qoobar.sourceforge.net/en/documentation.htm#tags
https://picard.musicbrainz.org/docs/mappings/

P.S.: Looks like you forget to add the string for translation.

**Comment by danpla** [comment]
"Total Discs" string is not translatable (`translation/extra.c`).

**Comment by Alexey-Yakovenko** [comment]
@danpla dude.. bug reports are like toilet paper. DO NOT REUSE!
