### ISSUE TITLE
Search window should have drag n drop disabled

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1341]
An internal "copy" drag, that is within Deadbeef and with the ctrl key held down, does not copy although the drag icon indicates that it will.  It moves just like a regular drag.  Should it make a copy, or is copying never intended for this case?  The copy icon always appears for an external drag, indicating that the external file will be loaded into the playlist.

A drag from the main playlist to the search playlist indicates that it will move the play item, but it doesn't.  Similarly, external drags into the search playlist indicate that they will be copied (aka loaded into Deadbeef), but they aren't.  So, should drags into the search window be fully disabled, including the drag icon and marker, or made to work in accordance with the indicators.  The drop position might be problematic since there may be few or no tracks currently visible.  No drags can be started from the search playlist.

Edit: copying does work.  Sometimes.  Copying multiple items seems to just copy the first one multiple times.  Copying a single item is working today, not sure what I was seeing yesterday.

**Comment by Lithopsian** [comment]
The drop icon also indicates a possible drop onto a tab top, but this doesn't happen.  Only external files can be dropped onto tab tops.  Might be nice to support for playitems too?

Edit: Looks like there is code for this, but it doesn't seem to be working.  The code suggests that it should drop at the tail, but I'm not seeing it.  I think it is simply looking for the wrong target string.  The playlist sends "DDB_URI_LIST", but the tabstrip is waiting for "STRING".

**Comment by Lithopsian** [comment]
One more thing.  Holding ctrl and clicking the mouse to start a copy immediately deselects the item on mousedown.  It is necessary to start the drag without the ctrl key, then press it before doing the drop.  It would be nicer to wait for mouseup to decide whether it is a drag or a select, similar to the action without the ctrl key.

**Comment by Alexey-Yakovenko** [comment]
> An internal "copy" drag, that is within Deadbeef and with the ctrl key held down, does not copy although the drag icon indicates that it will. It moves just like a regular drag.

Can't repro

> A drag from the main playlist to the search playlist indicates that it will move the play item, but it doesn't. 

This is not supposed to work. Search list should not be accepting drops.

> So, should drags into the search window be fully disabled

Yes.

Renaming the bug.

**Comment by Alexey-Yakovenko** [comment]
> Holding ctrl and clicking the mouse to start a copy immediately deselects the item on mousedown.

ctrl+click is "toggle selection", just like in any other GTK app.
