### ISSUE TITLE
Add ID3v1 genres introduced in Winamp 5.6

### ISSUE THREAD

**Issue by danpla** [Alexey-Yakovenko/deadbeef#1345]
https://de.wikipedia.org/wiki/Liste_der_ID3v1-Genres

Most programs handle them:

taglib: [taglib/mpeg/id3v1/id3v1genres.cpp](https://github.com/taglib/taglib/blob/fa4289e0440b1be75fa3cd63a1b085c88885e1a4/taglib/mpeg/id3v1/id3v1genres.cpp)
mutagen: [mutagen/_constants.py](https://bitbucket.org/lazka/mutagen/src/05f8591a075c3523ac1fba094f640535479312f8/mutagen/_constants.py)

**Comment by danpla** [comment]
You forgot to update the size (lines 1079 and 3725).

**Comment by Alexey-Yakovenko** [comment]
thanks :)
