### ISSUE TITLE
linux static build fails to start with AFS homedir

### ISSUE THREAD

**Issue by zao** [Alexey-Yakovenko/deadbeef#1353]
On my work workstation the application fails to start up with the following output.

    ∫ /opt/deadbeef-0.6.2/deadbeef 
    starting deadbeef 0.6.2 [static] [portable]
    server_start
    INFO: unlink socket: No such file or directory
    bind: Operation not permitted

I suspect this is due to the home directory being on an OpenAFS filesystem, which is known for being restrictive in what operations it permits. (One famous feature is lack of hardlinks between files in different directories.)

Setting `XDG_CONFIG_HOME` to a local filesystem allows the application to start properly but is a workaround.

`strace` on the binary results in the following output, with a bunch of `ENOENT` and `EPERM` on local sockets created in the config directory.

Maybe session-specific things like local sockets and other per-machine state shall be in local locations like the XDG-suggested `$XDG_RUNTIME_DIR`?

    execve("/opt/deadbeef-0.6.2/deadbeef", ["/opt/deadbeef-0.6.2/deadbeef"], [/* 84 vars */]) = 0
    brk(0)                                  = 0x7eb000
    access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
    mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa269325000
    readlink("/proc/self/exe", "/opt/deadbeef-0.6.2/deadbeef", 4096) = 28
    access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
    open("/opt/deadbeef-0.6.2/../lib/tls/x86_64/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/opt/deadbeef-0.6.2/../lib/tls/x86_64", 0x7ffe84f20e70) = -1 ENOENT (No such file or directory)
    open("/opt/deadbeef-0.6.2/../lib/tls/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/opt/deadbeef-0.6.2/../lib/tls", 0x7ffe84f20e70) = -1 ENOENT (No such file or directory)
    open("/opt/deadbeef-0.6.2/../lib/x86_64/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/opt/deadbeef-0.6.2/../lib/x86_64", 0x7ffe84f20e70) = -1 ENOENT (No such file or directory)
    open("/opt/deadbeef-0.6.2/../lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/opt/deadbeef-0.6.2/../lib", 0x7ffe84f20e70) = -1 ENOENT (No such file or directory)
    open("/opt/deadbeef-0.6.2/../lib/autopackage/tls/x86_64/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/opt/deadbeef-0.6.2/../lib/autopackage/tls/x86_64", 0x7ffe84f20e70) = -1 ENOENT (No such file or directory)
    open("/opt/deadbeef-0.6.2/../lib/autopackage/tls/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/opt/deadbeef-0.6.2/../lib/autopackage/tls", 0x7ffe84f20e70) = -1 ENOENT (No such file or directory)
    open("/opt/deadbeef-0.6.2/../lib/autopackage/x86_64/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/opt/deadbeef-0.6.2/../lib/autopackage/x86_64", 0x7ffe84f20e70) = -1 ENOENT (No such file or directory)
    open("/opt/deadbeef-0.6.2/../lib/autopackage/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/opt/deadbeef-0.6.2/../lib/autopackage", 0x7ffe84f20e70) = -1 ENOENT (No such file or directory)
    open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    fstat(3, {st_mode=S_IFREG|0644, st_size=179386, ...}) = 0
    mmap(NULL, 179386, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fa2692f9000
    close(3)                                = 0
    access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
    open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
    read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\16\0\0\0\0\0\0"..., 832) = 832
    fstat(3, {st_mode=S_IFREG|0644, st_size=14664, ...}) = 0
    mmap(NULL, 2109744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fa268f01000
    mprotect(0x7fa268f04000, 2093056, PROT_NONE) = 0
    mmap(0x7fa269103000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fa269103000
    close(3)                                = 0
    access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
    open("/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
    read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20V\0\0\0\0\0\0"..., 832) = 832
    fstat(3, {st_mode=S_IFREG|0644, st_size=1071552, ...}) = 0
    mmap(NULL, 3166568, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fa268bfb000
    mprotect(0x7fa268d00000, 2093056, PROT_NONE) = 0
    mmap(0x7fa268eff000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x104000) = 0x7fa268eff000
    close(3)                                = 0
    access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
    open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
    read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0po\0\0\0\0\0\0"..., 832) = 832
    mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa2692f8000
    fstat(3, {st_mode=S_IFREG|0755, st_size=141574, ...}) = 0
    mmap(NULL, 2217264, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fa2689dd000
    mprotect(0x7fa2689f6000, 2093056, PROT_NONE) = 0
    mmap(0x7fa268bf5000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18000) = 0x7fa268bf5000
    mmap(0x7fa268bf7000, 13616, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fa268bf7000
    close(3)                                = 0
    access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
    open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
    read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\37\2\0\0\0\0\0"..., 832) = 832
    fstat(3, {st_mode=S_IFREG|0755, st_size=1840928, ...}) = 0
    mmap(NULL, 3949248, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fa268618000
    mprotect(0x7fa2687d3000, 2093056, PROT_NONE) = 0
    mmap(0x7fa2689d2000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ba000) = 0x7fa2689d2000
    mmap(0x7fa2689d8000, 17088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fa2689d8000
    close(3)                                = 0
    mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa2692f7000
    mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa2692f5000
    arch_prctl(ARCH_SET_FS, 0x7fa2692f5740) = 0
    mprotect(0x7fa2689d2000, 16384, PROT_READ) = 0
    mprotect(0x7fa268bf5000, 4096, PROT_READ) = 0
    mprotect(0x7fa268eff000, 4096, PROT_READ) = 0
    mprotect(0x7fa269103000, 4096, PROT_READ) = 0
    mprotect(0x63c000, 4096, PROT_READ)     = 0
    mprotect(0x7fa269327000, 4096, PROT_READ) = 0
    munmap(0x7fa2692f9000, 179386)          = 0
    set_tid_address(0x7fa2692f5a10)         = 11574
    set_robust_list(0x7fa2692f5a20, 24)     = 0
    futex(0x7ffe84f216b0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, 7fa2692f5740) = -1 EAGAIN (Resource temporarily unavailable)
    rt_sigaction(SIGRTMIN, {0x7fa2689e39f0, [], SA_RESTORER|SA_SIGINFO, 0x7fa2689ed340}, NULL, 8) = 0
    rt_sigaction(SIGRT_1, {0x7fa2689e3a80, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7fa2689ed340}, NULL, 8) = 0
    rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
    getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
    lstat("/opt", {st_mode=S_IFDIR|0755, st_size=27, ...}) = 0
    lstat("/opt/deadbeef-0.6.2", {st_mode=S_IFDIR|0755, st_size=111, ...}) = 0
    lstat("/opt/deadbeef-0.6.2/deadbeef", {st_mode=S_IFREG|0775, st_size=296880, ...}) = 0
    stat("/opt/deadbeef-0.6.2/.ddb_portable", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
    rt_sigaction(SIGSEGV, {0x403920, [SEGV], SA_RESTORER|SA_RESTART, 0x7fa26864ed40}, {SIG_DFL, [], 0}, 8) = 0
    brk(0)                                  = 0x7eb000
    brk(0x80c000)                           = 0x80c000
    open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
    fstat(3, {st_mode=S_IFREG|0644, st_size=10313168, ...}) = 0
    mmap(NULL, 10313168, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fa267c42000
    close(3)                                = 0
    write(2, "starting deadbeef 0.6.2 [static]"..., 44starting deadbeef 0.6.2 [static] [portable]
    ) = 44
    prctl(PR_SET_NAME, 0x42ebc5, 0, 0, 0)   = 0
    mkdir("/home/l/lars/.config", 0755)     = -1 EEXIST (File exists)
    mkdir("/opt/deadbeef-0.6.2/plugins", 0755) = -1 EEXIST (File exists)
    mkdir("/home/l/lars/.config/deadbeef", 0755) = -1 EEXIST (File exists)
    socket(PF_LOCAL, SOCK_STREAM, 0)        = 3
    connect(3, {sa_family=AF_LOCAL, sun_path="/home/l/lars/.config/deadbeef/socket"}, 38) = -1 ENOENT (No such file or directory)
    close(3)                                = 0
    write(2, "server_start\n", 13server_start
    )          = 13
    socket(PF_LOCAL, SOCK_STREAM, 0)        = 3
    fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
    fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
    unlink("/home/l/lars/.config/deadbeef/socket") = -1 ENOENT (No such file or directory)
    open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 4
    fstat(4, {st_mode=S_IFREG|0644, st_size=2570, ...}) = 0
    mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa269324000
    read(4, "# Locale name alias data base.\n#"..., 4096) = 2570
    read(4, "", 4096)                       = 0
    close(4)                                = 0
    munmap(0x7fa269324000, 4096)            = 0
    open("/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/usr/share/locale-langpack/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/usr/share/locale-langpack/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    write(2, "INFO: unlink socket: No such fil"..., 47INFO: unlink socket: No such file or directory
    ) = 47
    bind(3, {sa_family=AF_LOCAL, sun_path="/home/l/lars/.config/deadbeef/socket"}, 38) = -1 EPERM (Operation not permitted)
    write(2, "bind: Operation not permitted\n", 30bind: Operation not permitted
    ) = 30
    exit_group(-1)                          = ?
    +++ exited with 255 +++

**Comment by Alexey-Yakovenko** [comment]
Yeah, seems like XDG_RUNTIME_DIR is the correct variable to use, if it's set. I'll make the fix.
