### ISSUE TITLE
pulseaudio pa_write bad file descriptor

### ISSUE THREAD

**Issue by conformist-mw** [Alexey-Yakovenko/deadbeef#1363]
Не часто бывает, но доходит до конца трека и падает. Лог из терминала:

	$ deadbeef
	starting deadbeef devel
	server_start
	searching for GUI plugins in /home/conformist/.local/lib64/deadbeef
	searching for GUI plugins in /home/conformist/.local/lib/deadbeef
	searching for GUI plugins in /usr/lib/deadbeef
	load_plugin_dir /usr/lib/deadbeef: scandir found 92 files
	found gui plugin ddb_gui_GTK2.so
	added GTK2 gui plugin
	load gui plugin
	checking GUI plugin: GTK2
	found selected GUI plugin: GTK2
	loading plugin /usr/lib/deadbeef/ddb_gui_GTK2.so
	loading plugins from /home/conformist/.local/lib64/deadbeef
	loading plugins from /home/conformist/.local/lib/deadbeef
	loading plugins from /usr/lib/deadbeef
	load_plugin_dir /usr/lib/deadbeef: scandir found 92 files
	loading plugin /usr/lib/deadbeef/aac.so
	loading plugin /usr/lib/deadbeef/adplug.so
	loading plugin /usr/lib/deadbeef/alac.so
	loading plugin /usr/lib/deadbeef/alsa.so
	loading plugin /usr/lib/deadbeef/artwork.so
	loading plugin /usr/lib/deadbeef/cdda.so
	loading plugin /usr/lib/deadbeef/converter.so
	loading plugin /usr/lib/deadbeef/converter_gtk2.so
	loading plugin /usr/lib/deadbeef/dca.so
	loading plugin /usr/lib/deadbeef/ddb_ao.so
	loading plugin /usr/lib/deadbeef/ddb_dumb.so
	loading plugin /usr/lib/deadbeef/ddb_mono2stereo.so
	loading plugin /usr/lib/deadbeef/ddb_shn.so
	loading plugin /usr/lib/deadbeef/dsp_libsrc.so
	loading plugin /usr/lib/deadbeef/ffap.so
	loading plugin /usr/lib/deadbeef/ffmpeg.so
	loading plugin /usr/lib/deadbeef/flac.so
	loading plugin /usr/lib/deadbeef/gme.so
	loading plugin /usr/lib/deadbeef/hotkeys.so
	loading plugin /usr/lib/deadbeef/in_sc68.so
	loading plugin /usr/lib/deadbeef/lastfm.so
	loading plugin /usr/lib/deadbeef/m3u.so
	loading plugin /usr/lib/deadbeef/mms.so
	loading plugin /usr/lib/deadbeef/mp3.so
	loading plugin /usr/lib/deadbeef/musepack.so
	loading plugin /usr/lib/deadbeef/notify.so
	loading plugin /usr/lib/deadbeef/nullout.so
	loading plugin /usr/lib/deadbeef/oss.so
	loading plugin /usr/lib/deadbeef/pltbrowser_gtk2.so
	loading plugin /usr/lib/deadbeef/pulse.so
	loading plugin /usr/lib/deadbeef/shellexec.so
	loading plugin /usr/lib/deadbeef/shellexecui_gtk2.so
	loading plugin /usr/lib/deadbeef/sid.so
	loading plugin /usr/lib/deadbeef/sndfile.so
	loading plugin /usr/lib/deadbeef/supereq.so
	loading plugin /usr/lib/deadbeef/tta.so
	loading plugin /usr/lib/deadbeef/vfs_curl.so
	loading plugin /usr/lib/deadbeef/vfs_zip.so
	loading plugin /usr/lib/deadbeef/vorbis.so
	loading plugin /usr/lib/deadbeef/vtx.so
	loading plugin /usr/lib/deadbeef/wavpack.so
	loading plugin /usr/lib/deadbeef/wildmidi.so
	loading plugin /usr/lib/deadbeef/wma.so
	selected output plugin: PulseAudio output plugin
	INFO: loading playlist podcasts
	INFO: from file /home/conformist/.config/deadbeef/playlists/0.dbpl
	INFO: loading playlist Saliva
	INFO: from file /home/conformist/.config/deadbeef/playlists/1.dbpl
	INFO: loading playlist hits
	INFO: from file /home/conformist/.config/deadbeef/playlists/2.dbpl
	INFO: loading playlist red
	INFO: from file /home/conformist/.config/deadbeef/playlists/3.dbpl
	gtkui plugin compiled for gtk version: 2.24.28
	** (deadbeef:7523): WARNING **: Widget not found: Skip to_menu
	pthread_join failed: Invalid argument
	pulse: failed to write buffer
	pa_write() failed while trying to wake up the mainloop: Bad file descriptor
	Segmentation Fault
	Segmentation fault	

>~ $ aptitude versions deadbeef
>Package deadbeef:                        
>i   0.6.2+git20151113-1                           unstable                  500

**Comment by Alexey-Yakovenko** [comment]
Hello.
Is there any way to reproduce the problem, or a backtrace?

**Comment by Alexey-Yakovenko** [comment]
pthread_join failed seems to be from another bug #1358 

which is already fixed.

@pingplug can you confirm that this is the same problem? you didn't provide much information about the bug either, so I can't really see..

**Comment by conformist-mw** [comment]
@Alexey-Yakovenko I don't know how to reproduce the problem, because it happens accidentally. And deadbeef-dbg not available in repo http://notesalexp.org, from which I had install this version.

**Comment by pingplug** [comment]
It seems the same before the line `pulse: failed to write buffer`. But in my issue deadbeef received SIGABRT, not SIGSEGV, and in the error message there is nothing about `pa_write()`. I'm not sure.

@conformist-mw : in my issue, deadbeef will always crash between two songs

**Comment by Alexey-Yakovenko** [comment]
@conformist-mw can you try [the latest build](https://drone.io/github.com/Alexey-Yakovenko/deadbeef/files) and see if the problem has been fixed?

**Comment by conformist-mw** [comment]
@Alexey-Yakovenko, it seems like problem solved. If I'll find any bug, then I'll report here.

**Comment by Alexey-Yakovenko** [comment]
Thanks
