### ISSUE TITLE
Wiki update: Bookmark Manager does not exist

### ISSUE THREAD

**Issue by tvannahl** [Alexey-Yakovenko/deadbeef#1365]
The deadbeef plugin *Bookmark Manager* by Christian Boxdörfer is referenced in the wiki but the project does not exists anymore. The link leads to a Githubs 404.

Would recommend to remove the line.

**Comment by Alexey-Yakovenko** [comment]
@cboxdoerfer ^^ what happened with it? :)

**Comment by cboxdoerfer** [comment]
Totally forgot about that. There was a bug that caused data loss so I made that repo private. Bug was fixed in the meantime, but not pushed and the repo is still private. Should be online tomorrow again ;)

**Comment by cboxdoerfer** [comment]
Plugin is online again. Issue can be closed.
