### ISSUE TITLE
Deadbeef freeze when I add fb plugin

### ISSUE THREAD

**Issue by kxzaon** [Alexey-Yakovenko/deadbeef#1369]
Here's my output : 

starting deadbeef 0.6.2
server_start
searching for GUI plugins in /home/X/.local/lib64/deadbeef
searching for GUI plugins in /home/X/.local/lib/deadbeef
searching for GUI plugins in /usr/lib/deadbeef
plug_load_all: scandir found 53 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /usr/lib/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/kxzaon/.local/lib64/deadbeef
loading plugins from /home/kxzaon/.local/lib/deadbeef
loading plugins from /usr/lib/deadbeef
plug_load_all: scandir found 53 files
loading plugin /usr/lib/deadbeef/aac.so
loading plugin /usr/lib/deadbeef/adplug.so
loading plugin /usr/lib/deadbeef/alac.so
loading plugin /usr/lib/deadbeef/alsa.so
loading plugin /usr/lib/deadbeef/artwork.so
loading plugin /usr/lib/deadbeef/cdda.so
loading plugin /usr/lib/deadbeef/converter.so
loading plugin /usr/lib/deadbeef/converter_gtk2.so
loading plugin /usr/lib/deadbeef/converter_gtk3.so
loading plugin /usr/lib/deadbeef/dca.so
loading plugin /usr/lib/deadbeef/ddb_ao.so
loading plugin /usr/lib/deadbeef/ddb_dumb.so
loading plugin /usr/lib/deadbeef/ddb_misc_filebrowser_GTK3.so
loading plugin /usr/lib/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib/deadbeef/ddb_shn.so
loading plugin /usr/lib/deadbeef/dsp_libsrc.so
loading plugin /usr/lib/deadbeef/ffap.so
loading plugin /usr/lib/deadbeef/ffmpeg.so
loading plugin /usr/lib/deadbeef/flac.so
loading plugin /usr/lib/deadbeef/gme.so
loading plugin /usr/lib/deadbeef/hotkeys.so
loading plugin /usr/lib/deadbeef/lastfm.so
loading plugin /usr/lib/deadbeef/m3u.so
loading plugin /usr/lib/deadbeef/mms.so
loading plugin /usr/lib/deadbeef/mpgmad.so
loading plugin /usr/lib/deadbeef/musepack.so
loading plugin /usr/lib/deadbeef/notify.so
loading plugin /usr/lib/deadbeef/nullout.so
loading plugin /usr/lib/deadbeef/oss.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /usr/lib/deadbeef/pulse.so
loading plugin /usr/lib/deadbeef/shellexec.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk2.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk3.so
loading plugin /usr/lib/deadbeef/sid.so
loading plugin /usr/lib/deadbeef/sndfile.so
loading plugin /usr/lib/deadbeef/supereq.so
loading plugin /usr/lib/deadbeef/tta.so
loading plugin /usr/lib/deadbeef/vfs_curl.so
loading plugin /usr/lib/deadbeef/vfs_zip.so
loading plugin /usr/lib/deadbeef/vorbis.so
loading plugin /usr/lib/deadbeef/vtx.so
loading plugin /usr/lib/deadbeef/wavpack.so
loading plugin /usr/lib/deadbeef/wildmidi.so
loading plugin /usr/lib/deadbeef/wma.so
libWildMidi(WM_BufferFile:640): ERROR Unable to stat /etc/timidity/freepats/freepats.cfg (No such file or directory)
selected output plugin: ALSA output plugin
INFO: loading playlist Default
INFO: from file /home/kxzaon/.config/deadbeef/playlists/0.dbpl
INFO: loading playlist New Playlist
INFO: from file /home/kxzaon/.config/deadbeef/playlists/1.dbpl
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
fb api2
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 3.16.3
connecting button tray signals
gtkui: found cover-art loader plugin

(deadbeef:2151): GLib-CRITICAL **: g_str_has_suffix: assertion 'str != NULL' failed

(deadbeef:2151): Gtk-CRITICAL **: gtk_entry_set_text: assertion 'text != NULL' failed

The last two lines come when I try to add the fb plugin and deadbeef keep freezing.
I'm on a fresh install of arch x86_64 and I tried all GTK2/3 of deadbeef with correct GTK2/3 plugins versions.

Please help. 

Thanks.

**Comment by cboxdoerfer** [comment]
Where did you get the plugin from? Have you tried the one linked [here](http://deadbeef.sourceforge.net/plugins.html)?

**Comment by kxzaon** [comment]
I've taken the AUR version https://aur.archlinux.org/packages/deadbeef-plugin-fb/ or https://aur.archlinux.org/packages/deadbeef-plugin-fb-git/ or https://aur.archlinux.org/packages/deadbeef-plugin-fb-gtk3/

Same errors.

**Comment by Alexey-Yakovenko** [comment]
Please try the build from the link which @cboxdoerfer provided. If it doesn't work -- please contact upstream here: https://sourceforge.net/p/deadbeef-fb/bugs/

**Comment by kxzaon** [comment]
Same result. Ok I'll go.

**Comment by Alexey-Yakovenko** [comment]
@kxzaon It might be that the author accidentally broke compatibility with deadbeef 0.6.2.. in which case trying an old version of the plugin should help.

**Comment by Alexey-Yakovenko** [comment]
I just tried the plugin + deadbeef 0.6.2

I'm getting some spam in console, which looks different from your's:

gtk2:

```
(deadbeef:28931): Gtk-CRITICAL **: IA__gtk_list_store_clear: assertion `GTK_IS_LIST_STORE (list_store)' failed
gtk style: 
style "deadbeef-filebrowser" { 
} 
widget "*.deadbeef_filebrowser_treeview" style "deadbeef-filebrowser" 
```

and gtk3:
```
gtk style: 
* { 
} 
*:selected { 
} 
*:active { 
} 
```

I guess the dev forgot to remove some debug tracing.

But I'm not getting the problems which you describe.

**Comment by cboxdoerfer** [comment]
Maybe the plugins installed from the AUR weren't removed and deadbeef always picks the buggy one. So just be sure that deadbeef picks the right filebrowser plugin.

**Comment by kxzaon** [comment]
Ok so I tried compiling from git but it installs to /usr/local/lib, my system checks to /usr/lib. I tried a ln -s without success. Then I tried this release https://gitlab.com/zykure/deadbeef-fb/blob/release/binary/deadbeef-fb_20150930.tar.gz and I have some new : 

starting deadbeef 0.6.2
server_start
searching for GUI plugins in /home/kxzaon/.local/lib64/deadbeef
searching for GUI plugins in /home/kxzaon/.local/lib/deadbeef
plug_load_all: scandir found 4 files
searching for GUI plugins in /usr/lib/deadbeef
plug_load_all: scandir found 50 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /usr/lib/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/kxzaon/.local/lib64/deadbeef
loading plugins from /home/kxzaon/.local/lib/deadbeef
plug_load_all: scandir found 4 files
loading plugin /home/kxzaon/.local/lib/deadbeef/ddb_misc_filebrowser_GTK2.so
loading plugin /home/kxzaon/.local/lib/deadbeef/ddb_misc_filebrowser_GTK3.so
loading plugins from /usr/lib/deadbeef
plug_load_all: scandir found 50 files
loading plugin /usr/lib/deadbeef/aac.so
loading plugin /usr/lib/deadbeef/adplug.so
loading plugin /usr/lib/deadbeef/alac.so
loading plugin /usr/lib/deadbeef/alsa.so
loading plugin /usr/lib/deadbeef/artwork.so
loading plugin /usr/lib/deadbeef/cdda.so
loading plugin /usr/lib/deadbeef/converter.so
loading plugin /usr/lib/deadbeef/converter_gtk2.so
loading plugin /usr/lib/deadbeef/converter_gtk3.so
loading plugin /usr/lib/deadbeef/dca.so
loading plugin /usr/lib/deadbeef/ddb_ao.so
loading plugin /usr/lib/deadbeef/ddb_dumb.so
loading plugin /usr/lib/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib/deadbeef/ddb_shn.so
loading plugin /usr/lib/deadbeef/dsp_libsrc.so
loading plugin /usr/lib/deadbeef/ffap.so
loading plugin /usr/lib/deadbeef/ffmpeg.so
loading plugin /usr/lib/deadbeef/flac.so
loading plugin /usr/lib/deadbeef/gme.so
loading plugin /usr/lib/deadbeef/hotkeys.so
loading plugin /usr/lib/deadbeef/lastfm.so
loading plugin /usr/lib/deadbeef/m3u.so
loading plugin /usr/lib/deadbeef/mms.so
loading plugin /usr/lib/deadbeef/mpgmad.so
loading plugin /usr/lib/deadbeef/musepack.so
loading plugin /usr/lib/deadbeef/notify.so
loading plugin /usr/lib/deadbeef/nullout.so
loading plugin /usr/lib/deadbeef/oss.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /usr/lib/deadbeef/pulse.so
loading plugin /usr/lib/deadbeef/shellexec.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk2.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk3.so
loading plugin /usr/lib/deadbeef/sid.so
loading plugin /usr/lib/deadbeef/sndfile.so
loading plugin /usr/lib/deadbeef/supereq.so
loading plugin /usr/lib/deadbeef/tta.so
loading plugin /usr/lib/deadbeef/vfs_curl.so
loading plugin /usr/lib/deadbeef/vfs_zip.so
loading plugin /usr/lib/deadbeef/vorbis.so
loading plugin /usr/lib/deadbeef/vtx.so
loading plugin /usr/lib/deadbeef/wavpack.so
loading plugin /usr/lib/deadbeef/wildmidi.so
loading plugin /usr/lib/deadbeef/wma.so
filebrowser[filebrowser.c:3383] start
filebrowser[filebrowser.c:305] load config
filebrowser[filebrowser.c:420] config loaded - new settings: 
enabled:           1 
hidden:            0 
defaultpath:        
show_hidden:       0 
filter_enabled:    1 
filter:             
filter_auto:       1 
show_bookmarks:    1 
extra_bookmarks:   $HOME/.config/deadbeef/bookmarks 
show_icons:        1 
tree_lines:        0 
width:             220 
coverart:          cover.png;cover.jpg;folder.png;folder.jpg;front.png;front.jpg 
coverart_size:     24 
coverart_scale:    1 
save_treeview:     1 
bgcolor:            
fgcolor:            
bgcolor_sel:        
fgcolor_sel:        
icon_size:         24 
font_size:         0 
sort_treeview:     1 
search_delay:      1000 
fullsearch_wait:   5 
hide_navigation:   0 
hide_search:       0 
hide_toolbar:      0 
filebrowser[filebrowser.c:3383] start
filebrowser[filebrowser.c:305] load config
filebrowser[filebrowser.c:420] config loaded - new settings: 
enabled:           1 
hidden:            0 
defaultpath:        
show_hidden:       0 
filter_enabled:    1 
filter:             
filter_auto:       1 
show_bookmarks:    1 
extra_bookmarks:   $HOME/.config/deadbeef/bookmarks 
show_icons:        1 
tree_lines:        0 
width:             220 
coverart:          cover.png;cover.jpg;folder.png;folder.jpg;front.png;front.jpg 
coverart_size:     24 
coverart_scale:    1 
save_treeview:     1 
bgcolor:            
fgcolor:            
bgcolor_sel:        
fgcolor_sel:        
icon_size:         24 
font_size:         0 
sort_treeview:     1 
search_delay:      1000 
fullsearch_wait:   5 
hide_navigation:   0 
hide_search:       0 
hide_toolbar:      0 
libWildMidi(WM_BufferFile:640): ERROR Unable to stat /etc/timidity/freepats/freepats.cfg (No such file or directory)
selected output plugin: ALSA output plugin
INFO: loading playlist Default
INFO: from file /home/kxzaon/.config/deadbeef/playlists/0.dbpl
filebrowser[filebrowser.c:3480] connect
filebrowser[filebrowser.c:3498] error: could not find 'gtkui_1' plugin (gtkui api version 2.1)!
filebrowser[filebrowser.c:3503] trying to fall back to 0.5 api!
plugin File Browser failed to connect to dependencies, deactivated.
filebrowser[filebrowser.c:3528] disconnect
filebrowser[filebrowser.c:3393] stop
filebrowser[filebrowser.c:235] save config
filebrowser[filebrowser.c:296] expanded rows: 
filebrowser[filebrowser.c:3480] connect
filebrowser[filebrowser.c:3486] using 'gtkui3_1' plugin 2.1
fb api2
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 3.16.3
connecting button tray signals
gtkui: found cover-art loader plugin
filebrowser[filebrowser.c:3324] init filebrowser
filebrowser[filebrowser.c:3415] startup
filebrowser[filebrowser.c:735] create interface
filebrowser[filebrowser.c:1111] create sidebar
filebrowser[filebrowser.c:1042] create view and model
filebrowser[filebrowser.c:3336] init
filebrowser[filebrowser.c:229] autofilter: *.aac;*.mp4;*.m4a;*.m4b;*.A2M;*.ADL;*.AMD;*.BAM;*.CFF;*.CMF;*.D00;*.DFM;*.DMO;*.DRO;*.DTM;*.HSC;*.HSP;*.IMF;*.KSM;*.LAA;*.LDS;*.M;*.MAD;*.MKJ;*.MSC;*.MTK;*.RAD;*.RAW;*.RIX;*.ROL;*.S3M;*.SA2;*.SAT;*.SCI;*.SNG;*.XAD;*.XMS;*.XSM;*.JBM;*.mp4;*.m4a;*.cda;*.nrg;*.wav;*.dts;*.cpt;*.psf;*.psf2;*.spu;*.ssf;*.qsf;*.dsf;*.minipsf;*.minipsf2;*.minissf;*.miniqsf;*.minidsf;*.mod;*.mdz;*.s3m;*.s3z;*.stm;*.stz;*.it;*.itz;*.xm;*.xmz;*.ptm;*.ptz;*.mtm;*.mtz;*.669;*.psm;*.umx;*.am;*.j2b;*.dsm;*.amf;*.shn;*.ape;*.aa3;*.oma;*.ac3;*.vqf;*.amr;*.opus;*.tak;*.flac;*.oga;*.ay;*.gbs;*.gym;*.hes;*.kss;*.nsf;*.nsfe;*.sap;*.spc;*.vgm;*.vgz;*.mp1;*.mp2;*.mp3;*.mpga;*.mpc;*.mpp;*.mp+;*.sid;*.wav;*.aif;*.aiff;*.snd;*.au;*.paf;*.svx;*.nist;*.voc;*.ircam;*.w64;*.mat4;*.mat5;*.pvf;*.xi;*.htk;*.sds;*.avr;*.wavex;*.sd2;*.caf;*.wve;*.tta;*.ogg;*.ogx;*.oga;*.vtx;*.wv;*.mid;*.wma;
filebrowser[filebrowser.c:3312] update treeview
filebrowser[filebrowser.c:460] update rootdirs
filebrowser[filebrowser.c:2338] chroot to directory: (null)

(deadbeef:6129): GLib-CRITICAL **: g_str_has_suffix: assertion 'str != NULL' failed

(deadbeef:6129): Gtk-CRITICAL **: gtk_entry_set_text: assertion 'text != NULL' failed
filebrowser[filebrowser.c:2366] browse directory: (null)

**Comment by Alexey-Yakovenko** [comment]
I pinged the fb dev on IRC, I think he's AFK at the moment, but hopefully will respond when he's back.

**Comment by kxzaon** [comment]
Ok thanks for your time.

**Comment by kxzaon** [comment]
I started a fresh install of deadbeef from the app-menu and not a terminal and ... problem fixed. I don't get it but eh.
