### ISSUE TITLE
Cursor moves to different track when sorting.

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1370]
When sorting a playlist using the column header button or the sort actions, any selected tracks stay selected but the cursor position moves to a different track.  The cursor index stays the same, but the track at that index has usually moved to a different index.

**Comment by tvannahl** [comment]
Is there a reason I am overseeing why this issue is closed? I cannot see a commit that is fixing this issue nor is my solution merged.

I don't want to be rude, just don't know what is going on in this case.

**Comment by Alexey-Yakovenko** [comment]
Sorry mate, I thought that I merged the PR, but apparently I haven't. Fixed now.

**Comment by tvannahl** [comment]
Thanks Alexey.
