### ISSUE TITLE
pulseaudio: cannot unpause when paused

### ISSUE THREAD

**Issue by saivert** [Alexey-Yakovenko/deadbeef#1371]
This is due to a bug in the state tracking.
Function pulse_pause calls pulse_free which in turn sets the state to OUTPUT_STATE_STOPPED so deadbeef thinks it has stopped when it is really paused.

This is a regression in commit 8790cca4f43ccad0f61becd0b4fdf46fcc2f2f88

I can submit my quick fix for this but I am more inclined to rewrite the pulseaudio plugin instead of keep fixing the current one. It really should be rewritten to use the asynchronous API.

**Comment by DeadMetaler** [comment]
Same problem
https://www.youtube.com/watch?v=084i4Y8tgQs&feature=youtu.be
