### ISSUE TITLE
Playlist group title for Artist/Date/Album not rendered correctly

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1377]
The standard group by option for Artist/Date/Album does not show the date in the group title drawn in the playlist.  The format is "%album artist% - [(%year%) ]%album%", but only the artist and album are shown.  Using $meta(year) instead of %year% works.

**Comment by Alexey-Yakovenko** [comment]
This has been fixed a while ago.
