### ISSUE TITLE
gtkui: splitters: allow locking size of one side, leaving another dynamic

### ISSUE THREAD

**Issue by Soukyuu** [Alexey-Yakovenko/deadbeef#1378]
Currently, it's only possible to lock the splitter position, which leads to all sorts of problems when resizing the window (most of the time, they don't resize or break layout). It would be much nicer if we could lock one side of the splitter, fixing one component's size while allowing the other side to be sized dynamically.

While it's possible to achieve that (kind of) with leaving the splitters unlocked, it leads to several side issues. For example, use this:
```
 gtkui.layout.0.6.2 vsplitter pos=897 locked=0 {hsplitter pos=1341 locked=1 {tabs active=0 num_tabs=2 tab000="Now Playing" tab001="Library" {playlist hideheaders=0 {} placeholder {} } vsplitter pos=527 locked=1 {tabs active=0 num_tabs=2 tab000="Cover" tab001="Properties" {coverart {} selproperties {} } vsplitter pos=25 locked=1 {hsplitter pos=157 locked=1 {playtb {} hbox expand="1 1 1 1" fill="1 1 1 1" homogeneous=1 {button color="#000000" textcolor="#000000" label="SAC" action="toggle_stop_after_current" use_color=0 use_textcolor=0 {} button color="#000000" textcolor="#000000" label="Linear" action="order_linear" use_color=0 use_textcolor=0 {} button color="#000000" textcolor="#000000" label="Shuffle" action="order_shuffle" use_color=0 use_textcolor=0 {} button color="#000000" textcolor="#000000" label="Repeat" action="loop_cycle" use_color=0 use_textcolor=0 {} } } tabs active=1 num_tabs=2 tab000="Visualization" tab001="Playlists" {musical_spectrum {} pltbrowser {} } } } } waveform_seekbar {} } 
```

With unlocked splitters, the waveform part of the splitter keeps resizing itself on every start, even though I'm trying to keep it at about half the size: [intended](https://dl.dropboxusercontent.com/u/19330332/ddb_intended.jpg) and [after restart](https://dl.dropboxusercontent.com/u/19330332/ddb_unlocked_splitters.jpg)

With locked splitters, the window's status bar is [pushed outside visible range](https://dl.dropboxusercontent.com/u/19330332/ddb_locked_splitters.jpg), and resizing is impossible. Additionally, if you enable and disable the equalizer (popping up at the bottom), it [screws up splitter position/size](https://dl.dropboxusercontent.com/u/19330332/ddb_locked_splitters_eq.jpg) of the wavebar as well...

Strangely, while I was creating these screenshots, I managed to make it remember the waveform size, but now it forgets that it was launched maximized =/

Might be related to #975

**Comment by cboxdoerfer** [comment]
Yeah, foobar2000 does it in a similar way. Just had a look at the GtkPaned documentation and we might be able to achieve that with the "resize" property. I'll have a look at that.

**Comment by cboxdoerfer** [comment]
@Alexey-Yakovenko I think I managed to fix this and the other bugs related to that issue. I altered the internal behavior of the splitter widget (making use of the resize and shrink properties of gtk paned and expand/fill properties of gtk box) so it now works just like the splitter widget in foobar2000.

Do you think we should add those changes to the splitter widget, or maybe introduce a new layout widget?

**Comment by Alexey-Yakovenko** [comment]
Wow! that's really cool. This should be a part of normal splitter widget.
Is this change small enough to get on 0.7 branch?

**Comment by cboxdoerfer** [comment]
Well, it's nothing complicated. The change introduces two new checkboxes, "Lock left/top child" and "Lock right/bottom child". The first one replaces the current "Lock movement" and behaves just like that, so we can import the old splitter config without any issues. So the most part of the new code is for handling the new lock_child2 option, saving and loading new config entries and making some adjustments to the resize, shrink, expand, fill properties when we add new widgets or toggle locking.

I will open a pull request later that day, then you can have a look at that.

**Comment by Alexey-Yakovenko** [comment]
sounds good!

**Comment by cboxdoerfer** [comment]
Damit, tried a different window manager and ran into the same issues we had with auto column resizing, which breaks the layout during initialization when we launch in maximized mode. I managed to fix this, but it's an ugly hack. I'll open pull request in a couple minutes, then you can see for yourself.

**Comment by cboxdoerfer** [comment]
@Soukyuu, fixed on master.
