### ISSUE TITLE
Timed playlist updates stop working after item index changes

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1379]
Some column formats such as %playback_time% automatically update the playlist data every second.  This is done by submitting a timed redraw of a particular row index when tf_eval indicates that it is needed.  If the index of that row is changed, for example by sorting or dragging the row, no timed update is submitted because one is already pending.  When the pending update fires, it draws a different row and no further timers are set.  The timed updates will start again if an expose event triggers a draw including that row.

This could be fixed in a number of ways.  The timer could always be started, and cancelled if one is pending.  Or the timer could be left to run, but the row index that it will draw could be updated to the new index of that row.  Note that the logic currently can only handle a single row being updated in this way, so any pending timers are obsoleted whenever a new one is required.

**Comment by Lithopsian** [comment]
The updates also may stop when the playing track changes, either manually or naturally.  They actually alternate: if the updates are working for a track then they will stop when the next track plays, and if they are not working then a track switch will start them again.

**Comment by Alexey-Yakovenko** [comment]
now fixed on 0.7 branch

**Comment by anewuser** [comment]
@Alexey-Yakovenko  If you add `%playback_time%` to the title bar, it is updated only when you open/close a dialog window.

**Comment by Alexey-Yakovenko** [comment]
Yes, currently this feature is only supported in playlist, but not in the title bar.
