### ISSUE TITLE
Grouping by a "dynamic" field doesn't update the groups when the value changes

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1380]
1. Group a playlist by %playback_time%
2. Switch the playing track, or just let it finish and the next one start
The groups are not redrawn to match the new values of playback time.  With this type of grouping, the playing track should always be in its own group since there can only be one such track, and the groupings should change whenever the playing track changes.

**Comment by Lithopsian** [comment]
The displayed group title also doesn't update.  Overall, this type of grouping is going to be a pain and I don't see much value in it for the users.  It might be simplest just to not allow it, although I don't know how that would be done from an interface point of view.

**Comment by Lithopsian** [comment]
Sorting by %playing_time% is also problematic.  A playing time of 0:00 is represented as a blank string (a deliberate trick for non-playing tracks?) so around the time that the playing track changes, the list does not sort correctly.  Again, a bizarre field to sort by, but right now it is just broken.

**Comment by Alexey-Yakovenko** [comment]
I think it would be a really bad idea to base groups on dynamic fields.

It would make the most sense to add a flag to tf_eval which would always output "" for any dynamic fields (i.e. disable them), and always use that in group titles.

**Comment by Alexey-Yakovenko** [comment]
Added the flag described above, the issue is no longer valid.
