### ISSUE TITLE
Playlist creeps when resizing with auto-resize on, an album art column, and no cursor or group header on the screen

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1386]
1. Create a playlist with an album art column and one group.
2. Set auto-resize on.
3. Select the first row and scroll it off the top of the screen.
4. Resize the playlist width.
The playlist has no anchor to mark a scroll reference point, so it scrolls upwards gradually until it has one.  The anchor is chosen from: cursor; top of first visible group; or end of the first visible group.  It is possible for none of these to be within the visible portion of the playlist, then the playlist creeps with each resize event until an anchor is visible.  There needs to be a fallback position that is guaranteed to be visible, probably just the first row on the screen.

An alternative is not to try and maintain a scroll reference point at all.  Simply leave the vertical scroll position where it is, as happens during manual column resizes.  Or perhaps manual column resizes should also maintain a scroll reference point?

**Comment by cboxdoerfer** [comment]
Thx for spotting. I'll fix that.

But how would having no ref point work? The problem with resizing the album art column is that this also might increase the total height of the playlist (when an album art column becomes wider than the group height groups become larger and vice versa). Just keeping the vertical scroll position then makes the playlist content move. Which looks really strange and is very annoying.

>Or perhaps manual column resizes should also maintain a scroll reference point?

Manual column resizes are already done with a reference point.

**Comment by Lithopsian** [comment]
I guess manual resizes do try to maintain a scroll reference point.  It is so effective in most cases, it just looked like the scroll position was fixed.  A crucial difference is that the scroll reference point is only updated at button down, sometimes noticeable as a small jump at the start of the resize.  For a widget resize it is updated on every configure event.  Anyway, I'm sure you'll fix it up.

**Comment by Lithopsian** [comment]
This looks good now.  Certainly no creeping.

Can you think of any way to stop the anchor changing during a widget resize?  Because the ref point is recalculated for every configure event, it will switch to a different anchor when it rolls into the visible area.  I can't think of anything simple, but thought you might have some ideas.

**Comment by cboxdoerfer** [comment]
Nothing simple either, but on first configure event we could calculate the refpoint and set a timeout (maybe 100ms), if the next configure event happens and the timeout is still ticking we can avoid recalculation of the refpoint and instead set the timeout to 100ms again. So only if there are at least 100ms between two configure events the refpoint is updated.

**Comment by Lithopsian** [comment]
Timers was one idea I thought of.  Do you think it is robust enough to be worthwhile?  It would work for a single smooth resize action, but not when there are pauses or keyboard resizing.

The timer could also be quite a lot longer, I think, easily a second.  Holding onto the same anchor for two resizes very close together isn't a problem.  The anchor only needs to be recalculated if it becomes an invalid scroll reference point, from manually scrolling it away, changing the cursor, or rebuilding the groups (or tab switch?).  Is it possible to keep the same anchor indefinitely until one of those actions occurs?

**Comment by cboxdoerfer** [comment]
Well, certainly, a timer would be a hack, but I think it would work for the most part. And yes, the timer could probably be much longer, since the conditions when a timer has to be removed are pretty clear (of course, after it times out, when the user performs manual scrolling or album art column resizing and changes to the list content (font size, item count).

If you like I can do some experimenting with that as soon as your autoresize pull request gets merged.

**Comment by Lithopsian** [comment]
I think it is worth playing with.  I can create pathological cases that will skip from one group to the next (actually previous) until they reach the cursor row, but it isn't anything like as bad as the problem you already fixed, unlikely to even be noticed as a problem unless you are looking for it.

I can do the same sort of thing with column resizes, but only by lifting off between alternate increases and decreases to the column size.  That really is bizarre behaviour for anyone to do, with only a mildly odd result.
