### ISSUE TITLE
gtkui: DB_EV_FOCUS_SELECTION doesn't get handled properly

### ISSUE THREAD

**Issue by cboxdoerfer** [Alexey-Yakovenko/deadbeef#1398]
If the DB_EV_FOCUS_SELECTION event is sent from a plugin the gtkui listview doesn't focus the selection anymore, but does nothing.

@Lithopsian, I think this got broken in https://github.com/Alexey-Yakovenko/deadbeef/commit/f4b3799dd20f9ca0af349e4eb0e484b42198cd28, but I haven't done a git bisect.

**Comment by Lithopsian** [comment]
No need for a bisect.  I'm pretty sure that was the change.

**Comment by cboxdoerfer** [comment]
Fixed with https://github.com/Alexey-Yakovenko/deadbeef/commit/386851863f138c4a606a9b1869cc09e0a1640d43
