### ISSUE TITLE
Use a standard data format for playlists

### ISSUE THREAD

**Issue by influenza** [Alexey-Yakovenko/deadbeef#1409]
Rather than using a proprietary binary format for saving playlists, use json, xml, or even a csv text format. Any of these options would allow users to do interesting things with their playlists with only the standard GNU core-utils. Additionally, motivated users could easily create tools to gather statistics or automatically generate playlists based on their music collections.

**Comment by Alexey-Yakovenko** [comment]
There are reasons why binary format is used, and this won't be changed. It is possible to import / export m3u, if that's your thing.

**Comment by hi2u** [comment]
@Alexey-Yakovenko Is there any way to import playlists from the command line, while setting the playlist name?  I've only been able to get it to replace the playlist named "Default".

**Comment by Alexey-Yakovenko** [comment]
@hi2u I don't think so.

**Comment by LeDechaine** [comment]
I had the opposite problem, UAPP (android) only exports as XML, and DeadBeeF doesn't support XML.
Here's a fix. It takes time.

You basically have to write your own .m3u file, like that.
```
#EXTM3U
#EXTINF:257,
(full song #1 including filepath)
#EXTINF:257,
(full song #2 including filepath)

```
etc... So.

Open XML file with LibreOffice Calc (or Excel or whatever).
Ask to separate colums with: **"**.
If needed, replace all "/phone/music/folder" to "/computer/music/folder/"
Then, take ONLY the column "/computer/music/folder/songs", paste in a text file if you want.
Add **#EXTM3U** as the top line.
Add an **#EXTINF:257,** line before every song line.
Rename text file as playlist.m3u. Play.

Took me a few minutes and I don't have the knowledge needed to automate this. But hey, it works. Enjoy.
