### ISSUE TITLE
Tracks won't stay paused near to the end

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1411]
1. Play a track and pause it very close to the end.
2. Restart Deadbeef, and playback will resume all on its own.

Or
1. Pause a track and seek to near the end of the track. The playback column will show playing although playback does not usually resume.

Or
1. Create a playlist with multiple tracks and play the first track.
2. Repeatedly seek near the end of the track.
3. Allow to continue playing to the end.  Playback will then skip the next track, possibly several tracks, and play a track further down the playlist.

Other combinations are possible.  I think they are all linked to the way the streamer switches over from one track to another.

**Comment by Alexey-Yakovenko** [comment]
This bug has been fixed while working on ddb2/android. Just need to backport.
