### ISSUE TITLE
Successive descending sorts of the same data give different results

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1415]
The simplest way to see this is using the playlist column header sort.
1. Create a playlist with just one album or artist.
2. Click the album or artist header button twice to get a descending sort.
3. Click again until you reach descending sort again.  The order of the tracks will be reversed.

This example is relatively benign but the new listview code attempts to maintain a sorted playlist when a column header button has been clicked.  Playlist content changed messages cause a sort to be performed to keep the list in order.  It isn't good if this results in the track order being reversed.  Even worse, actions such as seeking or song changes send out content-changed messages which result in sorting.

I can work round this by sorting twice to get back to the original order, but it would be better to have the same input give the same output, even when the sort order isn't strictly defined because the formats match.

Since it is Christmas, it would be really nice to have a function showing if the playlist is already correctly sorted.  At least if it would be a lot faster than doing the actual sort, otherwise not much point.

**Comment by Lithopsian** [comment]
u8_strcasecmp() returns -1 when the strings are identical.  I think it should return zero in this case.  Unless someone squeals that I've lost the plot, I'll prepare a fix.

**Comment by Alexey-Yakovenko** [comment]
just looked when this was added, and it looks like it's a very old bug, which doesn't account for the case when both *p1 and *p2 are 0. so yeah, good catch, and pls fix it.

**Comment by Alexey-Yakovenko** [comment]
I think this is the cause of another related bug, that I noticed a few times lately, that when sorting first by track number, followed by another sort by album + artist -- the track sort order is lost.

**Comment by Lithopsian** [comment]
Yes, when the album/artist descending sort is done, the previous order of tracks gets reversed.  So the tracks end up exactly backwards within each album/artist group.  Then the next time it gets reversed again and is correct.  For the longest time I thought this was intentional.
