### ISSUE TITLE
vfs_curl is sending DDB_PLAYLIST_CHANGE_PLAYQUEUE messages

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1418]
This happens when streaming metadata changes.  This is effectively a track change as well as a metadata content change, but it doesn't seem like either is necessarily a playqueue change. Separate SONGCHANGED and SONGSTARTED messages are sent.  I think the DDB_PLAYLIST_CHANGE_PLAYQUEUE should probably be DDB_PLAYLIST_CHANGE_CONTENT to flag up the changed metadata.

**Comment by Alexey-Yakovenko** [comment]
First of all, you're confusing the DB_EV_PLAYLISTCHANGED message with one of its flags (DDB_PLAYLIST_CHANGE_PLAYQUEUE).

The actual bug - yes, it seems to be an accidental copy&paste error when refactoring.
