### ISSUE TITLE
Segmentation Fault when open properties of track

### ISSUE THREAD

**Issue by DeadMetaler** [Alexey-Yakovenko/deadbeef#1425]
DeadBeeF 0.7 latest
With clean config same issue

starting deadbeef devel [static] [portable]
server_start
searching for GUI plugins in /home/deadmetaler/.local/lib64/deadbeef
searching for GUI plugins in /home/deadmetaler/.local/lib/deadbeef
load_plugin_dir /home/deadmetaler/.local/lib/deadbeef: scandir found 5 files
searching for GUI plugins in /home/deadmetaler/Загрузки/deadbeef-devel/plugins
load_plugin_dir /home/deadmetaler/Загрузки/deadbeef-devel/plugins: scandir found 53 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/ddb_gui_GTK3.so
loading plugins from /home/deadmetaler/.local/lib64/deadbeef
loading plugins from /home/deadmetaler/.local/lib/deadbeef
load_plugin_dir /home/deadmetaler/.local/lib/deadbeef: scandir found 5 files
loading plugin /home/deadmetaler/.local/lib/deadbeef/ddb_customizabletb_gtk3.so
loading plugin /home/deadmetaler/.local/lib/deadbeef/ddb_misc_filebrowser_GTK3.so
loading plugin /home/deadmetaler/.local/lib/deadbeef/ddb_vis_musical_spectrum_GTK3.so
loading plugins from /home/deadmetaler/Загрузки/deadbeef-devel/plugins
load_plugin_dir /home/deadmetaler/Загрузки/deadbeef-devel/plugins: scandir found 53 files
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/aac.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/adplug.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/alac.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/alsa.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/artwork.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/cdda.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/converter.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/converter_gtk2.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/converter_gtk3.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/dca.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/ddb_ao.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/ddb_dumb.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/ddb_mono2stereo.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/ddb_shn.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/dsp_libsrc.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/ffap.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/ffmpeg.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/flac.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/gme.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/hotkeys.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/in_sc68.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/lastfm.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/m3u.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/mms.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/mp3.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/musepack.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/notify.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/nullout.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/oss.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/pltbrowser_gtk2.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/pltbrowser_gtk3.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/pulse.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/shellexec.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/shellexecui_gtk2.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/shellexecui_gtk3.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/sid.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/sndfile.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/supereq.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/tta.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/vfs_curl.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/vfs_zip.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/vorbis.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/vtx.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/wavpack.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/wildmidi.so
loading plugin /home/deadmetaler/Загрузки/deadbeef-devel/plugins/wma.so
selected output plugin: PulseAudio output plugin
INFO: loading playlist Continuo Renacer
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/0.dbpl
INFO: loading playlist Canvas Solaris
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/1.dbpl
INFO: loading playlist Cannibal corpse
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/2.dbpl
INFO: loading playlist Alghazanth
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/3.dbpl
INFO: loading playlist Abnormal Thought Patterns
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/4.dbpl
INFO: loading playlist Edge Of Sanity
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/5.dbpl
INFO: loading playlist Pessimist
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/6.dbpl
INFO: loading playlist Accept
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/7.dbpl
INFO: loading playlist Algebra
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/8.dbpl
INFO: loading playlist Pantera
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/9.dbpl
INFO: loading playlist Arch Enemy
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/10.dbpl
INFO: loading playlist Wayd
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/11.dbpl
INFO: loading playlist Portal
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/12.dbpl
INFO: loading playlist Sacrarium
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/13.dbpl
INFO: loading playlist Ryashon
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/14.dbpl
INFO: loading playlist Solarward
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/15.dbpl
INFO: loading playlist Spaced Out
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/16.dbpl
INFO: loading playlist Shade Empire
INFO: from file /home/deadmetaler/.config/deadbeef/playlists/17.dbpl
fb api2
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 3.0.0
gtk style: 
* { 
    background-color: #2D3030; 
    color:            #E6E6E6; 
} 
*:selected { 
    background-color: #215D9C; 
    color:            #FFFFFF; 
} 
*:active { 
    background-color: #215D9C; 
    color:            #FFFFFF; 
} 

** (deadbeef:21585): WARNING **: Widget not found: Skip to_menu
Segmentation Fault
backtrace() returned 27 addresses
/home/deadmetaler/Загрузки/deadbeef-devel/deadbeef() [0x4039f3]
/usr/lib/libc.so.6(+0x33680) [0x7f0eecf2c680]
/home/deadmetaler/Загрузки/deadbeef-devel/plugins/ddb_gui_GTK3.so(action_show_track_properties_handler_cb+0x4) [0x7f0eec9fe514]
/usr/lib/libgobject-2.0.so.0(g_closure_invoke+0x145) [0x7f0eeb8a1015]
/usr/lib/libgobject-2.0.so.0(+0x22061) [0x7f0eeb8b3061]
/usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0xfbc) [0x7f0eeb8bbdfc]
/usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f0eeb8bc12f]
/usr/lib/libgtk-3.so.0(gtk_widget_activate+0x6e) [0x7f0eec3a70f6]
/usr/lib/libgtk-3.so.0(gtk_menu_shell_activate_item+0x106) [0x7f0eec28f51e]
/usr/lib/libgtk-3.so.0(+0x226869) [0x7f0eec28f869]
/usr/lib/libgtk-3.so.0(+0x2098a2) [0x7f0eec2728a2]
/usr/lib/libgobject-2.0.so.0(+0x10244) [0x7f0eeb8a1244]
/usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x718) [0x7f0eeb8bb558]
/usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f0eeb8bc12f]
/usr/lib/libgtk-3.so.0(+0x33bd54) [0x7f0eec3a4d54]
/usr/lib/libgtk-3.so.0(+0x206cfe) [0x7f0eec26fcfe]
/usr/lib/libgtk-3.so.0(gtk_main_do_event+0x71c) [0x7f0eec271a2c]
/usr/lib/libgdk-3.so.0(+0x57572) [0x7f0eeb100572]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x2a7) [0x7f0eeb3c2dc7]
/usr/lib/libglib-2.0.so.0(+0x4a020) [0x7f0eeb3c3020]
/usr/lib/libglib-2.0.so.0(g_main_loop_run+0xc2) [0x7f0eeb3c3342]
/usr/lib/libgtk-3.so.0(gtk_main+0x7d) [0x7f0eec270c95]
/home/deadmetaler/Загрузки/deadbeef-devel/plugins/ddb_gui_GTK3.so(gtkui_thread+0x726) [0x7f0eec9b46d6]
/home/deadmetaler/Загрузки/deadbeef-devel/plugins/ddb_gui_GTK3.so(+0x3390d) [0x7f0eec9b490d]
/home/deadmetaler/Загрузки/deadbeef-devel/deadbeef() [0x403496]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f0eecf19610]
/home/deadmetaler/Загрузки/deadbeef-devel/deadbeef() [0x403901]

**Comment by Alexey-Yakovenko** [comment]
already fixed in 8108f2a646785112390acc242387458d966e55ff

**Comment by DeadMetaler** [comment]
Yes. Redownloaded after 3 minutes and it's fixed.
