### ISSUE TITLE
deadbeef doesn't play nice with tiling window managers

### ISSUE THREAD

**Issue by orbea** [Alexey-Yakovenko/deadbeef#1432]
On spectrwm 2.7.2 I am running the gtk2 deadbeef 0.6.2 compiled from source with this patch (Which it won't compile without). https://projects.archlinux.org/svntogit/community.git/tree/trunk/plugins_vfs_zip_vfs_zip_c.patch?h=packages/deadbeef

To illustrate the issue here is my current deadbeef layout.
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/deadbeef/2015-12-31-233111_748x1040_scrot.png)

When I open a new terminal deadbeef resizes to this, which is not really an issue.
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/deadbeef/2015-12-31-233122_1680x1050_scrot.png)

Now the problem is that when I close the new terminal deadbeef resizes to its original size, but fails to resize its layout appropriately leaving it for the user to do so manually, which quickly becomes tedious.
![3](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/deadbeef/2015-12-31-233152_748x1040_scrot.png)
![4](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/deadbeef/2015-12-31-233234_748x1040_scrot.png)

**Comment by Alexey-Yakovenko** [comment]
Other related issues: #975, #1378

**Comment by cboxdoerfer** [comment]
@orbea, This should be fixed on master. Would be great if you could verify that.

**Comment by orbea** [comment]
Yes, I can confirm this is fixed, thanks!
