### ISSUE TITLE
Characters Are Being Changed To Underscores

### ISSUE THREAD

**Issue by Geyup** [Alexey-Yakovenko/deadbeef#1435]
For deadbeef 0.6.2 compiled from source...

I noticed in my ~/cache/deadbeef/covers/ names with charactes in them, commas, apostrophes, dots, any symbol, is getting changed now to underscores for the images and directories...

***images***
A Day's Wait - Single.jpg
changed;
A Day_s Wait - Single.jpg

A Product of ... (Participation).jpg
changed;
A Product of ___ _Participation_.jpg

***Directory***
Siouxsie & The Banshees
changed;
Siouxsie_The Banshees

All I can think that possibly has caused this is when I changed my system locale;

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by Alexey-Yakovenko** [comment]
This is normal, not caused by locale. Part of the code.

**Comment by Alexey-Yakovenko** [comment]
@Lithopsian might be able to explain it in more details, as it was changed by him in commit 28a6afa2f7ef55f270de5bd258a51c02facd7a29

**Comment by Lithopsian** [comment]
I don't remember the exact reasons, but the intent is fairly clear.  The code replaces all characters which might cause trouble for file handling or parsing with an underscore.  It probably replaces more characters than are strictly necessary, certainly for Linux, but writing extra code to allow strange characters that might fail on operating systems I haven't tested seemed pointless and risky.

**Comment by Geyup** [comment]
I forgot to mention, this did not happen before, I have a backup of the cache with all the directorys and files, and pictures with the symbols...

This is something new that has happened, and I'm not sure what caused it to change.

**Comment by Geyup** [comment]
@Alexey-Yakovenko it can't be normal because this never happened when I first set up my music in deadbeef and I can tar up and show you an entire cache full of files that all the symbols are there and were never changed... 

hmm

**Comment by Alexey-Yakovenko** [comment]
I know that it didn't happen before. It was added in the commit I linked above. Still it is normal. Why do you care about the internal cache filenames? I could call them sha1 hashes, and this would still be normal.

**Comment by Geyup** [comment]
@Alexey-Yakovenko I'm using 0.6.2 I haven't changed it since it came out...

hmm

**Comment by Alexey-Yakovenko** [comment]
> maybe I saw it like this in 0.6.1 and then when I upgraded to 0.6.2

Yes, this has been added right before the 0.6.2 release, about 1.5 years ago.

> There's no way to put this back and make it work to perserve the names, and not be a problem?

Anything has to have a reason. I don't see any reason to do this yet.

> I'd love to see the names protected, not replaced if possible, if there's a way to figure this out a way...

Then stop looking into cache folders. You're not supposed to - it's for the programs, not for the users.

**Comment by Geyup** [comment]
Well the thing is, I personally look at my entire structure of directories in my $HOME, just for safety reasons, I think it's good to know what you have in your $HOME... hehe :)

But I also make a backup of the cache, so if something were to happen and I needed to reinstall I have it, so in the backup sense, of digging around through it, this is where it gets odd looking at it this way.

Look you're the Boss, LOL, but, let's think about it like this, cache or not, what other app do you know of that changes the naming of directories or files?

I've personally never seen this in any applicaiton I've used over the past 15 years, I'm just saying is all, this is not common at all... Just some thought here is all..

Alexey-Yakovenko, thank you very much though for the work you do, I really love deadbeef!

Cheers

**Comment by Alexey-Yakovenko** [comment]
I'm sorry man, can't help you. You're abusing the concept of a cache. The fact that the cache contains multiple files with human-readable names is a coincidence. It's not guaranteed to stay this way. It's not the most efficient way to store the data.

**Comment by Geyup** [comment]
Can you please explain what you believe the cache is for?

When I use deadbeef I only get 3 directories in the cache;

Bio
Cover
lyrics

I'm not following why these would be placed in a cache directory instead of along with deadbeef under ~/.config?

**Comment by Alexey-Yakovenko** [comment]
@Geyup 

http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

**Comment by Alexey-Yakovenko** [comment]
You should be able to find plenty of explanation what cache is, in computing.

In particular, this is the explanation of disk cache, which we have here:

https://en.wikipedia.org/wiki/Cache_(computing)#Disk_cache

**Comment by Alexey-Yakovenko** [comment]
@Geyup 
I decided to remove the escaping of filenames in the artwork plugin, because after some discussion we couldn't come up with any significant reason to do it. Hope that helps.

It's on master branch, and most likely will be in 0.7 too.

@Lithopsian FYI

**Comment by Alexey-Yakovenko** [comment]
Had to restore the filename escaping, but reduced it to only escape \ and / chars depending on current platform. Without escaping the /, it was possible to overwrite any accessible files in the system, by using `../../../whatever`.

**Comment by Geyup** [comment]
@Alexey-Yakovenko so the ```bio``` ```cover``` and ```lyrics``` won't have this anymore, when you mention Artwork Plugin, meaning all these directories?

**Comment by cboxdoerfer** [comment]
bio and lyrics folders are from a third party plugin, I guess infobar. But files in cover will now work like you expect.

**Comment by Geyup** [comment]
thanks
