### ISSUE TITLE
(master) Cannot invoke inline editing/renaming of audio files (F2)

### ISSUE THREAD

**Issue by andreas--e** [Alexey-Yakovenko/deadbeef#1438]
Definitely worked in an older `master` build compiled roughly 2 weeks ago.
This new feature is also the reason why in my personal settings, I moved 'Track Properties' to `F4` to be sure I won't be blocking `F2` with other actions.
In current master, however, `F2` is dead and does nothing.

**Comment by Alexey-Yakovenko** [comment]
I don't remember deadbeef to ever have this feature...
@cboxdoerfer do you remember if you added it recently?

**Comment by cboxdoerfer** [comment]
No, this feature was never there. @andreas--e, Maybe we you mean the inline editing in the playlist browser? Cause this was removed on purpose. However F2 shortcut might be added again at some point, but then it will open a dialog to rename the playlist.

**Comment by andreas--e** [comment]
A strange dream perhaps? ;)
Well, from one point, I was able to rename an audio file, i. e. the line where the file was displayed in the playlist got editable and the name was changeable.
At least I *seem to remember* that although I am permanently making use of playlist tabs, the playlist browser plugin (`pltbrowser`) requires a change in design mode, i. e. it is not available in default layout.

**Comment by Alexey-Yakovenko** [comment]
Sounds like you confused deadbeef with some other player, or a file manager. Closing.
