### ISSUE TITLE
Converting from a format handled by ffmpeg plugin adds !filetype tag

### ISSUE THREAD

**Issue by Soukyuu** [Alexey-Yakovenko/deadbeef#1442]
When converting from any format that is handled by the ffmpeg plugin, the resulting file will have an additional tag "!filetype" with value of the format as displayed in the UI, e.g.: "tak"

**Comment by Alexey-Yakovenko** [comment]
Which format are you converting into?

**Comment by Soukyuu** [comment]
Last time it was mpc, so APEv2 tags (junk lib?) 



On Alexey Yakovenko <notifications@github.com>, Jan 19, 2016 10:41 AM wrote:Which format are you converting into?
