### ISSUE TITLE
AppMenu integration for GTK3

### ISSUE THREAD

**Issue by Hori873** [Alexey-Yakovenko/deadbeef#1443]
Can you migrate the menu bar to the AppMenu for the GTK3 version, please? Or at least give us the ability to hide the menu bar.

**Comment by cboxdoerfer** [comment]
Take a look at this plugin: https://github.com/saivert/ddb_misc_headerbar_GTK3

**Comment by Alexey-Yakovenko** [comment]
> Or at least give us the ability to hide the menu bar.

This is not exposed in UI as a dedicated option, but it's possible to bind a hotkey on the action `View -> Show/Hide menu`, or add `gtkui.show_menu 0` to the config file.
