### ISSUE TITLE
from r6398.38497f5 to r6419.32a2d16: gtkui unresponsive, fails to resume playing track

### ISSUE THREAD

**Issue by Soukyuu** [Alexey-Yakovenko/deadbeef#1444]
I left a track playing on r6398 then exited to upgrade to r6419 - the playback won't resume, the GUI shows three dots in the playing column and is unresponsive as above. Passing a track to deadbeef via cmdline plays the track, but the UI is dead.

There are no error messages in the console. Both GTK2 and GTK3. 

You can still click on everything (correct highlighting and animation), but there is no reaction. So it's not really hanging, just not "wired", it seems.

**Comment by Alexey-Yakovenko** [comment]
FYI: the numbers 6398 etc are local to your computer.

**Comment by Soukyuu** [comment]
Ok... I thought it was using shortened versions of commit hashes.
r6398 was built yesterday@23:55 GMT+2
r6419 was built today 20 mins ago.

**Comment by Alexey-Yakovenko** [comment]
I think it's a result of bad merge in either streamer, or pulseaudio plugin.

**Comment by Alexey-Yakovenko** [comment]
I just repeated your description, and can't reproduce the problem.
Which output plugin are you using?

**Comment by Soukyuu** [comment]
pulse, input is ffmpeg

**Comment by Soukyuu** [comment]
it seems to be hanging in ffmpeg, the console output gets stuck at `[mjpeg @ 0x7fe568002140] Changeing bps to 8`

**Comment by Alexey-Yakovenko** [comment]
I didn't touch ffmpeg for a while, and both alsa and pulse work fine here.

Since you know that the problem was introduced between 38497f5 and 32a2d16, could you run a bisect?

**Comment by Alexey-Yakovenko** [comment]
> it seems to be hanging in ffmpeg


can't be caused by deadbeef then... the last ffmpeg change is 7fc437febaecadef7553ac4d1ca00e93fa7d8cbe

**Comment by Alexey-Yakovenko** [comment]
would be nice to get a backtrace too. the process described [here](https://github.com/Alexey-Yakovenko/deadbeef/wiki/GDB-HOWTO#generating-the-backtrace)

**Comment by Alexey-Yakovenko** [comment]
could you also check if the same problems happens on 0.7 branch?

**Comment by Soukyuu** [comment]
I've used an older ffmpeg.so and it's the same behavior, so it shouldn't be ffmpeg as I haven't updated it between the two builds. The only difference i see in the console is that the working build shows one of those `** (deadbeef:1197): WARNING **: Widget not found: Skip to_menu` and stuff works, while the broken build does not. 

I will be doing a bisect soon.

**Comment by Soukyuu** [comment]
Well, this is funny. The build works fine when not installed into the system (just make), but once I install it using makepkg, it breaks?!

**Comment by Alexey-Yakovenko** [comment]
I don't use packages, so can't really help you with the problem.. but it seems like some local problem.

**Comment by Soukyuu** [comment]
I goofed up, launched `deadbeef` instead of `./deadbeef` having a working version installed. According to bisect, the offending commit is:

```
22adf36d763b2e468b22902bb1ac2a55904555e8 is the first bad commit
commit 22adf36d763b2e468b22902bb1ac2a55904555e8
Author: Alexey Yakovenko <wakeroid@gmail.com>
Date:   Sun Jan 10 12:29:12 2016 +0100

    gtkui: import old tf in search window

:040000 040000 6f1ab1cdbe629fd6d7ddbbc686d10396253f8282 b7080709cf439811cc5059c3b45d1349fa8de112 M      plugins
```

**Comment by Soukyuu** [comment]
And indeed, checking out 76320a8e823f1f7099e4ea97cb505ca0f40e3aab works, checking out 22adf36d763b2e468b22902bb1ac2a55904555e8 breaks.
