### ISSUE TITLE
tf: Some sort of auto conversion broke my grouping

### ISSUE THREAD

**Issue by Soukyuu** [Alexey-Yakovenko/deadbeef#1447]
I'm not sure when it happened. Noticed only when loading an album with multiple discs and seeing it wasn't sorting it as it's supposed to. 

This is the original:
```
%album% $ifgreater(%totaldiscs%,1, Disc #%discnumber%,)[ (%date%)]
```
Mangled version:
```
%artist%lbum$ifgreater(%title%otaldiscs,1, Disc #%directoryname%iscnumber,)[ (%directoryname%ate)]
```
Only the custom grouping seems to have been affected.

**Comment by Alexey-Yakovenko** [comment]
I wrote about it on IRC.

You can get back your stuff by renaming the old variables (without _tf ending) into the new ones (with _tf ending).

This is caused by the 0.6.2 -> 0.7.0 title formatting migration.

The problem is caused by reuse of the 0.6.2 variable names in the development versions.
