### ISSUE TITLE
FFMPEG plugin seek is imprecise?

### ISSUE THREAD

**Issue by Soukyuu** [Alexey-Yakovenko/deadbeef#1449]
Found this issue as reported [here](https://github.com/cboxdoerfer/ddb_waveform_seekbar/issues/9). Seeking .tak files doesn't seek to the correct position, the error is about 1-3 seconds and can be reproduced with no relation to the length. Other decoders seem to seek correctly.

**Comment by Alexey-Yakovenko** [comment]
@Soukyuu 

Most likely it's the bug in ffmpeg TAK codec -- deadbeef doesn't implement its own seeking for ffmpeg formats.

I don't feel like this bug belongs here. If you want to get it fixed -- the best way is to repro with ffplay, and report to ffmpeg devs.

**Comment by Soukyuu** [comment]
The biggest problem is that there is no way to see the waveform and seek to a specific position, I guess I'll just live with it. I should be able to afford a HDD or two now, so maybe I'll just transcode my library back to FLAC and stop supporting a codec that's locked to one platform officially.
