### ISSUE TITLE
Fails to edit metadata of opus files

### ISSUE THREAD

**Issue by rekcuFniarB** [Alexey-Yakovenko/deadbeef#1451]
Opus files use ogg container afaik. [Example file](http://toxicity.myftp.org/Share/TMP/Audio/Paul%20Hartnoll%20-%2008%20-%20Nearly%20There.opus).

Tested in Deadbeef 7.0 beta2-1 static x86_64 only.

**Comment by Alexey-Yakovenko** [comment]
deadbeef doesn't support editing tags in opus files. there's a 3rd party plugin which you can use for that, see here: https://bitbucket.org/Lithopsian/deadbeef-opus/overview
