### ISSUE TITLE
Stock spectrum widget 2-3% CPU load when idle

### ISSUE THREAD

**Issue by rekcuFniarB** [Alexey-Yakovenko/deadbeef#1452]
There is little CPU load (2%-3%) when Deadbeef not playing anything (stopped) and even window is minimized. Strace continuously prints [this](http://pastebin.com/EWzdf8rP) at that time.

**Comment by Alexey-Yakovenko** [comment]
which version?

**Comment by rekcuFniarB** [comment]
Sorry, forgot to write the version. 0.7 beta2-1 official static build from sourceforge.net (both x86 and x86_64).

**Comment by Alexey-Yakovenko** [comment]
ok.. I'm about to make RC1, then will spend time profiling / performance testing. Thanks for the report.

**Comment by Alexey-Yakovenko** [comment]
Seems to be a local problem on your computer. I can't reproduce. If you're sure the bug is valid -- please send your configuration file, and deadbeef startup log, to see which plugins do you have.

**Comment by rekcuFniarB** [comment]
I found out that it was caused by spectrum widget (official one shipped with Deadbeef).
