### ISSUE TITLE
workaround to "play" cue files?

### ISSUE THREAD

**Issue by wdlkmpx** [Alexey-Yakovenko/deadbeef#1455]
Here are some examples:

http://digitalx.org/cue-sheet/examples

Basically, when opening a CUE file, deadbeef could

1) Look for the 1st 'FILE "path/to/file.ext" WAVE' and get path/to/file.ext
2) if path/to/file.ext or file.cue exists, then this CUE file can be assigned to it (tracks, properties)
3) Open that file and use the data from the .CUE file

If that fails, show error message (optional)

It would be more like an internal wrapper, a simple one.

I use a primitive script that lets me open "cue" files as long as the cue files
have the same base name as the audio files:

	EXE='deadbeef'
	case $1 in *.cue|*.CUE)
		[ ! -f "$1" ] && echo "File does not exist..." && exit 1
		file="$1" 
		exts='wav flac ape tta tak wv mp3 ogg aac m4a ac3'
		filebase=${file%.*}
		for ext in ${exts} ; do
			[ -f  "${filebase}.${ext}" ] && exec ${EXE} "${filebase}.${ext}"
			[ -f  "${filebase}.${ext^^}" ] && exec ${EXE} "${filebase}.${ext^^}" ##uppercase extension
		done
		msg="deadbeef doesn't support opening CUE files directly. You must open a nedia file, and it will search for the cue file with the same base name. Example: \n\n cdimage.wav \n cdimage.cue \n\nOpen cdimage.wav and deadbeef will automatically load the CUE file."
		exec yad --title=deadbeef --text="$msg" --image=dialog-error --center --button=gtk-ok
	esac

A "native" support would be nice, as it would take any cue file and assign it to any audio file...
as long as the audio file actually exists...

I guess that would require a variable or something like that.

If the "cue" variable is set by the function that "opens" the cue file, 
once the real audio file is opened, then it uses the data from the CUE file instead of 
searching for the .cue file with the same base name (or internal cue files)...

Just some ideas...

**Comment by Alexey-Yakovenko** [comment]
I don't really get what is this about... some sort of instruction?

**Comment by Alexey-Yakovenko** [comment]
This ticket seems to be a recipe to open cue files using an external shell script. It doesn't belong in the bug tracker. Perhaps you should post it on some forum.
