### ISSUE TITLE
CUE: deadbeef ignores TRACKS if there's no TITLE (or if it's blank)

### ISSUE THREAD

**Issue by wdlkmpx** [Alexey-Yakovenko/deadbeef#1456]
dead completely ignores this cue file

	FILE "file.wav" WAVE
	 TRACK 01 AUDIO
	  INDEX 01 00:00:00
	 TRACK 02 AUDIO
	  INDEX 01 05:50:65
	 TRACK 03 AUDIO
	  INDEX 01 09:47:50
  
if you add titles, then everything is ok:

	FILE "file.wav" WAVE
	 TRACK 01 AUDIO
	  TITLE "Track 1"
	  INDEX 01 00:00:00
	 TRACK 02 AUDIO
	  TITLE "Track 2"
	  INDEX 01 05:50:65
	 TRACK 03 AUDIO
	  TITLE "Track 3"
	  INDEX 01 09:47:50

If you remove TITLE from TRACK 02, deadbeef shows only Track 01 and Track 03

	FILE "file.wav" WAVE
	 TRACK 01 AUDIO
	  TITLE "Track 1"
	  INDEX 01 00:00:00
	 TRACK 02 AUDIO
	  INDEX 01 05:50:65
	 TRACK 03 AUDIO
	  TITLE "Track 3"
	  INDEX 01 09:47:50

If title is "", the track is also ignored

deadbeef completely ignores this cue file

	FILE "file.wav" WAVE
	 TRACK 01 AUDIO
	  TITLE ""
	  INDEX 01 00:00:00
	 TRACK 02 AUDIO
	  TITLE ""
	  INDEX 01 05:50:65
	 TRACK 03 AUDIO
	  TITLE ""
	  INDEX 01 09:47:50

Here it only recognizes and plays TRACK 03

	FILE "file.wav" WAVE
	 TRACK 01 AUDIO
	  TITLE ""
	  INDEX 01 00:00:00
	 TRACK 02 AUDIO
	  TITLE ""
	  INDEX 01 05:50:65
	 TRACK 03 AUDIO
	  TITLE "Track 3"
	  INDEX 01 09:47:50

--

I think the code that parses a cue file should report "Unknown" or "Track XX" or something like that when there is no title...

**Comment by wdlkmpx** [comment]
Apparently if you insert this

	if (!strcmp (title, "")) {
		strcpy (title, "Unknown");
	}

into line 1144, playlist.c .. solves the issue

**Comment by Alexey-Yakovenko** [comment]
This is not the correct solution. Title must remain undefined/empty if it's not specified.
