### ISSUE TITLE
Disc column contains invalid characters (%@disc@ 0.7.0 import problem)

### ISSUE THREAD

**Issue by Kilte** [Alexey-Yakovenko/deadbeef#1460]
![2016-02-01-094927_1920x1080_scrot](https://cloud.githubusercontent.com/assets/5552990/12710714/55b8890c-c8ca-11e5-8e01-aeaa61d68d16.png)

DeaDBeeF 0.7.0

**Comment by Alexey-Yakovenko** [comment]
Looks like title formatting config importer bug. It's easy to work around, just re-create the problematic column. But could you please send me a screenshot of your current configuration of this column, and relevant parts of the config file?

**Comment by Kilte** [comment]
I've changed format from `%disc%` to `%discnumber%` and it works for 0.7.0 and 0.6.2 both.

**Comment by Alexey-Yakovenko** [comment]
Ok, I probably forgot to implement the importing of this `%@disc@` syntax.
Will do in 0.7.1. Thanks.

**Comment by Kilte** [comment]
Same issue for `playlist.group_by %@ALBUM@`

**Comment by Alexey-Yakovenko** [comment]
Yes, if it's broken - it would happen with all $@...@ fields. Sorry for that. People rarely used this syntax in 0.6.2, and we didn't catch this during testing.
