### ISSUE TITLE
Сообщение в консоли

### ISSUE THREAD

**Issue by IgorSapkov** [Alexey-Yakovenko/deadbeef#1463]
Все работает, но при наведении курсора мыши на значок программы в трее в консоль выдаются  4 раза сообщение 
(deadbeef:32202): Gdk-CRITICAL **: IA__gdk_window_get_root_coords: assertion 'GDK_IS_WINDOW (window)' failed

**Comment by Alexey-Yakovenko** [comment]
баги GTK и WM (а именно они ответственны за отображение и обработку значка в системном трее) следует отправлять в багтрекеры GTK или вашего WM, соответственно.
