### ISSUE TITLE
New playlist from selection

### ISSUE THREAD

**Issue by dsx** [Alexey-Yakovenko/deadbeef#1468]
This is a feature request.

It would be quite convenient to have an option to create new playlist from selected tracks.

**Comment by dronord** [comment]
**How-to**
Ctrl+N
Select tracks
Drag and Drop tracks to previous created list

M?

**Comment by Alexey-Yakovenko** [comment]
yeah, it's possible to do using d-n-d, and this issue is actually kinda a duplicate of #655

**Comment by dsx** [comment]
Requires 3 (three!) actions instead of one. But yeah whatever.
