### ISSUE TITLE
Hiding/restoring maximized window by clicking tray icon doesn't preserve widget layout

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#1469]
Continued from the bug #1465.

Fixing the issue with tray is different than fixing the issue on start/quit, therefore the new bug.

Details: The window gets "restored" from maximized state at some point, and the widgets get "shrunk" in the process. That's especially a problem with Splitter widgets, which don't automatically adopt to window resizing, but clip to the max possible size instead.

**Comment by Alexey-Yakovenko** [comment]
The problem: we can't really prevent GTK from "unmaximizing" the window during restoration from notification area.

The proposed solution: implement proportional scaling for splitters, in reaction to configure event. That's quite a lot of work, so can't be done for 0.7.1, and should go on master.

**Comment by cboxdoerfer** [comment]
This should be fixed with the recent splitter changes on master.
