### ISSUE TITLE
Chinese characters used erroneously instead of some Latin characters in playlist

### ISSUE THREAD

**Issue by cipricus** [Alexey-Yakovenko/deadbeef#1470]
**ç, é, ä, oe** and others are replaced with Chinese characters.

This bug is rare on the whole but it happens very often in two circumstances that I encounter: 

1. when listening to radio streams and 

2. when listening to French music 

Sometimes whole groups of characters are replaced  with Chines ones, even if only one character is French/German.

This bug is present **in 0.7**  but it affected previous versions as reported [here as separate bug](https://github.com/Alexey-Yakovenko/deadbeef/issues/1137) - now closed

Also, although relatively rare, it involves files that are correctly read by **all** other players that I tested - not just VLC mentioned in the linked bug report.

[![enter image description here][1]][1]

  [1]: http://img.ctrlv.in/img/16/02/03/56b20e4422935.png

Saving this playlist as m3u, it contains these lines:

    #EXTM3U
    #EXTINF:163,Serge Gainsbourg - Le poin輟nneur des Lilas
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1958 - Du chant à la une !/02 - Le poinçonneur des Lilas.mp3
    #EXTINF:143,Serge Gainsbourg - Charleston des d駑駭ageurs de
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1958 - Du chant à la une !/10 - Charleston des déménageurs de piano.mp3
    #EXTINF:129,Serge Gainsbourg - Adieu cr饌ture
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1959 - Serge Gainsbourg N°2/14 - Adieu créature.mp3
    #EXTINF:134,Serge Gainsbourg - Indiff駻ente
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1959 - Serge Gainsbourg N°2/17 - Indifférente.mp3
    #EXTINF:180,Serge Gainsbourg - La chanson de Pr騅ert
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1961 - L'Étonnant Serge Gainsbourg/01 - La chanson de Prévert.mp3
    #EXTINF:158,Serge Gainsbourg - Les Go駑ons
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1962 - Serge Gainsbourg N° 4/11 - Les Goémons.mp3
    #EXTINF:142,Serge Gainsbourg - Ce grand m馗hant vous
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1962 - Serge Gainsbourg N° 4/18 - Ce grand méchant vous.mp3
    #EXTINF:143,Serge Gainsbourg - Chez les y騫駸
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1963 - Gainsbourg Confidentiel/01 - Chez les yéyés.mp3
    #EXTINF:123,Serge Gainsbourg - Joanna
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/1964 - Gainsbourg Percussions/13 - Joanna.mp3
    #EXTINF:163,Serge Gainsbourg - Chanson du for軋t
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/what/01 - Chanson du forçat.mp3
    #EXTINF:69,Serge Gainsbourg - Chanson du for軋t II
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/what/02 - Chanson du forçat II.mp3
    #EXTINF:115,Serge Gainsbourg - Vilaines filles, mauvais gar輟
    /media/cipeos/DEPO AUDIO/Pop&rock/Gainsbourg/what/20 - Vilaines filles, mauvais garçons.mp3

Opening this very m3u file with other players, all displayed the correct names (avoiding to read the Chinese characters), excepting one (Clementine). 

Under Edit -> Preferences -> GUI/Misc, only the Russian detection was enabled (by default), not the Chinese. Enabling or disabling all of them changes nothing here.

**Comment by Alexey-Yakovenko** [comment]
can you send me any of these mp3 files privately for testing?

**Comment by Alexey-Yakovenko** [comment]
There can be a number of reasons why this can happen.. which are hard to guess without having access to an example file.

**Comment by cipricus** [comment]
of course. how should I send them?

**Comment by Alexey-Yakovenko** [comment]
There was an example some time ago, when the file had an embedded cuesheet with wrong data, but since most players can't use this information - the file looked "correctly" in them, but looked "wrong" in deadbeef.

It can also be cp936 or shift-jis misdetection, but you're claiming that you disabled both.

Ah and the last thing -- shift-jis gets automatically enabled in certain cases even if disabled. Might be this as well. But I need to use debugger to find out.

**Comment by Alexey-Yakovenko** [comment]
> of course. how should I send them?

please only 1 file, use email wakeroid@gmail.com

**Comment by cipricus** [comment]
Iĺl send soon the file for testing

**Comment by cipricus** [comment]
I have sent a file to your gmail

**Comment by cipricus** [comment]
I have disabled all detection of non-Latin characters, restarted db and the setting was kept (at least shown as such by the GUI)

**Comment by cipricus** [comment]
There must be some wrong data involved, as many other files that I have (also mp3 files with French characters) are not affected by this.

**Comment by Alexey-Yakovenko** [comment]
I opened the file, and it doesn't have the problem you describe. Are you sure that you re-added / reloaded the file(s) after changing the settings?

**Comment by Alexey-Yakovenko** [comment]
hmmm.. ok, it doesn't happen on OSX, but happens on Linux. really strange. I'll get back to you when I figure it out.

**Comment by Alexey-Yakovenko** [comment]
Yeah, one of my guesses was correct. It's the shift-jis misfire. I'll disable it, and make another flag.

**Comment by cipricus** [comment]
They were Japanese characters then? Enabling/disabling that does not keep the setting?

**Comment by Alexey-Yakovenko** [comment]
Unfortunately this one can't be disabled.

**Comment by cipricus** [comment]
But even if they were all enabled (e.g. for someone having French, Chinese and Russian files), the French data should not be displayed as Chinese or Japanese.

**Comment by Alexey-Yakovenko** [comment]
In these files, it's impossible to find out which encoding it's using - that's why there's the detection.
French, Chinese, Japanese and Russian characters are the same bytes.

Here, I made the fix, should be working now. Please use [this build](http://sourceforge.net/projects/deadbeef/files/travis/linux/0.7/deadbeef-static_0.7.1-beta1-1_x86_64.tar.bz2/download).

**Comment by cipricus** [comment]
Thank you !  -- It works.
