### ISSUE TITLE
Add audio CD prompts to select a drive when there is only one drive

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1472]
In the 0.7.0 static build, adding an audio CD may show a dialog to select from several drive devices which are actually the same underlying device.  For example, /dev/cdrom and /dev/sr0 may both be names for the same drive.

This doesn't happen in my local build, but so far as I can tell nothing has changed in the Deadbeef code since 0.7.0.  I believe that it is due to the underlying library built in to the static build.  Very old libcdio_cdda versions used to do this, but not for at least 4 years.  I believe that v 0.81 was the first version of libcdio to correctly de-dupe the device list.  I am building and running with Debian v 0.83-4.

**Comment by Alexey-Yakovenko** [comment]
yes, libcdio is pretty old in static builds. I already added a task to update it, after you mentioned it doesn't have libcdparanoia.

**Comment by Alexey-Yakovenko** [comment]
@Lithopsian it's done, 0.7.1-rc3 is now using the latest stuff. Please let me know if the issue is still there.
