### ISSUE TITLE
Incorrect mp3 bitrate in track properties

### ISSUE THREAD

**Issue by spvkgn** [Alexey-Yakovenko/deadbeef#1474]
In 0.7 release I have noticed DeaDBeeF shows incorrect bitrate in many mp3 tracks - in track properties and with %bitrate%. With 0.6.2 this issue not occurs.

Here are screenshots 0.6.2 and 0.7 from the same mp3 track:

![screenshot - 02042016 - 06_11_25 pm](https://cloud.githubusercontent.com/assets/4147135/12816532/cd8f2f70-cb6e-11e5-9b25-4d8638587fb9.png)
![2](https://cloud.githubusercontent.com/assets/4147135/12816534/d2cdde8c-cb6e-11e5-87ff-da4a5ea76699.png)

**Comment by Alexey-Yakovenko** [comment]
how many is many? I sometimes get bug reports like this, and try to add more heuristics, then other files start showing incorrectly. usually when this happens it means the files have garbage in the beginning, and guessing the right bitrate from the header is not possible. or e.g. the Xing header contains wrong info. I know it works for most if not all of my mp3 files, and without having access to your specific file(s) I couldn't do anything. If you want me to try to fix this specific file -- please send it to my email, it should be on my github profile.

**Comment by spvkgn** [comment]
Thanks, I will try to find a way to fix it myself if it possible. How many - all tracks in many albums from rutracker encoded with LAME 3.98-3.99, not some separate files. I did not see this with 0.6 and thought it's like a bug.

**Comment by Alexey-Yakovenko** [comment]
It may as well be a bug. I don't have any way to know :)

**Comment by spvkgn** [comment]
@Alexey-Yakovenko I tried to encode with DB built-in LAME preset CBR 320 [the first available lossless flac file](http://www.eclassical.com/custom/eclassical/files/BIS1536-001-flac_16.flac) and resulting mp3 file DB shows as with inaccurate bitrate as well (186 kbps). Could you please download and encode this lossless file in the same way?

**Comment by Alexey-Yakovenko** [comment]
ok, will try.

**Comment by Alexey-Yakovenko** [comment]
Thanks, bitrate is obviously wrong. Thanks for the repro. Will look into fixing it.

**Comment by Alexey-Yakovenko** [comment]
was indeed a really stupid bug, pretty much a typo.
