### ISSUE TITLE
%tracknumber% and tracks with "Track/Total tracks"

### ISSUE THREAD

**Issue by spvkgn** [Alexey-Yakovenko/deadbeef#1475]
`%track number%` shows track number in tracks with 'Track/Total tracks' format.
`%tracknumber%` (two-digit index) does not show any index in these tracks.
Is it by design or can you please add this feature in `%tracknumber%` ?

**Comment by Alexey-Yakovenko** [comment]
Please provide a screenshot of the Metadata window for the file where you have the problem.

**Comment by spvkgn** [comment]
Would be useful if these tracks would display with two-digit index.

![1](https://cloud.githubusercontent.com/assets/4147135/12843891/ec0d34c4-cc1d-11e5-98ea-138acb195cc2.png)

**Comment by Alexey-Yakovenko** [comment]
looks like a bug

**Comment by Alexey-Yakovenko** [comment]
I fixed the title formatting bug, but I can see there's another bug that Track number and Total Tracks didn't get separated as intended. Which file format is this? FLAC?

**Comment by Alexey-Yakovenko** [comment]
could you also check if clicking "Reload metadata" fixed this?

**Comment by spvkgn** [comment]
Yes, this is FLAC. In 0.7.1-beta1 reloading metadata changes nothing. I tried latest devel build with your fix - it works as it should - these tracks now displays as two-digit index. Many thanks!
