### ISSUE TITLE
Paused tracks with 48kHz sample rate plays in lowered tone after DB restart

### ISSUE THREAD

**Issue by spvkgn** [Alexey-Yakovenko/deadbeef#1478]
Steps to reproduce:
1. Take a track with 48kHz, for instance [download](http://www.kozco.com/tech/piano2.wav)
2. Add it to DB, start playing and toggle pause.
3. Restart DB and unpause playback - the track will be playing in lowered tone.

**Comment by Alexey-Yakovenko** [comment]
can't reproduce it the way you described, but something is wrong with psshshhhsh-audio plugin (it literally makes pssshhshhs sounds after doing your steps).

ALSA works fine here.

**Comment by Alexey-Yakovenko** [comment]
coreaudio works fine too.

**Comment by spvkgn** [comment]
With ALSA output plugin the same issue occurs in my Ubuntu 12.04 (with PA 5.0).

**Comment by Alexey-Yakovenko** [comment]
I have been testing on 12.04 + pulseaudio + alsa output as well -- no issues.
Which build are you running? Any non-standard DSP settings?

**Comment by Alexey-Yakovenko** [comment]
Anyway, do not worry, I'll fix it either way when I get to it.

**Comment by spvkgn** [comment]
Tried with 0.7 release from ppa and beta static build - the same result. No DSP settings.

**Comment by Alexey-Yakovenko** [comment]
This is supposed to be fixed, closing therefore. Please let me know if still happening.
