### ISSUE TITLE
UI: text of selected track is not visible

### ISSUE THREAD

**Issue by dronord** [Alexey-Yakovenko/deadbeef#1480]
Fedora 23 x64 KDE
Dont use specific GTK2/3 settings
Player in GTK3 view not freandly %)
In GTK2 - nice! But text(Author/Album/Duration, ...)! Blue line only. See attacment.
In current and previous version is same.

![deadbeef-selected](https://cloud.githubusercontent.com/assets/259877/12882444/aee516ec-ce62-11e5-92fa-0e1e34e81015.png)

П.С. Не видно названия выбранного трека.

**Comment by Alexey-Yakovenko** [comment]
Sorry, but we can't fix this bug. Please configure playlist colors manually in deadbeef settings, or fix your GTK theme, or use GTK2.

**Comment by dronord** [comment]
OK!
This is GTK2.
In GTK3 text vesible, but big buttons, tabs, another - not friendly =)
I like QT =)

**Comment by Alexey-Yakovenko** [comment]
I still can't help you. It's a bug in GTK theme.

**Comment by dronord** [comment]
Ok. Thank you for reply! понедельник, 08 февраля 2016г., 14:53 +03:00 от Alexey Yakovenko < notifications@github.com> :
