### ISSUE TITLE
Graphical issues with cinnamon

### ISSUE THREAD

**Issue by eol3000** [Alexey-Yakovenko/deadbeef#1486]
Здравствуйте.
Я плохо говорю на английском, поэтому мне проще будет описать проблему на русском, а потом попробую повторить на английском.
Система Linux Mint 17.3 Cinnamon. Настроил внешний вид, как на первом снимке. После перезапуска плеера всё слетает, как на втором снимке. Если надо, могу прислать файл конфига.
Спасибо большое.

Hello
I do not speak English, so I find it easier to describe the problem in Russian, and then try to repeat in English.
System Linux Mint 17.3 Cinnamon. Customize the appearance of, as in the first picture. After restarting the player it becomes, as in the second picture. If necessary, I can send a config file.
Thank you very much.

![01](https://cloud.githubusercontent.com/assets/17265939/13068671/dd15683c-d48e-11e5-8222-dc065b6ef76e.png)
![02](https://cloud.githubusercontent.com/assets/17265939/13068673/e220b444-d48e-11e5-8f4a-0e821a4a337a.png)

**Comment by Alexey-Yakovenko** [comment]
duplicate of #1465
