### ISSUE TITLE
GYM files + gme.so = segfault

### ISSUE THREAD

**Issue by JakeSFR** [Alexey-Yakovenko/deadbeef#1490]
The latest, static build for Linux: deadbeef-static_0.7.0-1_x86_64.tar.bz2.
An attempt to play *.gym files results in immediate segfault.
0.7.0 plays them fine with gme.so taken from previous build (0.6.2).

testuser$ ./deadbeef 
starting deadbeef 0.7.0 [static] [portable]
server_start
searching for GUI plugins in /home/testuser/.local/lib64/deadbeef
searching for GUI plugins in /home/testuser/.local/lib/deadbeef
searching for GUI plugins in /home/testuser/deadbeef-0.7.0/plugins
load_plugin_dir /home/testuser/deadbeef-0.7.0/plugins: scandir found 53 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
found selected GUI plugin: GTK2
loading plugin /home/testuser/deadbeef-0.7.0/plugins/ddb_gui_GTK2.so
loading plugins from /home/testuser/.local/lib64/deadbeef
loading plugins from /home/testuser/.local/lib/deadbeef
loading plugins from /home/testuser/deadbeef-0.7.0/plugins
load_plugin_dir /home/testuser/deadbeef-0.7.0/plugins: scandir found 53 files
loading plugin /home/testuser/deadbeef-0.7.0/plugins/aac.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/adplug.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/alac.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/alsa.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/artwork.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/cdda.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/converter.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/converter_gtk2.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/converter_gtk3.so
dlopen error: libgtk-3.so.0: cannot open shared object file: No such file or directory
trying /home/testuser/deadbeef-0.7.0/plugins/converter_gtk3.fallback.so...
plugin not found or failed to load
loading plugin /home/testuser/deadbeef-0.7.0/plugins/dca.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/ddb_ao.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/ddb_dumb.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/ddb_mono2stereo.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/ddb_shn.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/dsp_libsrc.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/ffap.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/ffmpeg.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/flac.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/gme.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/hotkeys.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/in_sc68.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/lastfm.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/m3u.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/mms.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/mp3.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/musepack.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/notify.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/nullout.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/oss.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/pltbrowser_gtk2.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/pltbrowser_gtk3.so
dlopen error: libgtk-3.so.0: cannot open shared object file: No such file or directory
trying /home/testuser/deadbeef-0.7.0/plugins/pltbrowser_gtk3.fallback.so...
plugin not found or failed to load
loading plugin /home/testuser/deadbeef-0.7.0/plugins/pulse.so
dlopen error: libpulse-simple.so.0: wrong ELF class: ELFCLASS32
trying /home/testuser/deadbeef-0.7.0/plugins/pulse.fallback.so...
plugin not found or failed to load
loading plugin /home/testuser/deadbeef-0.7.0/plugins/shellexec.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/shellexecui_gtk2.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/shellexecui_gtk3.so
dlopen error: libgtk-3.so.0: cannot open shared object file: No such file or directory
trying /home/testuser/deadbeef-0.7.0/plugins/shellexecui_gtk3.fallback.so...
plugin not found or failed to load
loading plugin /home/testuser/deadbeef-0.7.0/plugins/sid.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/sndfile.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/supereq.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/tta.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/vfs_curl.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/vfs_zip.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/vorbis.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/vtx.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/wavpack.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/wildmidi.so
loading plugin /home/testuser/deadbeef-0.7.0/plugins/wma.so
selected output plugin: ALSA output plugin
INFO: loading playlist Default
INFO: from file /home/testuser/.config/deadbeef/playlists/0.dbpl
gtkui plugin compiled for gtk version: 2.16.0
connecting button tray signals
Segmentation Fault
backtrace() returned 18 addresses
./deadbeef() [0x403ab3]
/lib64/libc.so.6(+0x32440) [0x7f98a6d6a440]
/home/testuser/deadbeef-0.7.0/plugins/gme.so(ym2612_update_request+0) [0x7f989daf5420]
/home/testuser/deadbeef-0.7.0/plugins/gme.so(ym2612_write+0x36c) [0x7f989db321dc]
/home/testuser/deadbeef-0.7.0/plugins/gme.so(_ZN7Gym_Emu11parse_frameEv+0x117) [0x7f989dac1cb7]
/home/testuser/deadbeef-0.7.0/plugins/gme.so(_ZN7Gym_Emu11play_frame_EPviiPs+0x23) [0x7f989dac1dd3]
/home/testuser/deadbeef-0.7.0/plugins/gme.so(_ZN14Dual_Resampler11play_frame_ER13Stereo_BufferPsPPS0_i+0x74) [0x7f989daba304]
/home/testuser/deadbeef-0.7.0/plugins/gme.so(_ZN14Dual_Resampler9dual_playEiPsR13Stereo_BufferPPS1_i+0xb9) [0x7f989daba5c9]
/home/testuser/deadbeef-0.7.0/plugins/gme.so(_ZN7Gym_Emu5play_EiPs+0x1d) [0x7f989dac145d]
/home/testuser/deadbeef-0.7.0/plugins/gme.so(_ZN12Track_Filter8emu_playEPsi+0x34) [0x7f989dae6244]
/home/testuser/deadbeef-0.7.0/plugins/gme.so(_ZN12Track_Filter8fill_bufEv+0x2e) [0x7f989dae627e]
/home/testuser/deadbeef-0.7.0/plugins/gme.so(_ZN12Track_Filter11start_trackEv+0x38) [0x7f989dae6328]
/home/testuser/deadbeef-0.7.0/plugins/gme.so(_ZN5gme_t11start_trackEi+0x91) [0x7f989dacdfa1]
/home/testuser/deadbeef-0.7.0/plugins/gme.so(+0x3fb19) [0x7f989dab2b19]
./deadbeef() [0x4148b0]
./deadbeef() [0x41712a]
/lib64/libpthread.so.0(+0x7cc3) [0x7f98a70b5cc3]
/lib64/libc.so.6(clone+0x6d) [0x7f98a6dfb4ed]
testuser$

**Comment by Alexey-Yakovenko** [comment]
Seems to be caused by the new VGMPlay.. I applied a fix, and tested some random files. They play, but I'm not sure if they sound correctly. Could you verify? The fix is currently only on master branch.

**Comment by Alexey-Yakovenko** [comment]
The build https://sourceforge.net/projects/deadbeef/files/travis/linux/master/

**Comment by JakeSFR** [comment]
Well, I can't hear any noticeable differences, except the playback is a little louder than in 0.6.2, which I don't mind at all.
Thanks for fixing it.

Cheers!
