### ISSUE TITLE
cursor moves to previous track instead of next track, after "delete from disk"

### ISSUE THREAD

**Issue by vasyapupkin123456** [Alexey-Yakovenko/deadbeef#1492]
Допустим, я скачал дискографию какого-то исполнителя. В плеер закидываю песни. Потом делаю сортировку по названию песни и начинаю прослушивать и удалять. И тут появляется недоработка. Допустим, есть песни, я поставил на проигрывание "исполнитель - какая-то предыдущая песня" - она мне понравилась. Я ее оставляю. Я нажимаю хоткей B и перехожу на песню "исполнитель - новый год". Она мне не понравилась. Я выделяю все песни "исполнитель - новый год" включая новый год(live). И удаляю физически с накопителя. И далее у меня перекидывает не на "исполнитель - какая-то следующая песня",  а на "исполнитель - какая-то предыдущая песня". И приходится нажимать клавишу перемещения на песню "исполнитель - какая-то следующая песня"
исполнитель - какая-то предыдущая песня
исполнитель - новый год
исполнитель - новый год
исполнитель - новый год(live)
исполнитель - какая-то следующая песня

**Comment by Alexey-Yakovenko** [comment]
Either I misunderstood the bug report, or I can't reproduce. Everything works as it should (for me).

**Comment by Alexey-Yakovenko** [comment]
I understand that this is probably an issue for you, so if you still have this problem, and want to get it fixed, there are a few guidelines:
* make the description easy enough to understand and reproduce
* if you can't, try making a screen cast
* during screencast recording, it might be useful if you name the test tracks 1,2,3,4,5,6 for clarity

it could also work if you make 2-3 relevant screenshots.

**Comment by Alexey-Yakovenko** [comment]
oh, and a VERY important thing: always specify which version of the player you're using.
