### ISSUE TITLE
Since version 0.7.0 album cover is not showed

### ISSUE THREAD

**Issue by bmglad** [Alexey-Yakovenko/deadbeef#1496]
Since version 0.7.0 album cover does not appear in the "Album Cover" column. In version 0.6.2 it is displayed.

OS: Ubuntu 14.04.4

Installed from ppa:starws-box/deadbeef-player

**Comment by Alexey-Yakovenko** [comment]
Support for PPA cannot be provided here.
Either use the official build, or contact the PPA janitor.

**Comment by Alexey-Yakovenko** [comment]
There was a bug in the 0.6 -> 0.7 configuration importing code. Fixed now.
