### ISSUE TITLE
[Android] customizable keyboard shortcuts

### ISSUE THREAD

**Issue by eadmaster** [Alexey-Yakovenko/deadbeef#1501]
It is possible to use keyboard shortcuts to control the playback:
 - play/pause
 - next/prev track
 - seek forward
 - search in current playlist

My USB keyboard is lacking multimedia keys, so i cannot use them.

**Comment by Alexey-Yakovenko** [comment]
You should search on google play store for the apps that allow to remap multimedia keys to other keys.

Deadbeef itself doesn't (and is not supposed to) do this sort of thing.

**Comment by eadmaster** [comment]
Ok, but how can i quicksearch in the current playlist with the keyboard only?
(there is no shortcut currently for that)

**Comment by Alexey-Yakovenko** [comment]
You need to press the "search" button on your device or keyboard.
If this button is not available, it's present in the menu.
If the menu button is not available, there's the on-screen menu button.

**Comment by eadmaster** [comment]
Ok, thank you, i'll try with [this app](https://play.google.com/store/apps/details?id=innerlife.keyboard.multilanguagekeymapredefiner&hl=en).
