### ISSUE TITLE
About adding the untranslated strings on Transifex

### ISSUE THREAD

**Issue by TotalCaesar659** [Alexey-Yakovenko/deadbeef#1503]
There are many of untranslated strings in last version of DeadBeeF, could you add them on Transifex for translating? Screenshots are enclosed.
![1](https://cloud.githubusercontent.com/assets/14265316/13784213/6fbd547c-eadf-11e5-89b3-829589cd50ae.png)
![2](https://cloud.githubusercontent.com/assets/14265316/13784209/6fb92730-eadf-11e5-8948-5ab5d810c46c.png)
![3](https://cloud.githubusercontent.com/assets/14265316/13784212/6fbd8c08-eadf-11e5-878d-e8e569709ce6.png)
![4](https://cloud.githubusercontent.com/assets/14265316/13784211/6fb9c0dc-eadf-11e5-9aec-17efecb058b8.png)
![5](https://cloud.githubusercontent.com/assets/14265316/13784210/6fb9b75e-eadf-11e5-9c13-7282a8cd0914.png)

**Comment by Alexey-Yakovenko** [comment]
Thanks for reporting. Some of these are easy to localize, but localizing plugin actions will be tricky.

I think we'll need to make a custom po file generator from plugin action data.
