### ISSUE TITLE
Title formatting: incorrect behaviour of []

### ISSUE THREAD

**Issue by mallniya** [Alexey-Yakovenko/deadbeef#1513]
Hello,
[] yield non-variables in cases like this:
`[[%discnumber%]a]`
which displays "a" if discnumber tag is empty, and "1a" if discnumber tag is 1. This is not coherent with fb2k, where in the first case there will be nothing, because "a" in this case is not a variable.

**Comment by mallniya** [comment]
@Alexey-Yakovenko, I finally lay my hands on latest deadbeef 0.7.2 and that's what I saw:
- tf: %album artist% %origin% [[%album artist%][ (%origin%)] a]
- flac file: aritst present, origin tag absent
- result: only artist shown
- expected result: artist artist a
Construction like [[%discnumber%]a] works though.

**Comment by Alexey-Yakovenko** [comment]
Please file a separate bug report.
The original bug has been fixed, and your original example works as expected now, right?
The new stuff is a new bug report. Thanks.
