### ISSUE TITLE
Hotkeys plugin action "Skip to" is untranslatable

### ISSUE THREAD

**Issue by Pulfer** [Alexey-Yakovenko/deadbeef#1515]
Looks like "Skip to" string from plugins/hotkeys/hotkeys.c is untranslatable.

.title = "Playback/Skip to/Previous genre",
.title = "Playback/Skip to/Previous composer",
.title = "Playback/Skip to/Previous artist",
.title = "Playback/Skip to/Previous album",
.title = "Playback/Skip to/Next genre",
.title = "Playback/Skip to/Next composer",
.title = "Playback/Skip to/Next artist",
.title = "Playback/Skip to/Next album",

After ru.po update everything in Playback/ * / * is translated except for "Skip to" string.

-------------------------------------------
msgid "Skip to"
msgstr "Перейти к"

msgid "Previous genre"
msgstr "Предыдущему жанру"

msgid "Previous composer"
msgstr "Предыдущему композитору"

msgid "Previous artist"
msgstr "Предыдущему исполнителю"

msgid "Previous album"
msgstr "Предыдущему альбому"

msgid "Next genre"
msgstr "Следующему жанру"

msgid "Next composer"
msgstr "Следующему композитору"

msgid "Next artist"
msgstr "Следующему исполнителю"

msgid "Next album"
msgstr "Следующему альбому"

-------------------------------------------

**Comment by Alexey-Yakovenko** [comment]
duplicate of #1503
