### ISSUE TITLE
Custom sort does not work in 0.7.0

### ISSUE THREAD

**Issue by rohit-n** [Alexey-Yakovenko/deadbeef#1517]
Custom sorting a playlist does nothing in version 0.7.0 and 0.7.1. It still works in 0.6.0.

**Comment by Alexey-Yakovenko** [comment]
Are you using the new title formatting syntax, or the old one?
The old one is not supposed to work.

**Comment by rohit-n** [comment]
Yeah, looks like I didn't notice the syntax change. Closing this issue.
