### ISSUE TITLE
The options in Ubuntu Unity Quicklist is still in English.

### ISSUE THREAD

**Issue by laichiaheng** [Alexey-Yakovenko/deadbeef#1518]
![unity quicklist](https://cloud.githubusercontent.com/assets/9532105/13987336/0c179b44-f142-11e5-97fd-2a9b0582e1e5.png)

I have added the "Name[zh_TW]" to "deadbeef.desktop.in" in "https://github.com/Alexey-Yakovenko/deadbeef" 3 months ago, but it is still in English in 0.7.1, so I have to edit "/usr/share/applications/deadbeef.desktop" on my PC again.
Did I add the translation to wrong file?

**Comment by Alexey-Yakovenko** [comment]
Your pull request landed on master, but didn't get onto 0.7 branch.
I just fixed it, and it will for sure get included in 0.7.2

Sorry for the inconvenience.
