### ISSUE TITLE
add hotkey for opening track properties

### ISSUE THREAD

**Issue by shaforostoff** [Alexey-Yakovenko/deadbeef#1520]
pressing ctrl+c, ctrl+x and ctrl+v does nothing. in foobar2000 it copies/cuts selected track(s), ctrl+v pastes them above the current one. this works across playlists and foobar2000 instances

also alt+enter should open tag editing window.

**Comment by Alexey-Yakovenko** [comment]
deadbeef doesn't support copy&paste (yet), and this is a duplicate of #606

**Comment by shaforostoff** [comment]
at least deadbeef supports track info, and there is no shortcut for it

**Comment by Alexey-Yakovenko** [comment]
now it's also a duplicate of #1522
