### ISSUE TITLE
key/tuning and bpm metadata for columns

### ISSUE THREAD

**Issue by shaforostoff** [Alexey-Yakovenko/deadbeef#1521]
in foobar2000 i can add a column to display [%initial key%] [%tuning%] fields from mp3 files
actually i have: [%initial key%][%initialkey%][%key%] [%tuning%] 
this works with flac, m4a and mp3. these fields are filled with beatunes app.

i tried %@:INITIAL_KEY@ in deadbeef but it didn't work

the same goes for %bpm% field

**Comment by Alexey-Yakovenko** [comment]
have you tried the same syntax as in fb2k?

**Comment by shaforostoff** [comment]
yes. i tried. here is a sample file with metainfo filled:
https://yadi.sk/d/Izu6wyZDqWbSX

**Comment by Alexey-Yakovenko** [comment]
alright, have you tried this with anything else than mp4 file? I think it should work with flac & mp3.

**Comment by Alexey-Yakovenko** [comment]
Just tried your mp4 file, and it has all the fields, and they work fine in title formatting, with the syntax you wrote above.

![image](https://cloud.githubusercontent.com/assets/1895698/14067964/ca2edd74-f474-11e5-9df4-19154d0161c4.png)

Therefore, closing as "works for me".
