### ISSUE TITLE
Replace forward slashes with dashes when converting

### ISSUE THREAD

**Issue by danpla** [Alexey-Yakovenko/deadbeef#1525]
It seems like the converter plugin has a regression bug that appeared after implementing the new title formatting: forward slashes are not replaced with dashes.

See #787.

**Comment by Alexey-Yakovenko** [comment]
Is this a bug report? How do I reproduce the bug?

**Comment by danpla** [comment]
For example, if an MP3 track has a title "On/Off", after converting using "%title%" pattern for an output file name, you will get file "Off.mp3" in "On" directory. The expected result is "On-Off.mp3".

**Comment by Alexey-Yakovenko** [comment]
Thanks
