### ISSUE TITLE
"Is playing" status

### ISSUE THREAD

**Issue by sprnza** [Alexey-Yakovenko/deadbeef#1528]
Hi there!
What do you think about adding feature to get a status if Deadbeef is playing music?
It would be great to have it something like this:
deadbeef --nowplaying "%p"
paused/playing/stopped

**Comment by Alexey-Yakovenko** [comment]
It's already possible using the new title formatting, via %isplaying%

`deadbeef --nowplaying-tf '%isplaying%`

http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference#.25isplaying.25

**Comment by sprnza** [comment]
Hi Alexey!
Thank you for the pointing out. I've got another little question regarding this. Is there a way to suppress
"starting deadbeef 0.7.0" line in the output? What output stream is it?

**Comment by Alexey-Yakovenko** [comment]
I don't remember. It's either stderr or stdout, should be simple to figure this out by yourself :)

**Comment by sprnza** [comment]
Haha! It's stderr, I used wrong syntax to suppress it. Sorry! Thank you for support!
