### ISSUE TITLE
tf: legacy importer doesn't handle [] and \n correctly, needs to replace with [[, ]] and $crlf()

### ISSUE THREAD

**Issue by Amet13** [Alexey-Yakovenko/deadbeef#1531]
Обновил плеер с 0.6.2 до 0.7.1
После этого уведомление стало отображаться не так, как было:
```
from %album% 
by %artist%
```
а стало album и artist в одной строке, раньше там стоял `\n`, теперь это не помогает.
![screenshot at 2016-04-03 16 24 30](https://cloud.githubusercontent.com/assets/5184847/14232635/ffdd40d4-f9b8-11e5-91b2-fef571e59964.png)

Есть какой-нибудь метасимвол для переноса строки?

Второй вопрос о том, можно ли вернуть отображение года альбома в квадратных скобках, раньше это выглядело аккуратно, а сейчас сливается с названием альбома:
![screenshot at 2016-04-03 16 31 31](https://cloud.githubusercontent.com/assets/5184847/14232654/cdf5c860-f9b9-11e5-942d-9524fcafce14.png)

**Comment by Alexey-Yakovenko** [comment]
`$crlf()`

http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference#.24crlf.28.29

по поводу второго вопроса -- это баг, я исправлю.

**Comment by Alexey-Yakovenko** [comment]
собственно, первый вопрос -- это скорее всего тоже баг в импорте старых конфигов, который тоже надо исправлять, поэтому оставляю открытым.

к сожалению, в вашем случае, даже если я сделаю багфикс -- он не сработает, потому что импорт уже произошел.

вам необходимо вручную заменить title formatting на правильный.

**Comment by Amet13** [comment]
Спасибо.
Первый вопрос решил. По второму жду фикса.

**Comment by Alexey-Yakovenko** [comment]
его тоже можно решить аналогичным образом, нужно просто взять [ и ] в одиночные кавычки, вот так: `'['%date%']'`

**Comment by Amet13** [comment]
>его тоже можно решить аналогичным образом, нужно просто взять [ и ] в одиночные кавычки, вот так: '['%date%']'
Для колонки album art недоступно форматирование строки.
![screenshot at 2016-04-03 22 57 41](https://cloud.githubusercontent.com/assets/5184847/14234602/90b782aa-f9ef-11e5-9d0b-b93b339f9277.png)

**Comment by Alexey-Yakovenko** [comment]
вам не нужна колонка album art. вам нужно вызвать контекстное меню любой колонки, group by -> custom, и туда вписать `%album artist% - ['['%year%']' ]%album%`

**Comment by Amet13** [comment]
Спасибо, то что надо.

**Comment by Amet13** [comment]
Обновился с 0.7.1 до 0.7.2.
В OSD notify опять поломалось что-то?
![screenshot at 2016-07-30 14 29 19](https://cloud.githubusercontent.com/assets/5184847/17270069/2b64062e-5662-11e6-8384-3193b8d94952.png)

Вот как теперь отображается с `$crlf()`, вместо перевода строки `;`:
![screenshot at 2016-07-30 14 29 30](https://cloud.githubusercontent.com/assets/5184847/17270071/3b4d1558-5662-11e6-9d6c-827a14a5ba85.png)

**Comment by Alexey-Yakovenko** [comment]
@Amet13 
если вас не затруднит, создайте новый баг про это.
