### ISSUE TITLE
Некорректно парзит cue файл

### ISSUE THREAD

**Issue by mea405** [Alexey-Yakovenko/deadbeef#1532]
В playlist  показывает в колонке Title только имя альбома, а название песни не выводит.

В любом случае Спасибо. Лучший плеер под Линукс. Вы бы его и в OS X портанули :)

[a.zip](https://github.com/Alexey-Yakovenko/deadbeef/files/201404/a.zip)

**Comment by Alexey-Yakovenko** [comment]
> Вы бы его и в OS X портанули :)

прочтите внимательно титульную страницу (README.md), там есть ссылка на скачивание версии под OS X.

**Comment by Alexey-Yakovenko** [comment]
по поводу предмета бага: не могу у себя воспроизвести, все отображается корректно, как на скриншоте:

![image](https://cloud.githubusercontent.com/assets/1895698/14234037/e36db95e-f9d8-11e5-9618-52308857666c.png)

**Comment by mea405** [comment]
On 03.04.2016 21:16, Alexey Yakovenko wrote:
> по поводу предмета бага: не могу у себя воспроизвести, все отображается
> корректно, как на скриншоте:
>
> image
> <https://cloud.githubusercontent.com/assets/1895698/14234037/e36db95e-f9d8-11e5-9618-52308857666c.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Alexey-Yakovenko/deadbeef/issues/1532#issuecomment-205024193>
>

Спасибо за ссылку на версию для OSX. Как-то не заметил.

У меня версия deadbeef из ppa Ubuntu 15.10 - 0.7.1 - устарела?
Новую из сурсов собирать?

-- 
Maxim          mea405@gmail.com

**Comment by Alexey-Yakovenko** [comment]
более новых релизов, чем 0.7.1, пока не было.

**Comment by mea405** [comment]
On 03.04.2016 21:41, Alexey Yakovenko wrote:
> более новых релизов, чем 0.7.1, пока не было.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Alexey-Yakovenko/deadbeef/issues/1532#issuecomment-205027050>
>
Обменяемся скриншотами.
Странно что практически аналогичный (я не нашел существенных различий) 
cuesheet парзится правильно. И еще, парзится по разному, если идти через 
AddFolder или AddFile.

Если нужно, могу выложить всё с flac :)

-- 
Maxim          mea405@gmail.com

**Comment by Alexey-Yakovenko** [comment]
я не против, показывайте скриншот(ы), и присылайте все вместе. только лучше не на github, а прямо мне в email (есть в профиле), и лучше ссылкой на файлообменник
