### ISSUE TITLE
Change design of the seekbar

### ISSUE THREAD

**Issue by TotalCaesar659** [Alexey-Yakovenko/deadbeef#1533]
The playback scale looks really great in STOP state...
![7](https://cloud.githubusercontent.com/assets/14265316/14235891/9d93e436-fa13-11e5-9fbe-9f0c1e3405e8.png)
...but it does worse in PLAY state.
![8](https://cloud.githubusercontent.com/assets/14265316/14235941/d3b99032-fa14-11e5-95bf-37cfc6f53baf.png)
As you see, the black colour doesn't look so good, it's uncomfortable for seeking and unesthetic.
It would be better to correct PLAY state for the scale to something like this:
![9](https://cloud.githubusercontent.com/assets/14265316/14236021/b0be5c64-fa16-11e5-9f25-fa76c034b61e.png)

**Comment by Alexey-Yakovenko** [comment]
Changed the title to use preferred terminology
