### ISSUE TITLE
Last.fm: Can't scrobble

### ISSUE THREAD

**Issue by Xylemon** [Alexey-Yakovenko/deadbeef#1534]
I am no longer able to scrobble with DeaDBeeF since March 31st or April 1st. I can scrobble fine through my phone with Simple Scrobble Droid, so this isn't a problem with my account from what I can see. Starting DeaDBeeF from terminal seems to show no info related to the plugin, any way I can debug this?

If it matters, I compiled DeaDBeeF 0.7.1 from source and this issue started long after my last build.

**Comment by Alexey-Yakovenko** [comment]
Please search other similar (closed) issues for advice. If nothing helps, please contact last.fm technical support. I checked, scrobbling works fine for me, and didn't stop working.

**Comment by Xylemon** [comment]
Is there anyway I can get the last.fm plugin to spit out any info at all? At least it could give me some direction where to investigate.

**Comment by Alexey-Yakovenko** [comment]
yeah, this:

```
--- a/plugins/lastfm/lastfm.c
+++ b/plugins/lastfm/lastfm.c
@@ -24,8 +24,8 @@
 #include <math.h>
 #include "../../deadbeef.h"
 
-//#define trace(...) { fprintf(stderr, __VA_ARGS__); }
-#define trace(fmt,...)
+#define trace(...) { fprintf(stderr, __VA_ARGS__); }
+//#define trace(fmt,...)
 
 #define LFM_TESTMODE 0
 #define LFM_IGNORE_RULES 0
```

**Comment by Xylemon** [comment]
Alright thanks, I'll recompile the plugin later and hopefully I can see what's wrong.

**Comment by Alexey-Yakovenko** [comment]
good luck

**Comment by Xylemon** [comment]
So I've recompiled the plugin, and this is what it spits out in terminal:

```
lfm songstarted 0x1ba8000
cond signalled!
lfm sending nowplaying...
lfm_send_submissions
sending request: http://post.audioscrobbler.com/[censored]

scrobbler auth failed, response: BADTIME
auth failed! nowplaying cancelled.
lfm wating for cond...
```

The above is when it attempts to send a now playing status. Normal song submission (this time with disable now playing checked) receives the same "BADTIME" message from the post.audioscrobbler site as well:

```
lfm: song is now in queue for submission
cond signalled!
lfm sending nowplaying...
lfm_send_submissions
sending request: http://post.audioscrobbler.com/[censord]
lfm songstarted 0x2d45140
scrobbler auth failed, response: BADTIME
lfm wating for cond...
```
I could send you the full URL in an email or something, I've just censored into fear it contains sensitive information. Again all the login information is right and I've even re-entered just to make sure it's fine.

**Comment by Alexey-Yakovenko** [comment]
http://www.last.fm/api/submissions

BADTIME
The timestamp provided was not close enough to the current time. The system clock must be corrected before re-handshaking.

Check that your system time is correct.

**Comment by Xylemon** [comment]
Ah that was it, just three minutes off I guess. Thanks for the info, working perfect now. I'll have to keep a better eye on my system time.

**Comment by Alexey-Yakovenko** [comment]
np

**Comment by gogron** [comment]
sorry this isnt about deadbeef but im always getting BADTIME. on another player pragha it scrobbles fine even though last.fm shows them 1 hour before (website glitch or new api?). i cant fix by adjusting my time or location on last.fm. ever had a problem like this due to summer time or whatever?

**Comment by Alexey-Yakovenko** [comment]
@gogron I have never experienced this problem first-hand -- but it seems to be fairly common. 

Basically, that's the main reason why last.fm scrobbling doesn't work for many users in deadbeef, apart from when the server is down.

Indeed, it might be that the API v2 doesn't require the timestamp, and that's why the players using it don't suffer from the same problem.
