### ISSUE TITLE
Adding options for creating columns: "Date", "Codec" and "Bitrate"

### ISSUE THREAD

**Issue by TotalCaesar659** [Alexey-Yakovenko/deadbeef#1537]
Could you add new options for creating columns: "Date", "Codec" and "Bitrate"? They're existing in foobar2000 and would be grateful here for audiophiles with their discographies.
Yes, I know they can be created manually, but after changing syntaxis of the columns from 0.6.2 to 0.7.0 (e.g., variable < FILETYPE > to %codec% for "Codec" column), it would be better to simplify creating these new columns.
![2](https://cloud.githubusercontent.com/assets/14265316/14302884/3cf6d3bc-fbae-11e5-80dc-4c7c664c0124.png)
![screenshot from 2016-04-06 03-37-52](https://cloud.githubusercontent.com/assets/14265316/14302887/4740e1be-fbae-11e5-9e8e-2d9dc7956310.png)

**Comment by aphirst** [comment]
Was this actually added?

**Comment by aphirst** [comment]
Mm. Though I did struggle for a while to realise that `%year%` is the required format specifier. In [the Help page linked by the application](http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference), that string isn't present.

**Comment by Alexey-Yakovenko** [comment]
might be a bug. %date% is supposed to work.

**Comment by aphirst** [comment]
It does work! It's just not obvious that that's what you need to put.
