### ISSUE TITLE
Session restore issue

### ISSUE THREAD

**Issue by py-tosha** [Alexey-Yakovenko/deadbeef#1539]
Ububntu MATE 15.10, DeaDBeeF 0.71
In settings restore session option is checked, and if I quit from DB, and start it again — it's ok. But if I shut down Ubuntu until DB is running, player does not remember actual playlist position on next start.

PS: большое спасибо за отличный плеер!=)

**Comment by Alexey-Yakovenko** [comment]
duplicate of #1014

**Comment by py-tosha** [comment]
Прошу прощения. Я искал подобный тикет, но по-английски=)

**Comment by Alexey-Yakovenko** [comment]
по слову session элементарно ищется.
