### ISSUE TITLE
`--nowplaying-tf` should set different status code when nothing is playing.

### ISSUE THREAD

**Issue by andlrc** [Alexey-Yakovenko/deadbeef#1542]
Hey, I think it makse sense if `--nowplaying-tf` would give proper exit code when nothing is playing.

I took a glance at the source and afai can see `server_exec_command_line` should return a new integer and then `main` should response accordintly.

I would like to make a pull request, but I'm not to sure what integer should be returned from `server_exec_command_line`. I mean maybe some are "reserved" for future use?

It called from two different places in `main.c`: `main` and `server_update` the later don't listen to the response.
/ andlrc

**Comment by Alexey-Yakovenko** [comment]
What use case are you trying to solve? You can use `%isplaying%` and `%ispaused%` to get more detailed information about the player state.

**Comment by andlrc** [comment]
Thanks for your reply, I like `%isplaying%` and is `%paused` but I still think it's a shame that I either need to call deadbeef twice or check a sub string on the output, it would be nice if something like this was possible:

    title=$(deadbeef --nowplaying-tf '%title%');
    if [ $? -eq 0 ]; then
        printf "Listening to %s" "$title"
    fi

My current code is something like this:

    title=$(deadbeef --nowplaying-tf '%title%');
    if [ "$title" != "nothing" ]; then
        printf "Listening to %s" "$title"
    fi

which will fall short when I'm listening to a number which is called `nothing`, I could then add the following:

    title=$(deadbeef --nowplaying-tf '%isplaying% %title%');
    # Cannot use `-ne` here since `%isplaying%` prints nothing when deadbeef is not playing
    if [ "${title:0:1}" != "1" ]; then
        printf "Listening to %s" "${title#1 }"
    fi

**Comment by Alexey-Yakovenko** [comment]
Does it still return "nothing" even with the new title formatting? That actually sounds like a bug, I'll have a look.

**Comment by Alexey-Yakovenko** [comment]
--nowplaying-tf will no longer return "nothing", and I fixed the behavior of both %isplaying% and %ispaused%, so your script could now simply look like this:

```
title=$(deadbeef --nowplaying-tf '%title%');
```

This would return empty string if stopped.

And you can use %isplaying% and %ispaused% to get more fine grained control.

**Comment by andlrc** [comment]
You are the man! Thanks a bunch :-)
