### ISSUE TITLE
Regression: gtk2 themes no longer display properly. 

### ISSUE THREAD

**Issue by orbea** [Alexey-Yakovenko/deadbeef#1549]
OS: `Slackware64-current`
`deadbeef-f6830d1_2016.04.18_master-x86_64-1_git`

I compiled the master to test the fix for https://github.com/Alexey-Yakovenko/deadbeef/issues/1432.

Now I found that the gtk2 theme no longer displays correctly which worked with `deadbeef-0.7.1`.

Here is an old scrot from the previous issue with the correct appearance.
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/deadbeef/2015-12-31-233111_748x1040_scrot.png)

And now the current appearance.
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/deadbeef/2016-04-20-092136_748x1040_scrot_2.png)

**Comment by cboxdoerfer** [comment]
In Edit -> Preferences -> Appearance -> Playlist you need to uncheck the override checkbox

**Comment by orbea** [comment]
Thanks, but that's not the problem.

It was already unchecked and toggling it does not make a difference.

**Comment by orbea** [comment]
I played with this more and I realized it seems you were right as well as this being a regression.

I can confirm that override in the the following locations are unchecked.
`Edit -> Preferences -> Appearance -> Seekbar/Volumebar`
`Edit -> Preferences -> Appearance -> Tab strip`
`Edit -> Preferences -> Appearance -> Playlist`
However only the one in Playlist seems to make a difference.

Here is a new scrot to shot the issue, compare with the first one to see.
![3](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/deadbeef/2016-04-20-095328_748x1040_scrot.png)

**Comment by Alexey-Yakovenko** [comment]
This should be fixed now

**Comment by orbea** [comment]
Awesome! Thanks for still supporting gtk2! It looks a lot nicer here than gtk3. :)

**Comment by Alexey-Yakovenko** [comment]
It's not just "supporting" - GTK2 is still the main platform for deadbeef. Certain features don't work on GTK3 at all.
