### ISSUE TITLE
Title formatting: incorrect behaviour of nested square brackets

### ISSUE THREAD

**Issue by mallniya** [Alexey-Yakovenko/deadbeef#1559]
Condition to reproduce:
- tf field: %album artist% %origin% [[%album artist%][ (%origin%)] a]
- flac file: aritst present, origin tag absent
- result: only artist shown

Expected result: artist artist a
deadbeef version is 0.7.2.

**Comment by Alexey-Yakovenko** [comment]
btw, as far as I can see, FB2k's title formatting outputs something even when it's undef...

e.g. completely blank mp3 gives `? ?` for this script...

**Comment by Alexey-Yakovenko** [comment]
Apparently, my tf implementation fails on this example because the outer expression result is false if either of 2 subexpressions are false.

In FB2k, I guess, it's only false if ALL of the subexpressions yield false.

**Comment by mallniya** [comment]
> e.g. completely blank mp3 gives ? ? for this script...

That's... different of what I remember fb2k should do. Maybe in this case $meta() come in handy. But still -- even if fb2k give different result -- deadbeef can transcend it.
