### ISSUE TITLE
Add possibility to change tracks by scrolling over tray icon

### ISSUE THREAD

**Issue by Yanpas** [Alexey-Yakovenko/deadbeef#1562]
Currently tray icon only changes volume. The same does volume indicator. It would be handy to play next/prev track by scrolling over tray icon

**Comment by mitchnull** [comment]
I would love to see this, too.  the volume is better handled by the volume widget anyway imo.
Would you consider a patch that simply replaced the current functionality with next/prev track for mouse-wheel action on the tray icon, or a configuration setting is necessary?

**Comment by Alexey-Yakovenko** [comment]
Configuration setting would be necessary. Player volume control is an important feature, when using light weight WMs which don't have a volume control widget.

It's also a matter of personal taste. E.g. I prefer controlling the volume with mouse wheel over deadbeef tray icon, and switching tracks with global hotkeys.

**Comment by mitchnull** [comment]
I've just finished a patch that moves the volume control to ctrl-mousewheel while using the normal mousewheel event for next/prev track. I guess you'd still like a configuration option to select the "primary" function, right?  If so, is it acceptable to have it only a config-file option (not visible on the GUI)?

**Comment by Alexey-Yakovenko** [comment]
It's fine if it's config-file only option, but the default needs to stay the same it is now.

**Comment by mitchnull** [comment]
Pull request sent: #1640
