### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by TombusPL** [Alexey-Yakovenko/deadbeef#1565]
It is possible to create queue list? Example: playlist with selected queue songs with sorting. I cant create double playlist.
Add option double click to add song queue list.

Add option: In window (queue list) not removing names songs form queue list.
(sometime i like know what i played before ;) )

Free status bar! Moving and typing.
Like reaming time of song. I can add this only in playlist column.

Scrolling try icon - next/prev song. (actually asked ;) )

Thank for the fantastic music player :D

**Comment by Alexey-Yakovenko** [comment]
> It is possible to create queue list?

[No](https://github.com/Alexey-Yakovenko/deadbeef/issues/627)

>  sometime i like know what i played before

https://github.com/Alexey-Yakovenko/deadbeef/issues/1017

> Free status bar! Moving and typing.
> Like reaming time of song. I can add this only in playlist column.

I don't understand this. Please try to rephrase.

> Scrolling try icon - next/prev song. (actually asked ;) )

https://github.com/Alexey-Yakovenko/deadbeef/issues/1562
