### ISSUE TITLE
Possibility to drag&drop copy track

### ISSUE THREAD

**Issue by DigitalWarS** [Alexey-Yakovenko/deadbeef#1567]
Hi, 
many players have the possibility to copy a track to a location by simply draging it to that location directly from the plalist (ui). That way one doesn't have to open the folder where music is stored, minimize the player, search for the song ,open the destination folder and copy the track.
 Any chance you implement this?

Thank you!

**Comment by Alexey-Yakovenko** [comment]
I think that this is already implemented on master. Please try this version: https://sourceforge.net/projects/deadbeef/files/travis/linux/master/

**Comment by cboxdoerfer** [comment]
Confirmed. Drag and drop from DeaDBeeF to a file manager works, but not the other way around. I'll have a look at that.

**Comment by DigitalWarS** [comment]
Gr8, as soon as I get to my pc I'll check it out. Thank you
Il 09/mag/2016 10:45, "Christian Boxdörfer" <notifications@github.com> ha
scritto:

**Comment by cboxdoerfer** [comment]
Ok, so what should be the expected behavior when we drag a file from deadbeef to a file manager? 

1. the file is always copied to the destination
2. the file is copied or moved to the destination, based on the modifier key (ctrl)

If 2) and the file gets moved, what should happen with the playlist track in deadbeef?

1. nothing (so the track probably points to an invalid location) (that's what foobar2000 does)
2. the URL gets updated to the new location (not sure if we can get that information)
3. the track gets removed from the playlist

**Comment by Alexey-Yakovenko** [comment]
> Ok, so what should be the expected behavior when we drag a file from deadbeef to a file manager?

It should "feel" the same as when copying/moving files from one file manager to another. Isn't there a "standard" for it?

> If 2) and the file gets moved, what should happen with the playlist track in deadbeef?

I think we should keep the files in playlist, and add another action "Remove dead items" (or whatever it's called in FB2K), which would let user cleanup the playlist after he finished.

We should also make sure to test the case of multi-track files.. E.g. when you drag-n-drop multiple subtracks of the same file. The file should only be copied once. So before committing the file copy / drag-n-drop operation, the file list must be filtered, and duplicates removed.

**Comment by cboxdoerfer** [comment]
> It should "feel" the same as when copying/moving files from one file manager to another. Isn't there a "standard" for it?

Well, all audio players I tried handle it differently. E.g. Audacious only supports copying and Quod Libet works like most (all?) file managers, which I guess we could call "standard" behavior and that's what I prefer:
- source and destination are on the same disk: move by default and copy when modifier key is pressed
- source and destination are on different disks: copy by default and move when modifier key is pressed

> I think we should keep the files in playlist, and add another action "Remove dead items" (or whatever it's called in FB2K), which would let user cleanup the playlist after he finished.

Yes, that's a good idea.

> We should also make sure to test the case of multi-track files.. E.g. when you drag-n-drop multiple subtracks of the same file. The file should only be copied once. So before committing the file copy / drag-n-drop operation, the file list must be filtered, and duplicates removed.

Yes, and maybe url files need also special treatment. Need to try how other applications handle that.

**Comment by DigitalWarS** [comment]
Well, the idea is to copy (paste) the file by simply dragging it to the
desired location (and/or with the modifier key move it) . If the file gets
moved (and the behavior should be applied to only when moved, not copied),
best behavior would be that the player will point to an invalid location
(don't know if there can be a notif as "File moved" ).
Thank you, guys!
Ian.
Il 09/mag/2016 14:02, "Christian Boxdörfer" <notifications@github.com> ha
scritto:
