### ISSUE TITLE
artwork.h is broken in .deb package

### ISSUE THREAD

**Issue by hyperblast** [Alexey-Yakovenko/deadbeef#1568]
artwork.h seems to reference deadbeef.h at wrong location consequently failing to compile:

    $ gcc -I/opt/deadbeef/include/deadbeef -c test.c 
    In file included from test.c:1:0:
    /opt/deadbeef/include/deadbeef/artwork.h:27:28: fatal error: ../../deadbeef.h: No such file or directory
     #include "../../deadbeef.h"
                                ^
    compilation terminated.

**Comment by hyperblast** [comment]
Is it possible to backport this fix to 0.7 branch?
I'm currently developing a plugin that targets stable release of deadbeef and it's slightly inconvenient to use patched headers.

**Comment by Alexey-Yakovenko** [comment]
I can backport the patch to the branch, but I don't have any plans to make a new 0.7 release in the near future.

**Comment by hyperblast** [comment]
It's not critical issue at all, but IMO it would be useful if 0.7 release is ever going to happen.

**Comment by Alexey-Yakovenko** [comment]
@hyperblast done

**Comment by hyperblast** [comment]
@Alexey-Yakovenko thank you!
