### ISSUE TITLE
System directory for plugins

### ISSUE THREAD

**Issue by eblanca** [Alexey-Yakovenko/deadbeef#1572]
I upgraded my deadbeef 0.6.2 (shipped with lmde2-betsy-x86) with your new 0.7.2.
I chose to overwrite the default installation and I used './configure --prefix=/usr'
Now, just before issuing 'sudo make install' I searched for the plugins directory, it was into /usr/lib/i386-linux-gnu (because I have to remove the old plugins directory IIRC).
Renamed that old directory, then installed the new deadbeef.
Now, surprise, the Makefile installed the new plugins directory into /usr/lib, not into /usr/lib/i386-linux-gnu, and after that, everything worked flawlessly.
Is this an issue? will it work anyways? What is the difference in these two directory locations?

**Comment by Alexey-Yakovenko** [comment]
By default, autotools set the libdir to $PREFIX/lib.

It is possible to override the libdir using some configure option.

What you observed is that your previous build was using a custom libdir, set to /usr/lib/i386-linux-gnu, but when you made the new build, you used the default libdir. That's pretty much it.

The difference between these directories is that /usr/lib is for native libs, corresponding to the kernel's CPU architecture, while the /usr/lib/i386-linux-gnu has to contain the libs built for i386-linux-gnu.

But for deadbeef it doesn't matter -- it can install the libs anywhere you point the libdir to.
