### ISSUE TITLE
Does DEADBEEF support CLI?

### ISSUE THREAD

**Issue by 111116** [Alexey-Yakovenko/deadbeef#1574]
I tried running deadbeef in the terminal but failed. Can this program be opened in terminal?

**Comment by Alexey-Yakovenko** [comment]
Yes. I'm sorry that you failed, but deadbeef has CLI, and you can find out about the options by running `deadbeef --help`.

**Comment by 111116** [comment]
Sorry but I really have no idea.  
There are following words in '--help':
` options:  --gui PLUGIN       Tells which GUI plugin to use, default is "GTK2"  `
I tried and only found 2 valid arguments: `GTK2` and `GTK3`
I would appreciate if you could directly tell me the command!

**Comment by Alexey-Yakovenko** [comment]
@111116 tell me what you want to do, and I'll tell you the command.

I suppose that you might be asking about console UI, similar to moc etc - https://github.com/Alexey-Yakovenko/deadbeef/issues/572.

This one doesn't exist.

At the present time, only GTK2, GTK3 and Cocoa UI are officially supported.
