### ISSUE TITLE
Display total time of selected tracks in the statusbar

### ISSUE THREAD

**Issue by spvkgn** [Alexey-Yakovenko/deadbeef#1575]
It would be useful if Deadbeef could display selected tracks playtime in the statusbar like as displayed playlist total playtime. For instance foobar2k can demonstrate this feature ("show total time of selection" statusbar option).

**Comment by mallniya** [comment]
Maybe same thing should be displayed in "Duration" field, "Properties" tab of "Track properties" menu when more than 1 track is selected.
