### ISSUE TITLE
Signed-ness in threading code

### ISSUE THREAD

**Issue by eblanca** [Alexey-Yakovenko/deadbeef#1576]
I see you use a custom type (intptr_t, it is an alias for pthread_t) for threads.
Now, usage of this type is mixed with a similar one, uintptr_t (maybe the 'u' is from 'unsigned'?) and I can't see why.
You can see this in main.c, where server_tid and mainloop_tid are defined as uintptr_t but they receive return values from functions (thread_start and others) which are defined as intptr_t (without 'u') and are also used as parameters in thread_join (and others) which requires itself a intptr argument (again, without 'u').
This is not clear to me, is this done on purpose?

**Comment by Alexey-Yakovenko** [comment]
> I see you use a custom type (intptr_t, it is an alias for pthread_t) for threads.

yeah, because it's not necessarily pthread_t, it can be e.g. `HANDLE` on win32, or `SDL_Thread*` in SDL, etc (I use this code in more than 1 project :).

> Now, usage of this type is mixed with a similar one, uintptr_t (maybe the 'u' is from 'unsigned'?) and I can't see why.

They are typos.. It should always be `intptr_t`, as defined in `deadbeef.h`. but it doesn't really matter, as both should work the same way.

Is this causing any problems?

**Comment by eblanca** [comment]
No, I'm looking closer at the source code and applying little fixes in a (very early) attempt to build deadbeef with mingw32, then this issue came up to my attention.
Just wanted to know what I must take care of  ;-)

**Comment by Alexey-Yakovenko** [comment]
I see, then I'm closing this issue. Good luck :)

**Comment by eblanca** [comment]
Thank you for your support!

**Comment by Alexey-Yakovenko** [comment]
BTW, if you need the code for win32 implementation of the same module - posting it here.
[threading_win32.c.txt](https://github.com/Alexey-Yakovenko/deadbeef/files/272852/threading_win32.c.txt)

**Comment by Alexey-Yakovenko** [comment]
(it's slightly incomplete, so you might need to add the missing functions.. but better than writing it from scratch)

**Comment by eblanca** [comment]
Well, thank you again!
(BTW, is there a more proper place for asking questions which are not bug reports?)

**Comment by Alexey-Yakovenko** [comment]
there's IRC, mailing list, and the personal email. but use whatever you prefer more.
I personally like the mailing list option the best.

**Comment by eblanca** [comment]
> Is this causing any problems?

Well, the truth is, this scenario turned out to be hard indeed.
Sorry if I write into a closed thread but I think this topic is still not solved and I think I need your help.
The trouble into the code is, threads are mapped to intptr type and mutexes are mappend to uintptr, BUT those data types are NOT handled as abstract data types by the code, they're handled as integer types!
I mean, the code makes heavily usage of these types based on the assumption they are integer types (and this, on a posix system, is true) but when it comes to replace posix data types with some different ones (actually struct types) many statements such as:
tid = 0; /* tid is a thread id */
if (tid) /* check for thread validity */
void *data = (void *)(intptr_t)FOO; /* FOO is an enum item */
and many others, need a careful review.
I figure out this can be a long adventure, and the happy end would just be making the code build. Making it work... well, is another story.
Any suggestion is really welcome.

PS: I see the "tid=0;" statements may be easily skipped, the check for thread validity may be turned into a call to pthread_kill() and assignments can be converted, but they are so REALLY many...

**Comment by Alexey-Yakovenko** [comment]
@eblanca So what is the actual problem that you're having?

**Comment by eblanca** [comment]
Well, actually none, eh eh :-)
Didn't mean to be so verbose, but I just wanted to say:
it will be a challenging work to fix things without messing up the whole code.
