### ISSUE TITLE
Fails to edit tags in some ogg files 2

### ISSUE THREAD

**Issue by mallniya** [Alexey-Yakovenko/deadbeef#1580]
Find another ogg that stay untouched after modifying tags:
[example.ogg.zip](https://github.com/Alexey-Yakovenko/deadbeef/files/285301/Back.to.the.Future.NES.Music.-.Stage.Theme.ogg.zip)
Please check if there is a workaround as it was in #1332.

**Comment by kode54** [comment]
I just fixed this with a pull request.
