### ISSUE TITLE
copy current playing song to particular folder - custom shell command

### ISSUE THREAD

**Issue by rrevanth** [Alexey-Yakovenko/deadbeef#1581]
Hi,

I want to copy current playing song to a folder with global shortkey / delete the song from folder if exists .

I know it's simple but I have no knowledge of the variables of the file,directory that can be used in custom shell command.

Can you give me a direction to guide of this variables or explain the process.

Thank you!

**Comment by Alexey-Yakovenko** [comment]
Shellexec is still using the old title formatting. The syntax is on wiki: https://github.com/Alexey-Yakovenko/deadbeef/wiki/Title-formatting

looks like the ones that you need are %F and %D

**Comment by rrevanth** [comment]
@Alexey-Yakovenko 

I created a custom command like cp '%F' ~/Desktop/Favourites/

But it does not seem to be working.

Any pointers!

**Comment by Alexey-Yakovenko** [comment]
How do you know it's not working?

**Comment by rrevanth** [comment]
I tried running it from context menu on a selected file and it's not copying it to the destination folder.

**Comment by Alexey-Yakovenko** [comment]
I don't remember how it's supposed to be, but try without quotes.. I think it either adds quotes automatically, or escapes the spaces etc.

**Comment by rrevanth** [comment]
It's not working that way as well.afaik,shellexec will run any command we throw at it as long as it can be run by my machine.right?

I will try some alternatives and report working method!

**Comment by Alexey-Yakovenko** [comment]
try redirecting the output like this:

`cp '%F' ~/Desktop/Favourites/ 2>&1 >~/error.txt`

and see what cp prints.. there may be an error.

**Comment by rrevanth** [comment]
There is nothing in error.txt
I got to some stage.What I really want is a way to copy current playing song to a folder.

When I run this command in my shell.It's copying but I cannot make it happen with custom shell command in deadbeef

This is the command that's working 

`deadbeef --nowplaying '%F' | xargs -0 cp -t ~/Desktop/Favourites/`

**Comment by rrevanth** [comment]
@Alexey-Yakovenko I found another issue.The above command is working normally from a command line but when run through the menu of deadbeef.It's not working and also sometimes opens default playlist with nothing in it.The music also stops playing!

**Comment by rrevanth** [comment]
@Alexey-Yakovenko 

Can you please help me on this.I am so close.

`deadbeef --nowplaying '%F' | xargs -0 cp -t /home/raven/Desktop/Favourites/`

This command runs normally when run through terminal but opens up default playlist with nothing in and stops playing.

**Comment by cboxdoerfer** [comment]
@rrevanth, works for me. I'm using this custom shell command:
`cp %F ~/temp`

**Comment by Alexey-Yakovenko** [comment]
@rrevanth I think that you're over-complicating. it should work the way @cboxdoerfer said.

**Comment by rrevanth** [comment]
@cboxdoerfer @Alexey-Yakovenko the command you mentioned copies the highlighted file.But I want to copy current playing file to a folder with a global shortcut.

Is there any way to do that?

**Comment by cboxdoerfer** [comment]
@rrevanth there are multiple ways, you could add a button to the layout and assign that action to it (right click on it while in design mode and select `Configure Button,` or use a hotkey

Btw.: just found some bugs related to that. Going to fix those.

**Comment by cboxdoerfer** [comment]
@Alexey-Yakovenko, what do you think about adding a context menu to the statusbar that's populated like the context menu in the listview, with all the actions working on the now playing track. foobar2000 does that too.

**Comment by rrevanth** [comment]
@cboxdoerfer, but I am unable to create the action.The command is not working from application but is working when run in shell.

I debugged it to a level where the problem is that argument for cp is getting is up until the first space of filepath.

**Comment by cboxdoerfer** [comment]
@rrevanth, I can't follow you. Did adding the action in the Custom Shell Command settings work? But now the action doesn't show up in the Configure Button or Hotkeys dialog?

**Comment by cboxdoerfer** [comment]
Because it works perfectly fine for me and I can copy the currently playing track on button click.

**Comment by rrevanth** [comment]
@cboxdoerfer the custom shell command is not working.This is the process I followed

1.  for testing, I run the command from terminal.It's file copy works.

2. I added custom shell command setting in deadbeef with multicheck options singlefile & local checked.This gave me the command in file context menu

3. When I clicked the context menu.It opened default playlist empty and stopped the play.

e.g : Suppose this is the file that needs to be copied `/home/raven/Music/Shared/Best english songs/Enrique Iglesias - Live It Up Tonight.mp3`

and the command is `cp "$(deadbeef --nowplaying '%F')" /home/raven/Desktop/Favourites/ 2>&1 | tee ~/out.txt`

It works fine in terminal and when ran from custom shell context menu.This is the log

`cp: cannot stat ‘/home/raven/Music/Shared/Best’: No such file or directory`

As you can see,it stops at first space.Am I doing anything wrong here?

**Comment by rrevanth** [comment]
@cboxdoerfer sorry. I followed the steps as you mentioned and it works now.Thanks!

**Comment by cboxdoerfer** [comment]
@rrevanth, great :)

**Comment by rrevanth** [comment]
@cboxdoerfer Hi Chris,the commands are working fine from context menu but when I assign global keys on current playing file.It's not working.

Is there any problem with global hotkeys.If so,can I do anything? 

Thanks in Advance! :)

**Comment by Alexey-Yakovenko** [comment]
@rrevanth it works just fine. I repeated all steps just now. The shellexec command I used is this `cp %F ~/Desktop`, and I used global hotkey Ctrl+Alt+K for testing. Started a song, pressed the key combination, and the file appeared on desktop.

I can't say what is wrong on your computer, but it doesn't seem to be a bug. Closing.

**Comment by rrevanth** [comment]
@Alexey-Yakovenko Hi Alex,

It's working for the global hotkey once I apply settings in hotkey panel but not persisting.

**Comment by Alexey-Yakovenko** [comment]
which Desktop Environment are you using?

**Comment by rrevanth** [comment]
pantheon - elementary os

**Comment by Alexey-Yakovenko** [comment]
@rrevanth does the problem get fixed if you switch to any other DE, like KDE, or Unity, etc?

**Comment by rrevanth** [comment]
I haven't tried any other IDE.

Anyway,it's a minor issue for me.I just posted because if this might be issue for everyone.

If you want me to test it,I will test on other IDE's

**Comment by Alexey-Yakovenko** [comment]
@rrevanth I don't know if it's an issue for anyone else than you, but I suspect it's a problem for anyone who's using the same software as you.

**Comment by rrevanth** [comment]
I suppose too. I haven't tried in any other IDE.

Thanks for the help :)
