### ISSUE TITLE
Not changing/saving setting in Mac OS X

### ISSUE THREAD

**Issue by espete** [Alexey-Yakovenko/deadbeef#1588]
I wanted to change the color and other setting under Preference in deadbeef, but they do not take effect.
The program remembers my playlist, so something is being saved by it.

I tried both the travis build 0.7.2 from SF and to build it myself from github today (june 7th 2016) - both have this problem.
 
im on OS X 10.10.5

**Comment by Alexey-Yakovenko** [comment]
The settings window is not hooked-up yet, and most likely all the various color settings etc are not implemented either, so they're not even changeable from config.

**Comment by Alexey-Yakovenko** [comment]
just saying that this is not a bug -- the application is in development, and this part is not done yet.
