### ISSUE TITLE
Tiny fix for conf.c

### ISSUE THREAD

**Issue by eblanca** [Alexey-Yakovenko/deadbeef#1589]
In conf.c from master branch https://github.com/Alexey-Yakovenko/deadbeef/blob/master/conf.c#L108 it should be better to have a
`fclose (fp);`
since the flow will exit from 'conf_load' and a file handle will stay open, when it shouldn't.
This does not currently raise any issue but in some operating system may prevent any subsequent 'rename', since a file that we are going to overwrite remains opened.

**Comment by Alexey-Yakovenko** [comment]
Do you mean when the fread fails?

**Comment by eblanca** [comment]
yes, exactly
