### ISSUE TITLE
Can't open the GTK3 window in Ubuntu 16.04

### ISSUE THREAD

**Issue by laichiaheng** [Alexey-Yakovenko/deadbeef#1592]
![can t open](https://cloud.githubusercontent.com/assets/9532105/15985640/f7744fc4-3026-11e6-97f6-1b21928dbaed.png)

me@myPC:~$ /opt/deadbeef/bin/deadbeef 
starting deadbeef 0.7.2 [static]
server_start
searching for GUI plugins in /home/me/.local/lib64/deadbeef
searching for GUI plugins in /home/me/.local/lib/deadbeef
searching for GUI plugins in /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 63 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /opt/deadbeef/lib/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/me/.local/lib64/deadbeef
loading plugins from /home/me/.local/lib/deadbeef
loading plugins from /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 63 files
loading plugin /opt/deadbeef/lib/deadbeef/aac.so
loading plugin /opt/deadbeef/lib/deadbeef/adplug.so
loading plugin /opt/deadbeef/lib/deadbeef/alac.so
loading plugin /opt/deadbeef/lib/deadbeef/alsa.so
loading plugin /opt/deadbeef/lib/deadbeef/artwork.so
loading plugin /opt/deadbeef/lib/deadbeef/cdda.so
loading plugin /opt/deadbeef/lib/deadbeef/converter.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/dca.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_ao.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_dumb.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_misc_playback_status_GTK2.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_misc_playback_status_GTK3.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_misc_replaygain_scan.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_misc_replaygain_scan_GTK2.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_misc_replaygain_scan_GTK3.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_mono2stereo.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_shn.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_vis_musical_spectrum_GTK2.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_vis_musical_spectrum_GTK3.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_vis_vu_meter_GTK2.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_vis_vu_meter_GTK3.so
loading plugin /opt/deadbeef/lib/deadbeef/dsp_libsrc.so
loading plugin /opt/deadbeef/lib/deadbeef/ffap.so
loading plugin /opt/deadbeef/lib/deadbeef/ffmpeg.so
loading plugin /opt/deadbeef/lib/deadbeef/flac.so
loading plugin /opt/deadbeef/lib/deadbeef/gme.so
loading plugin /opt/deadbeef/lib/deadbeef/hotkeys.so
loading plugin /opt/deadbeef/lib/deadbeef/in_sc68.so
loading plugin /opt/deadbeef/lib/deadbeef/lastfm.so
loading plugin /opt/deadbeef/lib/deadbeef/m3u.so
loading plugin /opt/deadbeef/lib/deadbeef/mms.so
loading plugin /opt/deadbeef/lib/deadbeef/mp3.so
loading plugin /opt/deadbeef/lib/deadbeef/mpris.so
loading plugin /opt/deadbeef/lib/deadbeef/musepack.so
loading plugin /opt/deadbeef/lib/deadbeef/notify.so
loading plugin /opt/deadbeef/lib/deadbeef/nullout.so
loading plugin /opt/deadbeef/lib/deadbeef/oss.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/pulse.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexec.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/sid.so
loading plugin /opt/deadbeef/lib/deadbeef/sndfile.so
loading plugin /opt/deadbeef/lib/deadbeef/supereq.so
loading plugin /opt/deadbeef/lib/deadbeef/tta.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_curl.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_zip.so
loading plugin /opt/deadbeef/lib/deadbeef/vorbis.so
loading plugin /opt/deadbeef/lib/deadbeef/vtx.so
loading plugin /opt/deadbeef/lib/deadbeef/wavpack.so
loading plugin /opt/deadbeef/lib/deadbeef/wildmidi.so
loading plugin /opt/deadbeef/lib/deadbeef/wma.so
selected output plugin: ALSA output plugin
INFO: loading playlist 預設
INFO: from file /home/me/.config/deadbeef/playlists/0.dbpl
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
plugin Playback Status Widget failed to connect to dependencies, deactivated.
rgscangui: gtkui plugin not found
plugin Replay Gain Scanner GTK2 UI failed to connect to dependencies, deactivated.
plugin Musical Spectrum failed to connect to dependencies, deactivated.
plugin VU Meter failed to connect to dependencies, deactivated.
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 3.0.0
connecting button tray signals

(deadbeef:2538): GLib-GObject-WARNING **: cannot register existing type 'GtkIMContext'

(deadbeef:2538): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(deadbeef:2538): GLib-GObject-CRITICAL **: g_type_register_dynamic: assertion 'parent_type > 0' failed

(deadbeef:2538): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

**Comment by Alexey-Yakovenko** [comment]
Did you try rebooting your computer?

**Comment by Alexey-Yakovenko** [comment]
If this doesn't help, try reinstalling Ubuntu, because 16.04 works fine here.
