### ISSUE TITLE
About the Ubuntu snap package.

### ISSUE THREAD

**Issue by JulianLai** [Alexey-Yakovenko/deadbeef#1593]
I found you said that there were some problems when you built the snap package for DeaDBeeF player, would you tell us what the problem was? 
Maybe we should let the Ubuntu developers know it, so we can use the latest DeaDBeeF player all the time.

**Comment by Alexey-Yakovenko** [comment]
There was no problems with snap package.

The problem was that deadbeef crashes immediately at startup when running from a snap package.

I don't know what the problem was more specifically, because I couldn't figure out how to run an app off a snap package via GDB.

**Comment by mc4man** [comment]
There is this new? snap (deadbeef-vs), fails to start as supplied. At least here can be temp worked around by copying /snap/deadbeef-vs/1/usr/lib/deadbeef to $HOME/.local/lib 
obviously not a solution, maybe something in /snap/bin/deadbeef-vs needs editing/added?

**Comment by Alexey-Yakovenko** [comment]
I evaluated snap, and tried making snap package of deadbeef.

The conclusion is: Snap is not ready yet, and can't support the deadbeef's
needs as a package manager.
It's not possible to load external plugins, not possible to store
configuration, not even possible to load music from the hard drive, if
running from the isolated snap environment.
There are too many problems to list them all here.
But I'm fairly sure that the snap developers know about all of the problems.

I hope that eventually snap developers will solve all of that. I have a
snapcraft yml file ready, as soon as the underlying system is fixed.

But for now, just keep using the provided official builds -- they still
work just fine, and I hope they will keep working.

**Comment by mc4man** [comment]
Yeah, that's why I deleted after posting, sorry to have bothered you.
(forgot I was running deadbeef from the actual snap deadbeef binary to check with gdb, not the snap's shell script. Sorry about that...

**Comment by Alexey-Yakovenko** [comment]
sorry, I didn't realize you deleted, cause I replied to an email notification.

**Comment by Alexey-Yakovenko** [comment]
For the interested people..

I started a conversation with snap developers in their mailing list.

https://lists.ubuntu.com/archives/snapcraft/2016-August/000754.html

There was just a first round of Q&A at the time of writing this message, but I hope it continues, and we can get a good overview of what should we do about supporting snap, and whether it's feasible at all.

Leaving it here for tracking purpose, so that the users posting new snap-related issues can be redirected here.
