### ISSUE TITLE
Out of bound write in fmopl.c

### ISSUE THREAD

**Issue by eblanca** [Alexey-Yakovenko/deadbeef#1594]
In plugins/adplug/adplug/fmopl.c @ statement 599 the 'for' loop uses 'i' 16 times from value 60 to value 75.
Now, in plugins/adplug/adplug/fmopl.h @ statement 129 the array is 75 cells (o to 74), so the 'for' loop ends up writing 1 entry out of the array.
Maybe that '76' has to be a '75' ?

**Comment by eblanca** [comment]
Further, the previous 'for' loop in fmopl.c ends writing into entry 60, and the 'for' loop above begins writing into that same entry 60 again. Is it correct this way?

**Comment by Alexey-Yakovenko** [comment]
Yeah, it _looks_ like the intention was to have the first loop 4 to 60, and the next loop 61 to 74.

I will fix, thanks for spotting.
