### ISSUE TITLE
 Fails to edit tags in some ogg files

### ISSUE THREAD

**Issue by rekcuFniarB** [Alexey-Yakovenko/deadbeef#1596]
Continuation of  #1332 

Found [yet another ogg vorbis file](http://brainfucker.myihor.ru/share/tmp/audio/deadbeef_tag_edit_bug_example.ogg). Tested with static builds 0.7.2 and 0.7.3 alpha1.

**Comment by Alexey-Yakovenko** [comment]
@rekcuFniarB are you getting any warnings or errors? I just tested on master, and could tag the file without any problems.

**Comment by Alexey-Yakovenko** [comment]
Right. This is the same bug, it was not fixed in 0.7 -- only on master.
I should backport it..

**Comment by Alexey-Yakovenko** [comment]
I backported the fix, 0.7.3 will have it.
