### ISSUE TITLE
Random playback mode problem: system rand(3) API can produce repeatable patterns, which may lead to playing the same tracks in reverse order

### ISSUE THREAD

**Issue by tomatojam** [Alexey-Yakovenko/deadbeef#1597]
Может, это не баг, а фича, но при проигрывании любого плейлиста в случайном порядке в определенный момент плеер замирает (нет звука и реакции на кнопки управления) и после этого начинает включать все треки, проигранные до глюка, в обратном порядке. Малёхо надоело слушать одно и то же) Пожалуйста, ответте мне на эл почту. DeaDBeeF — лучший плеер, но эта мелочь не даёт им нормально пользоваться.

**Comment by Alexey-Yakovenko** [comment]
@tomatojam я не могу ответить вам на электронную почту, потому что я не знаю вашего адреса. это прекрасный баг, видимо у вас в системе какой-то совершенно дикая реализация rand в LIBC.. надо будет пораскинуть мозгами, как бы это исправить.. 

в любом случае, есть очень простой выход -- использовать Shuffle вместо Random.

**Comment by Alexey-Yakovenko** [comment]
Closing because the reporter can't be contacted, and the bug could not be reproduced.
