### ISSUE TITLE
Alternative to faad2.

### ISSUE THREAD

**Issue by hussamT** [Alexey-Yakovenko/deadbeef#1598]
Hello. Is it possible to use ffmpeg plugin as a fallback to playing AAC content if faad2 is not installed?
Thank you.

**Comment by Alexey-Yakovenko** [comment]
Yes. No problem.

**Comment by hussamT** [comment]
Thank you. One last question. Opening Help -> About or Help -> Changelog all say "Failed to load help file".
Am I missing some dependency or files?
Thank you.

**Comment by Alexey-Yakovenko** [comment]
yes, apparently you didn't install the software correctly.

**Comment by hussamT** [comment]
I accidentally removed the doc dir. I fixed that. thanks again.
