### ISSUE TITLE
Can't scrobble to last.fm

### ISSUE THREAD

**Issue by aldeano** [Alexey-Yakovenko/deadbeef#1599]
I'm using deadbeef 0.7.2 GTK3 with the last.fm scrobbler plugin and it doesn't send info.

Plugin is loaded:
`loading plugin /usr/lib/deadbeef/lastfm.so`

And the url is: http://post.audioscrobbler.com

**Comment by Alexey-Yakovenko** [comment]
@aldeano https://github.com/Alexey-Yakovenko/deadbeef/wiki/FAQ#lastfm-scrobbling-suddenly-stopped-working-my-username-and-password-are-correct

**Comment by aldeano** [comment]
I got my clock from the net, it's on time. I've tried changing the password and got no results. There's a way to get a log and paste it here?

**Comment by Alexey-Yakovenko** [comment]
There's no easy way, but if you compile from source -- you can uncomment the line plugins/lastfm/lastfm.c:27, and then comment out line 28.

That should give you more information

**Comment by aldeano** [comment]
I've recompiled the source and now i can see the log and figure out what was wrong, it was my fault, so nothing more to say. 

There's a possibility to show logs like this as an option in the preferences menu?

**Comment by Alexey-Yakovenko** [comment]
It's not possible right now, but I do have intention to make it possible.
