### ISSUE TITLE
DeaDBeeF plays dff files in slow motion.

### ISSUE THREAD

**Issue by JulianLai** [Alexey-Yakovenko/deadbeef#1600]
It only happens to DeaDBeeF, not ffplay.
https://youtu.be/VxdanJE5nWE

OS: Ubuntu 16.04
DeaDBeeF: 0.7.2-2

**Comment by Alexey-Yakovenko** [comment]
I answered to you about this in the previous thread about DFF.

Have you tried any of my suggestions? You didn't answer to any of them, so I'm assuming you didn't. 

Please try resetting deadbeef DSP configuration to default.

**Comment by JulianLai** [comment]
I have forgotten that I have asked this before...
What will the "Automatic Samplerate" of the Resampler do for a 96khz/24bit or 192khz/24bit audio?

**Comment by Alexey-Yakovenko** [comment]
Yes, resampling is only done when needed.

If your sound card supports the input samplerate, and your audio system (alsa/pulse) is configured in a way that permits setting this samplerate, if will be used, and no resampling will be done on the player's DSP chain.

**Comment by JulianLai** [comment]
It seems that the "Use Alsa resampling" of "Alsa output plugin" will be needless if there is a resampler.

**Comment by Alexey-Yakovenko** [comment]
Yes, it's preferable to switch it OFF if you're using the deadbeef's own resampler.
