### ISSUE TITLE
Open location from track context menu

### ISSUE THREAD

**Issue by anewuser** [Alexey-Yakovenko/deadbeef#1610]
Have you considered adding a context menu entry to open the directory of the selected track, like foobar2000? Currently, we need to see the track properties to copy the location manually from there.

**Comment by Alexey-Yakovenko** [comment]
Menu -> Edit -> Configure custom shell commands -> New -> name it -> xdg-open %D

you're welcome.

**Comment by anewuser** [comment]
Спасибо.
