### ISSUE TITLE
Outdated page: http://deadbeef.sourceforge.net/download-packages.html

### ISSUE THREAD

**Issue by anewuser** [Alexey-Yakovenko/deadbeef#1612]
Some people may find this old page accidently: http://deadbeef.sourceforge.net/download-packages.html

Suggestion: delete it or redirect it to http://deadbeef.sourceforge.net/download.html

**Comment by Alexey-Yakovenko** [comment]
Deleted.

**Comment by anewuser** [comment]
It'd also be nice to add a description to https://launchpad.net/~alexey-smirnov/+archive/ubuntu/deadbeef to warn people that the PPA is no longer maintained and that they should download it from http://deadbeef.sourceforge.net/download.html instead.

**Comment by Alexey-Yakovenko** [comment]
I can't add anything to this PPA page -- it's not mine.

**Comment by anewuser** [comment]
Oh, sorry. I just read his first name and assumed that account was yours.
