### ISSUE TITLE
GUI may hang after seeking during the final track of a CD (with libcdparanoia)

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1613]
libcdparanoia hangs (actually a CPU busy loop executing the callback forever) when attempting to read a sector beyond the end of a CD if the mode is PARANOIA_MODE_DISABLE.  Normally, reads stop at the last sector, but after seeking, the current sector number is not incremented and so one sector beyond the last one is read.  This is harmless with the cdio library (relatively harmless, the same sector is read twice at the seek), but hangs Deadbeef with libcdparanoia.

It would be good to get confirmation of this from someone else before making any changes, but I don't think the static build has libcdparanoia built in by default?

**Comment by Alexey-Yakovenko** [comment]
I'm not sure about static builds.. maybe now they have libcdparanoia included.
And I can't help testing this, cause none of my computers have CDROM anymore.

**Comment by Lithopsian** [comment]
I checked and recent static builds (0.7.2 and devel) do have libcdparanoia and do show the problem.
