### ISSUE TITLE
$crlf() incorrectly shows at OSD Notify

### ISSUE THREAD

**Issue by Amet13** [Alexey-Yakovenko/deadbeef#1616]
DeaDBeeF version 0.7.2

![image](https://cloud.githubusercontent.com/assets/5184847/17270431/fdd9ca32-566a-11e6-9594-666105b21d54.png)

It looks like
![image](https://cloud.githubusercontent.com/assets/5184847/17270435/12a514d0-566b-11e6-86db-862aa423748f.png)

```
from %album% $crlf()by %artist%
```

It was a workaround for 0.7.1 version in issue https://github.com/Alexey-Yakovenko/deadbeef/issues/1531 but doesn't work at 0.7.2

`\n` instead `$crlf()` does not work too.

**Comment by Alexey-Yakovenko** [comment]
please try this build: https://sourceforge.net/projects/deadbeef/files/travis/linux/0.7/deadbeef-static_0.7.3-alpha1-1_x86_64.tar.bz2/download

**Comment by Amet13** [comment]
I moved file `plugins/notify.so` from downloaded archive to `/opt/deadbeef/lib/deadbeef`.
After player restarting all ok.
![image](https://cloud.githubusercontent.com/assets/5184847/17272114/d05fd552-5696-11e6-883a-01edf893ff1f.png)
Thanks for hotfix.

**Comment by Alexey-Yakovenko** [comment]
ty
