### ISSUE TITLE
Deadbeef Not Respecting GTK3 settings.ini

### ISSUE THREAD

**Issue by Geyup** [Alexey-Yakovenko/deadbeef#1617]
My Specs;

Slacware 14.2 x86_64
Openbox 3.6.1
LXappearance 0.6.2
deadbeef 0.7.2
gtk3 -3.18.9

Most apps that I've seen will respect using LXAppearance for changing. I've personally only seen deadbeef not respect it for using GTK3.

With GTK2 I can get it to work using a .gtkrc-2.0.mine but for GTK3, with all the research I have been doing changing GTK3 themes happen under; /.config/gtk-3.0/settings.ini

deadbeef doesn't seem to work 100% with LXAppearance, only for changing the themes, but not the sizes.

This is my GTK3 settings.ini it's my understanding GTK3 apps are suppose to use the
```gtk-toolbar-icon-size=``` setting...

[Settings]
gtk-theme-name=Numix Flatstudio Dark
gtk-icon-theme-name=ACYL_0.9.4
gtk-font-name=Noto Sans 9
gtk-cursor-theme-name=Ecliz-cyan
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=0
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull
gtk-xft-rgba=rgb

**Comment by Alexey-Yakovenko** [comment]
hmmm... I'm not sure that deadbeef is actually using the GtkToolbar.. that's probably why it's not using the toolbar icon sizes.

if you look in the [https://github.com/Alexey-Yakovenko/deadbeef/blob/master/plugins/gtkui/widgets.c#L4078](plugins/gtkui/widgets.c), you'll see how it's created.

**Comment by Alexey-Yakovenko** [comment]
Closing as invalid, because only GtkToolbar icons should use the gtk-toolbar-icon-size.

**Comment by Geyup** [comment]
I'm sorry I'm lost here...

Can you please change deadbeef so it uses this?

Every app I've used in the past 10 years works, this is the only app I've used that doesn't. It's my understanding this is common and normal...

So I'm not sure what you mean that GtkToolbar icons should use the gtk-toolbar-icon-size, since deadbeef is a GTK app, so it should, yes, no?

What's the solution here, because I see nothing online to suggest otherwise?

thank you

**Comment by Alexey-Yakovenko** [comment]
I'm sorry, but I can't change it to use this.

**Comment by Alexey-Yakovenko** [comment]
> So I'm not sure what you mean that GtkToolbar icons should use the gtk-toolbar-icon-size, since deadbeef is a GTK app, so it should, yes, no?

The buttons in deadbeef's toolbar are not really a toolbar.

They are just buttons with icons. Therefore, they will respect button icon size, but not toolbar icon size.

**Comment by Geyup** [comment]
Ok please don't misunderstand me, I'm just trying to understand here is all and I'm confused, because I thought this is what a GTK app is suppose to use?

If deadbeef doesn't follow this way, how then do you change the icon sizes in deadbeef when using GTK3?

Thank you very much for you time Alexey, it's appreciated!

**Comment by oleksiy-unity3d** [comment]
> Ok please don't misunderstand me, I'm just trying to understand here is all and I'm confused, because I thought this is what a GTK app is suppose to use?

Deadbeef can't use GtkToolbar, because it would break the customizable layout support.

> how then do you change the icon sizes in deadbeef when using GTK3?

I suppose that icon size is set somewhere in the GTK3 theme, but I don't know the details.

**Comment by Geyup** [comment]
@oleksiy-unity3d how are you changing the icon sizes? When using GTK3 for me they are very small, they are all 16x16 in size.

This is the one reason I have stuck to using GTK2 with deadbeef I have never been able to figure out how to get them to appear bigger.

**Comment by Alexey-Yakovenko** [comment]
Just realised I was using the wrong account :)

> how are you changing the icon sizes?

I'm not changing them. I don't know what size they are, but they looked pretty normal. Exactly the same as in GTK2. I'm using default GTK setting in Ubuntu.

> Also as I mentioned, LXApperance has a setting for the GTK3 to change icon sizes in the settings.ini. gtk-toolbar-icon-size

That would only affect toolbars, but not icons used in normal non-toolbar buttons.

**Comment by Geyup** [comment]
Hmm they are very small for me when using GTk3 like 16x16 size.

Ok sorry I overlooked you saying Alexey about ```button icon size``` I'll have to play with this and see if this works....

As example ```gtk-button=16,16``` this is a GTK2 setting, putting ```gtk-button=16``` in the GTK3 settings.ini does nothing, I'm not sure GTK3 has a button option?

**Comment by Alexey-Yakovenko** [comment]
I never had any problems with GTK icons, they always "just worked" for me. I think your best bet is to ask on some GNOME or GTK support forum. I'm not a GTK theming expert, and prefer defaults these days.

**Comment by oleksiy-unity3d** [comment]
I think all of your problems come from this:

https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-icon-sizes

> GtkSettings:gtk-icon-sizes has been deprecated since version 3.10 and should not be used in newly-written code.
> This setting is ignored.

I suppose Ubuntu patched this.

**Comment by oleksiy-unity3d** [comment]
From what I can see, the icon size is now supposed to be defined by the Icon Theme, so try changing Icon Theme to another one, and see if it helps.

**Comment by Geyup** [comment]
@oleksiy-unity3d 

Please tell/show me what you are looking at?

The only file in an icon set is the index.theme that organizes the directory structure...

**Comment by Geyup** [comment]
I found in a gtk-widgets.css a button setting;

.button {
    -GtkWidget-focus-padding: 1;
    -GtkWidget-focus-line-width: 0;

    padding: 2px 6px;
    border-width: 0px;
    border-radius: 0px;
    border-style: solid;
    border-color: shade(@theme_bg_color, 0.9);
    background-color: shade(@theme_bg_color, 0.9);
    background-image: none;
    color: @theme_fg_color;
}

Can't seem to find anything in regards to sizes.

What a pain in the butt this is, just to change the sizes.

@Alexey-Yakovenko, if you ever have time, it would be nice to have a Preferences option for the GUI to be able to change the sizes, since this does not seem to be with GTK3 an easy solution...

**Comment by Alexey-Yakovenko** [comment]
I think you should be writing to GTK developers, instead of me.
However, I understand that they probably won't listen.
But on the other hand, I can't fix any of these problems.
It would be a huge waste of time to add this kind of GTK configuration to deadbeef.
Which distribution are you on? Have you considered switching to another one?
As I understand ubuntu solved this issue (for now).

**Comment by Geyup** [comment]
Well maybe in time it's just a simple change to make these recognized as icons not buttons in deadbeef, that way apps like LXAppearance will be able to change them. That way these options below work...

gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-toolbar-icon-size=GTK_ICON_SIZE_SMALL_TOOLBAR

In the meantime I'll keep looking around, I can't believe there is no button size option for GTK3

hmm

**Comment by Alexey-Yakovenko** [comment]
> Well maybe in time it's just a simple change to make these recognized as icons not buttons in deadbeef

I think that the way to do this is to actually use GtkToolbar, but I don't think this will work with deadbeef UI layout engine.

**Comment by Geyup** [comment]
I was told starting with 3.20x someone believed, that you can place in the /.config/gtk-3.0 a gtk.css and add lines like this I think is how it's suppose to look;

.button {
    min-height: 28
    min-width: 28
}

Or you swap .button for GtkButton

But since I'm using 3.18.9 I don't see any changes. It would be nice if someone using GTK3 3.20x could test this.
