### ISSUE TITLE
GitHub 302 issue

### ISSUE THREAD

**Issue by trueamensia** [Alexey-Yakovenko/deadbeef#1618]
``>>> Downloading 'http://sourceforge.net/projects/deadbeef/files/deadbeef-0.7.2.tar.bz2/download'
--2016-08-01 22:22:03--  http://sourceforge.net/projects/deadbeef/files/deadbeef-0.7.2.tar.bz2/download
Resolving sourceforge.net... 52.85.142.91, 52.85.142.31, 52.85.142.52, ...
Connecting to sourceforge.net|52.85.142.91|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://sourceforge.net/#!/projects/deadbeef/files/deadbeef-0.7.2.tar.bz2/download [following]
--2016-08-01 22:22:04--  http://sourceforge.net/
Reusing existing connection to sourceforge.net:80.
HTTP request sent, awaiting response... 200 OK
Length: 639 [text/html]
Saving to: ‘/usr/portage/distfiles/deadbeef-0.7.2.tar.bz2’

^M          /usr/port   0%[                    ]       0  --.-KB/s               ^M/usr/portage/distfi 100%[===========$

2016-08-01 22:22:04 (189 MB/s) - ‘/usr/portage/distfiles/deadbeef-0.7.2.tar.bz2’ saved [639/639]

!!! Fetched file: deadbeef-0.7.2.tar.bz2 VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      639
!!! Expected: 4736088
Refetching... File renamed to '/usr/portage/distfiles/deadbeef-0.7.2.tar.bz2._checksum_failure_._Zm4gV'

!!! Couldn't download 'deadbeef-0.7.2.tar.bz2'. Aborting.

So, it's downloading web page instead of .tar.bz2
Gentoo

**Comment by Alexey-Yakovenko** [comment]
Please open the web page that you're getting, and read its contents. I'm sure this will help you.
