### ISSUE TITLE
Some problems with the snap package version of DeaDBeeF

### ISSUE THREAD

**Issue by JulianLai** [Alexey-Yakovenko/deadbeef#1620]
I install the snap package version of DeaDBeef, there is no options in the output device menu, no sound if I choose ALSA Output plugin, no shortcut on the launcher or dash, can't input any language except English, and it has to be opened through the terminal, here are the error messages:

> ALSA lib conf.c:3750:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
could not open audio device (No such file or directory)
ALSA lib conf.c:3750:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
could not open audio device (No such file or directory)
streamer: failed to start playback (start track)

![screenshot from 2016-08-05 15-34-25](https://cloud.githubusercontent.com/assets/20014762/17429630/3a5880be-5b22-11e6-9974-4a0c947392f2.png)

**Comment by Alexey-Yakovenko** [comment]
Please don't post random unofficial package bugs here.
Thanks.
