### ISSUE TITLE
Cracks when starting playing 24/96 tracks through ALSA on NAD USB DAC 2

### ISSUE THREAD

**Issue by cdealti** [Alexey-Yakovenko/deadbeef#1621]
Playing 24/96 tracks with the below configuration works great except when you start playing the track after you stopped playback, you toggle the pause button, or you open deadbeef by double clicking the track.

In this situation the sound is noisy, like pink noise superposed to the track sound. To recover it's enough to click again the play button thus restarting playback. After this the audio is perfect, no pops, drops or cracks.

It only happens using the "NAD USB Audio, USB Audio / Direct hardware device without any conversions" device.

The configuration of the ALSA output plugin is irrelevant.

Info:

DeaDBeeF 0.72 on Linux Mint Nadia (I know, it's old).

Output Plugin: ALSA Audio Plugin
Output Device: NAD USB Audio, USB Audio
                         Direct hardware device without any conversions

ALSA Output Plugin Configuration:
Use ALSA resampling: unchecked
Preferred buffer size: 8192
Preferred period size: 1024

**Comment by Alexey-Yakovenko** [comment]
It's either a driver problem, or a player streaming bug.

If it's the latter, it should be possible to dump audio buffer to disk, and verify that it has the distortion, and maybe it will be possible to fix the problem.

If it's the former -- I can't fix this.

**Comment by cdealti** [comment]
Thanks Alexey. I've just tried to connect tje DAC to my only USB 3 port and the issue does not occur.
Time to upgrade Linux I guess.

Thanks for your work.
