### ISSUE TITLE
Provide OS X/macOS builds 

### ISSUE THREAD

**Issue by nvdv** [Alexey-Yakovenko/deadbeef#1623]
Since a lot of people don't have XCode installed, providing binaries for mac would be really nice (builds can be done using Travis CI).

**Comment by Alexey-Yakovenko** [comment]
wtf

**Comment by Alexey-Yakovenko** [comment]
I hate when people can't read, and usually refuse to help them, and if you couldn't see the link to the OSX build on the front page -- I can't really see how anyone could help you.
