### ISSUE TITLE
duplicate symbol error on macOS

### ISSUE THREAD

**Issue by yurikoles** [Alexey-Yakovenko/deadbeef#1624]
I'm trying to build current master at macOS. [Here](https://gist.github.com/baf4b4da0ca08b6a9673607df7b94553) is full log.
```
duplicate symbol __ZN7Nes_Apu11irq_changedEv in:
    .libs/Nes_Apu.o
duplicate symbol __ZN7Nes_ApuC2Ev in:
    .libs/Nes_Apu.o
[...]
ld: 25 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [gme.la] Error 1
make: *** [install-recursive] Error 1
```

**Comment by Alexey-Yakovenko** [comment]
You're building it in a wrong way. The correct way to build is written [here](https://github.com/Alexey-Yakovenko/deadbeef/blob/master/README.md), the section "OS X (COCOA version)"

Compiling and running GTK version using autotools is not supported on OSX, and is not supposed to work at all, even if you can somehow compile it.
