### ISSUE TITLE
Option to hide column headers

### ISSUE THREAD

**Issue by AcarBurak** [Alexey-Yakovenko/deadbeef#1657]
Option to hide column headers would be fine because:

1) This would lock the sorting customisation and so prevent an accidental messing up of the sorting. (I've experienced this and could come back thanks to my backup.)

2) Those headers (at least in some use cases) needlessly waste space and clutter the window. Once they're set the playlist window itself shows what's what.

**Comment by Alexey-Yakovenko** [comment]
The option itself is a bit hidden, but it exists - it's part of design mode (Edit -> Design Mode).

Enter the design mode, right click the playlist, then you should see the menu item to hide / show the column headers. Hope that helps.

**Comment by AcarBurak** [comment]
Oh! Sorry for the noise.
