### ISSUE TITLE
0.7.2 crash at startup

### ISSUE THREAD

**Issue by covex** [Alexey-Yakovenko/deadbeef#1658]
Ubuntu 14.04.5
1. not sure why some .pngs are unreadable
2. crashes on some weired memory allocation

starting deadbeef 0.7.2 [static]
server_start
searching for GUI plugins in /home/d/.local/lib64/deadbeef
searching for GUI plugins in /home/d/.local/lib/deadbeef
searching for GUI plugins in /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 53 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
found selected GUI plugin: GTK2
loading plugin /opt/deadbeef/lib/deadbeef/ddb_gui_GTK2.so
loading plugins from /home/d/.local/lib64/deadbeef
loading plugins from /home/d/.local/lib/deadbeef
loading plugins from /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 53 files
loading plugin /opt/deadbeef/lib/deadbeef/aac.so
loading plugin /opt/deadbeef/lib/deadbeef/adplug.so
loading plugin /opt/deadbeef/lib/deadbeef/alac.so
loading plugin /opt/deadbeef/lib/deadbeef/alsa.so
loading plugin /opt/deadbeef/lib/deadbeef/artwork.so
loading plugin /opt/deadbeef/lib/deadbeef/cdda.so
loading plugin /opt/deadbeef/lib/deadbeef/converter.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/dca.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_ao.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_dumb.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_mono2stereo.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_shn.so
loading plugin /opt/deadbeef/lib/deadbeef/dsp_libsrc.so
loading plugin /opt/deadbeef/lib/deadbeef/ffap.so
loading plugin /opt/deadbeef/lib/deadbeef/ffmpeg.so
loading plugin /opt/deadbeef/lib/deadbeef/flac.so
loading plugin /opt/deadbeef/lib/deadbeef/gme.so
loading plugin /opt/deadbeef/lib/deadbeef/hotkeys.so
loading plugin /opt/deadbeef/lib/deadbeef/in_sc68.so
loading plugin /opt/deadbeef/lib/deadbeef/lastfm.so
loading plugin /opt/deadbeef/lib/deadbeef/m3u.so
loading plugin /opt/deadbeef/lib/deadbeef/mms.so
loading plugin /opt/deadbeef/lib/deadbeef/mp3.so
loading plugin /opt/deadbeef/lib/deadbeef/musepack.so
loading plugin /opt/deadbeef/lib/deadbeef/notify.so
loading plugin /opt/deadbeef/lib/deadbeef/nullout.so
loading plugin /opt/deadbeef/lib/deadbeef/oss.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/pulse.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/pulse.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexec.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/sid.so
loading plugin /opt/deadbeef/lib/deadbeef/sndfile.so
loading plugin /opt/deadbeef/lib/deadbeef/supereq.so
loading plugin /opt/deadbeef/lib/deadbeef/tta.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_curl.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_zip.so
loading plugin /opt/deadbeef/lib/deadbeef/vorbis.so
loading plugin /opt/deadbeef/lib/deadbeef/vtx.so
loading plugin /opt/deadbeef/lib/deadbeef/wavpack.so
loading plugin /opt/deadbeef/lib/deadbeef/wildmidi.so
loading plugin /opt/deadbeef/lib/deadbeef/wma.so
selected output plugin: ALSA output plugin
INFO: loading playlist Default
INFO: from file /home/d/.config/deadbeef/playlists/0.dbpl
convgui: gtkui plugin not found
plugin Converter GTK3 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK3 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK3 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 2.16.0
Failed to load pixbuf file: /opt/deadbeef/share/deadbeef/pixmaps/play_16.png: Couldn't recognize the
image file format for file '/opt/deadbeef/share/deadbeef/pixmaps/play_16.png'
Failed to load pixbuf file: /opt/deadbeef/share/deadbeef/pixmaps/pause_16.png: Couldn't recognize
the image file format for file '/opt/deadbeef/share/deadbeef/pixmaps/pause_16.png'
Failed to load pixbuf file: /opt/deadbeef/share/deadbeef/pixmaps/buffering_16.png: Couldn't
recognize the image file format for file '/opt/deadbeef/share/deadbeef/pixmaps/buffering_16.png'
connecting button tray signals

(deadbeef:1925): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)'
failed

(deadbeef:1925): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)'
failed

(deadbeef:1925): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels: assertion 'GDK_IS_PIXBUF (pixbuf)'
failed

(deadbeef:1925): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)'
failed

(deadbeef:1925): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF
(pixbuf)' failed

(deadbeef:1925): GLib-ERROR **: /build/buildd/glib2.0-2.40.2/./glib/gmem.c:335: overflow allocating
18446744073709551615*18446744073709551615 bytes
Trace/breakpoint trap (core dumped)

**Comment by Alexey-Yakovenko** [comment]
It doesn't crash on startup on 14.04 here (I tried many times, basically 0.7.2 was developed in 14.04)

I can't help you with just the information that you provided. You need to create gdb backtrace, as described [here](https://github.com/Alexey-Yakovenko/deadbeef/wiki/GDB-HOWTO).

I'm closing the bug as invalid for now, but will reopen if you provide more information.

**Comment by Alexey-Yakovenko** [comment]
This error:
```Failed to load pixbuf file: /opt/deadbeef/share/deadbeef/pixmaps/play_16.png: Couldn't recognize the
image file format for file '/opt/deadbeef/share/deadbeef/pixmaps/play_16.png'```

indicates that either the pngs are corrupt, and you need to unpack deadbeef again, or that your system is broken.
