### ISSUE TITLE
Support of MP3 lyrics

### ISSUE THREAD

**Issue by TotalCaesar659** [Alexey-Yakovenko/deadbeef#1660]
Hello! Could you add MP3 lyrics into metadata window? foobar2000 shows them normally.
![1](https://cloud.githubusercontent.com/assets/14265316/19411377/3c3a9524-9309-11e6-8405-137deb8e97a7.png)
![2016-10-15-185330_1280x1000_scrot](https://cloud.githubusercontent.com/assets/14265316/19411373/317df540-9309-11e6-83d3-c33a93229353.png)

**Comment by loskutov** [comment]
Looks like a sufficient issue as some plugins may want to rely on the track metadata to extract lyrics, and now they have to implement extracting lyrics from ID3 with not-so-well-documented junklib.
