### ISSUE TITLE
Some .cue files are not recognized correclty

### ISSUE THREAD

**Issue by vostmarhk** [Alexey-Yakovenko/deadbeef#1662]
The metadata from some .cue files ([an example file](https://github.com/Alexey-Yakovenko/deadbeef/files/546550/The.Sound.Of.Perseverance.Reissue.Disc.1.cue.txt)) is not recognized when I try to open the corresponding .flac in the player. The track numbers are captured, but all the other content of the .cue file for some reason is appended to every track as a comment (see [screenshot](https://cloud.githubusercontent.com/assets/23016690/19628511/e88f7290-9967-11e6-8dc8-31ac29229a6c.png)) instead of proper tags. 

System: Ubuntu 16.04, deadbeef 0.7.2.

**Comment by Alexey-Yakovenko** [comment]
The cue file works fine here. Perhaps the problem has already been fixed later than the 0.7.2 was released. Try the latest build from master: https://sourceforge.net/projects/deadbeef/files/travis/linux/master/
