### ISSUE TITLE
Audio issues when playing some tracks with alsa.

### ISSUE THREAD

**Issue by orbea** [Alexey-Yakovenko/deadbeef#1666]
OS: `Slackware64-current`
`deadbeef-2016.10.25_265964c_master-x86_64-1_git`
`ffmpeg-3.1.5-x86_64_custom-1_SBo`
`alsa-lib-1.1.1-x86_64-1`

When playing a few songs with deadbeef and the alsa plugin the audio will have clear issues such as static or being too fast. This does not happen with the oss plugin (Using aoss) and it does not happen when using alsa with other media players such as cmus, mpv or mplayer.

I have only experienced this with some songs from a single album, so it might be connected to how the audio tracks were created?

Examples:
http://ks392457.kimsufi.com/orbea/stuff/music/YUNG%20BAE%20-%20Bae%20-%2002%20Take%20My%20Love.flac
http://ks392457.kimsufi.com/orbea/stuff/music/YUNG%20BAE%20-%20Bae%20-%2003%20I%20Want%20Your%20Love.flac
(You can download them with wget)

Source - https://yungbaebae.bandcamp.com/album/bae

**Comment by Alexey-Yakovenko** [comment]
It is a very common ALSA issue.

Please try the following things to fix it:

1. Restore deadbeef DSP settings to default
2. Disable "Use ALSA resampling" checkbox in the ALSA plugin settings
3. Make sure that you have the Resampler in the current DSP chain configuration.

Please let me know if you need any more help.

**Comment by orbea** [comment]
I found out what causes this, its the `SuperEQ` setting in the DSP chain configuration. Removing it will solve this.

However this indicates an additional problem, `SuperEQ` adds itself back as soon as I close the configuration settings and deadbeef will use it again next time its started. So ideally whatever `SuperEQ` is doing wrong should be corrected and / or the DSP configuration settings should not automatically revert themselves.

**Comment by Alexey-Yakovenko** [comment]
By default, supereq is disabled, and doesn't do anything.

The DSP node is required in the chain, to make the UI work.

**Comment by Alexey-Yakovenko** [comment]
The last change to dsp or eq was in 2014, so I doubt that you found a new bug -- someone, including myself, would have found it much sooner.

**Comment by orbea** [comment]
I've noticed something else strange, removing `SuperEQ` only worked when using a default configuration by moving my old deadbeef configuration out of the way. It does not work with my current configuration.

**Comment by orbea** [comment]
Given how this only affects less than 10 tracks out of multi thousands in my collection, I can see how it would be easy to miss.

**Comment by Alexey-Yakovenko** [comment]
I think it was a coincidence. Adding or removing the _disabled_ supereq node should not affect sound playback at all.

**Comment by Alexey-Yakovenko** [comment]
> Given how this only affects less than 10 tracks out of multi thousands in my collection, I can see how it would be easy to miss.

well, if only 10 of your tracks are 192khz tracks -- that clearly indicates that you disabled deadbeef's resampler plugin, and using the alsa resampler, which can't handle the files.

or there's something else odd in your system.

another thing that we can try to check though... recently I have been working on ReplayGain improvements, so this might have caused new bugs.

Try disabling replaygain in the playback settings.. however, well, you probably tried this already, because replaygain is disabled by default.

**Comment by Alexey-Yakovenko** [comment]
it's also worth checking:

* whether the problem exists in the official [0.7.2 build](https://sourceforge.net/projects/deadbeef/files/travis/linux/0.7/deadbeef-static_0.7.2-rc6-1_x86_64.tar.bz2/download)
* or even [0.7.3-alpha1](https://sourceforge.net/projects/deadbeef/files/travis/linux/0.7/deadbeef-static_0.7.3-alpha1-1_x86_64.tar.bz2/download)
* and of course the [dev build from master](https://sourceforge.net/projects/deadbeef/files/travis/linux/master/deadbeef-static_devel-1_x86_64.tar.bz2/download)

**Comment by orbea** [comment]
Yes, this is connected to the 192khz tracks, the album also contains tracks that are 44khz and 96khz which work correctly.

Though just now I realized I misread your initial directions, disabling  the `Use ALSA resampling` checkbox in the ALSA plugin settings solves this while before I somehow read that it should be enabled... This leaves me wondering why removing SuperEQ with an entirely default configuration consistently resolves the issue as well even if `Use ALSA resampling` is enabled... Well, I guess its not that important, thanks for your help!

**Comment by Alexey-Yakovenko** [comment]
> This leaves me wondering why removing SuperEQ with an entirely default configuration consistently resolves the issue as well even if Use ALSA resampling is enabled...

because sometimes alsa can resample from 192KHz successfully, and sometimes it fails, quite randomly.

I don't know why this is happening though.

**Comment by orbea** [comment]
One thing I noticed was that after listening to that entire album with the secret rabbit code resampler and then automatically switching to the next album in the playlist I would be greeted with white noise instead of music. Stopping and restarting the music would resolve it as it occurred in the same place twice.

After this I switched the Quality / Algorithm to `SINC_BEST_QUALITY` from `SINC_FASTEST` and it hasn't happened since. :)

**Comment by Alexey-Yakovenko** [comment]
This never occured to me ever, and I always use SINC_FASTEST because the SINC_BEST_QUALITY is taking too much CPU, and I couldn't use my computer while music is playing.

But it's worth looking into this.. might be some bug which we didn't know about.

**Comment by orbea** [comment]
I'll see if I can reproduce it consistently and easily later and get back to you. My cpu (amd fx 6350) seems powerful to run `SINC_BEST_QUALITY` without slowing down other programs.
