### ISSUE TITLE
Minimize to system tray command line option

### ISSUE THREAD

**Issue by jtechpro** [Alexey-Yakovenko/deadbeef#1668]
Always start the deadbeef player minimized (i.e. not to show up in Taskbar) but in system tray icon.
Especially useful while adding files to the queue (Enqueue option). The deadbeef window is always coming to front.
This doesn't happen when the deadbeef is minimized to tray.

For example..

by adding --hide-to-tray command line option.

**Comment by Alexey-Yakovenko** [comment]
duplicate of #521
