### ISSUE TITLE
Replaygain mode wont save status

### ISSUE THREAD

**Issue by mistersister** [Alexey-Yakovenko/deadbeef#1670]
Replay gain mode seems to revert to Track gain whenever I close deadbeef. 

I use mp3gain to adjust the volume of my mp3 so I want it to stay disabled but each time I close the player and open it again, the setting is back to Track gain again.

Im using Arch Linux + Deadbeef 0.7.2 static build with pulseaudio output.

**Comment by oleksiy-unity3d** [comment]
how exactly do you close deadbeef? It's a known issue, that when the process is killed during reboot, the configuration is not saved.

Please try quitting deadbeef immediately after changing the setting, then run again, and see if the problem is solved.

**Comment by Alexey-Yakovenko** [comment]
how exactly do you close deadbeef? It's a known issue, that when the process is killed during reboot, the configuration is not saved.

Please try quitting deadbeef immediately after changing the setting, then run again, and see if the problem is solved.

**Comment by mistersister** [comment]
It happens when closing the player via right click on the tray icon > Quit  as well as when I close with File > Quit

After changing the setting and closing, the setting is reverted back to Track gain.

**Comment by Alexey-Yakovenko** [comment]
Please run deadbeef from a terminal emulator, try changing the settings, then quit, and post the complete console output.

**Comment by mistersister** [comment]
seems theres a segfault both when closing the player via File > Quit and Tray icon > Quit


[filequit_dump.txt](https://github.com/Alexey-Yakovenko/deadbeef/files/585580/filequit_dump.txt)
[trayquit.txt](https://github.com/Alexey-Yakovenko/deadbeef/files/585579/trayquit.txt)

**Comment by Alexey-Yakovenko** [comment]
Yes. The player is crashing when quitting, before it could save configuration.

It seems that the output is incomplete. Usually deadbeef dumps a callstack after a crash.

It seems that something in your system is configured in a way that prevents the player from doing that.

To get around this, you need to execute this sequnce of commands:

```
gdb deadbeef
r
# deadbeef will start here, you need to quit it manually
bt
```

This should produce the callstack, that I need to understand the problem.

**Comment by mistersister** [comment]
there you go

[filequit_dump.txt](https://github.com/Alexey-Yakovenko/deadbeef/files/585603/filequit_dump.txt)
[trayquit.txt](https://github.com/Alexey-Yakovenko/deadbeef/files/585604/trayquit.txt)

**Comment by Alexey-Yakovenko** [comment]
It didn't crash when running in gdb.

**Comment by Alexey-Yakovenko** [comment]
One more thing to try:

* quit the player
* move the folder `$HOME/.config/deadbeef` to some other location (please don't delete it)
* run deadbeef with the clean config and see if the problem still happens.

If the problem "fixes itself" with a fresh config -- I'd like to get the whole contents of that folder for investigation.

**Comment by mistersister** [comment]
when running a fresh config file, it seems to revert to Album mode. 

Also, while i was running the gdb earlier, i got this:
[quit.txt](https://github.com/Alexey-Yakovenko/deadbeef/files/585617/quit.txt)

**Comment by Alexey-Yakovenko** [comment]
The above information is not very useful.

SIGINT is a user interrupt (you aborted the program with CTRL+C)

And I don't really think that the player is reverting anything. It just stays wherever it was, because it can't save the file -- the crash happens before the config is saved.

You might be able to trigger configuration save without quitting the player, e.g. by changing some other settings. But that wouldn't solve the crash.

**Comment by mistersister** [comment]
I tried changing some other config parameters and while those were saved, the replay gain specifs were not. 

I also tried to manually edit the config file and set  replaygain_mode to 0, 1 or 2 but it always defaults back to 1.

**Comment by Alexey-Yakovenko** [comment]
I can't reproduce this locally. The replaygain mode is saved to whatever value I set it too.

The player also doesn't crash. I tried in Ubuntu12.04, but going to try in archlinux in a moment

**Comment by Alexey-Yakovenko** [comment]
Tried in archlinux. Same thing -- the config is saved fine, nothing gets changed "on its own", and no crash.

**Comment by Alexey-Yakovenko** [comment]
I just noticed, that you have a plugin called "ddb_misc_replaygain_control". Most likely the replaygaing configuration issue on your machine is caused by it. The crash issue - I don't know.. Try removing any unofficial plugins, and find which one is causing that.

**Comment by cboxdoerfer** [comment]
Hi, I'm the author of the replay gain control plugin. And yeah, the whole purpose of that plugin is to override the default replaygain settings (http://i.imgur.com/a9XV7SC.png). Maybe I should add a simple on/off switch for it but, in general if you want to follow the replaygain settings of the player you don't need that plugin anyway, so removing it will solve that issue.

**Comment by mistersister** [comment]
removing the the replay gain control plugin has solved the issue. thanks to both of you for your help.
