### ISSUE TITLE
Clicking "Reload metadata" doesn't save playlist

### ISSUE THREAD

**Issue by KernelModule** [Alexey-Yakovenko/deadbeef#1671]
Subj. DeaDBeef after restart displays old metadata of music files, not the new.

**Comment by Alexey-Yakovenko** [comment]
Please state what steps do you perform in the player, what is the expected results, and what do you get instead. If you have a hard time explaining the problem with text, please use screenshots.

**Comment by KernelModule** [comment]
@Alexey-Yakovenko OK. Только давай тогда по-русски объясню, если ты не против.
1. Я изменяю метаданные музыкального файла с помощью посторонней программы-теггировщика.
2. Потом, т.к этот файл уже добавлен в плейлист, я нажимаю ПКМ по треку и кликаю "Обновить метаданные". Инфа обновляется, все хорошо. Но после перезапуска плеера, в плейлисте отображается старые данные (с которыми файл был добавлен изначально), а не обновленные.

**Comment by Alexey-Yakovenko** [comment]
updated the bug title
