### ISSUE TITLE
Any vfs_curl streams abort after 5 seconds of playing

### ISSUE THREAD

**Issue by greenvorbisfan** [Alexey-Yakovenko/deadbeef#1675]
В сборке git-master треки, добавленные из соцсети https://github.com/scorpp/db-vk играют первые 10-15 секунд. В консоли ошибок нет. При попытке открыть ссылку на трек из консоли в браузере трек проигрывается в браузере целиком. Если ту же ссылку добавить в deadbeef — проблема остаётся. На версиях 0.7.x такой проблемы нет.
Ubuntu 16.04.1 LTS (x64), DeaDBeeF git-master

**Comment by Alexey-Yakovenko** [comment]
у меня на этот счет есть два вопроса..

1. правильно ли я понимаю, что для проигрывания музыки, плагин просто добавляет URL с контакта в плейлист?

2. нужно ли иметь учетную запись на контакте для этого?

**Comment by Alexey-Yakovenko** [comment]
Reproduced the bug, it's not specific to vk.com plugin -- any HTTP/HTTPS streams do the same thing. Seems to be a very recently introduced regression.

**Comment by Alexey-Yakovenko** [comment]
Most likely caused by commit b4434d83fefc1e76fe00627115af12ba8c18c96b, fixing the issue #1094

**Comment by Alexey-Yakovenko** [comment]
Fixed
