### ISSUE TITLE
Mac OS: Homebrew package installation issue: sha256 mismatch

### ISSUE THREAD

**Issue by antonakv** [Alexey-Yakovenko/deadbeef#1677]
MacOS 10.12.1

$ brew update
Already up-to-date.
$ brew install Caskroom/cask/deadbeef
==> brew cask install Caskroom/cask/deadbeef
==> Downloading https://downloads.sourceforge.net/deadbeef/deadbeef-devel-osx-x86_64.zip
Already downloaded: /Users/anton/Library/Caches/Homebrew/Cask/deadbeef--0.7.2.zip
==> Verifying checksum for Cask deadbeef
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 8da871c4f8ab19515bb85119a85b32ed3917a8c01074afb8861a00debd3bb38e
Actual: 6b6be9dd564516b1c2c47362c81530a367245863cab894db0639514ca2e452fa
File: /Users/anton/Library/Caches/Homebrew/Cask/deadbeef--0.7.2.zip
To retry an incomplete download, remove the file above.

**Comment by Alexey-Yakovenko** [comment]
1. You should not rely on a checksum of the CI build artifact.
It rebuilds after every code change automatically, and of course the checksum changes every time.
2. Deadbeef on macOS has never been released, and doesn't have a version number. It is wrong to call it 0.7.2. The only version we have is the rolling build off trunk.
3. Deadbeef devs have nothing to do with homebrew or any other unofficial package managers, so if you want to have the homebrew package fixed -- you should report the problem to the homebrew package maintainer.

**Comment by antonakv** [comment]
Thank you. I will inform maintainers.
