### ISSUE TITLE
Cue load depends on filename

### ISSUE THREAD

**Issue by oserhiye** [Alexey-Yakovenko/deadbeef#1679]
**Tested build** - latest dev build.
**System** - Ubuntu 14.04

Loading folder with one cue and one flac.
If named like this cue is **ignored**:
```
wishmaster.cue
Nightwish - Wishmaster.flac
```
When renamed to be similar name - cue tracks are **loaded**:
```
Nightwish - Wishmaster.cue
Nightwish - Wishmaster.flac
```

**Why I want fix?**
Folders with one cue and several flacs, i.e.:
```
Dark Passion Play.cue
Side A.flac
Side B.flac
Side C.flac
Side D.flac
```

**Proposed solution:**
Extract used files from cue files instead of filename.
I.e. getting all music files used by cues in folder can be gone even like this:
`grep -r WAVE $(pathToFolderToLoad)/*.cue | xargs -n 1 echo | grep '\.'`

**Comment by Alexey-Yakovenko** [comment]
duplicate of #648

**Comment by oserhiye** [comment]
С марта 15го висит...
Ясно, проще самому фиксить.

**Comment by Alexey-Yakovenko** [comment]
@oserhiye 
фиксить - не совсем правильное слово. это не баг. просто так работает поддержка cue в deadbeef -- умеет только image+cue (single disc).

есть фичреквест на реализацию поддержки tracks+cue (ну или multiple discs with 1 cue). пока что руки не дошли.

**Comment by Alexey-Yakovenko** [comment]
ps. если вы не заметили, в issues висит 235 открытых фичреквестов, и некоторые значительно старше 15го года. Если есть фичреквест -- это еще не значит, что он будет реализован быстро, или будет реализован вообще когда либо. Нужно понимать, что 99.9% кода пилится силами 1 человека. Patches are welcome.
