### ISSUE TITLE
Incorrect charset (non-Latin) used for some local mp3 files

### ISSUE THREAD

**Issue by thepaparazzi** [Alexey-Yakovenko/deadbeef#1680]
OS: Mac OS X 10.9.5 Mavericks
Version: 2016-12-08 build from https://sourceforge.net/projects/deadbeef/files/travis/osx/master/

This set of local mp3 files causes the charset to be interpreted incorrectly: https://sli.mg/HAJZd7

For reference, this is the album Everything Is Wrong by Moby. Metadata should be all ASCII as far as I can tell. This hasn't happened for other albums I've played, either FLAC or mp3.

This appears to be the same issue as #1470.

**Comment by Alexey-Yakovenko** [comment]
The issue #1470 is marked as fixed. So apparently this is a different issue. Any chance that you could send an example file to my email?

**Comment by thepaparazzi** [comment]
Sent to your users.sourceforge.net email.

**Comment by Alexey-Yakovenko** [comment]
thanks

**Comment by Alexey-Yakovenko** [comment]
Thanks for the report, was a valid bug.
