### ISSUE TITLE
Field "Duration" on tab "Properties" in "Track properties" something "wrong"

### ISSUE THREAD

**Issue by gothluck** [Alexey-Yakovenko/deadbeef#1681]
If selected few track with the same track duration, then field "Duration" on tab "Properties" in "Track properties" contains only one value.

Also if selected few track with different and the same track duration, then field "Duration" contains only unique value for track duration, skipping duplicate values.

Details in attached screenshots (in 02.png selected 6 tracks, but in duration present 5 values)
![01](https://cloud.githubusercontent.com/assets/24501182/21077704/f210eb1c-bf5c-11e6-84de-e0a9f05026dc.png)
![02](https://cloud.githubusercontent.com/assets/24501182/21077705/f2121398-bf5c-11e6-9dd4-ac5d857eae21.png)

It must be so, or it's bug?

**Comment by Alexey-Yakovenko** [comment]
All fields work the same. Only unique values are displayed. There's nothing wrong with this.
