### ISSUE TITLE
problem with sampling rate when playing DSD files

### ISSUE THREAD

**Issue by NTMan** [Alexey-Yakovenko/deadbeef#1688]
Demostration: https://youtu.be/on8IdCh78jg

DeaDBeeF 0.7.2
DSD sample from here: http://shop.dsdfile.com/wp-content/plugins/download-monitor/download.php?id=3

**Comment by Alexey-Yakovenko** [comment]
ALSA can't handle high samplerates. You need disable the "Use ALSA resampling" setting, and have Resampler plugin in the DSP chain, configured to use automatic samplerate.

**Comment by NTMan** [comment]
It means on Linux impossible listen DSD without resampling? (I hope listen native DSD with this DAC http://www.fostexinternational.com/docs/products/HP-A8mk2.shtml)

**Comment by Alexey-Yakovenko** [comment]
It is possible. You need to select direct audio output in the sound settings. This will bypass dmix, and output at the closest supported native sampling rate. But you will lose software mixing.

**Comment by Alexey-Yakovenko** [comment]
If you hoped to output native DSD stream to a DAC using DoP -- then no, it's not currently possible with deadbeef. It has been requested, and covered in the issue #1653.

**Comment by NTMan** [comment]
Without DoP how it doing? In DeaDBeef on tab `Sound` select another `Output device` is enough? Or needed change some setting in OS?

**Comment by Alexey-Yakovenko** [comment]
Yes, you only need to select direct audio output in the output device settings, in the player.

But depending on your OS setup this may differ, sometimes this option is not present.

**Comment by Alexey-Yakovenko** [comment]
BTW, even if your device supports playing DSD over DoP at native sampling rate, doesn't mean it will be able to play decoded PCM at 300+KHz

**Comment by NTMan** [comment]
I don't want that DSD converted to PCM while playing.
And for some reason I have my doubts that the sound passes through the ALSA without  converting to PCM.
Poor that the system never displays the current frequency of sampling and mode of data transfer  PCM or DSD .

**Comment by Alexey-Yakovenko** [comment]
@NTMan 

> I don't want that DSD converted to PCM while playing.

As I mentioned above, deadbeef doesn't support sending DSD over DoP (i.e. without decoding it, or converting to PCM as you call it).

> Poor that the system never displays the current frequency of sampling and mode of data transfer PCM or DSD .

It does. It is displayed in the status bar of the main window. And the mode of data transfer is **always** PCM, even DoP stands for "DSD over **PCM**", except DoP means non-decoded DSD stream is sent to the receiver pretending it's PCM, without actually being real wave data in PCM.

**Comment by NTMan** [comment]
Oh, I am understood that on Linux the only way to send DSD to DAC without converting it is use DoP. I am ask because on Windows player I see DSD Native option. And I misunderstood that your proposal  "select direct audio output in the sound settings" it is same.

![screenshot from 2017-01-05 02-32-23](https://cloud.githubusercontent.com/assets/200750/21660588/cf42e290-d2f1-11e6-924e-fb453e41fb86.png)

DSD Native alternative not available under Linux, right?

> It is displayed in the status bar of the main window.

Seems it is not right because I see only source sampling rate (it not equal to output sampling rate)
![screenshot from 2017-01-05 02-59-22](https://cloud.githubusercontent.com/assets/200750/21661009/d501e256-d2f3-11e6-9ea6-ba8d8aaea0b7.png)
We know that output sampling rate is not 300K, but DeaDBeeF displayed in the status bar 352800Hz, it would be more honest to show what we have at the output or having option for switching displaying between source and output bitrate.

**Comment by Alexey-Yakovenko** [comment]
> DSD Native alternative not available under Linux, right?

I don't think it's not available. I think that DSD Native might the same thing as DoP, but under a more user-friendly name.

> We know that output sampling rate is not 300K, but DeaDBeeF displayed in the status bar 352800Hz, it would be more honest to show what we have at the output or having option for switching displaying between source and output bitrate.

ok, you're right, the **output** sampling rate is not displayed anywhere in the player.
the displayed one is the input rate.

the information in the status bar is about the current file, and not about the output device, so it kinda makes sense.
