### ISSUE TITLE
Allow event driven updates to --nowplaying info 

### ISSUE THREAD

**Issue by easysid** [Alexey-Yakovenko/deadbeef#1690]
Allow the an option for --nowplaying-tf information to listen for player events. The use case of this is to just make scripting the player easier. Currently, to get the song info, one needs to poll the player every few seconds, which sometimes goes out of sync. An event driven model would allow one to launch a listener loop in the background, and manipulate the output easily, and almost instantaneously. mpc imploys something similar for mpd.

Thanks.

**Comment by Alexey-Yakovenko** [comment]
How is this different from MPRIS?

**Comment by easysid** [comment]
> How is this different from MPRIS?

I forgot about MPRIS. Sorry. MPRIS with python should work. I'll look into it.  

Thanks. I'll close the issue.
