### ISSUE TITLE
Build error: relocation R_X86_64_32 against `ff_a64_muxer' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by jasonMisaq** [Alexey-Yakovenko/deadbeef#1691]
Once configure has run successfully, I get the following when I run make, 

```
/usr/bin/ld: /usr/local/lib/libavformat.a(allformats.o): relocation R_X86_64_32 against `ff_a64_muxer' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavformat.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:465: recipe for target 'ffmpeg.la' failed
make[2]: *** [ffmpeg.la] Error 1
make[2]: Leaving directory '/home/john/src/deadbeef-0.7.2/plugins/ffmpeg'
Makefile:769: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/john/src/deadbeef-0.7.2'
Makefile:527: recipe for target 'all' failed
make: *** [all] Error 2
```
What is the problem? What shared object is the error talking about? What and how should I recompile using -fPIC option? I used it with make but make did not accept the option.

**Comment by Alexey-Yakovenko** [comment]
You seem to have built a custom ffmpeg without -fPIC flag.

When building ffmpeg, make sure to pass this extra parameter:

`./configure --extra-cflags="-fPIC"`

**Comment by jasonMisaq** [comment]
I built ffmpeg with -fPIC and yet I got another error:   
```
  CCLD   ffmpeg.la
/usr/bin/ld: /usr/local/lib/libavformat.a(rmsipr.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavformat.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:465: recipe for target 'ffmpeg.la' failed
make[2]: *** [ffmpeg.la] Error 1
make[2]: Leaving directory '/home/john/src/deadbeef-0.7.2/plugins/ffmpeg'
Makefile:769: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/john/src/deadbeef-0.7.2'
Makefile:527: recipe for target 'all' failed
make: *** [all] Error 2

```
I recompile libav with `-fPIC`, too, but still the error persists.

**Comment by Alexey-Yakovenko** [comment]
You don't need libav.

libavformat etc are parts of ffmpeg.

You need to make sure to clean the tree (make clean at a minimum), then reconfigure with `--extra-cflags="-fPIC"`, rebuild, and reinstall.

Right now, it seems that parts of ffmpeg did not rebuild with -fPIC.

**Comment by Alexey-Yakovenko** [comment]
It's possible that you also need to pass --enable-pic to ./configure.

There may be other issues as well even if you compile with PIC enabled.

This is how static ffmpeg is built for mac:
https://github.com/Alexey-Yakovenko/deadbeef-osx-deps/blob/master/ffmpeg-build.sh

it won't work as-is on linux, but should give some ideas maybe.
