### ISSUE TITLE
Migrating to PortAudio

### ISSUE THREAD

**Issue by alexeysvrv** [Alexey-Yakovenko/deadbeef#1692]
I propose to migrate to the PortAudio audio system. Better API, from what I've heard generally better hardware support... This audio use for example Audacity and VLC

**Comment by Alexey-Yakovenko** [comment]
Deadbeef supports various audio output libraries through its modular architecture.

Currently, it supports ALSA, OSS, CoreAudio and Android AudioTrack output.

There are additional plugins that add JACK, RSound and others.

You should be able to create a new output plugin to support PortAudio as well, if you have the need for it.

"Migrating" is not the right term though.

**Comment by Alexey-Yakovenko** [comment]
Closing as invalid, because migration from the current audio framework to PortAudio can't and won't ever happen, for multiple reasons.
