### ISSUE TITLE
Configure dialog for DSP samplerate is missing

### ISSUE THREAD

**Issue by eblanca** [Alexey-Yakovenko/deadbeef#1694]
In [deadbeef/plugins/dsp_libsrc/src.c](https://github.com/Alexey-Yakovenko/deadbeef/blob/master/plugins/dsp_libsrc/src.c) near the end, the statement
`.configdialog = settings_dlg,`
should be
`.plugin.configdialog = settings_dlg,`
in order to allow the configuration dialog to appear.

**Comment by Alexey-Yakovenko** [comment]
DSP plugin configuration works differently, see DSP tab in preferences.

**Comment by eblanca** [comment]
oh didn't notice this, sorry.
Thank you.
