### ISSUE TITLE
ogg vorbis files shows as 32-bit

### ISSUE THREAD

**Issue by spvkgn** [Alexey-Yakovenko/deadbeef#1695]
Is it a bug ?

![- - 3_1843 - deadbeef-devel](https://cloud.githubusercontent.com/assets/4147135/22422552/395856ea-e717-11e6-8cf7-86af15ddd85f.png)

File from https://archive.org/download/tn041/3_1843.ogg

**Comment by Alexey-Yakovenko** [comment]
Not really. Vorbis files are decoded as float32 in recent deadbeef builds.
