### ISSUE TITLE
tf: segfault

### ISSUE THREAD

**Issue by saivert** [Alexey-Yakovenko/deadbeef#1696]
```
Thread 1 "deadbeef-gtkui" received signal SIGSEGV, Segmentation fault.
0x000000000042581e in tf_eval_int (ctx=ctx@entry=0x7fffffff05c0, code=0xfedd5a "path7http://Internet streams", 
    code@entry=0xfedd57 "", size=<optimized out>, out=out@entry=0x7ffffffef4a0 "http://87.99.117.209:8500/", 
    outlen=outlen@entry=1000, bool_out=bool_out@entry=0x7ffffffef48c, fail_on_undef=<optimized out>) at tf.c:1975
1975	                    if (!strncmp (val, "file://", 7)) {
```

Offending TF string (used as custom grouping in GTKUI):
```
$if($strcmp($left(%path%,7),'http://'),Internet streams,%album artist% - [(%year%) ]%album%)
```

Fixed by changing TF string to:

```
$if($strcmp($left(%_path_raw%,7),'http://'),Internet streams,%album artist% - [(%year%) ]%album%)
```

Still no TF string should crash deadbeef.

**Comment by Alexey-Yakovenko** [comment]
@saivert 
I can't reproduce the crash.
Do you have some weird track in playlist?
Can you identify which track caused the error?

**Comment by Alexey-Yakovenko** [comment]
The only issue I could come up with...
https://github.com/Alexey-Yakovenko/deadbeef/commit/5acf75f38c3aeb55eeeaae20e6a8c2ddd768940d

Please try.

There should not be tracks in playlist, which have NULL `:URI`. There may be a bug in another place.
