### ISSUE TITLE
[Android] DDB2 Bluetooth query wrong track number and time

### ISSUE THREAD

**Issue by mlamothe-broadsoft** [Alexey-Yakovenko/deadbeef#1701]
When DDB2 sends the now playing information to compatible bluetooth devices the track number is always 0 and the track duration is sent as the initial time (ex.: 2:30 instead of 0:00) so the time starts counting up from there and at the end of the song the time ends up as being double the song's duration (ex.: 5:00 for a 2:30 song).

Also since you just added album art support to DDB2, would be nice to also send it to bluetooth devices that support it.

Note: I am using Android Nougat and my library consists of entire albums in single mp3 files with embedded cuesheet.

Thank you for the great app and for supporting embedded cuesheet in mp3s!

**Comment by Alexey-Yakovenko** [comment]
Hello. Thanks for your report. This website is not the correct place to report DDB2 issues.
They need to be sent directly to support@ddb2.me, as stated on the play store page.
Therefore, you did good that you closed the issue after adding it. I'll copy it to DDB2 issue tracking system.
