### ISSUE TITLE
[Android] DDB2 bluetooth wrong track number & time

### ISSUE THREAD

**Issue by Malbeth81** [Alexey-Yakovenko/deadbeef#1702]
When DDB2 sends the now playing information to compatible bluetooth devices the track number is always 0 and the track duration is sent as the initial time (ex.: 2:30 instead of 0:00) so the time starts counting up from there and at the end of the song the time ends up as being double the song's duration (ex.: 5:00 for a 2:30 song).

Also since you just added album art support to DDB2, would be nice to also send it to bluetooth devices that support it.

Note: I am using Android Nougat and my library consists of entire albums in single mp3 files with embedded cuesheet.

Thank you for the great app and for supporting embedded cuesheet in mp3s!

**Comment by Malbeth81** [comment]
Sorry I opened the previous issue under my work account so opened this one thinking I could delete the previous one, which turns out cannot be done.

**Comment by Alexey-Yakovenko** [comment]
Yeah, it's a shame github doesn't let to delete issues.
