### ISSUE TITLE
SOX resampler = noise

### ISSUE THREAD

**Issue by ad1862** [Alexey-Yakovenko/deadbeef#1711]
After the last update (gentoo deadbeef-9999 x86-64) using SOX resampler is noise. If I set "Auto discretization" or "Target samplerate 44100 ..." = 48000.

**Comment by Alexey-Yakovenko** [comment]
Master branch is undergoing a large refactoring, and some parts are malfunctioning.
Reverting to 6f218a214dd8b734fc007cfeab0f0c2adf5bdc5e should sort this out.
Things should get back to normal in about couple of weeks.

**Comment by ad1862** [comment]
Ясно. Откатился пока на стабильный 0.7.2.
Спасибо за отличный проигрыватель !

**Comment by Alexey-Yakovenko** [comment]
This issue should be fixed when this PR lands: https://github.com/silentlexx/deadbeef_soxr/pull/1
Or you can apply it as a patch locally. I will be looking into ways to solve this in a better way.

**Comment by Alexey-Yakovenko** [comment]
nvm the PR above, I fixed the issue on deadbeef side, should work now.
