### ISSUE TITLE
Crash When Playlist Is Finished

### ISSUE THREAD

**Issue by shoober420** [Alexey-Yakovenko/deadbeef#1712]
After listening to an album and the playlist is done, deadbeef will crash with this error.

selected output plugin: ALSA output plugin
INFO: from file /home/jukilo420_-/.config/deadbeef/playlists/0.dbpl
resume: track 5 pos 424.530243 playlist 0
gtkui plugin compiled for gtk version: 2.24.31
connecting button tray signals
Cannot create status notifier, falling back to GtkStatusIcon
pthread_join failed: Resource deadlock avoided
Segmentation Fault
backtrace() returned 7 addresses
deadbeef(+0x34676) [0x557b320d1676]
/usr/lib/libc.so.6(+0x330b0) [0x7f129f3840b0]
/usr/lib/libpthread.so.0(pthread_mutex_lock+0) [0x7f129f6f8ad0]
deadbeef(+0x4a769) [0x557b320e7769]
/usr/lib/deadbeef/alsa.so(+0x1dc7) [0x7f12967d2dc7]
/usr/lib/libpthread.so.0(+0x7454) [0x7f129f6f6454]
/usr/lib/libc.so.6(clone+0x5f) [0x7f129f4397df]

**Comment by Alexey-Yakovenko** [comment]
Please see issue #1711 , it has a workaround and an explanation

**Comment by Alexey-Yakovenko** [comment]
this should have been fixed by now.
