### ISSUE TITLE
OptimFROG Dual Stream Feature Request

### ISSUE THREAD

**Issue by pmphd7549** [Alexey-Yakovenko/deadbeef#1714]
The website for OptimFROG is : (http://losslessaudio.org/)
This has a "Dual Stream" encoder ([ofs] (http://losslessaudio.org/DualStream.php) for music files.

**Comment by Alexey-Yakovenko** [comment]
NOTE: while it should be possible to create the plugin for this format, the OptimFROG is not opensource, so it won't be possible to include the plugin in mainline deadbeef distribution, as this would violate GPL terms.

**Comment by greenvorbisfan** [comment]
Here' s a plugin for deadbeef: https://github.com/cspiegel/deadbeef-optimfrog

**Comment by Alexey-Yakovenko** [comment]
Great work man!

**Comment by pmphd7549** [comment]
Thank you!
