### ISSUE TITLE
playing time is not right when looping a track

### ISSUE THREAD

**Issue by pingplug** [Alexey-Yakovenko/deadbeef#1716]
If I looping a single song, the playing time is longer than the length of track, and seekbar is full

![screenshot_20170228_182229](https://cloud.githubusercontent.com/assets/6712475/23401501/ec0631ea-fde2-11e6-903f-4d1c7580f5f4.png)
![screenshot_20170228_182656](https://cloud.githubusercontent.com/assets/6712475/23401668/818748ee-fde3-11e6-8a09-ada5c35a97a4.png)

**Comment by pingplug** [comment]
happened again in the latest version, breaks "stop after current track"
![screenshot_20170325_184113](https://cloud.githubusercontent.com/assets/6712475/24321593/01f4e17a-118b-11e7-8e19-977795eff6e8.png)

**Comment by IvanDSM** [comment]
I'm not sure if it is the same issue, but on git master I have noticed that playing times have been off by  around +3 seconds. That is, a track that is 3 minutes and 57 seconds long will show up as lasting 3:57, but will start at 0:03 and end at 4:00. I have had this issue outside of looping mode. Maybe this has a relation with #1733?

**Comment by Alexey-Yakovenko** [comment]
@IvanDSM I had this issue some time ago, but it's been fixed. Are you sure you're running latest?

**Comment by Alexey-Yakovenko** [comment]
Can't reproduce this.
