### ISSUE TITLE
Crash When Playing Track

### ISSUE THREAD

**Issue by shoober420** [Alexey-Yakovenko/deadbeef#1717]
When trying to open a file, it will crash when double clicking the track. Here is the error.

deadbeef: streamer.c:1288: streamer_start_new_song: Assertion `0' failed.

**Comment by TheDevKing** [comment]
I'm having the same issue. it seems to be related to the output plugin/device. I get the crash when using ALSA on "Direct hardware device without any conversions", "Direct sample mixing device", "Direct sample snooping device", but not "Default Device".

Perhaps this is another issue entirely, but when using ALSA with default device (the one that will play), it seems to try to play all files at 48khz, even if they are 96khz (or other). I determined this by doing "cat /proc/asound/STX/pcm0p/sub0/hw_params" (running Xonar Essence STX that can definitely handle this frequency). This occurs with or without ALSA resambling enabled, though with it enabled the track plays too fast and without it it plays too slow, either way outputting at 48khz at the hardware level. I know this isn't normal, as with previous builds it would output at the correct rate on the hardware level. As far as I can tell bit depth is not a factor.

Let me know if there's any additional information I could provide.

**Comment by Alexey-Yakovenko** [comment]
> Perhaps this is another issue entirely, but when using ALSA with default device (the one that will play), it seems to try to play all files at 48khz, even if they are 96khz (or other).

As far as I remember, default device is using dmix, which is configured to 48KHz. Everything will always play at the dmix samplerate by definition. I don't think dmix allows changing samplerate on the fly.
