### ISSUE TITLE
Title formatting issues

### ISSUE THREAD

**Issue by spvkgn** [Alexey-Yakovenko/deadbeef#1722]
These title formatting examples works with 0.7.2 and not with devel: 

`$ifgreater(%totaldiscs%,1,[%discnumber%-][%tracknumber%],[%tracknumber%]`

`$if($or($strcmp(%album artist%,Various Artists),$strcmp(%album artist%,VA)),%artist% - %title%,%title%`

The column displays nothing. Could you please take a look - is it a bug?

**Comment by Alexey-Yakovenko** [comment]
The first expression is missing closing parenthesis. If I add it -- it works.

**Comment by Alexey-Yakovenko** [comment]
And the same with the 2nd expression... Definitely missing `)` (not sure yet if it works)

**Comment by Alexey-Yakovenko** [comment]
Yeah, works too.
