### ISSUE TITLE
The artwork plugin loads random images

### ISSUE THREAD

**Issue by danpla** [Alexey-Yakovenko/deadbeef#1724]
If the track's directory doesn't contain images that match the patterns given in the preferences, the artwork plugin simply loads random one (which obviously not related to the track in any way). It looks like there is [a code](https://github.com/Alexey-Yakovenko/deadbeef/blob/7a6106c824aacb1aa6cdebbdc53cf22d2f40dddf/plugins/artwork/artwork.c#L1254) for that. Is this a bug or a future?

**Comment by Alexey-Yakovenko** [comment]
which os / player version?

**Comment by danpla** [comment]
Linux x64; DeaDBeeF 0.7.2.

**Comment by Alexey-Yakovenko** [comment]
I think you're saying that the plugin loads a random image from the track's folder. That's the expected behavior.

**Comment by danpla** [comment]
Ok.
