### ISSUE TITLE
Add new %E format specifier for remaining track time

### ISSUE THREAD

**Issue by danfe** [Alexey-Yakovenko/deadbeef#1726]
Currently, there is `%e` format specifier to obtain current time position of a playing track.  Many players support (and people prefer) negative (time to end) position instead, aka remaining time.  Consider this simple [patch](https://github.com/Alexey-Yakovenko/deadbeef/files/847205/patch-playlist.txt) that adds `%E` (since `%r` was already taken) format specifier for this very purpose.

I've been running with this patch well over a year now, works great with playback status plugin.

**Comment by Alexey-Yakovenko** [comment]
How is this supposed to be used? The function that your patch is modifying is deprecated, and is not used anymore.

Why not just use this?

```
%playback_time_remaining%

The time remaining until the track ends, formatted as [HH:]MM:SS. Old version: %_time_remaining%
```
It's been supported

**Comment by Alexey-Yakovenko** [comment]
I just checked the playback status plugin. It had been updated to use the new title formatting plugin, so you need to update the plugin, and use the `%playback_time_remaining%`. Hope that solves the problem for you.

**Comment by danfe** [comment]
Ah, I see, `%playback_time_remaining%` was not in 0.6.2 so I had to patch it.  I guess it is not relevant for newer versions, sorry for the noise.
