### ISSUE TITLE
Собственные shell команды

### ISSUE THREAD

**Issue by ForumLiker** [Alexey-Yakovenko/deadbeef#1729]
Не могу найти справку по списку доступных shell команд и их опций.
Хочу добавить копирование\перемещение выбранной песни или нескольких песен в нужную мне ~~папку~~ директорию.

**Comment by Alexey-Yakovenko** [comment]
всю необходимую информацию вы можете найти [здесь](http://lmgtfy.com/?q=%D1%88%D0%B5%D0%BB%D0%BB+%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%8B+linux")

**Comment by ForumLiker** [comment]
с командами все понятно. как передать команде **cp** аргумент **%patch%**
cp %patch% /home/user/

**Comment by Alexey-Yakovenko** [comment]
shellexec еще не использует новый синтаксис title formatting. описание старого здесь:  https://github.com/Alexey-Yakovenko/deadbeef/wiki/Title-formatting

**Comment by ForumLiker** [comment]
Спасибо. Теперь совершенно другое дело)
