### ISSUE TITLE
Failed to bypass dmix resample

### ISSUE THREAD

**Issue by rickyzhang82** [Alexey-Yakovenko/deadbeef#1730]
When I use ALSA output plugin output to iFi idsd DAC, 44.1kHz ALAC always up sample to 48kHz. If I disable use ALSA resampling in ALSA output plugin, the output sounds are distorted. The output sample rate is still 48kHz.

It seems that ALSA output plugin didn't bypass dmix with/without 'use ALSA resampling' enabled. Is it expected?

Here is my configuration:

- Fedora 25 Kernel 4.8.16
- alsa-lib-1.1.1
- deadbeef on commit 87d3fd529d76.

**Comment by Alexey-Yakovenko** [comment]
They are not related. Resampling configuration does not affect whether dmix is enabled or not. If you want to bypass dmix, you need to select an output device which is configured to not use dmix.

**Comment by rickyzhang82** [comment]
I found a workaround. 

First, I disable pulse audio.

Secondly, add ~/.asoundrc (My DAC shows as hw:3,0)

```bash
pcm.DAC {
   type hw
   card 3
   device 0
}

ctl.!default {
   type hw
   card "hw:3,0"
}

pcm.!default {
   type plug
   slave {
      pcm "DAC"
      rate "unchanged"
      format S32_LE
   }
}

```

Then choose output device as 'Default Audio Device' in ALSA output plugin. Only then disable 'use ALSA resampling' didn't distort tempo of music. I can see that output sample rate didn't get up-sample to 48kHz.

```bash
cat /proc/asound/card3/pcm0p/sub0/hw_params
access: MMAP_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 1024
buffer_size: 8192

```

However, when I play music with different sample rate like 96kHz FLAC, I can only hear white noise. I could see that sample rate has been changed:

```bash
cat /proc/asound/card3/pcm0p/sub0/hw_params
access: MMAP_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 96000 (96000/1)
period_size: 1024
buffer_size: 8192
```
