### ISSUE TITLE
Feature Request: Waveform seekbar

### ISSUE THREAD

**Issue by s0nspark** [Alexey-Yakovenko/deadbeef#1731]
I would love to see a waveform seekbar added...

**Comment by Alexey-Yakovenko** [comment]
There are no plans to add it, as in shipping it with deadbeef standard plugins, but it exists here https://github.com/cboxdoerfer/ddb_waveform_seekbar

**Comment by s0nspark** [comment]
Awesome - thanks for the link :)

On Tue, Mar 21, 2017 at 10:09 AM, Alexey Yakovenko <notifications@github.com
