### ISSUE TITLE
Собрался, но не запускается

### ISSUE THREAD

**Issue by Alek-dr** [Alexey-Yakovenko/deadbeef#1735]
Все успешно собралось, но не запускается. Появляется иконка, мигает и исчезает.
Ubuntu 16.04 LTS

**Comment by Alexey-Yakovenko** [comment]
Я не оказываю помощь в сборке программы из исходноков. Вся необходимая документация предоставлена. Если не можете собрать -- пожалуйста, не теряйте свое и чужое время, и пользуйтесь готовыми сборками.
