### ISSUE TITLE
Deadbeef IPC documentation

### ISSUE THREAD

**Issue by slashbeast** [Alexey-Yakovenko/deadbeef#1736]
Hi,

I'd like to request some information on the ~/.config/deadbeef/socket. I'd like to know how can I operate over it. For instance, the feature I miss from deadbeef is to copy currently playing file to another playlist, that should be rather simple to script, if I can get the file path from the socket, and then add it to a playlist of choice.

**Comment by Alexey-Yakovenko** [comment]
The socket is used to pass commands that you enter on command line to an already running instance of the player. It can't really do anything else, than what's possible via cmdline options. And the format is internal, undocumented, and subject to change. It's not supposed to be used by anything else.
