### ISSUE TITLE
My radios.pls file does not work anymore

### ISSUE THREAD

**Issue by wdlkmpx** [Alexey-Yakovenko/deadbeef#1737]
It displays the radio stations in the list, but does not play any of them.

I have a radios.pls file I open every once in a while and select one
but lately i noticed that deadbeef does not play it anymore

I'm using the latest i686 portable static release..

This is the file

	[playlist]
	File1=http://s5.voscast.com:7736
	Title1=Free Talk Live 64k Broadband
	Length1=-1
	File2=http://fmt01.egihosting.com:21700/;stream/1
	Title2=LA Talk Radio Channel 1 Live
	Length2=-1
	File3=http://fmt01.egihosting.com:21702/;stream/1 
	Title3=LA Talk Radio Channel 2 Live
	Length3=-1
	File4=http://173.192.207.51:8042/stream
	Title4=TalkZone.com
	Length4=-1
	File5=http://77.92.76.190:9165
	Title5=Crime & Suspense Channel - ROK C Radio - OTR - Old Time Radio
	Length5=-1
	File6=http://64.27.3.104:3121/
	Title6=Rense Radio Network
	Length6=-1
	File7=http://s3.voscast.com:7204/
	Title7=http://www.k-talk.com
	Length7=-1
	NumberOfEntries=7
	Version=2

After I close deadbeef, these messages are printed

	WARNING: playitem 0x92cef60 http://s5.voscast.com:7736((null)) has refc=3 at delete time
	WARNING: playitem 0x92ce990 http://fmt01.egihosting.com:21700/;stream/1((null)) has refc=2 at delete time
	WARNING: playitem 0x92cece0 http://77.92.76.190:9165((null)) has refc=3 at delete time
	WARNING: playitem 0x92ceab0 http://fmt01.egihosting.com:21702/;stream/1 ((null)) has refc=2 at delete time
	WARNING: playitem 0x92cee10 http://64.27.3.104:3121/((null)) has refc=3 at delete time
	WARNING: playitem 0x92cf770 http://s3.voscast.com:7204/((null)) has refc=2 at delete time

I'm using a distro based on Debian Stretch, you may close this issue
if it's actually my fault or the distro's fault...

**Comment by Alexey-Yakovenko** [comment]
> I'm using the latest i686 portable static release..

Does that mean 0.7.2, or a build from git master?

**Comment by wdlkmpx** [comment]
Thanks that fixed the issue. 

I download and install from: https://sourceforge.net/projects/deadbeef/files/travis/linux/master
