### ISSUE TITLE
gtkui: Playlist does not redraw on manual track changes

### ISSUE THREAD

**Issue by saivert** [Alexey-Yakovenko/deadbeef#1738]
Like when double clicking in the playlist or pressing return after changing selection with keyboard.
The previously playing track remains bolded and with playbutton symbol in the now playing columns.

Other track change events like when pressing next or previous track redraws as expected.

**Comment by Alexey-Yakovenko** [comment]
Thanks for the report. I'm aware about this issue, and fix it when I get to it, hopefully soon.
