### ISSUE TITLE
Playlist browser plays selected playlist on pressing Space key, no way to turn it off

### ISSUE THREAD

**Issue by Kzer-Za** [Alexey-Yakovenko/deadbeef#1739]
Сейчас это действие невозможно переопределить в горячих клавишах, из-за этого оно конфликтует с "Toggle Pasue". Пробел работает как пауза только если фокус в плейлисте. Если фокус в "Playlist browser", то пробел запускает проигрывание плейлиста с самого начала. Сказать что это неудобно - это ничего не сказать. Если в плейлисте несколько десятков записей, то попытка поставить на паузу может обернуться тем, что придется долго искать, где остановился. С песнями это еще ничего, а если ты слушал аудиоуроки по какому-нибудь языку? Они обычно имеют названия вида "Урок 1, Урок 2, ..." и их может быть несколько десятков.

Из той же оперы - хорошо бы дать возможность определить действие, запускаемое по двойному клику на названии плейлиста в "Playlist browser". Тоже иногда бывает, что, задумавшись, кликаешь по названию два раза, и это запускает проигрывание плейлиста с начала. Но это бывает редко, поэтому я бы определил это как незначительное улучшение, а вот с пробелом - это, на мой взгляд, просто-таки критично.

**Comment by Alexey-Yakovenko** [comment]
хмм.. разве в deadbeef есть предустановленное действие на пробеле?

**Comment by Kzer-Za** [comment]
Ну, я "играть плейлист" точно на пробел не назначал, наоборот ищу возможность переназначить это действие, но в списке доступных действий для горячих клавиш его нет. Оно активно только, когда фокус - в "Playlist browser". Т.е. если фокус в плейлисте, то по пробелу запускается "Toggle Pasue". А когда фокус в "Playlist browser" - начинает проигрываться выбранный плейлист с самого начала. Так что если ты, не останавливая трек переключался между плейлистами, а потом нажал пробел, то, если фокус был в браузере плейлстов, теряется позиция, потому что плейлист начинает проигрываться сначала.

**Comment by Alexey-Yakovenko** [comment]
ок.. это странное поведение. я проверю.

**Comment by Alexey-Yakovenko** [comment]
Обработка пробела в playlist browser -- это фича GTK, и ее нельзя отключить (стандартный список, стандартные сочетания клавиш).

Если вы нажимаете пробел в списке плейлистов -- вы просто активируете выбранный плейлист. То же самое что двойной клик по плейлисту.

Обработка пробела в плейлисте для toggle pause -- похоже, это ваши персональные настройки.

По умолчанию deadbeef этого не делает.

Причина этого как раз в том, что пробел очень часто используется самим GTK для многих вещей, и вызывает проблемы такого характера как вы описали. Остается вместо пробела использовать другие сочетания клавиш.
