### ISSUE TITLE
Incorrect playback of some IT modules

### ISSUE THREAD

**Issue by nick758** [Alexey-Yakovenko/deadbeef#1743]
Sound of playback of some Impulse Tracker's modules by DeaDBeeF is quite different from sound which produced by XMP (Linux) or XMPlay (Windows).
It can be heard in a few modules from this archive: https://files.scene.org/view/music/groups/sands/toysongs3.zip

I've checked following modules:
sands-slow_scrabble.it
sands-underwater_ambient.it

I'm not sure about others.

**Comment by Alexey-Yakovenko** [comment]
I listened to both files in deadbeef and XMP, and could not hear any difference.
Please be more specific, what exactly is different.

Either way, it's unlikely that I'll be fixing internals of DUMB library, which is used for IT playback in deadbeef. You might want to reproduce the issue with dumb directly:

```
dumbout -o - filename | aplay -f cd -t raw
```

and if the issue persists, report it upstream.
