### ISSUE TITLE
Ability to Add Space Between Albums in Group Mode

### ISSUE THREAD

**Issue by jadenPete** [Alexey-Yakovenko/deadbeef#1745]
I wish there could be an option to add space (customizable in pixels) between albums in the "Group By" mode.

**Comment by saivert** [comment]
I'm working on this feature now and would like to clarify what is meant by albums? Do you mean spacing between groups in general? Album art already adds a bit of space for albums with few tracks (less than 4).
It should be an easy fix to add space below groups (the last track in the group).

**Comment by jadenPete** [comment]
Yes please, between groups.
