### ISSUE TITLE
Ability To Change Color, Font Size of Album Titles in Group Mode

### ISSUE THREAD

**Issue by jadenPete** [Alexey-Yakovenko/deadbeef#1746]
Maybe there could be an ability to change the color and font sizes of the album names in the "Group By" mode.

**Comment by Alexey-Yakovenko** [comment]
@jadenPete isn't that already possible through some settings in the preferences?

**Comment by Alexey-Yakovenko** [comment]
So if you want to change just the size of album title in group title, but keep the other part of group title in it's original font -- that's not possible. The whole group title is configurable.

**Comment by jadenPete** [comment]
I'm talking about the whole thing. Where can I find that in the preferences?

**Comment by jadenPete** [comment]
Nevermind, I found it. Thanks.
