### ISSUE TITLE
Double clicking tracks sometimes stops playback

### ISSUE THREAD

**Issue by orbea** [Alexey-Yakovenko/deadbeef#1749]
OS: `Slackware64-current`
`deadbeef-2017.04.15_0a4dcf51_master-x86_64-1_git`

When double clicking a song in one of my playlists while another song is already playing instead of starting that song sometimes it will stop playback instead. This doesn't happen every time and may need to click several different songs in quick succession to reproduce.

I bisected the issue with git and found it started in the following commit.
```
f8e93ac518c1ad72b9f8d02d7b1c97b6e24f0276 is the first bad commit
commit f8e93ac518c1ad72b9f8d02d7b1c97b6e24f0276
Author: Alexey Yakovenko <wakeroid@gmail.com>
Date:   Thu Apr 13 12:26:03 2017 +0200

    streamer: cleanup play_index

:100644 100644 92b626c2da14bc60f55f8e4489b5bbe151da860f 8fe1d0d2f72d9f3f7e71b1de15ba5ff7182a237d M	streamer.c
```
f8e93ac518c1ad72b9f8d02d7b1c97b6e24f0276

I then built the parent commit (a77e7ecd2fd68883a81f4c4ed32df3e093ec7da4) and confirmed the issue was not present.

**Comment by Alexey-Yakovenko** [comment]
I could not reproduce this issue. Maybe I fixed it while fixing something else. Please try the latest build.

Let me know if you're still having the issue.

**Comment by orbea** [comment]
I tried the latest commit and was able to still reproduce it, but not nearly as often.

So I then recreated my rather old configuration and the issue seems to have vanished. Potentially it was because the playlists I had were very large and old? I'll let you know if it comes back. Thanks for your time.

**Comment by orbea** [comment]
@Alexey-Yakovenko I have been experiencing this again, I think it might be connected to larger playlists. When you have a chance can you try reproducing it with a much large playlist? Maybe dump a few large discographies into one playlist. My current one has 1008 tracks and 2 days playtime while it occurs occasionally. My previous playlist where this occurred often was much larger.

**Comment by orbea** [comment]
I have not experienced this in months, enough that I forgot about this issue even when my current playlist is 4 times as large as it was in April (4254 tracks). I'll assume this has since been fixed somehow. I'm going to close this issue until it can be reproduced again.
