### ISSUE TITLE
gtk log viewer complains about GTK3/GTK2.

### ISSUE THREAD

**Issue by orbea** [Alexey-Yakovenko/deadbeef#1750]
OS: `Slackware64-current`
`deadbeef-2017.04.20_bdc76c49_master-x86_64-1_git`

After updating to the latest commit I found that every time deadbeef starts I am greeted with a gtk log with the following.
```
plugin Converter GTK3 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK3 failed to connect to dependencies, deactivated.
plugin Shellexec GTK3 UI failed to connect to dependencies, deactivated.
```
If I change to gtk3 in the preferences it then complains about gtk2 instead (I far prefer gtk2). Is there any way to have not complain every time deadbeef opens? :)

**Comment by Alexey-Yakovenko** [comment]
This is normal, and has been like this for very long time. The messages are for diagnostics, and can be safely ignored.

**Comment by orbea** [comment]
Yea, I understood that much, what is new though is the log open every time deadbeef opens regardless if `Log` is enabled under `view`. Can this be disabled? Its kind of annoying to have to close an extra window every time deadbeef opens

**Comment by Alexey-Yakovenko** [comment]
oh.. yeah, ok. I misunderstood the problem, and thought you're talking about console output.
Then it needs fixing.

**Comment by orbea** [comment]
Works for me too, thanks!
