### ISSUE TITLE
status bar selected playback time is not configurable

### ISSUE THREAD

**Issue by orbea** [Alexey-Yakovenko/deadbeef#1753]
Is it possible to edit the contents of the status bar?  I guess somewhat recently more information has been added to the status bar which is fine, but the problem is that its now too long for the width of my monitor and I can no longer see some useful information.

I would think the best way to solve this would be to allow to edit the contents of the status bar, but I can't seem to find a way with either the preferences or the design mode. Is this supported? If not can it be? :)

**Comment by Alexey-Yakovenko** [comment]
> the problem is that its now too long for the width of my monitor and I can no longer see some useful information.

It is not yet possible to edit status bar.

The additional information in the status bar was supposed to be optional and disabled by default, but I forgot to enforce this when going through the pull request.

**Comment by orbea** [comment]
Thanks again!
