### ISSUE TITLE
Add an additional Sort Key playlist column parameter, for when display TF is not sufficient

### ISSUE THREAD

**Issue by Bfgeshka** [Alexey-Yakovenko/deadbeef#1758]
Current sorting by %filesize_natural% mixes different units (MB, KB etc) together and is more confusing rather than helping.

**Comment by Alexey-Yakovenko** [comment]
Can you be more precise about this problem? The usual 3Q:

* What are you doing?
* What is the expectation?
* What is the reality?

**Comment by Alexey-Yakovenko** [comment]
I think I figured (guessed) the meaning of your question.. You're trying to sort a playlist by a column, which uses `%filesize_natural%`, but expect it to be sorted by `%filesize%`.

However, that is not quite simple to implement. You should instead use Sort By -> Custom, and then type %filesize%.

One generic solution to this problem would be to specify the Sort Key separately for each column.

**Comment by saivert** [comment]
I'm working on this feature now and want to know if it is acceptable to just add a new text field for Sort format in the Add/Edit column dialog.

**Comment by Alexey-Yakovenko** [comment]
I don't know if that's enough or not, that's just one of the ideas how to solve that.

So I guess it breaks down into 2 things:

1. How to tell the UI what to use as a sort key
2. How to tell sort routine that something is a number

Right now, the first is the same as displayed value, and the second is hardcoded.

**Comment by saivert** [comment]
This feature is now implemented.
If you build from git you can try it now.

**Comment by Alexey-Yakovenko** [comment]
Closed by https://github.com/Alexey-Yakovenko/deadbeef/commit/43a3019ba6f423b59872bfc0a42ac0bcc9270470
