### ISSUE TITLE
deadbeef refuses to add .opus files

### ISSUE THREAD

**Issue by Bfgeshka** [Alexey-Yakovenko/deadbeef#1779]
If file has extension _.opus_ it won't be added to playlist. Meanwhile, same file but renamed with extension _.ogg_ would be added and played just fine.

**Comment by Alexey-Yakovenko** [comment]
That can't be true. FFMPEG plugin has "opus" extension in the list, and that was the case in 0.7.2 too. In any case, if it's not there -- you can just add it, in the plugin settings.

**Comment by Bfgeshka** [comment]
File extension is listed in ffmpeg plugin setting.

In case if I'm adding .opys file there're errors in log:

`plt_load: failed to open file:///`

**Comment by Alexey-Yakovenko** [comment]
Are you running 0.7.2 or trunk?

**Comment by Bfgeshka** [comment]
Built it just now.

**Comment by Alexey-Yakovenko** [comment]
I can't reproduce that. The file with .opus extension gets added without problems. Local trunk build, opus via ffmpeg.

![image](https://cloud.githubusercontent.com/assets/1895698/26107358/49312bac-3a49-11e7-8a25-ef20793e9c35.png)

**Comment by Bfgeshka** [comment]
Found out: files cannot be added, if in ffmpeg plugin enabled option "Use all extensions supported by ffmpeg". Works fine after disabling.

**Comment by Alexey-Yakovenko** [comment]
OK, that's actually a known issue, and this is why this option is OFF by default. I should probably make it more visible, that enabling this option may cause problems. The result varies depending on ffmpeg version/build options, and some builds don't send the correct list of supported file extensions.

**Comment by cipricus** [comment]
I still have this problem in 1.8.2, no matter if "Use all extensions supported by ffmpeg" is activated, with or without "opus" in the list, or deactivated.

Linux Mint 19.2
ffmpeg version 4.2.1

**Comment by Alexey-Yakovenko** [comment]
@cipricus deadbeef now has full native opus support, and doen't require ffmpeg for that.
Although you're running a 3rd party build of an outdated version, which I can't provide any support for - I recommend using the official build of the most recent version (1.8.4), and see if you still have the issue.

**Comment by cipricus** [comment]
@Alexey-Yakovenko - sorry, I have just installed 1.8.4, same thing.

**Comment by Alexey-Yakovenko** [comment]
Does the build that you installed includes opus plugin?

**Comment by cipricus** [comment]
@Alexey-Yakovenko I have installed from the deb "DeaDBeeF 1.8.4 universal deb package amd64" https://sourceforge.net/projects/deadbeef/files/travis/linux/1.8.4/deadbeef-static_1.8.4-1_amd64.deb/download

**Comment by cipricus** [comment]
> Does the build that you installed includes opus plugin?

How can I tell that for the 1.8.4 installed as said above? Normally opus should be played by default in that version.

That's the error message:

starting deadbeef 1.8.4 [static]
server_start
searching for GUI plugins in /home/cip/.local/lib64/deadbeef
searching for GUI plugins in /home/cip/.local/lib/deadbeef
load_plugin_dir /home/cip/.local/lib/deadbeef: scandir found 6 files
searching for GUI plugins in /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 55 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
found selected GUI plugin: GTK2
loading plugin /opt/deadbeef/lib/deadbeef/ddb_gui_GTK2.so
loading plugins from /home/cip/.local/lib64/deadbeef
loading plugins from /home/cip/.local/lib/deadbeef
load_plugin_dir /home/cip/.local/lib/deadbeef: scandir found 6 files
loading plugin /home/cip/.local/lib/deadbeef/ddb_infobar_gtk2.so
loading plugin /home/cip/.local/lib/deadbeef/ddb_infobar_gtk3.so
loading plugin /home/cip/.local/lib/deadbeef/ddb_misc_filebrowser_GTK2.so
loading plugin /home/cip/.local/lib/deadbeef/ddb_misc_filebrowser_GTK3.so
loading plugins from /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 55 files
loading plugin /opt/deadbeef/lib/deadbeef/aac.so
loading plugin /opt/deadbeef/lib/deadbeef/adplug.so
loading plugin /opt/deadbeef/lib/deadbeef/alac.so
loading plugin /opt/deadbeef/lib/deadbeef/alsa.so
loading plugin /opt/deadbeef/lib/deadbeef/artwork.so
loading plugin /opt/deadbeef/lib/deadbeef/cdda.so
loading plugin /opt/deadbeef/lib/deadbeef/converter.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/dca.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_dumb.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_mono2stereo.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_shn.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_soundtouch.so
loading plugin /opt/deadbeef/lib/deadbeef/dsp_libsrc.so
loading plugin /opt/deadbeef/lib/deadbeef/ffap.so
loading plugin /opt/deadbeef/lib/deadbeef/ffmpeg.so
loading plugin /opt/deadbeef/lib/deadbeef/flac.so
loading plugin /opt/deadbeef/lib/deadbeef/gme.so
loading plugin /opt/deadbeef/lib/deadbeef/hotkeys.so
loading plugin /opt/deadbeef/lib/deadbeef/in_sc68.so
loading plugin /opt/deadbeef/lib/deadbeef/lastfm.so
loading plugin /opt/deadbeef/lib/deadbeef/m3u.so
loading plugin /opt/deadbeef/lib/deadbeef/mms.so
loading plugin /opt/deadbeef/lib/deadbeef/mp3.so
loading plugin /opt/deadbeef/lib/deadbeef/musepack.so
loading plugin /opt/deadbeef/lib/deadbeef/notify.so
loading plugin /opt/deadbeef/lib/deadbeef/nullout.so
loading plugin /opt/deadbeef/lib/deadbeef/opus.so
loading plugin /opt/deadbeef/lib/deadbeef/oss.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/psf.so
loading plugin /opt/deadbeef/lib/deadbeef/pulse.so
loading plugin /opt/deadbeef/lib/deadbeef/rg_scanner.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexec.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/sid.so
loading plugin /opt/deadbeef/lib/deadbeef/sndfile.so
loading plugin /opt/deadbeef/lib/deadbeef/supereq.so
loading plugin /opt/deadbeef/lib/deadbeef/tta.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_curl.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_zip.so
loading plugin /opt/deadbeef/lib/deadbeef/vorbis.so
loading plugin /opt/deadbeef/lib/deadbeef/vtx.so
loading plugin /opt/deadbeef/lib/deadbeef/wavpack.so
loading plugin /opt/deadbeef/lib/deadbeef/wildmidi.so
loading plugin /opt/deadbeef/lib/deadbeef/wma.so
starting plugin GTK2 user interface
starting plugin Infobar
starting plugin Infobar
starting plugin File Browser
starting plugin File Browser
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin ALSA output plugin
starting plugin Album Artwork
starting plugin Audio CD player
starting plugin Converter
starting plugin Converter GTK2 UI
starting plugin Converter GTK3 UI
starting plugin dts decoder
starting plugin DUMB module player
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Soundtouch
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Game-Music-Emu player
starting plugin Hotkey manager
starting plugin SC68 player (Atari ST SNDH YM2149)
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin mms vfs
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin OSD Notify
starting plugin Null output plugin
starting plugin Opus player
starting plugin OSS output plugin
starting plugin Playlist browser GTK2
starting plugin Playlist browser GTK3
starting plugin PSF player using Audio Overload SDK
starting plugin PulseAudio output plugin
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin Shellexec GTK2 UI
starting plugin Shellexec GTK3 UI
starting plugin SID player
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin VTX player
starting plugin WavPack decoder
starting plugin WildMidi player
starting plugin WMA player
starting plugin stdio vfs
starting plugin FFMPEG audio player
selected output plugin: ALSA output plugin
plugin Infobar failed to connect to dependencies, deactivated.
plugin File Browser failed to connect to dependencies, deactivated.
plugin Converter GTK3 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK3 failed to connect to dependencies, deactivated.
plugin Shellexec GTK3 UI failed to connect to dependencies, deactivated.
resume: track -1 pos -1.000000 playlist 5
ERROR: could not load: /home/cip/Music/Classical/Bach/J.S. Bach_ Complete Partitas_Yuan_Sheng.opus

**Comment by cipricus** [comment]
@Alexey-Yakovenko  While that file is played in Audacious and Clementine, could something be wrong with it? Or with my ffmpeg?

I see that `ffmpeg path/to/my_opus` gives this:

`Output #0, opus, to '/home/cip/Music/Classical/Bach/J.S. Bach_ Complete Partitas_Yuan_Sheng.opus':
Output file #0 does not contain any stream`

**Comment by Alexey-Yakovenko** [comment]
what are the contents of that file? have you tried to identify it using `file` command?
Perhaps it has opus extension, but is really some other format?

**Comment by cipricus** [comment]
> what are the contents of that file? have you tried to identify it using `file` command?
> Perhaps it has opus extension, but is really some other format?

As I said, it is a music file that can be played by Clementine and Audacious. In fact I have several files like that, other players can play them (also vlc, mpv, smplayer) except deadbeef and qmmp

**Comment by cipricus** [comment]
I think I've got it. **There'a a problem with those opus files, they are a bit special**: sort of webm audio containing an opus audio stream that `ffmpeg` doesn't see but which is seen by `file` command as `WebM`.   Mediainfo shows that too.

![image](https://user-images.githubusercontent.com/3447868/98361202-6a0f4400-202b-11eb-90fb-7e6433dc155e.png)

**I have other opus files that can be played by Deadbeef**, and they are different. `files` says `Ogg data, Opus audio`, while Mediainfo shows:

![image](https://user-images.githubusercontent.com/3447868/98361722-603a1080-202c-11eb-82ea-d4d28be38c7a.png)

**Comment by Alexey-Yakovenko** [comment]
Deadbeef with default settings is not using ffmpeg for playing back opus files
Also Deadbeef doesn't support webm

Now, how can you potentially get this file to play..
First you need to get ffmpeg to recognize the file.
Perhaps, if you rename the file into .webm -- ffmpeg might be able to demux it.
I don't know. But you could try.
If that works -- you can recompile Deadbeef with system ffmpeg, and configure ffmpeg plugin in Deadbeef to open webm files.

Disclaimer: I've no idea whether ffmpeg can handle opus in webm container at all.
What I know is that Deadbeef itself only supports opus in Ogg container.

**Comment by cipricus** [comment]
@Alexey-Yakovenko - Thank you. This doesn't look to me anymore as a problem with db.

I understand now that the opus in webm container is a rare and odd format, even improper. It was created in this case by downloading from youtube with a Firefox addon an "audio only" file that should have been a normal opus but it's not. The solution is to re-download in a different way or format, or to use ffmpeg to process the "bad" opus by giving it an ogg container. 

All the best!

**Comment by CouponCodeSwap** [comment]
This type of opus file is probably becoming more prevalent as more people are using youtube-dl to download audio files. I got halfway there:

Edit > Preferences > Plugins > FFMPEG audio player > Configure

add:

`opus;webm;`

to File Extensions and hit OK.

It is now possible to add the opus files but they will not play. Audacious, Clementine, Dolphin preview, VLC… are all able to play the same opus files without any additional configuration.

Arch Linux | DeaDBeeF-1.8.4

**Comment by Alexey-Yakovenko** [comment]
As was stated before, deadbeef doesn't support webm.
Please feel free to comment or like the webm feature request #1511
