### ISSUE TITLE
Copy playlist to folder (USB Stick)

### ISSUE THREAD

**Issue by Smirftsch** [Alexey-Yakovenko/deadbeef#1782]
is there a way to copy the files of a playlist to a folder? Pretty much like "convert" does just without converting?
Would be nice to have for preparing an USB stick for my car :)

PS: Very cool work you do here, great player!

**Comment by Bfgeshka** [comment]
You can use custom shell commands

**Comment by Soukyuu** [comment]
Am I missing something, or why can't you just
- select the files of a playlist
- press ctrl+c
- navigate to folder
- press ctrl+v

Another option when you want to rename the files (for example sort them by playlist index) is to 
- select the files
- convert
- set your output pattern (for example %list_index%. %title%)
- set "copy if the format is not changing" option
- set format to your source format
- click convert

**Comment by Alexey-Yakovenko** [comment]
@Soukyuu I think that's cause copy&paste was added in git, but there was no new release yet. Most users prefer to use stable release, which is about 2 years old or more.

**Comment by Alexey-Yakovenko** [comment]
@Smirftsch I personally use converter for that.. It has "File copy" preset.
But that's also not available in 0.7.2. If you don't mind using unstable version -- that's possible in a number of ways.
