### ISSUE TITLE
volume control from command line

### ISSUE THREAD

**Issue by tianna1121** [Alexey-Yakovenko/deadbeef#1785]
### Expected behavior
I want to control the volume from command line, any suggestions? Thanks

**Comment by oleksiy-unity3d** [comment]
There's no way to send volume control commands to deadbeef via command line.

**Comment by Alexey-Yakovenko** [comment]
There's no way to send volume control commands to deadbeef via command line.

**Comment by tianna1121** [comment]
Then, how can I control the volume without GUI?

**Comment by Alexey-Yakovenko** [comment]
Deadbeef can run without GUI, but you won't get much functionality.

You'd have to control the volume externally, using alsamixer or similar.

**Comment by tianna1121** [comment]
Got it! Thank you. We are now building an AI-enabled HiFi audio player without screen support.

**Comment by saivert** [comment]
As an alternative you can install MPRIS plugin for deadbeef and use dbus from command line to control the volume.
`dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.DeaDBeeF /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Set string:'org.mpris.MediaPlayer2.Player' string:'Volume' variant:double:1`

And to get volume:

`dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.DeaDBeeF /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Volume'`
