### ISSUE TITLE
Last Track Stop 1 Second Before It Ends (4:03 / 4:04)

### ISSUE THREAD

**Issue by shoober420** [Alexey-Yakovenko/deadbeef#1787]
### Expected behavior
For it to finish the whole song

### Actual behavior
Stop at the last second of the song

### Steps to reproduce the behavior
The last song of a playlist will stop at the last second of the track and not finish. Just play the last song of a playlist and skip almost the end of it.

I'm using git builds on Arch Linux. This build is of the lastest commit from May 23rd.

This is an error thats generated when closing Deadbeef at the last track when its stuck on the last second.

WARNING: playitem 0x7fc8a00057b0 /run/media/abc/FED2F471D2F4300F/Henry Cow - 5 Albums Mini LP SHM-CD (Belle Antique Japan 2015)/1973 Leg End (Mini LP SHM-CD
Belle Japan 2015)/Henry Cow - Leg End SHM-CD.flac(13) has refc=5 at delete time

**Comment by Alexey-Yakovenko** [comment]
I cannot reproduce this issue (tried the build from commit 294df3cf90c6a6d1da4d05ac52feb575b98591de on linux and mac).

The warning is unrelated, and can be ignored.

**Comment by shoober420** [comment]
This no longer occurs anymore. Thank you sir
