### ISSUE TITLE
Time in status bar is showed without hours

### ISSUE THREAD

**Issue by TotalCaesar659** [Alexey-Yakovenko/deadbeef#1796]
Time in status bar is showed without hours, only minutes and seconds. Is it normal?
![1](https://cloud.githubusercontent.com/assets/14265316/26602999/fb35654e-458d-11e7-9986-bd52d38c62bc.png)

**Comment by Alexey-Yakovenko** [comment]
according to @saivert this bug is not valid on trunk (i.e. fixed already, but of course not gonna be fixed in 0.7.2 -- you either need to switch to dev builds, or wait for 0.8)

**Comment by TotalCaesar659** [comment]
Yeah, you're right, I'm on 0.7.2. OK, I'll wait.
