### ISSUE TITLE
Bad 0.dbpl when playback DSD file on ARM machines

### ISSUE THREAD

**Issue by tianna1121** [Alexey-Yakovenko/deadbeef#1797]
I can playback DSD files(.dsf, dff) on my x86_x64 Ubuntu desktop(with GUI). However, when I play the same DSD file on my ARM dev boards(without GUI), the deadbeef complains about playlist error. When I cat the 0.dbpl, I notice that the information is not complete, compared with the Ubuntu desktop. Then, I reconfigure & make the FFmpeg and the deadbeef(with --enable-src), nothing changed. I have checked the FFmpeg, it can decode the .dff file on both platforms.

The two 0.dbpl files are attached. Any suggestions? Thank you!
![screenshot from 2017-05-31 07-36-49](https://cloud.githubusercontent.com/assets/729062/26609484/f7d25802-4566-11e7-93d4-37c6eba4c377.png)
![screenshot from 2017-05-31 07-35-27](https://cloud.githubusercontent.com/assets/729062/26609485/f7e00e84-4566-11e7-9001-d8ac513671e8.png)

**Comment by Alexey-Yakovenko** [comment]
> the deadbeef complains about playlist error. 

which error?

**Comment by Alexey-Yakovenko** [comment]
Playlist on 2nd screenshot is empty (the data represents magic cookie, version and 0 items).

**Comment by tianna1121** [comment]
Yes, the 2nd screenshot is empty. I have no idea why this happens (ARM board+deadbeef) . Other audio files work fine.

**Comment by Alexey-Yakovenko** [comment]
@tianna1121 when you created this issue, there was a template that you were supposed to fill out.

It's especially important to write the reproduction steps -- i.e. what commands or UI actions did you perform to get the result which is a problem.

It's also expected that you would provide any error messages that you are getting.

There's obviously not enough information for me to be able to find out what's wrong on your side.

If this information can't be provided, the issue will be closed as Invalid.

**Comment by tianna1121** [comment]
### Expected behavior
Playback DSD files(.dsf for exsample) on ARM-Llinux environment as expected(like Ubuntu desktop).
### Actual behavior
Do not play DSD files at all(no sound). And the playlist are empty.
### Steps to reproduce the behavior
1) configure and make ffmpeg natively on ARM board(with all Codec buildin), using arm-linux-gcc-4.8.
2) configure the deadbeef with --enable-src, make, make install.
3) playback .dsf file by command line: deadbeef xxxx.dsf
4) the outputs are list blow:
(I will paste the output 10 hours later... It is midnight now, Sorry)

**Comment by Alexey-Yakovenko** [comment]
Please make sure to attach the FULL output of deadbeef. Including when it's loading the plugins.
Thanks.

**Comment by Alexey-Yakovenko** [comment]
My only guess now is that ffmpeg plugin either is not built at all, or can't find the libraries at runtime.

**Comment by tianna1121** [comment]
Hi @Alexey-Yakovenko , here is the full output. Thank you!
root@easyMusic:/m# deadbeef haikuo.dff 
starting deadbeef 0.7.2
server_start
searching for GUI plugins in /root/.local/lib32/deadbeef
searching for GUI plugins in /root/.local/lib/deadbeef
searching for GUI plugins in /usr/local/lib/deadbeef
load_plugin_dir /usr/local/lib/deadbeef: scandir found 65 files
load gui plugin
selected GUI plugin not found or failed to load, trying to find another GUI plugin
loading plugins from /root/.local/lib32/deadbeef
loading plugins from /root/.local/lib/deadbeef
loading plugins from /usr/local/lib/deadbeef
load_plugin_dir /usr/local/lib/deadbeef: scandir found 65 files
loading plugin /usr/local/lib/deadbeef/adplug.so
loading plugin /usr/local/lib/deadbeef/alac.so
loading plugin /usr/local/lib/deadbeef/alsa.so
loading plugin /usr/local/lib/deadbeef/dca.so
loading plugin /usr/local/lib/deadbeef/ddb_ao.so
loading plugin /usr/local/lib/deadbeef/ddb_dumb.so
loading plugin /usr/local/lib/deadbeef/ddb_mono2stereo.so
loading plugin /usr/local/lib/deadbeef/ddb_shn.so
loading plugin /usr/local/lib/deadbeef/dsp_libsrc.so
loading plugin /usr/local/lib/deadbeef/ffap.so
loading plugin /usr/local/lib/deadbeef/flac.so
loading plugin /usr/local/lib/deadbeef/gme.so
loading plugin /usr/local/lib/deadbeef/hotkeys.so
loading plugin /usr/local/lib/deadbeef/in_sc68.so
loading plugin /usr/local/lib/deadbeef/m3u.so
loading plugin /usr/local/lib/deadbeef/mms.so
loading plugin /usr/local/lib/deadbeef/mp3.so
loading plugin /usr/local/lib/deadbeef/musepack.so
loading plugin /usr/local/lib/deadbeef/notify.so
loading plugin /usr/local/lib/deadbeef/nullout.so
loading plugin /usr/local/lib/deadbeef/oss.so
loading plugin /usr/local/lib/deadbeef/pulse.so
loading plugin /usr/local/lib/deadbeef/shellexec.so
loading plugin /usr/local/lib/deadbeef/sid.so
loading plugin /usr/local/lib/deadbeef/sndfile.so
loading plugin /usr/local/lib/deadbeef/supereq.so
loading plugin /usr/local/lib/deadbeef/tta.so
loading plugin /usr/local/lib/deadbeef/vorbis.so
loading plugin /usr/local/lib/deadbeef/vtx.so
loading plugin /usr/local/lib/deadbeef/wildmidi.so
loading plugin /usr/local/lib/deadbeef/wma.so
hotkeys: could not open display
plugin Hotkey manager failed to start, deactivated.
selected output plugin: ALSA output plugin
INFO: loading playlist Default
INFO: from file /root/.config/deadbeef/playlists/0.dbpl
playlist load fail (/m/haikuo.dff)!
failed to add file or folder /m/haikuo.dff
gui plugin has quit; waiting for mainloop thread to finish

**Comment by tianna1121** [comment]
@Alexey-Yakovenko I found the problem, you can close this issue. Thank you again!
