### ISSUE TITLE
GUI unnatural jumping when Page Up

### ISSUE THREAD

**Issue by Hulk-Hogan** [Alexey-Yakovenko/deadbeef#1800]
### Expected behavior
The cursor should just jump on the first position.
### Actual behavior
The whole playlist blinks and switches over to the end of playlist for a moment, then it returns to the beginning at actual first position, where it should be.
### Steps to reproduce the behavior
In a playlist, have cursor at position 2 - 10 (including) and press Page Up.

**Comment by Alexey-Yakovenko** [comment]
which OS, and which deadbeef version?

**Comment by Hulk-Hogan** [comment]
OS: Debian Jessie (8)
IDE: Gnome 3.14
Deadbeef version: 0.7.2

**Comment by Alexey-Yakovenko** [comment]
Can you check if the problem is already fixed in this build? https://sourceforge.net/projects/deadbeef/files/travis/linux/master/deadbeef-static_devel-1_x86_64.tar.bz2/download

**Comment by Hulk-Hogan** [comment]
Yes, the problem is fixed.

**Comment by Alexey-Yakovenko** [comment]
Then, I guess, you need to wait for the next release, or use development builds (like the one linked above).
