### ISSUE TITLE
How can I use multiCore to playback

### ISSUE THREAD

**Issue by Ray5wang** [Alexey-Yakovenko/deadbeef#1805]
### What's going on? Describe the problem in as much detail as possible.
I have a 4 core CPU.But when I play DFF128.dff ,I use top to see that deadbeef only use one core to work.How can I use other three core to decode the music?

the information of top when I play :
top - 03:49:37 up  3:51,  1 user,  load average: 1.63, 1.45, 1.36
Tasks:  87 total,   1 running,  86 sleeping,   0 stopped,   0 zombie
**%Cpu(s): 23.2** us,  2.1 sy,  0.0 ni, 74.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:    524288 total,   520164 used,     4124 free,    30500 buffers
KiB Swap:        0 total,        0 used,        0 free.   410880 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
 **1426 root      20   0   71232   9836   4220 S 100.8  1.9   0:56.35 deadbeef-m+** 
 1431 root      20   0    3772   1268    912 R   0.3  0.2   0:00.23 top         

### Information about the software:
loading plugin /usr/local/lib/deadbeef/wma.so
hotkeys: could not open display
plugin Hotkey manager failed to start, deactivated.
selected output plugin[13567.490526] sndpcm_startup,l:1688,pa_vol:62
: ALSA output plugin
INFO: loading playlist Default
INFO: from[13567.501842] sndpcm_startup,l:1688,pa_vol:62
 file /root/.config/deadbeef/playlists/0.dbpl
[iff @ 0x147070] Estimating duration from bitrate, this may be inaccurate
gui plugin has quit; waiting for mainloop thread to finish
[iff @ 0xb3400560] Estimating duration from bitrate, this may be inaccurate
cannot set parameters (Invalid argument)
Deadbeef version:deadbeef-0.7.2  
OS:ubuntu-14.04arm-hf

**Comment by Alexey-Yakovenko** [comment]
deadbeef does DSF/DFF decoding using FFMPEG, and if you want FFMPEG to decode DSF using multiple cores -- you need to contact FFMPEG developers.

**Comment by Ray5wang** [comment]
Thanks for you help !
