### ISSUE TITLE
Track gets removed from playqueue if added multiple times

### ISSUE THREAD

**Issue by kuba160** [Alexey-Yakovenko/deadbeef#1811]
Steps to reproduce the problem:
1. Add a track to playqueue multiple times. It will be shown like (1,2,3,4)
2. Add another track to playqueue. It will get place 5 in queue (5).
3. When the first track begins the second track gets place 1. (expected to play first song 4 times)

Right after the track begins, it removes all iterations of it from playqueue. It removes all iterations.

**Comment by Alexey-Yakovenko** [comment]
Fixed in 6910b265c32edf4d60e89ed988ee3a54b304fb56
