### ISSUE TITLE
Playing jumps on 2 positions after mouse seeking

### ISSUE THREAD

**Issue by TotalCaesar659** [Alexey-Yakovenko/deadbeef#1815]
### Steps to reproduce the problem
Hi, I've found very strange bug: after mouse seeking on the first track to its beginning and playing til the end, DeadBeef starts to play 3rd track, not next one, as it has to be.
### What's going on? Describe the problem in as much detail as possible.
I had luck to re-create it after very many attempts and to record the video. Please, watch it carefully til the end.
https://yadi.sk/i/vGJwSEc23KDSTv
I don't want to upload it on YouTube cause of copyrights.
### Information about the software:
Deadbeef version: 0.7.2
OS: Lubuntu 16.04.2 x64

**Comment by Alexey-Yakovenko** [comment]
Can you check if the problem is still there in [development build](https://sourceforge.net/projects/deadbeef/files/travis/linux/master/deadbeef-static_devel-1_x86_64.tar.bz2/download)?

**Comment by TotalCaesar659** [comment]
Yeah, the bug is gone, it may be closed, I guess.

**Comment by Alexey-Yakovenko** [comment]
Thanks
