### ISSUE TITLE
Can't convert DSD to FLAC

### ISSUE THREAD

**Issue by gravelld** [Alexey-Yakovenko/deadbeef#1820]
I have added DSF files to DeaDBeeF. When I right click _Convert_, I choose the following settings:

![screenshot_2017-06-23_10-55-23](https://user-images.githubusercontent.com/873704/27476928-7e66dfb6-5802-11e7-87d4-828b8747eb54.png)

When I click _OK_, nothing happens, the dialog is removed, and I'm back in the main DeaDBeeF window again. No FLAC file was created.

If I run on the command line, the output is:
```
[dsf @ 0x7ff9940012f0] Estimating duration from bitrate, this may be inaccurate
converter: will encode using: flac -o "/tmp/ - 07 - Cream - SWLABR (Stereo).flac" -5 --ignore-chunk-sizes -

flac 1.3.1, Copyright (C) 2000-2009  Josh Coalson, 2011-2014  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

INFO: Make sure you know what you're doing when using --ignore-chunk-sizes.
      Improper use can cause flac to encode non-audio data as audio.
-: ERROR: unsupported WAVEFORMATEXTENSIBLE chunk with non-PCM format 3
converter: write error (4096 bytes written out of 16000)
```

I saw this discussion: https://hydrogenaud.io/index.php/topic,56432.0.html , so I tried to add `--channel-map=none` to the `lib/deadbeef/convpreset/FLAC_(compression_level_5).txt` file. This doesn't appear to help.

### Information about the software:

Deadbeef version: 0.7.2
OS: Xubuntu 16.04

**Comment by Alexey-Yakovenko** [comment]
It's completely possible for any encoder to not support some given input data.
Apparently, flac encoder is not very good at telling what part of the format it didn't like..

My guess is that it doesn't like the sample format, so try playing with this one -- i.e convert to say 24 bit.

**Comment by Alexey-Yakovenko** [comment]
are there any news? did you figure out what was wrong?
I'm closing the issue, as there's not much I could do.

But please let me know if you have any suggestions on how to improve this.

**Comment by Lithopsian** [comment]
Isn't 3 = WAVE_FORMAT_IEEE_FLOAT?  The flac encoder cannot accept float input.  There seems to be a similar problem converting from Vorbis to Flac, should you ever want to do such a thing, although the error message is slightly different,

**Comment by mmcc-xx** [comment]
I ran into this same issue. Passthrough didn't work, and 32bit float gave the same error. 32bit int also failed with an error of "ERROR: unsupported bits-per-sample 32". 24bit worked, but the resulting FLAC files were more than twice the size of the source dsf files. 16bit also worked, but the resulting FLAC file was 1.3x larger than the source file. 8bit went through the process of converting, but when playing the resulting, it file contained white noise in addition to the music.
