### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by alxv-su** [Alexey-Yakovenko/deadbeef#1822]
### Steps to reproduce the problem

Try to drag and drop some music files from any file manager to DeaDBeeF playlist.

### What's going on? Describe the problem in as much detail as possible.

Nothing happens, but files should appears in playlist.

### Information about the software:

Deadbeef version: 0.7.2 (from ~~Debian repository~~ [debian-multimedia](http://deb-multimedia.org/))
OS: Debian 9 (Stretch)
DE: Xfce 4.12.3 
File managers: PCManFM 1.2.5-3, Thunar 1.6.11-1

**Comment by Alexey-Yakovenko** [comment]
It is not 100% clear what this means

> Deadbeef version: 0.7.2 (from Debian repository)

because deadbeef was never present in debian repositories.

Could you try running [this build](https://sourceforge.net/projects/deadbeef/files/travis/linux/0.7/deadbeef-static_0.7.2-rc6-1_i686.tar.bz2/download), and see if it solves the problem?

**Comment by alxv-su** [comment]
Sorry, I was wrong.  It from [debian-multimedia](http://deb-multimedia.org/) repository.
Anyway, I have tried running DeaDBeeF from provided link, and it also has this problem.

**Comment by Alexey-Yakovenko** [comment]
Ok, before I jump to installing debian 9 to try this out, we can try one more thing - please try [this build](https://sourceforge.net/projects/deadbeef/files/travis/linux/master/deadbeef-static_devel-1_x86_64.tar.bz2/download).

It's a development build, which includes a change I made some time ago, which affects how drag-n-drop works.

**Comment by alxv-su** [comment]
Drag and drop in this build works.

**Comment by Alexey-Yakovenko** [comment]
ok, this is good to know. then you have the following options:

* use the development build from master branch
* wait for the next release (0.8), which I'm afraid is not soon enough, as there's still quite a bit of work there
* build 0.7.2 from sources, and apply this patch: 8201827d42e2ab37d097ba95cb1295d19f5acb78

**Comment by Alexey-Yakovenko** [comment]
diplicate of #933
