### ISSUE TITLE
Change design of the volumebar

### ISSUE THREAD

**Issue by TotalCaesar659** [Alexey-Yakovenko/deadbeef#1823]
Continuing of https://github.com/Alexey-Yakovenko/deadbeef/issues/1533
It would be good to change the old volumebar
![1](https://user-images.githubusercontent.com/14265316/27519543-07086828-59ff-11e7-9b8b-f90dfb1871b8.png)
to something like this
![2](https://user-images.githubusercontent.com/14265316/27519547-0a5e38f4-59ff-11e7-88dd-66385bf44d34.png)

**Comment by Alexey-Yakovenko** [comment]
Probably would work better with semitones instead of thin lines though.

**Comment by TotalCaesar659** [comment]
Well, it has to be test with many colors. E.g., rectangles may be good for theme with dark background and bright main color (I have a doubt about semitones in this case).
Maybe somebody'll make it, because I've already said about my lack of coding skills. I've already worked hard with the seekbar, so I have to have a rest before a new target.

**Comment by Alexey-Yakovenko** [comment]
Please see the latest build on master, and let me know what you think. It should have better volumebar.

**Comment by TotalCaesar659** [comment]
Well, I think it may be OK for now. If i have any more ideas, I'll let you know.
