### ISSUE TITLE
Possible memory leak.

### ISSUE THREAD

**Issue by JakeSFR** [Alexey-Yakovenko/deadbeef#1824]
I just noticed, while playing SID files, that mem usage keeps growing and isn't freed.
I'm using 0.7.2, but the latest static build (master, x86_64) still has this issue.

To reproduce it quickly:
- load one track and keep pressing Play, over and over again,

\<or\>

- load many tracks and keep pressing Next (or Prev) button.

It seems to happen also with "normal" files (e.g. MP3s), although the increase rate isn't that fast as with SIDs.

Cheers!

**Comment by Alexey-Yakovenko** [comment]
mp3 leaking confirmed too, reopening

**Comment by Alexey-Yakovenko** [comment]
Fixed both now, was a good catch, really appreciate it.

**Comment by JakeSFR** [comment]
Great, thanks for fixing it!
