### ISSUE TITLE
Where exactly do the plugins go? 

### ISSUE THREAD

**Issue by sd12832** [Alexey-Yakovenko/deadbeef#1825]
On the Plugins page of `deadbeef`, it is said that I need to put my plugins in the folder `~/.local/lib/deadbeef/`. However, there are no changes reflected on my media player when I put those specific plugins in. Therefore, I decided to find where the other plugins are installed. I found this to be the folder: `/usr/lib/deadbeef`. However, I still don't get changes to my interface as shown below, though the plugins I'm trying to install are shown on `Plugins` tab of `Preferences`: 

My current `deadbeef` UI
------------------------
[![enter image description here][1]][1]

My `Preferences` tab
--------------------
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/tFeun.png
  [2]: https://i.stack.imgur.com/uqMPH.png

**Comment by Alexey-Yakovenko** [comment]
The plugins can be found in multiple locations.
The `/usr/lib/deadbeef` is system location, and should not be altered.
`~/.local/lib`, `~/.local/lib32` and `~/.local/lib64` are the places where you should put the manually downloaded plugins.

The plugin Waveform Seekbar is installed, and shows up in the list.
Now you need to configure it, to make it appear in the UI.
This is documented on the [plugin's webpage](https://github.com/cboxdoerfer/ddb_waveform_seekbar#usage).

How to use design mode is not very well documented, but it's pretty straight forward when you get a hang of it.

In this mode, you can right-click the UI elements, and delete them, or replace with the other ones.
Add vertical / horizontal splitters in place of the main playlist view, then insert the UI elements which you want.

Let me know if you need any more help with that.

**Comment by sd12832** [comment]
![more doubts](https://user-images.githubusercontent.com/11153119/27540625-72b0ec4a-5a9e-11e7-8808-c8df40b34920.png)
It looks like I only get some of the configuration options with the plugin. I definitely need more help with this

**Comment by Alexey-Yakovenko** [comment]
what kind of help do you need?

**Comment by Alexey-Yakovenko** [comment]
There are 2 different configuration dialogs.

The one you're looking at is a global configuration plugin.

The one you want to see is the configuration of a specific UI element, which you can access when you place the element into the player's UI.

**Comment by sd12832** [comment]
How would you go about placing an element into the Player's UI?

**Comment by Bfgeshka** [comment]
Go to view/design mode and config your ui with new elements.

**Comment by Alexey-Yakovenko** [comment]
I wrote how to do that in https://github.com/Alexey-Yakovenko/deadbeef/issues/1825#issuecomment-311047644

**Comment by sd12832** [comment]
Yeah, got a proper hang of things now! Thanks all!
