### ISSUE TITLE
Resizing changes the window changes the designs that have been set in Design mode

### ISSUE THREAD

**Issue by sd12832** [Alexey-Yakovenko/deadbeef#1826]
### Steps to reproduce the problem

Currently I want to commit to this design below: 

But I when I resize the window as such: 

![prelimsteps3](https://user-images.githubusercontent.com/11153119/27542748-d0654a5a-5aa5-11e7-8a84-b2ac43d92ae0.png)

And maximize it again, I get the window below: 

All my design mode changes seem to have been overridden. 

Also when I choose to get the equalizer up, my designs seem to be overridden once again. Without my equalizer up: 

With the EQ: 

![prelims5](https://user-images.githubusercontent.com/11153119/27542894-3a1ed060-5aa6-11e7-9cdd-c50b726e2ff5.png)

Removing the EQ once again: 

Am I doing something wrong? Should I be committing some sort of changes? 

### Information about the software:

Deadbeef version: Latest
OS: Ubuntu

**Comment by Alexey-Yakovenko** [comment]
I think there was some way to lock the splitters, and make them autoresize proportionally to the main window, but I'm pretty sure you'd have to run the [dev build](https://sourceforge.net/projects/deadbeef/files/travis/linux/master/deadbeef-static_devel-1_x86_64.tar.bz2/download) for this.

P.S. It's enough to keep just 1 github issue open for all of your configuration issues, no need to create a new ticket for every new problem like this.

**Comment by Alexey-Yakovenko** [comment]
> Deadbeef version: Latest

The version you're running is not latest, it's the 0.7.2 which is more than a year old.

Development version has many things added / fixed / improved, but there was no stable release yet.

**Comment by sd12832** [comment]
Sure, I shall leave this as the issue where all my configuration problems end up. Thank you for all your support!

**Comment by Alexey-Yakovenko** [comment]
Please let me know, if you try the dev version and whether it solved your problems or not. Maybe this issue needs another look.

**Comment by sd12832** [comment]
I'm planning on trying the dev version. However, I do not understand how to install it. It's not a conventional tar.bz2 file?

**Comment by Alexey-Yakovenko** [comment]
just unpack and run the file `deadbeef` in the unpacked folder.

**Comment by sd12832** [comment]
So I think it mostly works now. The design mode changes are committed over time when resizing the window and closing it. Perfect! 

However, with the devel version I am facing issues with the audio output. I usually use an audio interface to connect to the speakers I possess. Now the problem lies in the fact the audio output comes from my laptop speakers. How would I route the audio to the speakers through my interface? Are there any details you need to make this possible?

**Comment by Alexey-Yakovenko** [comment]
I'm not aware of any changes that would have caused this.
Try playing with sound output settings in the player though, maybe you'll find something.
