### ISSUE TITLE
Is there a way to get the audio output to stdout?

### ISSUE THREAD

**Issue by ao-il** [Alexey-Yakovenko/deadbeef#1836]
Just started using deadbeef for the first time and I'm loving it. Is there any plugin that can allow output to a pipe for streaming?
Thanks in advance!

**Comment by Alexey-Yakovenko** [comment]
I'm afraid there's no such thing. sorry.

**Comment by ao-il** [comment]
Thanks for the quick response. I can see there is a null output plugin, can I write my own that basically would receive the audio instead of discarding it? Thanks for any further help.

**Comment by Alexey-Yakovenko** [comment]
Yes, you can quite easily write an output plugin which would capture and do whatever.

**Comment by ao-il** [comment]
Good to know that it's easy. Could you be kind and refer me to a guide on how to write such plugin and how to incorporate it. Thanks again.

**Comment by Alexey-Yakovenko** [comment]
No guide, sorry, You can make any existing plugin, modify it to suit your needs, then compile and drop it into ~/.local/lib/deadbeef.

The general plugin development guide is in the WIKI.

**Comment by ao-il** [comment]
Thanks alot. I have browsed through some code (nullout), but don't really know how to modify. I guess it's basically to figure out which function receives the audio buffer and point it to stdout instead of sound device. I'll keep looking.

**Comment by Alexey-Yakovenko** [comment]
You need to copy nullout.c to some new folder, save under "yourplugin.c", and then change it -- i.e. replace all function names with your new plugin prefix, change the strings containing plugin name, etc.

Basically, find and replace "nullout", "null_", etc. to "yourplugin"

Then you can compile like this: `gcc -std=c99 -shared -o yourplugin.so yourplugin.c`

**Comment by Alexey-Yakovenko** [comment]
You're getting the audio data in `pnull_callback`, so basically you can add something like this:

```
if (len > 0) {
    fwrite (stream, len, 1, stdout);
}
```

at the end of pnull_callback

**Comment by ao-il** [comment]
I appreciate. I will study some more code and see what I can do.

**Comment by ao-il** [comment]
Oh, didn't see that before posting. I will try that. Thanks alot.

**Comment by ao-il** [comment]
Now, I have modified as instructed, but when try to compile, I get:
`fatal error: ../../deadbeef.h No such file or dir
...`
Does that mean I have to download the sources and compile from scratch?

**Comment by Alexey-Yakovenko** [comment]
in your own plugins, you need to `#include <deadbeef/deadbeef.h>`, and make sure that it's in the INCLUDE path.

**Comment by ao-il** [comment]
A thousand thanks. I have compiled now and it seems to work, but playback is not simulated correctly and the progress indicator is moving too fast.

**Comment by Alexey-Yakovenko** [comment]
It's not supposed to be simulating playback. It just writes the audio data to stdout.

**Comment by ao-il** [comment]
Sorry I didn't mention that earlier. If I want playback simulation, is there a way to achieve this? I know I could use a dummy card but the only one I have found `snd-dummy` does not support 24 bit audio. Grateful for any further tips!

**Comment by Alexey-Yakovenko** [comment]
what exactly do you mean by playback simulation?
if it's just timing, which doesn't need to be very precise, you can just insert the necessary amount of sleep after each write.

**Comment by ao-il** [comment]
Thanks. 

By playback simulation I mean to play the audio as if we are using a device and the time/progress indicator should update each second. `fwrite` in your snippet seems to write whole length of audio, as I get gigs of data in output. Changing it to `fwrite (stream, bytesread, 1, stdout)` does it more correctly. What exactly is `len`, 1024? 

I am not sure how I should calculate the delay, but I am testing with 1024/44.1 * 1000 usec and putting it in `usleep` before the call to `plugstdout_callback(buf, 1024)`, and this is not working correctly.

**Comment by Alexey-Yakovenko** [comment]
To make this work, you need to sync with your "real" output, and know how much data it really needs at a given time. Sleep will run out of sync very quickly, and cause either buffer starvation, or overfill.

**Comment by ao-il** [comment]
Thanks.

I don't follow, but isn't the length of data written to output constant? Are we dealing with bytes or frames ? In `nullout' you have a buffer of 4096, is that in frames or bytes? You also use a length of 1024 for chunk size? I was also wondering why `fwrite` with `len` (as you suggested) writes more data than with `bytesread`. I have also discovered that the raw output is formatted with `bigendian` and not the source endianness. How do I make it to use `litte endian`?

**Comment by Alexey-Yakovenko** [comment]
> I don't follow, but isn't the length of data written to output constant?

no. I can be any amount of data, and is dictated by audio system configuration.

> In nullout you have a buffer of 4096, is that in frames or bytes? 

bytes

> You also use a length of 1024 for chunk size?

which chunk size?

>  I was also wondering why fwrite with len (as you suggested) writes more data than with bytesread

because "len" is constant, and "bytesread" is the actual number of bytes that came from streamer_read, so it can be smaller than requested.

> I have also discovered that the raw output is formatted with bigendian and not the source endianness. How do I make it to use litte endian?

It's native-endian. If you get BE data on LE system -- that means you have an off-by-one error somewhere, i.e. 1 byte is lost somewhere, or something like that.

**Comment by ao-il** [comment]
Ok. I mean `len` is 1024 bytes. If it is native endian, does it mean the system is using BE by default? How can I change that?

**Comment by Alexey-Yakovenko** [comment]
> Ok. I mean len is 1024 bytes. 

it's just a random hardcoded value. for nullout purpose, it doesn't matter. can be literally ANY value there.

> If you get BE data on LE system -- that means you have an off-by-one error somewhere, i.e. 1 byte is lost somewhere, or something like that.

all modern systems are little-endian. the chance is very low that you're running a big-endian system.

**Comment by Alexey-Yakovenko** [comment]
> does it mean

I told you what it means -- it means you lost a byte somewhere, and your data is not aligned correctly.

**Comment by ao-il** [comment]
Thanks.

This is how I am capturing the audio:
`./deadbeef | cat > out.wav`
I have compared the size of output with the original source and they are the same, but when I import into audacity with little-endian, it is not the same as the source. When I use big-endian instead, it is looking like the source but not normalized to 0dB. What do you think is responsible for that?

**Comment by Alexey-Yakovenko** [comment]
you should be importing as raw data in the same format as you write (which is I suppose 16 bit signed PCM little endian)

**Comment by Alexey-Yakovenko** [comment]
what you're writing is not a WAV file -- it's raw PCM

**Comment by Alexey-Yakovenko** [comment]
also, you don't need `cat`, just `./deadbeef >out.raw` will do exactly the same.

**Comment by ao-il** [comment]
I have also tried to set `dd_waveformat_t->is_bigendian` to 0 in plugin.fmt , but this does not change anything.

**Comment by ao-il** [comment]
Ok thanks!

But that was exactly what I did importing as raw data in audacity. I will try your command now.

**Comment by ao-il** [comment]
Nothing changed. I will now export the original to raw and import into audacity and see what happens.

**Comment by ao-il** [comment]
Exported the original to raw and imported into audacity, the result is the same as the original. So, there's something not right.

**Comment by Alexey-Yakovenko** [comment]
another thing that you might want to try..

nullout accepts any input format, by simply doing this:

```
int
pnull_setformat (ddb_waveformat_t *fmt) {
    memcpy (&plugin.fmt, fmt, sizeof (ddb_waveformat_t));
    return 0;
}
```

That's because nullout doesn't care about the data contents.

So whatever comes in -- it won't be converted, and you'll be getting the original decoded stream, without resampling, etc.

Which is probably not what you want.

So first thing to try is to remove the memcpy above. Then you'll be always getting 44100/16bit/stereo.

I doubt that this is your problem though.

Have you tried looking into your raw file via hexdump or a text editor, and see if there wasn't some random garbage?
I mean.. it's stdout, something might have printed a text message in there.. And if this wasn't 4-byte aligned -- that may cause exactly the kind of misalignment that you're seeing.

**Comment by ao-il** [comment]
Thanks.

Ok, I will remove `memcpy` and see. Can I instead write to a file directly, to rule out the corruption?

**Comment by Alexey-Yakovenko** [comment]
yes, writing to a file will completely exclude the possibility of any random garbage in the output.

**Comment by ao-il** [comment]
As you suspected, the output was corrupted, but still not like the original and not normalized. Is deadbeef applying replaygain by default? I have disabled this in gui.

**Comment by ao-il** [comment]
I have tried with another file and it's the same. It goes from -1 to ~ -0.5 amplitude.

**Comment by oleksiy-unity3d** [comment]
it should not be applying replaygain by default, but it applies volume control... so you need to put the volume slider to 100%.

**Comment by Alexey-Yakovenko** [comment]
it should not be applying replaygain by default, but it applies volume control... so you need to put the volume slider to 100%.

**Comment by Alexey-Yakovenko** [comment]
It's also possible to override volume control in the output plugin by setting some flag...
`plugin.has_volume = 1`

**Comment by ao-il** [comment]
That is very correct, it's the volume. Thanks alot! Now, I need the output to pipe, is there a way of preventing it from being corrupted?

**Comment by oleksiy-unity3d** [comment]
I'm afraid, you can't count that nothing would print something to stdout. however, you can pipe directly to another process using `popen`, instead of `fopen`.

**Comment by Alexey-Yakovenko** [comment]
I'm afraid, you can't count that nothing would print something to stdout. however, you can pipe directly to another process using popen, instead of fopen.

**Comment by Alexey-Yakovenko** [comment]
and btw.. for next time when you need something like this -- it will save a huge amount of time to contact over email or slack, instead of making a chat out of the issue tracker.

**Comment by ao-il** [comment]
Ok. Will do some googling and see how it can be done.

**Comment by ao-il** [comment]
Ok. Will keep that in mind. Sorry for any inconvenience I may have caused.

**Comment by Alexey-Yakovenko** [comment]
something like:

```
FILE *f = popen ("/path/to/myprogram", "w");

.....

fwrite (buf, len, 1, f);

.....

fclose (f);
```

this would start the process `/path/to/myprogram` and write the data to its stdin.

basically, the same thing as `deadbeef | /path/to/myprogram`, except without stdout.

**Comment by ao-il** [comment]
Got it. BIG thanks!
Now, I am left with two last problems:
How to get the time/progress to sync with the output, and how to reset the plugin when changing to another audio track with different sampling data format to not have different streams in output.

**Comment by Alexey-Yakovenko** [comment]
Please contact me using Slack or Email if you have any more questions!
Best regards.
