### ISSUE TITLE
Reload/update ALSA config when samples change

### ISSUE THREAD

**Issue by ao-il** [Alexey-Yakovenko/deadbeef#1837]
The asoundrc is not updated when the sample rate changes. There is an option to release device when stopped. Is this supposed to be for updating ALSA configuration when the sample rate changes?

**Comment by Alexey-Yakovenko** [comment]
Just to give you some insight into why your issues are getting closed as invalid:

1. Deadbeef never changes ALSA configuration.
2. When you maximize a window and your system dies, not even reacting to power button --deadbeef doesn't have anything to do with it, even if the sound is still playing. That just means that X11 is dead, and maybe something else is dead, like input subsystem, but audio driver is still alive and working, and all of the apps are still running. You just can't see that on the screen.
3. When you're creating new issue -- you're supposed to fill out the template. Otherwise the issue will be closed in most cases.

**Comment by ao-il** [comment]
Thanks for your explanations. 
1. I see that, but that wasn't really what I meant. Deadbeef releases the device via option 'release device when stopped', and I think it's equally important to also release the device when there is sample deviation. Other players like audacious do this. Let's say I am capturing audio with my asoundrc, releasing the device during sample deviation prevents my recording from containing streams with varying formats.

2. This does not happen with other players, only  deadbeef, and has happened many times. Deadbeef reports:
`convgui: gtkui plugin not found
shellexecui: can't find gtkui plugin
... failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version 2.16.0` when started. This has happened with both static and repo versions.

3. Sorry,  posting from my phone. Will try and use template next time.

**Comment by Alexey-Yakovenko** [comment]
> I see that, but that wasn't really what I meant. Deadbeef releases the device via option 'release device when stopped', and I think it's equally important to also release the device when there is sample deviation. Other players like audacious do this. Let's say I am capturing audio with my asoundrc, releasing the device during sample deviation prevents my recording from containing streams with varying formats.

I'm sorry, but I have no idea what you're talking about here.
What's a "sample deviation"? Why the device needs to be released when it happens? What does it all has to do with asoundrc? What does it all has to do with your recording and streams?

It's not helpful at all. You need to present your problem in a way that I can understand.

> This does not happen with other players, only deadbeef, and has happened many times. 

I can move any windows on my computer all day long, and nothing is freezing. If something like that started happening on my computer -- I'd reinstall the OS.

> Deadbeef reports:

This is normal. Just means that some plugins didn't load for various reasons.

**Comment by ao-il** [comment]
1. By sample deviation, I mean when I change between audio/tracks with varying sample formats. For example, if I am using my asoundrc to capture using a file device, and I don't release the device when the sample rate changes, it means the resulting out.wav will contain audio with varying sample formats which is not supposed to be. So, to prevent that the stream should be flushed by releasing the device each time the sample format changes.
<pre>
<code>
pcm.filedev {
type file
pcm.slave "hw:0,0"
format "wav"
file "out.wav"
}
</code>
</pre>

2. I know it is difficult to figure out the cause of the problem with the detail provided, but it could be that the graphical components in deadbeef are not compatible with X11/graphics drivers. 
##System specs
`Lubuntu 16.04
1GB RAM
Intel atom 1.66 GHz
Display
X11 1024x600
Multimedia
HDA-Intel 
`

**Comment by ao-il** [comment]
1. The solution is similar to the option to release the device when stopped, except that we also want release it when sample format changes. So, adding an option to release when sampling changes would solve the problem.

**Comment by Alexey-Yakovenko** [comment]
1. please explain what do you mean by this "I am using my asoundrc to capture using a file device".
When the output sample format changes -- deadbeef just asks ALSA to set a new format, and keeps going. Releasing and re-initializing the device between tracks would cause noticeable gaps and pops.

2. "the graphical components in deadbeef are not compatible with X11/graphics drivers"

Then you should be reporting the issue to GTK devs. I can't do much about this.

**Comment by Alexey-Yakovenko** [comment]
> The solution is similar to the option to release the device when stopped, except that we also want release it when sample format changes. So, adding an option to release when sampling changes would solve the problem.

It would make sense to post a new issue, correctly filled out with this information.

**Comment by ao-il** [comment]
1. ALSA includes a file device which allows one to capture audio to a file while sending the audio to sound device at the same time. The alsa config I posted is my asoundrc. I don't think there would be any noticeable drops as it does not happen with other players.

2. I have not confirmed this to be true as I was only guessing. Is this happening to others using X11? Is deadbeef tested with X11?

**Comment by ao-il** [comment]
Okay, will post new issue.

**Comment by Alexey-Yakovenko** [comment]
> I have not confirmed this to be true as I was only guessing. Is this happening to others using X11? Is deadbeef tested with X11?

Deadbeef is not really using X11 directly. It's using GTK on Linux. You can also switch between GTK2 and GTK3 in the settings. And of course it's been tested with X11. It's pretty much the only graphics/input system on Linux.

**Comment by ao-il** [comment]
Okay. I will test with different gtk version.

**Comment by ao-il** [comment]
I don't know whether it is the recent update or switching to gtk3, but the problem seems to have disappeared :)
