### ISSUE TITLE
Extraneous device entries in ALSA devices list.

### ISSUE THREAD

**Issue by keantoken** [Alexey-Yakovenko/deadbeef#1840]
### Steps to reproduce the problem

My best guess:
Add soundcard
Remove soundcard

### What's going on? Describe the problem in as much detail as possible.

The ALSA devices list keeps growing and is full of non-working devices.

### Information about the software:

Deadbeef version: 0.6.2
OS: Debian Sid
![deadbeef-devices](https://user-images.githubusercontent.com/4388640/29000704-7c1a0054-7a39-11e7-97b6-68ea03c320d6.png)

**Comment by Alexey-Yakovenko** [comment]
This list comes from ALSA, not deadbeef.

**Comment by ngleb** [comment]
Can confirm the issue but it is definely not on deadbeef side. I tried to find the origin of this huge list of unnecessary devices and it looks like it is hardcoded in the system alsa configuration which is very hard to modify (no documentation available).

**Comment by keantoken** [comment]
Other programs such as ALSA seem to successfully ignore most of the entries. I'm all for extra options, but it doesn't help if there is no useful descriptions for them. Strange.

**Comment by Alexey-Yakovenko** [comment]
@keantoken everything about the entries, including their titles and descriptions, **is** coming from **ALSA**. Running `aplay -l` if expected to give the same list.

Here, side by side screenshot for you

![image](https://user-images.githubusercontent.com/1895698/29703334-616e9300-8975-11e7-9629-a470a50e6af0.png)

**Comment by keantoken** [comment]
I understand.
