### ISSUE TITLE
If track was paused, in new session wrong signal about PlayPause

### ISSUE THREAD

**Issue by rvs38** [Alexey-Yakovenko/deadbeef#1842]
### Steps to reproduce the problem

- Use plugin https://github.com/Serranya/deadbeef-mpris2-plugin
- Check "Resume previous session on startup" in Deadbeef Settings
- Stop session (Deadbeef -> Exit) with Paused track
- Run: `dbus-monitor --session "type='signal', interface='org.freedesktop.DBus.Properties', path='/org/mpris/MediaPlayer2'"`
- Run new Deadbeef session

### What's going on? Describe the problem in as much detail as possible.

- Click button Play and under `dbus-monitor` output: 
PlaybackStatus … string "Paused" 
But if u type: `dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.DeaDBeeF /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:"org.mpris.MediaPlayer2.Player" string:"PlaybackStatus"`
Output:
variant       string "Playing"

- click button Pause and under `dbus-monitor` output:
PlaybackStatus … string "Playing"
But `dbus-send` output:
variant       string "Paused"

### Information about the software:
Deadbeef version: Devel, building with last git commit 939360a
deadbeef-mpris2-plugin version: Devel, building with last git commit 93997fb
OS: Debian GNU/Linux Unstable

**Comment by Alexey-Yakovenko** [comment]
Hi. Please validate the fix. It's a bit hard for me to test it atm, but it should work.

**Comment by rvs38** [comment]
It's mostly ok now, but something strange during testing with `dbus-monitor`:
Play only one track. Pause -> exit. 
Start new. `dbus-monitor` show "Paused". _OK_. Unpause, Pause ->exit
It maybe 2-3 times in row all OK, but 
Start new. `dbus-monitor` show "Playing". _FAIL_.  Unpause, Pause ->exit
Start new. `dbus-monitor` show "Playing". _FAIL_.  Unpause, Pause ->exit.
It maybe 2-3 times in row all WRONG, but 
Start new. `dbus-monitor` show "Paused". _OK_. Unpause, Pause ->exit.

Maybe race condition somethere?
It maybe unneeded info, but test above changing 3 strings in Deadbeef user config file :
playlist.cursor
playlist.scroll
resume.position

**Comment by oleksiy-unity3d** [comment]
It might be a race condition too, yeah.. I don't know.. depends how dbus plugin gets the "paused" state.

**Comment by Alexey-Yakovenko** [comment]
It might be a race condition too, yeah.. I don't know.. depends how dbus plugin gets the "paused" state.

**Comment by Alexey-Yakovenko** [comment]
Is there a possibility for you to build the mpris plugin with -DMPRIS__DEBUG=1?
This should make it log stuff to console, and you may be able to see what events are coming through..

Looking at the code, it doesn't look like mpris plugin is doing it 100% correctly.
It should be checking the `p1` argument of the event for 1 or 0, but instead it checks output state, which may have a delay before it really changes.

I'll try another fix though..

**Comment by Alexey-Yakovenko** [comment]
Please try again

**Comment by rvs38** [comment]
With commits 560dec0 & 47a0c81 wrong behavior returned.
6021afb work sometimes and let test it again. In the mpris-plugin debug output calls order is always different. So maybe race condition in plugin. Interesting in DIFF mpris-plugin debug output is:
Wrong:
DB_EV_PAUSED event received
PlayPause toggled... last state -1
DB_EV_TRACKINFOCHANGED event received

Right:
DB_EV_PAUSED event received
PlayPause toggled... last state 1
DB_EV_TRACKINFOCHANGED event received

last state explained here:
https://github.com/Serranya/deadbeef-mpris2-plugin/blob/master/src/mpris.c#L76


I can post full mpris-debug logs if u want

**Comment by Alexey-Yakovenko** [comment]
ok, I can see that the plugin code is obviously wrong. It misinterprets what DB_EV_PAUSE event is about. It's not a "toggle pause", it's sent whenever pause state changes, and it tells specifically what state it's changing to (via the `p1` parameter -- paused=1 or unpaused=0).

I'd change the code to simple do this in the DB_EV_PAUSED handler:

`emitPlaybackStatusChanged(p1 ? OUTPUT_STATE_PAUSED : OUTPUT_STATE_PLAYING, &mprisData);`

and to this in the DB_EV_SONGSTARTED handler:

`emitPlaybackStatusChanged(OUTPUT_STATE_PLAYING, &mprisData);`

and remove the lastState variable altogether.

**Comment by Alexey-Yakovenko** [comment]
Anyways, I'll do more testing of this stuff.. I'm pretty sure it's used in android version in a similar way, and probably broken atm.

**Comment by Alexey-Yakovenko** [comment]
I just checked android version, which uses the same events for displaying the play/pause button state. It works fine with latest codebase. So.. try applying my suggested fixes above to the plugin, and if they work -- submit the patch upstream. Undeniably, the plugin worked in the past, but that was a coincidence. I'm trying my best to maintain compatibility, but I can't maintain the same event sending patterns to maintain compat with 3rd party bugs.
