### ISSUE TITLE
Не сохраняет настройки дизайна после перезапуска

### ISSUE THREAD

**Issue by alexeysvrv** [Alexey-Yakovenko/deadbeef#1844]
Здравствуйте Алексей.
Deadbeef 0.7.2 не сохраняет настройки изменения внешнего вида после изменения дизайна. В частности, он не сохраняет закрепление рамок окон. Бывает, что после запуска некоторые части плеера большие, а некоторые маленькие(допустим анализатор спектра на весь экран, а плейлист очень небольшой)

**Comment by Alexey-Yakovenko** [comment]
здравствуйте. я думаю, что эта проблема исправлена в транке (master branch). исправление не может и не будет бэкпортировано в ветку 0.7.
поэтому баг закрываю, но если у вас возникнут проблемы с транком -- сообщите, будем разбираться.

**Comment by alexeysvrv** [comment]
Спасибо большое Алексей.
