### ISSUE TITLE
Some bugs with Russian translation

### ISSUE THREAD

**Issue by TotalCaesar659** [Alexey-Yakovenko/deadbeef#1846]
### What's going on? Describe the problem in as much detail as possible.
There are some bugs with Russian translation:

1) The time of playing in status bar has bug with showing the time that's longer than 1 day: it has to be "1 день" instead of this one.
![1](https://user-images.githubusercontent.com/14265316/29132787-01ec4e0a-7d3a-11e7-84d9-4f13c7b20374.png)

2) There are many untranslated places. I wanted to help with them on Transifex (https://www.transifex.com/deadbeef-player/deadbeef-player/), but there are 100%.
![1](https://user-images.githubusercontent.com/14265316/29132926-746fd2a8-7d3a-11e7-9d62-e05e8f7c2400.png)
![3](https://user-images.githubusercontent.com/14265316/29133164-46caf0ac-7d3b-11e7-94b6-6316e3ec0dd6.png)
![1](https://user-images.githubusercontent.com/14265316/29133172-4dccc114-7d3b-11e7-9479-9a6fc0d7b6ba.png)
![2](https://user-images.githubusercontent.com/14265316/29133179-52c65216-7d3b-11e7-8c58-e7be767a689f.png)
And that's not all ones.

### Information about the software:

Deadbeef version: latest master build
OS: Lubuntu 16.04.3

**Comment by Alexey-Yakovenko** [comment]
Part of the issues are work in progress (translating of the texts which are added by plugins).
Some other issues are simply because the texts are new, and have not been translated yet. They should get translated before the release.
And the status bar issue is definitely a serious bug, I'll look into it as soon as possible.
While this issue covers 3 different problems -- I'll close it as soon as the status bar issue is fixed.

**Comment by Alexey-Yakovenko** [comment]
I will push the new texts to transifex too.

**Comment by Alexey-Yakovenko** [comment]
The new strings are in.

**Comment by TotalCaesar659** [comment]
There are some more untranslated strings (when Transifex is 100%).
![1](https://user-images.githubusercontent.com/14265316/33487309-d2ce0c5c-d6bd-11e7-9a71-54b94f55c8ed.png)
![2](https://user-images.githubusercontent.com/14265316/33487314-d5db1eee-d6bd-11e7-8710-95d428a2650d.png)
![3](https://user-images.githubusercontent.com/14265316/33487319-d8b04ad6-d6bd-11e7-8cf8-8d960e7207f5.png)
![4](https://user-images.githubusercontent.com/14265316/33487323-dad98cc8-d6bd-11e7-8ae3-ebd40a8ddf1d.png)

**Comment by Alexey-Yakovenko** [comment]
Transifex is not automatically synced with source code. That's why some stuff is localized in Transifex, but not yet in the current builds.

And some stuff doesn't support localization (yet)

**Comment by Alexey-Yakovenko** [comment]
(And I don't think that opening bugs about updating localization makes a lot of sense.. there would be many of those, pretty much after every newly added string, therefore closing this one)

**Comment by Alexey-Yakovenko** [comment]
oops didn't realize it's a closed issue. nothing to see here then

**Comment by TotalCaesar659** [comment]
Isn't it possible to force Transifex update some strings? I see that some of them may be translated (like this one https://github.com/DeaDBeeF-Player/deadbeef/blob/c531bf35f340975929a953db0fc85f2f63181158/plugins/gtkui/interface.c#L1909), but I can't cause of Transifex.
And I didn't even thought about re-opening bug that may be closed soon after update.
