### ISSUE TITLE
gtk+ themes no longer display properly

### ISSUE THREAD

**Issue by orbea** [Alexey-Yakovenko/deadbeef#1849]
### Steps to reproduce the problem

1. Open deadbeef with either gtk+2 or gtk+3.
2. Observe that the seek bar no longer displays the gtk+ theme correctly.

### What's going on? Describe the problem in as much detail as possible.

The seek bar no longer displays the correct gtk+ theme, this affects both gtk+2 and gtk+3.

Before
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/deadbeef/2017-08-12-213049_748x518_scrot.png)

After
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/deadbeef/2017-08-12-213359_748x518_scrot.png)

git bisect revealed this as the bad commit.
```
dc639a05fcff0654e446af567839abda5761105e is the first bad commit
commit dc639a05fcff0654e446af567839abda5761105e
Author: Alexey Yakovenko <wakeroid@gmail.com>
Date:   Wed Aug 9 13:43:19 2017 +0200

    gtkui: improved seekbar

:040000 040000 627b0e38bc65006da0a0ea3c05828fabe9792a5d a4223350c5e5974bbe19b2ff2270b3d9fa58a222 M	plugins
```
dc639a05fcff0654e446af567839abda5761105e

This issue was similar. https://github.com/Alexey-Yakovenko/deadbeef/issues/1549

### Information about the software:
`deadbeef-2017.08.10_604f60c4_master-x86_64-1_git`
`gtk+2-2.24.31-x86_64-2`
`gtk+3-3.22.18-x86_64-1`

Deadbeef version:
OS: `Slackware64-current`

**Comment by Alexey-Yakovenko** [comment]
The screenshots doesn't show any issues -- that's how the current code is supposed to work. The revision you linked has changed the rendering this way.

**Comment by orbea** [comment]
Alright, just to be clear the current correct behavior is to render the right half of the seek bar showing the unfinished portion of the track with the background color?

**Comment by orbea** [comment]
I tried to override it with `Edit > Preferences > Seekbar/Volumebar > Override`, but found I can only change the foreground color. Is that also intended?

**Comment by Alexey-Yakovenko** [comment]
> Alright, just to be clear the current correct behavior is to render the right half of the seek bar showing the unfinished portion of the track with the background color?

Background color is not used anymore. I guess its customization needs to be removed from the UI. I'll do it.

**Comment by orbea** [comment]
Okay, thanks for the clarification!

**Comment by Alexey-Yakovenko** [comment]
The background color is used in the EQ panel, so I could not remove its customization. I clarified the usage in the preferences window though.

**Comment by Alexey-Yakovenko** [comment]
oh.. I figured that equalizer now has the same foreground and background color :(

**Comment by Alexey-Yakovenko** [comment]
all should be good now.
