### ISSUE TITLE
allow foobar-like syntax for optional tags [%a - ]%t

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#491]
Original [issue 589](https://code.google.com/p/ddb/issues/detail?id=589) created by Alexey-Yakovenko on 2012-04-19T11:49:30.000Z:

submitted by: anonymous
Date: 2010-02-09 21:58:47

Couple of feature requests for title formatting:
 * Show empty string instead of '?' for empty tags
 * if title tag is missing, use filename without extension
 * allow foobar-like syntax for optional tags in brackets - eg [%a - ]%t would output 'arist - title' if artist tag exists, and just 'title' if aryist tag is missing.

Thank you.

**Comment by yunake** [comment]
should this be merged with #647?

**Comment by Alexey-Yakovenko** [comment]
it should be closed, because it works since 0.7.0 (as well as 647)
