### ISSUE TITLE
ReplayGain scanner

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#493]
Original [issue 591](https://code.google.com/p/ddb/issues/detail?id=591) created by Alexey-Yakovenko on 2012-04-19T11:49:31.000Z:

submitted by: nobody
Date: 2010-02-25 13:09:50

I think, that it would be nice to implement ReplayGain scanning of tracks and adds tags in mp3 files, as is in FooBar2000.

**Comment by xinyazhang** [comment]
Hi Alexey,
It seems nobody are working on it so I'd like to take over this task.
Do you have any suggestions? (like coding standard to mainline the code)
@Alexey-Yakovenko

**Comment by Alexey-Yakovenko** [comment]
yeah, it's more like "nobody closes the bugs" :)

**Comment by vibrasphere111** [comment]
I added the third-party plugin xinyazhang was talking about, but I'm still not able to get it to work... i opened a new issue for this: https://github.com/DeaDBeeF-Player/deadbeef/issues/2063
i appreciate all kinds of help!
