### ISSUE TITLE
Double click on playlist title (tab) to start it playing

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#507]
Original [issue 605](https://code.google.com/p/ddb/issues/detail?id=605) created by Alexey-Yakovenko on 2012-04-19T11:49:45.000Z:

submitted by: piko7a
Date: 2010-05-17 17:42:30

Double click on playlist title (tab) to start it playing.

**Comment by tvn87** [comment]
I am investigating currently in this matter and even implemented it. But my current version is using a wrong typecast to `GtkWidget` to be able to use `on_playbtn_clicked(GtkButton, gpointer)`. And here I got the problem: The only way make this clean would be to outsource the function body of `on_playbtn_clicked` to a new function or copy `action_play_cb|on_playbtn_clicked` again, which I would rather not like to do. Are there any plans to serve a generic play-function that can be used to implement this?

**Comment by Alexey-Yakovenko** [comment]
You should need to do what on_playbtn_clicked is doing for implementing this feature request.

Instead, you should just do something like `deadbeef->sendmessage (DB_EV_PLAY_NUM, 0, 0, 0);`

What's the problem with that?

**Comment by tvn87** [comment]
Oh ok, nothing wrong with that, I did not know about the event sent mechanism. Thank you for the help :-).
