### ISSUE TITLE
Copy and paste support between playlists

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#606]
Original [issue 704](https://code.google.com/p/ddb/issues/detail?id=704) created by Alexey-Yakovenko on 2012-04-19T11:51:26.000Z:

submitted by: tedtriol
Date: 2011-03-24 13:09:47

Foobar has a context item &quot;Copy&quot;, which lets me copy the filename (in my
case is this &quot;Artist - Title.mp3&quot;) to the clipboard. I just have to paste
this at discogs (and remove the .mp3 part) to find interesting information
on tracks to complete my file's tags. I never use automated tagging.

**Comment by shaforostoff** [comment]
also copy and paste between two instances of deadbeef (outputting to different soundcards), and also between deadbeef and other players like vlc (use case: argentine tango DJing)

**Comment by Alexey-Yakovenko** [comment]
This should be working on master
