### ISSUE TITLE
Display metadata field only if present

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#647]
Original [issue 745](https://code.google.com/p/ddb/issues/detail?id=745) created by Alexey-Yakovenko on 2012-04-19T11:52:10.000Z:

submitted by: nobody
Date: 2011-08-06 00:44:51

This feature is found in foobar2000. If you wrap metadata fields in brackets (I believe foobar uses '[' and ']'), it is only displayed if that field has a value in the file. Currently deadbeef shows the value of fields without a value as a '?'

For example, for the &quot;group by&quot; option, using '{' and '}' as the display-only-if-present brackets:

%a - [%y] %b{ | disc %@disc@%}

The album Dark Side of the Moon would render as

Pink Floyd - [1973] Dark Side of the Moon

and the double album The Wall would render as

Pink Floyd - [1979] The Wall | disc 1
and
Pink Floyd - [1979] The Wall | disc 2

**Comment by Xylemon** [comment]
Is there a way to display the BPS (bits per second)? I use to be able to do %@BPS@ but now I can't display that in my playlist since the 0.7 series. I've converted every column to use the Foobar2k formatting, but I can't figure out the BPS equivalent.

**Comment by Alexey-Yakovenko** [comment]
`$meta(:bps)` should work (this is not how it's supposed to work when full TF spec is implemented, but would do for now)

**Comment by Xylemon** [comment]
@Alexey-Yakovenko Thank you, that worked perfectly.
