### ISSUE TITLE
Keyboard shotcuts for volume control have step of +-2dB, need +-1dB accuracy

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#920]
Original [issue 1018](https://code.google.com/p/ddb/issues/detail?id=1018) created by Alexey-Yakovenko on 2013-12-10T00:37:39.000Z:

(Enhancement request - not a bug report.)

Especially late at night, a difference of +/- 2 dB (the current step width) will, for good ears, appear as quite a change down or up. (At the light of day, this step width is more than enough.)

I can turn volume up/down in much gentler steps with my speaker's remote control. That is, when everything is dead silent around me except for the audio coming out of my speaker, I always have to have my remote nearby to compensate the volume jumps.

Please note that this might also imply GUI changes, i. e. the wedge-shaped visual volume control might have to be enlarged in width.

Thanks for considering.

**Comment by wasteofoxygen** [comment]
any progress on this?

**Comment by Alexey-Yakovenko** [comment]
I'm not sure if I totally understand what this request is about. Pretty sure deadbeef allows to control volume in small enough steps.

**Comment by wasteofoxygen** [comment]
for keyboard shortcuts the volume steps are 2,0 db, using the mouse on the volume icon they are 1,0db. 2 db is too much for some people using high-efficiency headphones or IEMS, like me, without having to reach for analog volume control.

**Comment by Alexey-Yakovenko** [comment]
It doesn't look like +-2dB was requested by anyone, seems like it was a random choice.
Changing it to +-1dB.

**Comment by wasteofoxygen** [comment]
Thanks!

**Comment by wasteofoxygen** [comment]
Not sure if this is the right place to post this, but when trying to compile I get the following error:

autogen.sh and ./configure run fine without error messages

When doing make i get : make[2]: *** No rule to make target 'game-music-emu-0.6pre/gme/.deps/ymdeltat.Plo'.  Stop.


What am I missing?

**Comment by Alexey-Yakovenko** [comment]
the latest build is always here:
https://drone.io/github.com/Alexey-Yakovenko/deadbeef/files

**Comment by Alexey-Yakovenko** [comment]
I'm not sure why you're getting error, but looks like temporary files need some cleanup.

Try running ```git clean -f```. If that doesn't help, clone the repository from scratch.

**Comment by wasteofoxygen** [comment]
I had to add subdir-objects to AM_INIT_AUTOMAKE in configure ac for the script to autogen script to work, could that have something to do with it?

Anyways, since hotkeys.so compiled fine I went and replaced the one in /opt/deadbeef with it, even changed it to float and 0.5 values, and now I'm effectively getting 0.5 dB steps, which is perfect for my usage.

**Comment by Alexey-Yakovenko** [comment]
That is strange. Looks like some automake compatibility break. Which linux distro are you using?

**Comment by wasteofoxygen** [comment]
Debian Jessie

**Comment by Alexey-Yakovenko** [comment]
I think that you're right, and adding the subdir-objects is what broke it.

What was the error before you added this?

**Comment by wasteofoxygen** [comment]
Most if not all plugins would fail to compile, for example:

plugins/adplug/Makefile.am:12: warning: source file 'adplug/xsm.cpp' is in a subdirectory,
plugins/adplug/Makefile.am:12: but option 'subdir-objects' is disabled
plugins/ao/Makefile.am:4: warning: source file 'eng_dsf/eng_dsf.c' is in a subdirectory,
plugins/ao/Makefile.am:4: but option 'subdir-objects' is disabled
plugins/ao/Makefile.am:4: warning: source file 'eng_dsf/dc_hw.c' is in a subdirectory,

**Comment by Alexey-Yakovenko** [comment]
these are warnings, not errors. did it actually fail later?

**Comment by wasteofoxygen** [comment]
No, it compiled fine. My bad.

**Comment by Alexey-Yakovenko** [comment]
ok, then it's a known problem, but the fix is not found yet :)
newer automake complains about this subdir-objects, but if subdir-objects is added nothing works.
just ignore it.

**Comment by andreas--e** [comment]
Well, I think these complaints fill about 20 percent of build log on their own ;-) Should be fixed in recent automake, application developers are mostly unable to do something about that (esp. those who rely on the plugin system, where not every plugin developer does things the same way as their fellow developers)
