### ISSUE TITLE
Not remembering the positioning of viewports\windows on restart

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#975]
Original [issue 1073](https://code.google.com/p/ddb/issues/detail?id=1073) created by Alexey-Yakovenko on 2014-03-09T04:40:10.000Z:

<b>What steps will reproduce the problem?</b>
<b>Какие шаги приводят к воспроизведению</b>
<b>проблемы?</b>
1. Design a custom layout
Ex: 2 horizontal splits (3 slices)
   Left: File Browser (Plugin)
   Middle: Playlist with Tabs
   Right: Horizontal Split
      Top: Selection Properties
      Bottom: Spectrum Analyser
2. Close Deadbeef
3. Start Deadbeef

<b>What is the expected output? What do you see instead?</b>
<b>Какой ожидаемый вывод? Что вы видите</b>
<b>вместо него?</b>

All the window\viewports position (size only) has changed, when I would expect it to open the same way I opened it.  I have reposition\expand\etc the different windows to make them usable again.

<b>What version of the product are you using? On what operating system and CPU</b>
<b>architecture?</b>
<b>Какую версию продукта вы используете? На</b>
<b>какой операционной системе и</b>
<b>архитектуре CPU?</b>

UbuntuGnome 14.04 (64) - 3.13.0-10-generic
DeadBeef version 0.6.1
Installed: debubuntu package amd64

<b>How did you install the product?</b>
<b>Как вы установили продукт?</b>
install manager

<b>Please provide any additional information below.</b>
<b>Пожалуйста, предоставьте любую</b>
<b>дополнительную информацию ниже.</b>

**Comment by cboxdoerfer** [comment]
This should be fixed with the recent splitter changes on master.
