### ISSUE TITLE
DeaDBeeF-0.6.1 superslow startup time with superlarge playlists

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#976]
Original [issue 1074](https://code.google.com/p/ddb/issues/detail?id=1074) created by Alexey-Yakovenko on 2014-03-09T12:19:37.000Z:

<b>What steps will reproduce the problem?</b>
1. Create two huge playlists A (254620 files) and B (154473 files)
2. Quit DeaDBeeF
3. Start DeaDBeeF

What is the expected output?
 I would expect the DeaDBeeF player window to instantly load and be available.
What do you see instead?
 DeaDBeeF delays showing it's GUI until the playlists are processed

What version of the product are you using? 
 DeaDBeeF-0.6.1

On what operating system and CPU architecture?
 Debian (Jessie). amd64 Linux 3.12

<b>How did you install the product?</b>
 Installed by dpkg with official DeaDBeeF packages (from website)

<b>Please provide any additional information below.</b>
 It would be nice if DeaDBeeF could load huge playlists in the background after startup so DeaDBeeF can be used right away without having to wait for the loading to complete. My files are on a (slow) NFS share and it takes up to 60-70 seconds loading the playlists. The reason I have so huge playlists are that I have the entire SOASC and SOAMC archive on my disks and it contain a total of 1.4 terrabytes of mp3 files.

**Comment by mdooligan** [comment]
I found that delaying file scanning until everything is up and running works very well. 

I used the same method XMMS used to use: spawn a thread that only scans the files that are actually displayed in the playlist first. It allows loading of massive playlists very quickly.  There was actually an option checkbox to delay file scanning until display.

While the player is running, idle threads fill in the rest of the playlist data.

You can see this behavior also when you load a plain file list that has many 1000s of files. The player insists on scanning every single one of them before you can use it.

**Comment by Alexey-Yakovenko** [comment]
@mdooligan you misunderstand what this issue is talking about.
It's about deadbeef startup, when it loads playlists, which already contain the information about all files.
UI doesn't appear, before the player gets initialized.

What you talking about is adding files to playlist, when the information has to be loaded from each file, the type of file detected, etc. That's another issue: #690

**Comment by mdooligan** [comment]
Ah yes, thank you for the response. I guess I missed #690 in my cursory 
pass through of the issues.

I just 'discovered' deadbeef a couple weeks ago. It's almost exactly 
like the player I've written with GTK, except, well... very much better. 
:) Very much awesome, as a matter of fact. So I thought I'd dump mine 
and have a go at deadbeef. I'm still totally new to git and github.

My playlists regularly run about 20,000 items, and they load fine in 
deadbeef. Alsaplayer fails at a couple hundred. Looks nice, works awful. 
Plus it's written in C++. I like C much better, more fun to program.

So I'm poking around throught the code and website getting familiar with 
the project. I thought I'd pipe up with my 2 bits about a few issues, 
you may see a couple more of my poorly informed comments here and there. 
My interest at this point is the UI, I see a number of small issues that 
need to be dealt with. I look forward to having my own set of patches to 
share.

Thanks for the great work. I'll try not to be a pest.



On 2016-04-19 06:09, Alexey Yakovenko wrote:
>
> @mdooligan <https://github.com/mdooligan> you misunderstand what this 
> issue is talking about.
> It's about deadbeef startup, when it loads playlists, which already 
> contain the information about all files.
> UI doesn't appear, before the player gets initialized.
>
> What you talking about is adding files to playlist, when the 
> information has to be loaded from each file, the type of file 
> detected, etc. That's another issue: #690 
> <https://github.com/Alexey-Yakovenko/deadbeef/issues/690>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/Alexey-Yakovenko/deadbeef/issues/976#issuecomment-211917918>
>

-- 
Peace and Cheer

**Comment by Alexey-Yakovenko** [comment]
deadbeef playlist loading time is about as fast as it can be.

It is possible that the speed will be improved *slightly* while working on media library, but it's unlikely that the change will be significant.

Therefore closing this issue as wontfix.
